In [25]:
import requests 
import os
from dotenv import load_dotenv
import pandas as pd
import re
import time

In [2]:
# env 파일 로드
load_dotenv()

True

# 지식산업센터

## 데이터 불러오기

In [27]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "300"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/InfoBizcenterApply/{start_index}/{end_index}/"

response = requests.get(url)
print(response.content.decode('utf-8'))

{"InfoBizcenterApply":{"list_total_count":213,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"IDX":208.0,"FAC_NM":"신내테크노타운","ADDRESS":"봉화산로 123(상봉동)","TELEPHONE":"02)3423-0057","APPROVAL_DATE":"96.5.28","COMPLE_DATE":"99.10.18"},{"IDX":136.0,"FAC_NM":"월곡동아파트형공장","ADDRESS":"하월곡동 96-113","TELEPHONE":"02-090-8083","APPROVAL_DATE":"33289","COMPLE_DATE":"1990.12.31"},{"IDX":135.0,"FAC_NM":"월곡동아파트형공장","ADDRESS":"하월곡동 96-113","TELEPHONE":"02-912-1034","APPROVAL_DATE":"33289","COMPLE_DATE":"1990.12.31"},{"IDX":140.0,"FAC_NM":"문정아르페온 1차 지식산업센터","ADDRESS":"서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)","TELEPHONE":"031-706-8577","APPROVAL_DATE":"2016.06.27","COMPLE_DATE":"2016.06.27"},{"IDX":139.0,"FAC_NM":"문정 대명벨리온","ADDRESS":"서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)","TELEPHONE":"02-2222-7357","APPROVAL_DATE":"2016.03.23","COMPLE_DATE":"2016.03.23"},{"IDX":141.0,"FAC_NM":"문정 현대지식산업센터Ｉ-1","ADDRESS":"서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)","TELEPHONE":"02-3451-0100","APPROVAL_DATE":"2016.02.29","COMPLE_DATE":"2016.02.29"},{"IDX":138.0,"FAC_NM":"송파유탑테크밸리","ADDRESS":"서울특별시 송파구 문정동 651-14 (문정도시개발구역 3-12BL)","TELEPHONE":"062-526-8383","APPROVAL_DATE":"2015.12.18","COMPLE_DATE":"2015.12.18"},{"IDX":207.0,"FAC_NM":"포휴","ADDRESS":"성수동1가 656-3","TELEPHONE":"3416-1500","APPROVAL_DATE":"2013.08.30","COMPLE_DATE":"2016.5.3"},{"IDX":117.0,"FAC_NM":"에이스하이엔드타워 10차","ADDRESS":"가산동 660","TELEPHONE":"6309-6045","APPROVAL_DATE":"2013.08.29","COMPLE_DATE":"2015.10.28"},{"IDX":206.0,"FAC_NM":"BY센터","ADDRESS":"성수동2가 301-51,301-38","TELEPHONE":"(02) 467-2247","APPROVAL_DATE":"2013.08.12","COMPLE_DATE":"2015.12.04"},{"IDX":205.0,"FAC_NM":"신한IT타워","ADDRESS":"성수동1가 656-603","TELEPHONE":"","APPROVAL_DATE":"2013.07.02","COMPLE_DATE":"2015.06.04"},{"IDX":116.0,"FAC_NM":"에스비즈니스센터","ADDRESS":"가산동 343-8","TELEPHONE":"2163-6749","APPROVAL_DATE":"2013.03.26","COMPLE_DATE":"2015.06.01"},{"IDX":165.0,"FAC_NM":"선유도역2차 아이에스비즈타워","ADDRESS":"선유로49길 23(양평동4가)","TELEPHONE":"6123-4100","APPROVAL_DATE":"2012.12.18","COMPLE_DATE":"2014.11.19"},{"IDX":115.0,"FAC_NM":"대륭테크노타운17차","ADDRESS":"가산동 670","TELEPHONE":"3466-0051","APPROVAL_DATE":"2012.12.10","COMPLE_DATE":"2015.05.15"},{"IDX":204.0,"FAC_NM":"서울숲\n드림타워(삼공)","ADDRESS":"성수동2가 323, 309-51","TELEPHONE":"(02)6222-8114","APPROVAL_DATE":"2012.10.31","COMPLE_DATE":"2015.03.23"},{"IDX":164.0,"FAC_NM":"에이스하이테크시티 2","ADDRESS":"선유로13길 25(문래동6가)","TELEPHONE":"2257-8114","APPROVAL_DATE":"2012.08.27","COMPLE_DATE":"2014.10.24"},{"IDX":2.0,"FAC_NM":"NICE그룹 지식산업센터","ADDRESS":"상일로6길 55 (상일동)","TELEPHONE":"2122-4415","APPROVAL_DATE":"2012.06.29","COMPLE_DATE":"2014.02.28"},{"IDX":166.0,"FAC_NM":"SK V1 center","ADDRESS":"당산로41길 11(당산동4가)","TELEPHONE":"6121-8100","APPROVAL_DATE":"2012.06.19","COMPLE_DATE":"2015.02.17"},{"IDX":203.0,"FAC_NM":"서울숲IT캐슬","ADDRESS":"성수동1가 671-6, -41 외 4필지","TELEPHONE":"(02) 2086-3346","APPROVAL_DATE":"2012.05.10","COMPLE_DATE":"2014.06.17"},{"IDX":1.0,"FAC_NM":"세종투자㈜","ADDRESS":"강동구 상일로10길 36 (상일동)","TELEPHONE":"3415-4971","APPROVAL_DATE":"2011.11.30","COMPLE_DATE":"2013.09.13"},{"IDX":202.0,"FAC_NM":"에이스하이앤드\n 성수타워","ADDRESS":"성수동2가 269-25,269-51,\n269-115,328-5","TELEPHONE":"(02) 2112-6491","APPROVAL_DATE":"2011.11.15","COMPLE_DATE":"2015.06.19"},{"IDX":201.0,"FAC_NM":"에이스성수타워1차","ADDRESS":"성수2가 280-15,19","TELEPHONE":"(02) 591-0607","APPROVAL_DATE":"2011.10.20","COMPLE_DATE":"2014.03.11"},{"IDX":52.0,"FAC_NM":"G플러스 코오롱 디지털타워","ADDRESS":"구로동 222-31","TELEPHONE":"858-3650","APPROVAL_DATE":"2011.06.09","COMPLE_DATE":"2013.7.24"},{"IDX":163.0,"FAC_NM":"선유도역1차 아이에스비즈타워","ADDRESS":"양평로21길 26(양평동5가)","TELEPHONE":"6968-1004","APPROVAL_DATE":"2011.04.21","COMPLE_DATE":"2013.5.27"},{"IDX":200.0,"FAC_NM":"서울숲\n한라시그마밸리II","ADDRESS":"성수동2가 333-15","TELEPHONE":"(02) 4199-5621","APPROVAL_DATE":"2011.02.25","COMPLE_DATE":"2013.03.28"},{"IDX":51.0,"FAC_NM":"대륭포스트타워7차","ADDRESS":"구로동 170-10 외 2필지","TELEPHONE":"6942-9500","APPROVAL_DATE":"2011.02.21","COMPLE_DATE":"2012.12.11"},{"IDX":10.0,"FAC_NM":"강서IT밸리","ADDRESS":"화곡로68길 82","TELEPHONE":"6961-5111","APPROVAL_DATE":"2010.3.9","COMPLE_DATE":"2012.2.6"},{"IDX":11.0,"FAC_NM":"강서한강자이","ADDRESS":"양천로 401","TELEPHONE":"6968-5801~2","APPROVAL_DATE":"2010.10.15","COMPLE_DATE":"2013.6.7"},{"IDX":199.0,"FAC_NM":"서울숲 \n한라에코벨리","ADDRESS":"성수동1가 656-36\n656-1222","TELEPHONE":"(02) 549-6693","APPROVAL_DATE":"2010.09.09","COMPLE_DATE":"2012.09.06"},{"IDX":198.0,"FAC_NM":"성수동\n아이에스비즈타워","ADDRESS":"성수동2가289-319,327,328","TELEPHONE":"(02) 3218-6643","APPROVAL_DATE":"2010.08.28","COMPLE_DATE":"2012.07.23"},{"IDX":162.0,"FAC_NM":"KnK디지털타워","ADDRESS":"영신로 220(영등포동8가)","TELEPHONE":"2675-6060","APPROVAL_DATE":"2010.08.27","COMPLE_DATE":"2012.12.07"},{"IDX":167.0,"FAC_NM":"문래동 하우스디 비즈","ADDRESS":"선유로3길 10(문래동5가)","TELEPHONE":"2112-6339","APPROVAL_DATE":"2010.08.10","COMPLE_DATE":"2016.05.09"},{"IDX":160.0,"FAC_NM":"선유도코오롱디지털타워","ADDRESS":"양평로22길21(양평동5가)","TELEPHONE":"2062-5996","APPROVAL_DATE":"2010.07.13","COMPLE_DATE":"2012.03.23"},{"IDX":197.0,"FAC_NM":"성수에이팩센터","ADDRESS":"성수동2가 289-5\n289-334,289-335","TELEPHONE":"(02) 3416-1541","APPROVAL_DATE":"2010.06.24","COMPLE_DATE":"2012.08.24"},{"IDX":196.0,"FAC_NM":"아연디지털타워","ADDRESS":"성수동2가314-37","TELEPHONE":"(02) 499-2275","APPROVAL_DATE":"2010.06.01","COMPLE_DATE":"2012.08.31"},{"IDX":195.0,"FAC_NM":"서울숲 SK V1 타워","ADDRESS":"성수동2가284-55, 284-107","TELEPHONE":"(02) 6233-8000","APPROVAL_DATE":"2010.04.13","COMPLE_DATE":"2014.07.18"},{"IDX":114.0,"FAC_NM":"에이스하이엔드9차","ADDRESS":"가산동 481-2","TELEPHONE":"6309-6051","APPROVAL_DATE":"2010.04","COMPLE_DATE":"2012.07.20"},{"IDX":194.0,"FAC_NM":"서울숲\nIT 밸리","ADDRESS":"성수동1가 13-170\n외9필지(13-170,13-166,13-472,13-169,13-256,13-164,13-253,13-171,13-255,13-167)","TELEPHONE":"(02) 2090-8202","APPROVAL_DATE":"2010.03.24.","COMPLE_DATE":"2013.02.08"},{"IDX":50.0,"FAC_NM":"JnK 디지털타워","ADDRESS":"구로3동 222-3","TELEPHONE":"6124-6611","APPROVAL_DATE":"2010.01.20","COMPLE_DATE":"2012.2.15"},{"IDX":121.0,"FAC_NM":"대성D-POLIS","ADDRESS":"가산동 543-1","TELEPHONE":"861-9114","APPROVAL_DATE":"2009.12","COMPLE_DATE":"2012.09"},{"IDX":159.0,"FAC_NM":"동아프라임밸리","ADDRESS":"영등포로5길19(양평동2가)","TELEPHONE":"6210-7201","APPROVAL_DATE":"2009.10.21","COMPLE_DATE":"2011.11.25"},{"IDX":161.0,"FAC_NM":"솔버스 비즈타워","ADDRESS":"선유서로31길3(양평동3가)","TELEPHONE":"6963-8080","APPROVAL_DATE":"2009.10.19","COMPLE_DATE":"2012.09.05"},{"IDX":212.0,"FAC_NM":"동대문패션비즈센터 ","ADDRESS":"신당동 251-160","TELEPHONE":"070-8895-7347","APPROVAL_DATE":"2009.05.14","COMPLE_DATE":"2012.03.07"},{"IDX":129.0,"FAC_NM":"현대지식산업센터","ADDRESS":"독산동 291-1 ","TELEPHONE":"858-3080","APPROVAL_DATE":"2009.04","COMPLE_DATE":"2014.03.04"},{"IDX":193.0,"FAC_NM":"이레타워","ADDRESS":"성수동2가 277-175번지","TELEPHONE":"(02) 466-2663","APPROVAL_DATE":"2009.01.22","COMPLE_DATE":"2009.08.07"},{"IDX":9.0,"FAC_NM":"강서한화비즈메트로2차","ADDRESS":"양천로551-24","TELEPHONE":"6957-1990","APPROVAL_DATE":"2008.7.25","COMPLE_DATE":"2012.1.16"},{"IDX":8.0,"FAC_NM":"강서한화비즈메트로1차","ADDRESS":"양천로551-17","TELEPHONE":"6957-1990","APPROVAL_DATE":"2008.7.25","COMPLE_DATE":"2012.1.13"},{"IDX":113.0,"FAC_NM":"알에스엠타워","ADDRESS":"가산동 327-29","TELEPHONE":"2112-6300","APPROVAL_DATE":"2008.12.03","COMPLE_DATE":"2012.12.18"},{"IDX":137.0,"FAC_NM":"가든파이브웍스","ADDRESS":"충민로52(문정동)","TELEPHONE":"02-2047-1014","APPROVAL_DATE":"2008.11.12","COMPLE_DATE":"2008.10.16"},{"IDX":47.0,"FAC_NM":"STX-W 타워","ADDRESS":"구로동 615-3외 4필지","TELEPHONE":"6124-3333","APPROVAL_DATE":"2008.10.23","COMPLE_DATE":"2011.10.30"},{"IDX":192.0,"FAC_NM":"서울숲 코오롱\n디지털타워2차","ADDRESS":"성수동2가 333-140번지","TELEPHONE":"(031) 727-1461","APPROVAL_DATE":"2008.10.21","COMPLE_DATE":"2010.09.10"},{"IDX":110.0,"FAC_NM":"에이스하이엔드7차","ADDRESS":"가산동 345-33","TELEPHONE":"6111-1500","APPROVAL_DATE":"2008.10.10","COMPLE_DATE":"2010.07"},{"IDX":191.0,"FAC_NM":"서울숲 코오롱\n디지털타워3차","ADDRESS":"성수동1가 14-18번지 외 1 필지","TELEPHONE":"(02) 499-0430","APPROVAL_DATE":"2008.10.02","COMPLE_DATE":"2010.11.24"},{"IDX":69.0,"FAC_NM":"엘리시아","ADDRESS":"가산동 60-69","TELEPHONE":"890-8888","APPROVAL_DATE":"2008.09.23","COMPLE_DATE":"2011.03"},{"IDX":190.0,"FAC_NM":"휴먼테코","ADDRESS":"성수동2가 281-16 번지 외 1 필지","TELEPHONE":"02)6466-5000","APPROVAL_DATE":"2008.09.12","COMPLE_DATE":"2010.06.07"},{"IDX":112.0,"FAC_NM":"KCC웰츠밸리","ADDRESS":"가산동 470-8","TELEPHONE":"6111-8100","APPROVAL_DATE":"2008.09.09","COMPLE_DATE":"2010.12"},{"IDX":68.0,"FAC_NM":"대륭포스트타워6차","ADDRESS":"가산동 50-3","TELEPHONE":"2083-5114","APPROVAL_DATE":"2008.09.05","COMPLE_DATE":"2010.08"},{"IDX":189.0,"FAC_NM":"서울숲 \n한라시그마밸리","ADDRESS":"성수동2가 325-2 번지 외 12 필지","TELEPHONE":"(02) 6466-8114","APPROVAL_DATE":"2008.09.03","COMPLE_DATE":"2011.02.16"},{"IDX":111.0,"FAC_NM":"더루벤스밸리","ADDRESS":"가산동 691-3","TELEPHONE":"2109-9800","APPROVAL_DATE":"2008.08.14","COMPLE_DATE":"2011.09"},{"IDX":49.0,"FAC_NM":"파트너스타워2차","ADDRESS":"구로동 1128-3","TELEPHONE":"2028-3993","APPROVAL_DATE":"2008.07.28","COMPLE_DATE":"2010.02.16"},{"IDX":108.0,"FAC_NM":"STX V-TOWER","ADDRESS":"가산동 371-37","TELEPHONE":"8111-3102","APPROVAL_DATE":"2008.07","COMPLE_DATE":"2010.11"},{"IDX":188.0,"FAC_NM":"한신 아크밸리","ADDRESS":"성수동2가 277-43번지","TELEPHONE":"(02) 421-2367","APPROVAL_DATE":"2008.05.26","COMPLE_DATE":"2010.05.27"},{"IDX":158.0,"FAC_NM":"양평동이노플렉스","ADDRESS":"양산로57-5(양평동3가)","TELEPHONE":"2675-0134","APPROVAL_DATE":"2008.05.14","COMPLE_DATE":"2010.01.20"},{"IDX":67.0,"FAC_NM":"갑을아파트형공장","ADDRESS":"가산동60-5","TELEPHONE":"3397-7705","APPROVAL_DATE":"2008.05.09","COMPLE_DATE":"2010.07"},{"IDX":107.0,"FAC_NM":"IT프리미어타워","ADDRESS":"가산동 345-50","TELEPHONE":"2621-1991","APPROVAL_DATE":"2008.04.24","COMPLE_DATE":"2010.02"},{"IDX":106.0,"FAC_NM":"에이스하이엔드8차","ADDRESS":"가산동 345-4","TELEPHONE":"6123-5000","APPROVAL_DATE":"2008.03.20","COMPLE_DATE":"2010.09"},{"IDX":105.0,"FAC_NM":"BYC하이씨티","ADDRESS":"가산동 371-17","TELEPHONE":"6947-3100","APPROVAL_DATE":"2008.03.12","COMPLE_DATE":"2012.02"},{"IDX":104.0,"FAC_NM":"INNOPLEX 2차","ADDRESS":"가산동 371-59","TELEPHONE":"6111-0123","APPROVAL_DATE":"2008.02.20","COMPLE_DATE":"2010.03"},{"IDX":66.0,"FAC_NM":"대륭포스트타워5차","ADDRESS":"가산동 60-3","TELEPHONE":"2624-4116","APPROVAL_DATE":"2008.02.19","COMPLE_DATE":"2010.01"},{"IDX":103.0,"FAC_NM":"파트너스타워","ADDRESS":"가산동 345-13","TELEPHONE":"859-5641","APPROVAL_DATE":"2008.02.12","COMPLE_DATE":"2009.10"},{"IDX":102.0,"FAC_NM":"한라시그마밸리","ADDRESS":"가산동 345-90 ","TELEPHONE":"6343-6800","APPROVAL_DATE":"2008.01.17","COMPLE_DATE":"2009.12"},{"IDX":101.0,"FAC_NM":"백상스타타워2차","ADDRESS":"가산동 459-22","TELEPHONE":"6111-6100","APPROVAL_DATE":"2007.12.06","COMPLE_DATE":"2010.07"},{"IDX":65.0,"FAC_NM":"백상스타타워1차","ADDRESS":"가산동 60-17","TELEPHONE":"6111-7116","APPROVAL_DATE":"2007.11.29","COMPLE_DATE":"2010.07"},{"IDX":46.0,"FAC_NM":"한화비즈 메트로1차","ADDRESS":"구로동 851외 2필지","TELEPHONE":"2621-2490","APPROVAL_DATE":"2007.11.20","COMPLE_DATE":"2010.12.28"},{"IDX":211.0,"FAC_NM":"아시아미디어타워","ADDRESS":"초동 42","TELEPHONE":"2275-3332","APPROVAL_DATE":"2007.11.13","COMPLE_DATE":"2009.12.01"},{"IDX":99.0,"FAC_NM":"디지털엠파이어","ADDRESS":"가산동 685","TELEPHONE":"2624-2121","APPROVAL_DATE":"2007.10.17","COMPLE_DATE":"2009.02"},{"IDX":98.0,"FAC_NM":"LG아파트형공장","ADDRESS":"가산동 459-9","TELEPHONE":"6945-4455","APPROVAL_DATE":"2007.10.12","COMPLE_DATE":"2009.04"},{"IDX":154.0,"FAC_NM":"선유도우림라이온스밸리A","ADDRESS":"양평로 149(양평동5가)","TELEPHONE":"2638-7114","APPROVAL_DATE":"2007.09.17","COMPLE_DATE":"2009.08.07"},{"IDX":155.0,"FAC_NM":"선유도우림라이온스밸리B","ADDRESS":"양평로21가길19(양평동5가)","TELEPHONE":"2638-7114","APPROVAL_DATE":"2007.09.17","COMPLE_DATE":"2009.08.07"},{"IDX":64.0,"FAC_NM":"에이스하이엔드6차","ADDRESS":"가산동 60-25","TELEPHONE":"6299-5100","APPROVAL_DATE":"2007.08.24","COMPLE_DATE":"2009.08"},{"IDX":157.0,"FAC_NM":"벽산디지털밸리","ADDRESS":"경인로71길 70(문래동5가)","TELEPHONE":"6098-5114","APPROVAL_DATE":"2007.08.24","COMPLE_DATE":"2009.12.17"},{"IDX":97.0,"FAC_NM":"에이스하이엔드5차","ADDRESS":"가산동 505-18","TELEPHONE":"6340-0200","APPROVAL_DATE":"2007.08.23","COMPLE_DATE":"2009.07"},{"IDX":96.0,"FAC_NM":"이앤씨드림타워8차","ADDRESS":"가산동 327-27","TELEPHONE":"6277-8200","APPROVAL_DATE":"2007.08.16","COMPLE_DATE":"2009.02"},{"IDX":109.0,"FAC_NM":"가산비즈니스센터","ADDRESS":"가산동 371-6 ","TELEPHONE":"3289-9114","APPROVAL_DATE":"2007.08.16","COMPLE_DATE":"2011.09"},{"IDX":100.0,"FAC_NM":"한국전자협동APT공장","ADDRESS":"가산동 371-51","TELEPHONE":"858-9261","APPROVAL_DATE":"2007.08.13","COMPLE_DATE":"2007.12.06"},{"IDX":156.0,"FAC_NM":"금강펜테리움IT타워","ADDRESS":"당산로 171(당산동4가)","TELEPHONE":"2638-8585","APPROVAL_DATE":"2007.07.24","COMPLE_DATE":"2010.01.08"},{"IDX":44.0,"FAC_NM":"벽산디지털밸리7차","ADDRESS":"구로동 170-13","TELEPHONE":"839-3152","APPROVAL_DATE":"2007.07.23","COMPLE_DATE":"2009.06.23"},{"IDX":95.0,"FAC_NM":"에이스하이엔드3차","ADDRESS":"가산동 371-51","TELEPHONE":"2624-1100","APPROVAL_DATE":"2007.06.13","COMPLE_DATE":"2009.07"},{"IDX":86.0,"FAC_NM":"INNOPLEX 1차","ADDRESS":"가산동 371-47","TELEPHONE":"6679-0007","APPROVAL_DATE":"2007.04.13","COMPLE_DATE":"2008.08.14"},{"IDX":94.0,"FAC_NM":"벽산디지털밸리6차","ADDRESS":"가산동 481-4","TELEPHONE":"869-1166","APPROVAL_DATE":"2007.04.04","COMPLE_DATE":"2009.03"},{"IDX":187.0,"FAC_NM":"서울숲 코오롱 1차","ADDRESS":"성수동2가 308-4번지","TELEPHONE":"시행사:2115-8899","APPROVAL_DATE":"2007.02.11","COMPLE_DATE":"2010.06.10"},{"IDX":7.0,"FAC_NM":"우림블루나인비즈니스센터","ADDRESS":"양천로 583","TELEPHONE":"2093-1011","APPROVAL_DATE":"2006.4.26","COMPLE_DATE":"2008.9.26"},{"IDX":93.0,"FAC_NM":"롯데IT캐슬2차","ADDRESS":"가산동 371-16","TELEPHONE":"2627-8114","APPROVAL_DATE":"2006.11.21","COMPLE_DATE":"2008.09"},{"IDX":63.0,"FAC_NM":"이앤씨드림타워7차","ADDRESS":"가산동 60-44","TELEPHONE":"6277-8200","APPROVAL_DATE":"2006.11.06","COMPLE_DATE":"2008.01"},{"IDX":43.0,"FAC_NM":"에이스하이엔드타워2차","ADDRESS":"구로동 222-14","TELEPHONE":"6340-5555","APPROVAL_DATE":"2006.08.17","COMPLE_DATE":"2008.04.15"},{"IDX":186.0,"FAC_NM":"아주디지털타워","ADDRESS":"성수동2가 284-56번지","TELEPHONE":"(02) 462-2235","APPROVAL_DATE":"2006.07.27","COMPLE_DATE":"2010.01.08"},{"IDX":213.0,"FAC_NM":"산타플러스","ADDRESS":"난곡로 60","TELEPHONE":"02-865-6976","APPROVAL_DATE":"2005.11.28","COMPLE_DATE":"2006.7.26"},{"IDX":92.0,"FAC_NM":"㈜동광인터내셔날","ADDRESS":"가산동 459-14","TELEPHONE":"3479-2700","APPROVAL_DATE":"2005.11.23","COMPLE_DATE":"2006.01"},{"IDX":152.0,"FAC_NM":"월드메르디앙비즈센터","ADDRESS":"양산로 53(양평동3가)","TELEPHONE":"2165-8980","APPROVAL_DATE":"2005.10.05","COMPLE_DATE":"2007.02.14"},{"IDX":61.0,"FAC_NM":"(주)한섬임대아파트형공장","ADDRESS":"가산동 60-42","TELEPHONE":"838-0146","APPROVAL_DATE":"2005.09.28","COMPLE_DATE":"2006.09"},{"IDX":41.0,"FAC_NM":"㈜대양디앤티","ADDRESS":"구로동 197-47","TELEPHONE":"858-2111","APPROVAL_DATE":"2005.09.09","COMPLE_DATE":"2007.08.07"},{"IDX":91.0,"FAC_NM":"승일벤쳐타워","ADDRESS":"가산동 371-42","TELEPHONE":"862-2351","APPROVAL_DATE":"2005.06.18","COMPLE_DATE":"2006.12"},{"IDX":42.0,"FAC_NM":"대륭포스트타워3차","ADDRESS":"구로동 182-4","TELEPHONE":"2028-0114","APPROVAL_DATE":"2005.06.10","COMPLE_DATE":"2007.06.07"},{"IDX":153.0,"FAC_NM":"에이스하이테크시티","ADDRESS":"경인로 775(문래동3가)","TELEPHONE":"6309-6112","APPROVAL_DATE":"2005.05.15","COMPLE_DATE":"2007.04.13"},{"IDX":90.0,"FAC_NM":"롯데정보통신","ADDRESS":"가산동 533-2","TELEPHONE":"2626-4000","APPROVAL_DATE":"2005.05.11","COMPLE_DATE":"2007.03"},{"IDX":134.0,"FAC_NM":"DMC 첨단산업센터","ADDRESS":"마포구 상암동 1580 \n첨단산업센터","TELEPHONE":"2171-2847","APPROVAL_DATE":"2004.11.03","COMPLE_DATE":"2008.03.31"},{"IDX":62.0,"FAC_NM":"IT미래타워","ADDRESS":"가산동 60-21","TELEPHONE":"2027-5757","APPROVAL_DATE":"2004.10.27","COMPLE_DATE":"2007.04.30"},{"IDX":89.0,"FAC_NM":"뉴티캐슬","ADDRESS":"가산동 429-1","TELEPHONE":"2626-9960","APPROVAL_DATE":"2004.08.11","COMPLE_DATE":"2006.12"},{"IDX":88.0,"FAC_NM":"대륭테크노타운13차","ADDRESS":"가산동 664","TELEPHONE":"2029-5600","APPROVAL_DATE":"2004.07.28","COMPLE_DATE":"2008.05"},{"IDX":185.0,"FAC_NM":"성수동\n 우림e-BIZ Center","ADDRESS":"성수동2가 280-21번지","TELEPHONE":"(02)2024-2110","APPROVAL_DATE":"2004.07.26","COMPLE_DATE":"2006.10.18"},{"IDX":132.0,"FAC_NM":"중계제1공단","ADDRESS":"노원구 노원로19길 31(중계동)\n[중계동 511-2]","TELEPHONE":"948-2846","APPROVAL_DATE":"2004.07.13","COMPLE_DATE":"1991.12.07"},{"IDX":130.0,"FAC_NM":"월계테크노타운","ADDRESS":"노원구 월계로45길 28(월계동)\n[월계동 562번지]","TELEPHONE":"990-2727","APPROVAL_DATE":"2004.07.08","COMPLE_DATE":"1994.12.19"},{"IDX":87.0,"FAC_NM":"대륭테크노타운12차","ADDRESS":"가산동 327-32","TELEPHONE":"2029-6114","APPROVAL_DATE":"2004.07.08","COMPLE_DATE":"2008.05"},{"IDX":131.0,"FAC_NM":"하계테크노타운","ADDRESS":"노원구 노원로15길 10(하계동)\n[하계동 250-3]","TELEPHONE":"6235-3500","APPROVAL_DATE":"2004.07.07","COMPLE_DATE":"1998.11.17"},{"IDX":184.0,"FAC_NM":"풍림테크원","ADDRESS":"성수동2가 273-10번지","TELEPHONE":"(02) 468-9319/464-0133","APPROVAL_DATE":"2004.05.31","COMPLE_DATE":"2005.09.15"},{"IDX":31.0,"FAC_NM":"이앤씨드림타워6차","ADDRESS":"구로동 197-28","TELEPHONE":"801-8603","APPROVAL_DATE":"2004.05.10","COMPLE_DATE":"2005.12.21"},{"IDX":39.0,"FAC_NM":"대륭포스트타워2차","ADDRESS":"구로동 182-13","TELEPHONE":"2082-0114","APPROVAL_DATE":"2004.03.24","COMPLE_DATE":"2005.10.06"},{"IDX":60.0,"FAC_NM":"스타밸리","ADDRESS":"가산동 60-11","TELEPHONE":"2027-0114","APPROVAL_DATE":"2004.02.27","COMPLE_DATE":"2006.04"},{"IDX":37.0,"FAC_NM":"코오롱빌란트2차","ADDRESS":"구로동 222-8","TELEPHONE":"2081-1111","APPROVAL_DATE":"2004.02.25","COMPLE_DATE":"2006.12.28"},{"IDX":38.0,"FAC_NM":"대륭포스트타워1차","ADDRESS":"구로동 212-8","TELEPHONE":"2082-2331","APPROVAL_DATE":"2004.01.10","COMPLE_DATE":"2005.10.18"},{"IDX":36.0,"FAC_NM":"코오롱싸이언스밸리2차","ADDRESS":"구로동 811","TELEPHONE":"850-3150","APPROVAL_DATE":"2003.12.30","COMPLE_DATE":"2005.12.13"},{"IDX":34.0,"FAC_NM":"에이스하이엔드1차","ADDRESS":"구로동 235-2","TELEPHONE":"6220-2010","APPROVAL_DATE":"2003.12.30","COMPLE_DATE":"2005.09.30"},{"IDX":150.0,"FAC_NM":"메가벤처타워","ADDRESS":"문래로20길60(문래동3가)","TELEPHONE":"2632-4438","APPROVAL_DATE":"2003.12.22","COMPLE_DATE":"2005.12.27"},{"IDX":79.0,"FAC_NM":"롯데IT캐슬","ADDRESS":"가산동 550-1","TELEPHONE":"2026-8970","APPROVAL_DATE":"2003.12.20","COMPLE_DATE":"2005.09"},{"IDX":30.0,"FAC_NM":"이앤씨드림타워5차","ADDRESS":"구로동 197-13","TELEPHONE":"6336-3591","APPROVAL_DATE":"2003.12.19","COMPLE_DATE":"2004.12.14"},{"IDX":59.0,"FAC_NM":"벽산디지털밸리5차","ADDRESS":"가산동 60-73","TELEPHONE":"2082-5990","APPROVAL_DATE":"2003.11.05","COMPLE_DATE":"2005.10"},{"IDX":33.0,"FAC_NM":"마리오디지털밸리","ADDRESS":"구로동 222-12","TELEPHONE":"890-8498","APPROVAL_DATE":"2003.10.13","COMPLE_DATE":"2005.10.25"},{"IDX":85.0,"FAC_NM":"코오롱디지털타워애스톤","ADDRESS":"가산동 505-14","TELEPHONE":"2082-8114","APPROVAL_DATE":"2003.09.26","COMPLE_DATE":"2005.09"},{"IDX":84.0,"FAC_NM":"에이스테크노타워10차","ADDRESS":"가산동 470-5","TELEPHONE":"6670-5300","APPROVAL_DATE":"2003.09.16","COMPLE_DATE":"2005.07"},{"IDX":35.0,"FAC_NM":"코오롱싸이언스밸리1차","ADDRESS":"구로동 187-10","TELEPHONE":"2025-4580","APPROVAL_DATE":"2003.08.08","COMPLE_DATE":"2005.07.05"},{"IDX":40.0,"FAC_NM":"삼성IT밸리","ADDRESS":"구로동 197-5","TELEPHONE":"2028-2363","APPROVAL_DATE":"2003.07.20","COMPLE_DATE":"2007.03.30"},{"IDX":149.0,"FAC_NM":"문래동빅토리테크노타워","ADDRESS":"선유서로 17(문래동5가)","TELEPHONE":"2068-8212","APPROVAL_DATE":"2003.07.08","COMPLE_DATE":"2004.10.08"},{"IDX":183.0,"FAC_NM":"(주)삼우","ADDRESS":"성수동2가 272-38번지","TELEPHONE":"(02) 2274-2734","APPROVAL_DATE":"2003.06.30","COMPLE_DATE":"2003.12.17"},{"IDX":83.0,"FAC_NM":"에이스테크노타워9차","ADDRESS":"가산동 345-30","TELEPHONE":"2026-1900","APPROVAL_DATE":"2003.06.30","COMPLE_DATE":"2005.07"},{"IDX":181.0,"FAC_NM":"영동테크노타워","ADDRESS":"성수동2가 300-4번지","TELEPHONE":"(02) 2118-7012","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2003.06.20"},{"IDX":182.0,"FAC_NM":"삼환디지털\n벤처타워","ADDRESS":"성수동2가 280-13번지","TELEPHONE":"2024-0020(관리실)","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2006.01.19"},{"IDX":82.0,"FAC_NM":"제이플라츠","ADDRESS":"가산동 459-11 ","TELEPHONE":"2028-5000","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2007.04"},{"IDX":29.0,"FAC_NM":"이앤씨드림타워3차","ADDRESS":"구로동 197-33","TELEPHONE":"6330-2302","APPROVAL_DATE":"2003.06.13","COMPLE_DATE":"2004.09.08"},{"IDX":81.0,"FAC_NM":"우림라이온스밸리2차","ADDRESS":"가산동 680","TELEPHONE":"2027-2114","APPROVAL_DATE":"2003.05.28","COMPLE_DATE":"2006.05"},{"IDX":28.0,"FAC_NM":"이앤씨드림타워2차","ADDRESS":"구로동 197-10","TELEPHONE":"6330-2200","APPROVAL_DATE":"2003.05.07","COMPLE_DATE":"2004.09.08"},{"IDX":80.0,"FAC_NM":"호서대벤처타워","ADDRESS":"가산동 319","TELEPHONE":"2627-5980","APPROVAL_DATE":"2003.04.24.","COMPLE_DATE":"2008.10.07"},{"IDX":58.0,"FAC_NM":"SJ테크노빌","ADDRESS":"가산동 60-19","

In [147]:
data = response.json()
rows = data['InfoBizcenterApply']['row']
print(rows)

center_df = pd.DataFrame(rows)
center_df

[{'IDX': 208.0, 'FAC_NM': '신내테크노타운', 'ADDRESS': '봉화산로 123(상봉동)', 'TELEPHONE': '02)3423-0057', 'APPROVAL_DATE': '96.5.28', 'COMPLE_DATE': '99.10.18'}, {'IDX': 136.0, 'FAC_NM': '월곡동아파트형공장', 'ADDRESS': '하월곡동 96-113', 'TELEPHONE': '02-090-8083', 'APPROVAL_DATE': '33289', 'COMPLE_DATE': '1990.12.31'}, {'IDX': 135.0, 'FAC_NM': '월곡동아파트형공장', 'ADDRESS': '하월곡동 96-113', 'TELEPHONE': '02-912-1034', 'APPROVAL_DATE': '33289', 'COMPLE_DATE': '1990.12.31'}, {'IDX': 140.0, 'FAC_NM': '문정아르페온 1차 지식산업센터', 'ADDRESS': '서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)', 'TELEPHONE': '031-706-8577', 'APPROVAL_DATE': '2016.06.27', 'COMPLE_DATE': '2016.06.27'}, {'IDX': 139.0, 'FAC_NM': '문정 대명벨리온', 'ADDRESS': '서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)', 'TELEPHONE': '02-2222-7357', 'APPROVAL_DATE': '2016.03.23', 'COMPLE_DATE': '2016.03.23'}, {'IDX': 141.0, 'FAC_NM': '문정 현대지식산업센터Ｉ-1', 'ADDRESS': '서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)', 'TELEPHONE': '02-3451-0100', 'APPROVAL_DATE': '2016.02.29', 'COMPLE_DATE': '2016.02.29'}, {'IDX': 138.0, 'FAC_NM': '송파유탑테크밸리', 'ADDRESS': '서울특별시 송파구 문정동 651-14 (문정도시개발구역 3-12BL)', 'TELEPHONE': '062-526-8383', 'APPROVAL_DATE': '2015.12.18', 'COMPLE_DATE': '2015.12.18'}, {'IDX': 207.0, 'FAC_NM': '포휴', 'ADDRESS': '성수동1가 656-3', 'TELEPHONE': '3416-1500', 'APPROVAL_DATE': '2013.08.30', 'COMPLE_DATE': '2016.5.3'}, {'IDX': 117.0, 'FAC_NM': '에이스하이엔드타워 10차', 'ADDRESS': '가산동 660', 'TELEPHONE': '6309-6045', 'APPROVAL_DATE': '2013.08.29', 'COMPLE_DATE': '2015.10.28'}, {'IDX': 206.0, 'FAC_NM': 'BY센터', 'ADDRESS': '성수동2가 301-51,301-38', 'TELEPHONE': '(02) 467-2247', 'APPROVAL_DATE': '2013.08.12', 'COMPLE_DATE': '2015.12.04'}, {'IDX': 205.0, 'FAC_NM': '신한IT타워', 'ADDRESS': '성수동1가 656-603', 'TELEPHONE': '', 'APPROVAL_DATE': '2013.07.02', 'COMPLE_DATE': '2015.06.04'}, {'IDX': 116.0, 'FAC_NM': '에스비즈니스센터', 'ADDRESS': '가산동 343-8', 'TELEPHONE': '2163-6749', 'APPROVAL_DATE': '2013.03.26', 'COMPLE_DATE': '2015.06.01'}, {'IDX': 165.0, 'FAC_NM': '선유도역2차 아이에스비즈타워', 'ADDRESS': '선유로49길 23(양평동4가)', 'TELEPHONE': '6123-4100', 'APPROVAL_DATE': '2012.12.18', 'COMPLE_DATE': '2014.11.19'}, {'IDX': 115.0, 'FAC_NM': '대륭테크노타운17차', 'ADDRESS': '가산동 670', 'TELEPHONE': '3466-0051', 'APPROVAL_DATE': '2012.12.10', 'COMPLE_DATE': '2015.05.15'}, {'IDX': 204.0, 'FAC_NM': '서울숲\n드림타워(삼공)', 'ADDRESS': '성수동2가 323, 309-51', 'TELEPHONE': '(02)6222-8114', 'APPROVAL_DATE': '2012.10.31', 'COMPLE_DATE': '2015.03.23'}, {'IDX': 164.0, 'FAC_NM': '에이스하이테크시티 2', 'ADDRESS': '선유로13길 25(문래동6가)', 'TELEPHONE': '2257-8114', 'APPROVAL_DATE': '2012.08.27', 'COMPLE_DATE': '2014.10.24'}, {'IDX': 2.0, 'FAC_NM': 'NICE그룹 지식산업센터', 'ADDRESS': '상일로6길 55 (상일동)', 'TELEPHONE': '2122-4415', 'APPROVAL_DATE': '2012.06.29', 'COMPLE_DATE': '2014.02.28'}, {'IDX': 166.0, 'FAC_NM': 'SK V1 center', 'ADDRESS': '당산로41길 11(당산동4가)', 'TELEPHONE': '6121-8100', 'APPROVAL_DATE': '2012.06.19', 'COMPLE_DATE': '2015.02.17'}, {'IDX': 203.0, 'FAC_NM': '서울숲IT캐슬', 'ADDRESS': '성수동1가 671-6, -41 외 4필지', 'TELEPHONE': '(02) 2086-3346', 'APPROVAL_DATE': '2012.05.10', 'COMPLE_DATE': '2014.06.17'}, {'IDX': 1.0, 'FAC_NM': '세종투자㈜', 'ADDRESS': '강동구 상일로10길 36 (상일동)', 'TELEPHONE': '3415-4971', 'APPROVAL_DATE': '2011.11.30', 'COMPLE_DATE': '2013.09.13'}, {'IDX': 202.0, 'FAC_NM': '에이스하이앤드\n 성수타워', 'ADDRESS': '성수동2가 269-25,269-51,\n269-115,328-5', 'TELEPHONE': '(02) 2112-6491', 'APPROVAL_DATE': '2011.11.15', 'COMPLE_DATE': '2015.06.19'}, {'IDX': 201.0, 'FAC_NM': '에이스성수타워1차', 'ADDRESS': '성수2가 280-15,19', 'TELEPHONE': '(02) 591-0607', 'APPROVAL_DATE': '2011.10.20', 'COMPLE_DATE': '2014.03.11'}, {'IDX': 52.0, 'FAC_NM': 'G플러스 코오롱 디지털타워', 'ADDRESS': '구로동 222-31', 'TELEPHONE': '858-3650', 'APPROVAL_DATE': '2011.06.09', 'COMPLE_DATE': '2013.7.24'}, {'IDX': 163.0, 'FAC_NM': '선유도역1차 아이에스비즈타워', 'ADDRESS': '양평로21길 26(양평동5가)', 'TELEPHONE': '6968-1004', 'APPROVAL_DATE': '2011.04.21', 'COMPLE_DATE': '2013.5.27'}, {'IDX': 200.0, 'FAC_NM': '서울숲\n한라시그마밸리II', 'ADDRESS': '성수동2가 333-15', 'TELEPHONE': '(02) 4199-5621', 'APPROVAL_DATE': '2011.02.25', 'COMPLE_DATE': '2013.03.28'}, {'IDX': 51.0, 'FAC_NM': '대륭포스트타워7차', 'ADDRESS': '구로동 170-10 외 2필지', 'TELEPHONE': '6942-9500', 'APPROVAL_DATE': '2011.02.21', 'COMPLE_DATE': '2012.12.11'}, {'IDX': 10.0, 'FAC_NM': '강서IT밸리', 'ADDRESS': '화곡로68길 82', 'TELEPHONE': '6961-5111', 'APPROVAL_DATE': '2010.3.9', 'COMPLE_DATE': '2012.2.6'}, {'IDX': 11.0, 'FAC_NM': '강서한강자이', 'ADDRESS': '양천로 401', 'TELEPHONE': '6968-5801~2', 'APPROVAL_DATE': '2010.10.15', 'COMPLE_DATE': '2013.6.7'}, {'IDX': 199.0, 'FAC_NM': '서울숲 \n한라에코벨리', 'ADDRESS': '성수동1가 656-36\n656-1222', 'TELEPHONE': '(02) 549-6693', 'APPROVAL_DATE': '2010.09.09', 'COMPLE_DATE': '2012.09.06'}, {'IDX': 198.0, 'FAC_NM': '성수동\n아이에스비즈타워', 'ADDRESS': '성수동2가289-319,327,328', 'TELEPHONE': '(02) 3218-6643', 'APPROVAL_DATE': '2010.08.28', 'COMPLE_DATE': '2012.07.23'}, {'IDX': 162.0, 'FAC_NM': 'KnK디지털타워', 'ADDRESS': '영신로 220(영등포동8가)', 'TELEPHONE': '2675-6060', 'APPROVAL_DATE': '2010.08.27', 'COMPLE_DATE': '2012.12.07'}, {'IDX': 167.0, 'FAC_NM': '문래동 하우스디 비즈', 'ADDRESS': '선유로3길 10(문래동5가)', 'TELEPHONE': '2112-6339', 'APPROVAL_DATE': '2010.08.10', 'COMPLE_DATE': '2016.05.09'}, {'IDX': 160.0, 'FAC_NM': '선유도코오롱디지털타워', 'ADDRESS': '양평로22길21(양평동5가)', 'TELEPHONE': '2062-5996', 'APPROVAL_DATE': '2010.07.13', 'COMPLE_DATE': '2012.03.23'}, {'IDX': 197.0, 'FAC_NM': '성수에이팩센터', 'ADDRESS': '성수동2가 289-5\n289-334,289-335', 'TELEPHONE': '(02) 3416-1541', 'APPROVAL_DATE': '2010.06.24', 'COMPLE_DATE': '2012.08.24'}, {'IDX': 196.0, 'FAC_NM': '아연디지털타워', 'ADDRESS': '성수동2가314-37', 'TELEPHONE': '(02) 499-2275', 'APPROVAL_DATE': '2010.06.01', 'COMPLE_DATE': '2012.08.31'}, {'IDX': 195.0, 'FAC_NM': '서울숲 SK V1 타워', 'ADDRESS': '성수동2가284-55, 284-107', 'TELEPHONE': '(02) 6233-8000', 'APPROVAL_DATE': '2010.04.13', 'COMPLE_DATE': '2014.07.18'}, {'IDX': 114.0, 'FAC_NM': '에이스하이엔드9차', 'ADDRESS': '가산동 481-2', 'TELEPHONE': '6309-6051', 'APPROVAL_DATE': '2010.04', 'COMPLE_DATE': '2012.07.20'}, {'IDX': 194.0, 'FAC_NM': '서울숲\nIT 밸리', 'ADDRESS': '성수동1가 13-170\n외9필지(13-170,13-166,13-472,13-169,13-256,13-164,13-253,13-171,13-255,13-167)', 'TELEPHONE': '(02) 2090-8202', 'APPROVAL_DATE': '2010.03.24.', 'COMPLE_DATE': '2013.02.08'}, {'IDX': 50.0, 'FAC_NM': 'JnK 디지털타워', 'ADDRESS': '구로3동 222-3', 'TELEPHONE': '6124-6611', 'APPROVAL_DATE': '2010.01.20', 'COMPLE_DATE': '2012.2.15'}, {'IDX': 121.0, 'FAC_NM': '대성D-POLIS', 'ADDRESS': '가산동 543-1', 'TELEPHONE': '861-9114', 'APPROVAL_DATE': '2009.12', 'COMPLE_DATE': '2012.09'}, {'IDX': 159.0, 'FAC_NM': '동아프라임밸리', 'ADDRESS': '영등포로5길19(양평동2가)', 'TELEPHONE': '6210-7201', 'APPROVAL_DATE': '2009.10.21', 'COMPLE_DATE': '2011.11.25'}, {'IDX': 161.0, 'FAC_NM': '솔버스 비즈타워', 'ADDRESS': '선유서로31길3(양평동3가)', 'TELEPHONE': '6963-8080', 'APPROVAL_DATE': '2009.10.19', 'COMPLE_DATE': '2012.09.05'}, {'IDX': 212.0, 'FAC_NM': '동대문패션비즈센터 ', 'ADDRESS': '신당동 251-160', 'TELEPHONE': '070-8895-7347', 'APPROVAL_DATE': '2009.05.14', 'COMPLE_DATE': '2012.03.07'}, {'IDX': 129.0, 'FAC_NM': '현대지식산업센터', 'ADDRESS': '독산동 291-1 ', 'TELEPHONE': '858-3080', 'APPROVAL_DATE': '2009.04', 'COMPLE_DATE': '2014.03.04'}, {'IDX': 193.0, 'FAC_NM': '이레타워', 'ADDRESS': '성수동2가 277-175번지', 'TELEPHONE': '(02) 466-2663', 'APPROVAL_DATE': '2009.01.22', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 9.0, 'FAC_NM': '강서한화비즈메트로2차', 'ADDRESS': '양천로551-24', 'TELEPHONE': '6957-1990', 'APPROVAL_DATE': '2008.7.25', 'COMPLE_DATE': '2012.1.16'}, {'IDX': 8.0, 'FAC_NM': '강서한화비즈메트로1차', 'ADDRESS': '양천로551-17', 'TELEPHONE': '6957-1990', 'APPROVAL_DATE': '2008.7.25', 'COMPLE_DATE': '2012.1.13'}, {'IDX': 113.0, 'FAC_NM': '알에스엠타워', 'ADDRESS': '가산동 327-29', 'TELEPHONE': '2112-6300', 'APPROVAL_DATE': '2008.12.03', 'COMPLE_DATE': '2012.12.18'}, {'IDX': 137.0, 'FAC_NM': '가든파이브웍스', 'ADDRESS': '충민로52(문정동)', 'TELEPHONE': '02-2047-1014', 'APPROVAL_DATE': '2008.11.12', 'COMPLE_DATE': '2008.10.16'}, {'IDX': 47.0, 'FAC_NM': 'STX-W 타워', 'ADDRESS': '구로동 615-3외 4필지', 'TELEPHONE': '6124-3333', 'APPROVAL_DATE': '2008.10.23', 'COMPLE_DATE': '2011.10.30'}, {'IDX': 192.0, 'FAC_NM': '서울숲 코오롱\n디지털타워2차', 'ADDRESS': '성수동2가 333-140번지', 'TELEPHONE': '(031) 727-1461', 'APPROVAL_DATE': '2008.10.21', 'COMPLE_DATE': '2010.09.10'}, {'IDX': 110.0, 'FAC_NM': '에이스하이엔드7차', 'ADDRESS': '가산동 345-33', 'TELEPHONE': '6111-1500', 'APPROVAL_DATE': '2008.10.10', 'COMPLE_DATE': '2010.07'}, {'IDX': 191.0, 'FAC_NM': '서울숲 코오롱\n디지털타워3차', 'ADDRESS': '성수동1가 14-18번지 외 1 필지', 'TELEPHONE': '(02) 499-0430', 'APPROVAL_DATE': '2008.10.02', 'COMPLE_DATE': '2010.11.24'}, {'IDX': 69.0, 'FAC_NM': '엘리시아', 'ADDRESS': '가산동 60-69', 'TELEPHONE': '890-8888', 'APPROVAL_DATE': '2008.09.23', 'COMPLE_DATE': '2011.03'}, {'IDX': 190.0, 'FAC_NM': '휴먼테코', 'ADDRESS': '성수동2가 281-16 번지 외 1 필지', 'TELEPHONE': '02)6466-5000', 'APPROVAL_DATE': '2008.09.12', 'COMPLE_DATE': '2010.06.07'}, {'IDX': 112.0, 'FAC_NM': 'KCC웰츠밸리', 'ADDRESS': '가산동 470-8', 'TELEPHONE': '6111-8100', 'APPROVAL_DATE': '2008.09.09', 'COMPLE_DATE': '2010.12'}, {'IDX': 68.0, 'FAC_NM': '대륭포스트타워6차', 'ADDRESS': '가산동 50-3', 'TELEPHONE': '2083-5114', 'APPROVAL_DATE': '2008.09.05', 'COMPLE_DATE': '2010.08'}, {'IDX': 189.0, 'FAC_NM': '서울숲 \n한라시그마밸리', 'ADDRESS': '성수동2가 325-2 번지 외 12 필지', 'TELEPHONE': '(02) 6466-8114', 'APPROVAL_DATE': '2008.09.03', 'COMPLE_DATE': '2011.02.16'}, {'IDX': 111.0, 'FAC_NM': '더루벤스밸리', 'ADDRESS': '가산동 691-3', 'TELEPHONE': '2109-9800', 'APPROVAL_DATE': '2008.08.14', 'COMPLE_DATE': '2011.09'}, {'IDX': 49.0, 'FAC_NM': '파트너스타워2차', 'ADDRESS': '구로동 1128-3', 'TELEPHONE': '2028-3993', 'APPROVAL_DATE': '2008.07.28', 'COMPLE_DATE': '2010.02.16'}, {'IDX': 108.0, 'FAC_NM': 'STX V-TOWER', 'ADDRESS': '가산동 371-37', 'TELEPHONE': '8111-3102', 'APPROVAL_DATE': '2008.07', 'COMPLE_DATE': '2010.11'}, {'IDX': 188.0, 'FAC_NM': '한신 아크밸리', 'ADDRESS': '성수동2가 277-43번지', 'TELEPHONE': '(02) 421-2367', 'APPROVAL_DATE': '2008.05.26', 'COMPLE_DATE': '2010.05.27'}, {'IDX': 158.0, 'FAC_NM': '양평동이노플렉스', 'ADDRESS': '양산로57-5(양평동3가)', 'TELEPHONE': '2675-0134', 'APPROVAL_DATE': '2008.05.14', 'COMPLE_DATE': '2010.01.20'}, {'IDX': 67.0, 'FAC_NM': '갑을아파트형공장', 'ADDRESS': '가산동60-5', 'TELEPHONE': '3397-7705', 'APPROVAL_DATE': '2008.05.09', 'COMPLE_DATE': '2010.07'}, {'IDX': 107.0, 'FAC_NM': 'IT프리미어타워', 'ADDRESS': '가산동 345-50', 'TELEPHONE': '2621-1991', 'APPROVAL_DATE': '2008.04.24', 'COMPLE_DATE': '2010.02'}, {'IDX': 106.0, 'FAC_NM': '에이스하이엔드8차', 'ADDRESS': '가산동 345-4', 'TELEPHONE': '6123-5000', 'APPROVAL_DATE': '2008.03.20', 'COMPLE_DATE': '2010.09'}, {'IDX': 105.0, 'FAC_NM': 'BYC하이씨티', 'ADDRESS': '가산동 371-17', 'TELEPHONE': '6947-3100', 'APPROVAL_DATE': '2008.03.12', 'COMPLE_DATE': '2012.02'}, {'IDX': 104.0, 'FAC_NM': 'INNOPLEX 2차', 'ADDRESS': '가산동 371-59', 'TELEPHONE': '6111-0123', 'APPROVAL_DATE': '2008.02.20', 'COMPLE_DATE': '2010.03'}, {'IDX': 66.0, 'FAC_NM': '대륭포스트타워5차', 'ADDRESS': '가산동 60-3', 'TELEPHONE': '2624-4116', 'APPROVAL_DATE': '2008.02.19', 'COMPLE_DATE': '2010.01'}, {'IDX': 103.0, 'FAC_NM': '파트너스타워', 'ADDRESS': '가산동 345-13', 'TELEPHONE': '859-5641', 'APPROVAL_DATE': '2008.02.12', 'COMPLE_DATE': '2009.10'}, {'IDX': 102.0, 'FAC_NM': '한라시그마밸리', 'ADDRESS': '가산동 345-90 ', 'TELEPHONE': '6343-6800', 'APPROVAL_DATE': '2008.01.17', 'COMPLE_DATE': '2009.12'}, {'IDX': 101.0, 'FAC_NM': '백상스타타워2차', 'ADDRESS': '가산동 459-22', 'TELEPHONE': '6111-6100', 'APPROVAL_DATE': '2007.12.06', 'COMPLE_DATE': '2010.07'}, {'IDX': 65.0, 'FAC_NM': '백상스타타워1차', 'ADDRESS': '가산동 60-17', 'TELEPHONE': '6111-7116', 'APPROVAL_DATE': '2007.11.29', 'COMPLE_DATE': '2010.07'}, {'IDX': 46.0, 'FAC_NM': '한화비즈 메트로1차', 'ADDRESS': '구로동 851외 2필지', 'TELEPHONE': '2621-2490', 'APPROVAL_DATE': '2007.11.20', 'COMPLE_DATE': '2010.12.28'}, {'IDX': 211.0, 'FAC_NM': '아시아미디어타워', 'ADDRESS': '초동 42', 'TELEPHONE': '2275-3332', 'APPROVAL_DATE': '2007.11.13', 'COMPLE_DATE': '2009.12.01'}, {'IDX': 99.0, 'FAC_NM': '디지털엠파이어', 'ADDRESS': '가산동 685', 'TELEPHONE': '2624-2121', 'APPROVAL_DATE': '2007.10.17', 'COMPLE_DATE': '2009.02'}, {'IDX': 98.0, 'FAC_NM': 'LG아파트형공장', 'ADDRESS': '가산동 459-9', 'TELEPHONE': '6945-4455', 'APPROVAL_DATE': '2007.10.12', 'COMPLE_DATE': '2009.04'}, {'IDX': 154.0, 'FAC_NM': '선유도우림라이온스밸리A', 'ADDRESS': '양평로 149(양평동5가)', 'TELEPHONE': '2638-7114', 'APPROVAL_DATE': '2007.09.17', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 155.0, 'FAC_NM': '선유도우림라이온스밸리B', 'ADDRESS': '양평로21가길19(양평동5가)', 'TELEPHONE': '2638-7114', 'APPROVAL_DATE': '2007.09.17', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 64.0, 'FAC_NM': '에이스하이엔드6차', 'ADDRESS': '가산동 60-25', 'TELEPHONE': '6299-5100', 'APPROVAL_DATE': '2007.08.24', 'COMPLE_DATE': '2009.08'}, {'IDX': 157.0, 'FAC_NM': '벽산디지털밸리', 'ADDRESS': '경인로71길 70(문래동5가)', 'TELEPHONE': '6098-5114', 'APPROVAL_DATE': '2007.08.24', 'COMPLE_DATE': '2009.12.17'}, {'IDX': 97.0, 'FAC_NM': '에이스하이엔드5차', 'ADDRESS': '가산동 505-18', 'TELEPHONE': '6340-0200', 'APPROVAL_DATE': '2007.08.23', 'COMPLE_DATE': '2009.07'}, {'IDX': 96.0, 'FAC_NM': '이앤씨드림타워8차', 'ADDRESS': '가산동 327-27', 'TELEPHONE': '6277-8200', 'APPROVAL_DATE': '2007.08.16', 'COMPLE_DATE': '2009.02'}, {'IDX': 109.0, 'FAC_NM': '가산비즈니스센터', 'ADDRESS': '가산동 371-6 ', 'TELEPHONE': '3289-9114', 'APPROVAL_DATE': '2007.08.16', 'COMPLE_DATE': '2011.09'}, {'IDX': 100.0, 'FAC_NM': '한국전자협동APT공장', 'ADDRESS': '가산동 371-51', 'TELEPHONE': '858-9261', 'APPROVAL_DATE': '2007.08.13', 'COMPLE_DATE': '2007.12.06'}, {'IDX': 156.0, 'FAC_NM': '금강펜테리움IT타워', 'ADDRESS': '당산로 171(당산동4가)', 'TELEPHONE': '2638-8585', 'APPROVAL_DATE': '2007.07.24', 'COMPLE_DATE': '2010.01.08'}, {'IDX': 44.0, 'FAC_NM': '벽산디지털밸리7차', 'ADDRESS': '구로동 170-13', 'TELEPHONE': '839-3152', 'APPROVAL_DATE': '2007.07.23', 'COMPLE_DATE': '2009.06.23'}, {'IDX': 95.0, 'FAC_NM': '에이스하이엔드3차', 'ADDRESS': '가산동 371-51', 'TELEPHONE': '2624-1100', 'APPROVAL_DATE': '2007.06.13', 'COMPLE_DATE': '2009.07'}, {'IDX': 86.0, 'FAC_NM': 'INNOPLEX 1차', 'ADDRESS': '가산동 371-47', 'TELEPHONE': '6679-0007', 'APPROVAL_DATE': '2007.04.13', 'COMPLE_DATE': '2008.08.14'}, {'IDX': 94.0, 'FAC_NM': '벽산디지털밸리6차', 'ADDRESS': '가산동 481-4', 'TELEPHONE': '869-1166', 'APPROVAL_DATE': '2007.04.04', 'COMPLE_DATE': '2009.03'}, {'IDX': 187.0, 'FAC_NM': '서울숲 코오롱 1차', 'ADDRESS': '성수동2가 308-4번지', 'TELEPHONE': '시행사:2115-8899', 'APPROVAL_DATE': '2007.02.11', 'COMPLE_DATE': '2010.06.10'}, {'IDX': 7.0, 'FAC_NM': '우림블루나인비즈니스센터', 'ADDRESS': '양천로 583', 'TELEPHONE': '2093-1011', 'APPROVAL_DATE': '2006.4.26', 'COMPLE_DATE': '2008.9.26'}, {'IDX': 93.0, 'FAC_NM': '롯데IT캐슬2차', 'ADDRESS': '가산동 371-16', 'TELEPHONE': '2627-8114', 'APPROVAL_DATE': '2006.11.21', 'COMPLE_DATE': '2008.09'}, {'IDX': 63.0, 'FAC_NM': '이앤씨드림타워7차', 'ADDRESS': '가산동 60-44', 'TELEPHONE': '6277-8200', 'APPROVAL_DATE': '2006.11.06', 'COMPLE_DATE': '2008.01'}, {'IDX': 43.0, 'FAC_NM': '에이스하이엔드타워2차', 'ADDRESS': '구로동 222-14', 'TELEPHONE': '6340-5555', 'APPROVAL_DATE': '2006.08.17', 'COMPLE_DATE': '2008.04.15'}, {'IDX': 186.0, 'FAC_NM': '아주디지털타워', 'ADDRESS': '성수동2가 284-56번지', 'TELEPHONE': '(02) 462-2235', 'APPROVAL_DATE': '2006.07.27', 'COMPLE_DATE': '2010.01.08'}, {'IDX': 213.0, 'FAC_NM': '산타플러스', 'ADDRESS': '난곡로 60', 'TELEPHONE': '02-865-6976', 'APPROVAL_DATE': '2005.11.28', 'COMPLE_DATE': '2006.7.26'}, {'IDX': 92.0, 'FAC_NM': '㈜동광인터내셔날', 'ADDRESS': '가산동 459-14', 'TELEPHONE': '3479-2700', 'APPROVAL_DATE': '2005.11.23', 'COMPLE_DATE': '2006.01'}, {'IDX': 152.0, 'FAC_NM': '월드메르디앙비즈센터', 'ADDRESS': '양산로 53(양평동3가)', 'TELEPHONE': '2165-8980', 'APPROVAL_DATE': '2005.10.05', 'COMPLE_DATE': '2007.02.14'}, {'IDX': 61.0, 'FAC_NM': '(주)한섬임대아파트형공장', 'ADDRESS': '가산동 60-42', 'TELEPHONE': '838-0146', 'APPROVAL_DATE': '2005.09.28', 'COMPLE_DATE': '2006.09'}, {'IDX': 41.0, 'FAC_NM': '㈜대양디앤티', 'ADDRESS': '구로동 197-47', 'TELEPHONE': '858-2111', 'APPROVAL_DATE': '2005.09.09', 'COMPLE_DATE': '2007.08.07'}, {'IDX': 91.0, 'FAC_NM': '승일벤쳐타워', 'ADDRESS': '가산동 371-42', 'TELEPHONE': '862-2351', 'APPROVAL_DATE': '2005.06.18', 'COMPLE_DATE': '2006.12'}, {'IDX': 42.0, 'FAC_NM': '대륭포스트타워3차', 'ADDRESS': '구로동 182-4', 'TELEPHONE': '2028-0114', 'APPROVAL_DATE': '2005.06.10', 'COMPLE_DATE': '2007.06.07'}, {'IDX': 153.0, 'FAC_NM': '에이스하이테크시티', 'ADDRESS': '경인로 775(문래동3가)', 'TELEPHONE': '6309-6112', 'APPROVAL_DATE': '2005.05.15', 'COMPLE_DATE': '2007.04.13'}, {'IDX': 90.0, 'FAC_NM': '롯데정보통신', 'ADDRESS': '가산동 533-2', 'TELEPHONE': '2626-4000', 'APPROVAL_DATE': '2005.05.11', 'COMPLE_DATE': '2007.03'}, {'IDX': 134.0, 'FAC_NM': 'DMC 첨단산업센터', 'ADDRESS': '마포구 상암동 1580 \n첨단산업센터', 'TELEPHONE': '2171-2847', 'APPROVAL_DATE': '2004.11.03', 'COMPLE_DATE': '2008.03.31'}, {'IDX': 62.0, 'FAC_NM': 'IT미래타워', 'ADDRESS': '가산동 60-21', 'TELEPHONE': '2027-5757', 'APPROVAL_DATE': '2004.10.27', 'COMPLE_DATE': '2007.04.30'}, {'IDX': 89.0, 'FAC_NM': '뉴티캐슬', 'ADDRESS': '가산동 429-1', 'TELEPHONE': '2626-9960', 'APPROVAL_DATE': '2004.08.11', 'COMPLE_DATE': '2006.12'}, {'IDX': 88.0, 'FAC_NM': '대륭테크노타운13차', 'ADDRESS': '가산동 664', 'TELEPHONE': '2029-5600', 'APPROVAL_DATE': '2004.07.28', 'COMPLE_DATE': '2008.05'}, {'IDX': 185.0, 'FAC_NM': '성수동\n 우림e-BIZ Center', 'ADDRESS': '성수동2가 280-21번지', 'TELEPHONE': '(02)2024-2110', 'APPROVAL_DATE': '2004.07.26', 'COMPLE_DATE': '2006.10.18'}, {'IDX': 132.0, 'FAC_NM': '중계제1공단', 'ADDRESS': '노원구 노원로19길 31(중계동)\n[중계동 511-2]', 'TELEPHONE': '948-2846', 'APPROVAL_DATE': '2004.07.13', 'COMPLE_DATE': '1991.12.07'}, {'IDX': 130.0, 'FAC_NM': '월계테크노타운', 'ADDRESS': '노원구 월계로45길 28(월계동)\n[월계동 562번지]', 'TELEPHONE': '990-2727', 'APPROVAL_DATE': '2004.07.08', 'COMPLE_DATE': '1994.12.19'}, {'IDX': 87.0, 'FAC_NM': '대륭테크노타운12차', 'ADDRESS': '가산동 327-32', 'TELEPHONE': '2029-6114', 'APPROVAL_DATE': '2004.07.08', 'COMPLE_DATE': '2008.05'}, {'IDX': 131.0, 'FAC_NM': '하계테크노타운', 'ADDRESS': '노원구 노원로15길 10(하계동)\n[하계동 250-3]', 'TELEPHONE': '6235-3500', 'APPROVAL_DATE': '2004.07.07', 'COMPLE_DATE': '1998.11.17'}, {'IDX': 184.0, 'FAC_NM': '풍림테크원', 'ADDRESS': '성수동2가 273-10번지', 'TELEPHONE': '(02) 468-9319/464-0133', 'APPROVAL_DATE': '2004.05.31', 'COMPLE_DATE': '2005.09.15'}, {'IDX': 31.0, 'FAC_NM': '이앤씨드림타워6차', 'ADDRESS': '구로동 197-28', 'TELEPHONE': '801-8603', 'APPROVAL_DATE': '2004.05.10', 'COMPLE_DATE': '2005.12.21'}, {'IDX': 39.0, 'FAC_NM': '대륭포스트타워2차', 'ADDRESS': '구로동 182-13', 'TELEPHONE': '2082-0114', 'APPROVAL_DATE': '2004.03.24', 'COMPLE_DATE': '2005.10.06'}, {'IDX': 60.0, 'FAC_NM': '스타밸리', 'ADDRESS': '가산동 60-11', 'TELEPHONE': '2027-0114', 'APPROVAL_DATE': '2004.02.27', 'COMPLE_DATE': '2006.04'}, {'IDX': 37.0, 'FAC_NM': '코오롱빌란트2차', 'ADDRESS': '구로동 222-8', 'TELEPHONE': '2081-1111', 'APPROVAL_DATE': '2004.02.25', 'COMPLE_DATE': '2006.12.28'}, {'IDX': 38.0, 'FAC_NM': '대륭포스트타워1차', 'ADDRESS': '구로동 212-8', 'TELEPHONE': '2082-2331', 'APPROVAL_DATE': '2004.01.10', 'COMPLE_DATE': '2005.10.18'}, {'IDX': 36.0, 'FAC_NM': '코오롱싸이언스밸리2차', 'ADDRESS': '구로동 811', 'TELEPHONE': '850-3150', 'APPROVAL_DATE': '2003.12.30', 'COMPLE_DATE': '2005.12.13'}, {'IDX': 34.0, 'FAC_NM': '에이스하이엔드1차', 'ADDRESS': '구로동 235-2', 'TELEPHONE': '6220-2010', 'APPROVAL_DATE': '2003.12.30', 'COMPLE_DATE': '2005.09.30'}, {'IDX': 150.0, 'FAC_NM': '메가벤처타워', 'ADDRESS': '문래로20길60(문래동3가)', 'TELEPHONE': '2632-4438', 'APPROVAL_DATE': '2003.12.22', 'COMPLE_DATE': '2005.12.27'}, {'IDX': 79.0, 'FAC_NM': '롯데IT캐슬', 'ADDRESS': '가산동 550-1', 'TELEPHONE': '2026-8970', 'APPROVAL_DATE': '2003.12.20', 'COMPLE_DATE': '2005.09'}, {'IDX': 30.0, 'FAC_NM': '이앤씨드림타워5차', 'ADDRESS': '구로동 197-13', 'TELEPHONE': '6336-3591', 'APPROVAL_DATE': '2003.12.19', 'COMPLE_DATE': '2004.12.14'}, {'IDX': 59.0, 'FAC_NM': '벽산디지털밸리5차', 'ADDRESS': '가산동 60-73', 'TELEPHONE': '2082-5990', 'APPROVAL_DATE': '2003.11.05', 'COMPLE_DATE': '2005.10'}, {'IDX': 33.0, 'FAC_NM': '마리오디지털밸리', 'ADDRESS': '구로동 222-12', 'TELEPHONE': '890-8498', 'APPROVAL_DATE': '2003.10.13', 'COMPLE_DATE': '2005.10.25'}, {'IDX': 85.0, 'FAC_NM': '코오롱디지털타워애스톤', 'ADDRESS': '가산동 505-14', 'TELEPHONE': '2082-8114', 'APPROVAL_DATE': '2003.09.26', 'COMPLE_DATE': '2005.09'}, {'IDX': 84.0, 'FAC_NM': '에이스테크노타워10차', 'ADDRESS': '가산동 470-5', 'TELEPHONE': '6670-5300', 'APPROVAL_DATE': '2003.09.16', 'COMPLE_DATE': '2005.07'}, {'IDX': 35.0, 'FAC_NM': '코오롱싸이언스밸리1차', 'ADDRESS': '구로동 187-10', 'TELEPHONE': '2025-4580', 'APPROVAL_DATE': '2003.08.08', 'COMPLE_DATE': '2005.07.05'}, {'IDX': 40.0, 'FAC_NM': '삼성IT밸리', 'ADDRESS': '구로동 197-5', 'TELEPHONE': '2028-2363', 'APPROVAL_DATE': '2003.07.20', 

,IDX,FAC_NM,ADDRESS,TELEPHONE,APPROVAL_DATE,COMPLE_DATE
0,208.0,신내테크노타운,봉화산로 123(상봉동),02)3423-0057,96.5.28,99.10.18
1,136.0,월곡동아파트형공장,하월곡동 96-113,02-090-8083,33289,1990.12.31
2,135.0,월곡동아파트형공장,하월곡동 96-113,02-912-1034,33289,1990.12.31
3,140.0,문정아르페온 1차 지식산업센터,서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL),031-706-8577,2016.06.27,2016.06.27
4,139.0,문정 대명벨리온,서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL),02-2222-7357,2016.03.23,2016.03.23
...,...,...,...,...,...,...
208,169.0,서울제일인쇄협동조합,성수2가제3동 277-7번지,(02) 498-8727,1992.02.06,1993.05.08
209,168.0,삼풍,성수2가제3동 284-50번지,(02) 466-4515,1991.01.31,1992.08.03
210,122.0,대동아파트형공장,독산동 999-3,804-3362,1990.12,1992.02
211,3.0,비젼타워관리조합,양천로57길26,2659-0360,1990.10.31,1992.11.30
212,142.0,문정 현대지식산업센터Ｉ-2,서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL),02-3451-0100,2016.02.29,2016.02.29

## 데이터 전처리

In [148]:
# 필요한 데이터만 추출하고, 열이름 모두 소문자로 통일
center_df = center_df[['IDX', 'FAC_NM', "ADDRESS"]]
center_df.columns = center_df.columns.str.lower()

center_df

       idx            fac_nm                                address
0    208.0           신내테크노타운                          봉화산로 123(상봉동)
1    136.0         월곡동아파트형공장                            하월곡동 96-113
2    135.0         월곡동아파트형공장                            하월곡동 96-113
3    140.0  문정아르페온 1차 지식산업센터    서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)
4    139.0          문정 대명벨리온  서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)
..     ...               ...                                    ...
208  169.0        서울제일인쇄협동조합                        성수2가제3동 277-7번지
209  168.0                삼풍                       성수2가제3동 284-50번지
210  122.0          대동아파트형공장                              독산동 999-3
211    3.0          비젼타워관리조합                               양천로57길26
212  142.0    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[213 rows x 3 columns]

In [149]:
# idx: float → int 로 변경
center_df['idx'] = center_df['idx'].astype(int)

# 값 중복 여부 확인
print(center_df['idx'].duplicated().sum()) # 0

0

In [150]:
# 공장 이름과 주소가 모두 같은 행이 있는지 확인
print(center_df.duplicated(subset=['fac_nm', 'address']).sum()) # 1

dup_all_mask = center_df.duplicated(subset=['fac_nm', 'address'], keep=False)
center_df[dup_all_mask].sort_values(['fac_nm', 'address'])

1

   idx     fac_nm      address
1  136  월곡동아파트형공장  하월곡동 96-113
2  135  월곡동아파트형공장  하월곡동 96-113

In [151]:
# 공장 이름과 주소 중복 행 제거
center_df = center_df.drop_duplicates(subset=['fac_nm', 'address'], keep='first').reset_index(drop=True)
center_df

     idx            fac_nm                                address
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    140  문정아르페온 1차 지식산업센터    서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)
3    139          문정 대명벨리온  서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)
..   ...               ...                                    ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
208  168                삼풍                       성수2가제3동 284-50번지
209  122          대동아파트형공장                              독산동 999-3
210    3          비젼타워관리조합                               양천로57길26
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[212 rows x 3 columns]

In [152]:
# 주소 이상치 제거
center_df["address"] = (
    center_df["address"]
    .str.replace(r"(,|\n|외).*$", "", regex=True)  # 첫 , 또는 \n 또는 외 이후 전부 삭제
    .str.strip()
)

center_df

     idx            fac_nm                                address
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    140  문정아르페온 1차 지식산업센터                      서울특별시 송파구 문정동 640
3    139          문정 대명벨리온                    서울특별시 송파구 문정동 641-4
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)
..   ...               ...                                    ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
208  168                삼풍                       성수2가제3동 284-50번지
209  122          대동아파트형공장                              독산동 999-3
210    3          비젼타워관리조합                               양천로57길26
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[212 rows x 3 columns]

In [161]:
print(center_df['address'].str.contains(',').sum()) # 외 = 0, \n = 0, , = 1
print(center_df[center_df['address'].str.contains(',', na=False)]) # idx = 202

cond = center_df['idx'] == 202
center_df.loc[cond, 'address'] = '성수동2가 269-25' # 첫 주소로 대체

center_df.loc[cond, :]

1
    idx          fac_nm               address
19  202  에이스하이앤드\n 성수타워  성수동2가 269-25,269-51,

    idx          fac_nm       address
19  202  에이스하이앤드\n 성수타워  성수동2가 269-25

In [164]:
# type 변수 추가
center_df['type'] = '지식산업센터'
center_df

     idx            fac_nm                                address    type
0    208           신내테크노타운                          봉화산로 123(상봉동)  지식산업센터
1    136         월곡동아파트형공장                            하월곡동 96-113  지식산업센터
2    140  문정아르페온 1차 지식산업센터                      서울특별시 송파구 문정동 640  지식산업센터
3    139          문정 대명벨리온                    서울특별시 송파구 문정동 641-4  지식산업센터
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)  지식산업센터
..   ...               ...                                    ...     ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지  지식산업센터
208  168                삼풍                       성수2가제3동 284-50번지  지식산업센터
209  122          대동아파트형공장                              독산동 999-3  지식산업센터
210    3          비젼타워관리조합                               양천로57길26  지식산업센터
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)  지식산업센터

[212 rows x 4 columns]

### 주소 → 위도, 경도

In [49]:
kakao_key  = os.getenv("KAKAO_REST_APIKEY")     # 인증키

In [163]:
# test
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)
params = {"query": "성수동2가 269-25"}  # 입력할 주소
resp = requests.get(url,headers=headers, params=params).json() #카카오 API 요청
                      
print(resp) #API 결과 출력
resp['documents'][0]['road_address']

{'documents': [{'address': {'address_name': '서울 성동구 성수동2가 269-25', 'b_code': '1120011500', 'h_code': '1120067000', 'main_address_no': '269', 'mountain_yn': 'N', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_h_name': '성수2가1동', 'region_3depth_name': '성수동2가', 'sub_address_no': '25', 'x': '127.056741837461', 'y': '37.5402196364231'}, 'address_name': '서울 성동구 성수동2가 269-25', 'address_type': 'REGION_ADDR', 'road_address': {'address_name': '서울 성동구 성수이로10길 14', 'building_name': '에이스 하이엔드 성수타워', 'main_building_no': '14', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_name': '성수동2가', 'road_name': '성수이로10길', 'sub_building_no': '', 'underground_yn': 'N', 'x': '127.056789858953', 'y': '37.5401307747523', 'zone_no': '04784'}, 'x': '127.056741837461', 'y': '37.5402196364231'}], 'meta': {'is_end': True, 'pageable_count': 1, 'total_count': 1}}

{'address_name': '서울 성동구 성수이로10길 14',
 'building_name': '에이스 하이엔드 성수타워',
 'main_building_no': '14',
 'region_1depth_name': '서울',
 'region_2depth_name': '성동구',
 'region_3depth_name': '성수동2가',
 'road_name': '성수이로10길',
 'sub_building_no': '',
 'underground_yn': 'N',
 'x': '127.056789858953',
 'y': '37.5401307747523',
 'zone_no': '04784'}

In [26]:
def add_kakao_geocode(df, kakao_key, address_col="address", sleep_sec=0.03, max_retry=5):
    url = "https://dapi.kakao.com/v2/local/search/address.json"
    out = df.copy()

    for c in ["road_address", "lat", "lng"]:
        if c not in out.columns:
            out[c] = pd.NA

    session = requests.Session()
    session.headers.update({"Authorization": f"KakaoAK {kakao_key}"})

    # 중복 주소 1회만 호출
    uniq_addrs = (
        out[address_col]
        .dropna()
        .astype(str)
        .str.strip()
    )
    uniq_addrs = uniq_addrs[uniq_addrs != ""].drop_duplicates()

    cache = {}  # {addr: (road_address, lat, lng)}

    for add in uniq_addrs:
        params = {"query": add}
        result = None

        for i in range(max_retry):
            try:
                r = session.get(url, params=params, timeout=10)

                if r.status_code == 429:  # rate limit
                    time.sleep((i + 1) * 0.8)
                    continue

                r.raise_for_status()
                result = r.json()
                break
            except requests.exceptions.RequestException:
                time.sleep((i + 1) * 0.8)

        if not result:
            cache[add] = (pd.NA, pd.NA, pd.NA)
            continue

        docs = result.get("documents", [])
        if not docs:
            cache[add] = (pd.NA, pd.NA, pd.NA)
            continue

        road = docs[0].get("road_address")
        if road:
            cache[add] = (road.get("address_name"), road.get("y"), road.get("x"))
        else:
            addr = docs[0].get("address") or {}
            cache[add] = (addr.get("address_name"), addr.get("y"), addr.get("x"))

        time.sleep(sleep_sec)

    mapped = out[address_col].astype(str).str.strip().map(cache)
    out[["road_address", "lat", "lng"]] = mapped.apply(pd.Series)

    return out

In [ ]:
center_df = add_kakao_geocode(center_df, kakao_key)

,idx,fac_nm,address,type,road_address,lat,lng
0,208,신내테크노타운,봉화산로 123(상봉동),지식산업센터,서울 중랑구 봉화산로 123,37.6040273751759,127.087795907582
1,136,월곡동아파트형공장,하월곡동 96-113,지식산업센터,서울 성북구 오패산로 21,37.6041194415259,127.037068364923
2,140,문정아르페온 1차 지식산업센터,서울특별시 송파구 문정동 640,지식산업센터,서울 송파구 정의로 70,37.486047580834,127.115467768303
3,139,문정 대명벨리온,서울특별시 송파구 문정동 641-4,지식산업센터,서울 송파구 법원로 127,37.4863159476467,127.118783475412
4,141,문정 현대지식산업센터Ｉ-1,서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL),지식산업센터,서울 송파구 법원로11길 11,37.4846302643031,127.118322322397
...,...,...,...,...,...,...,...
207,169,서울제일인쇄협동조합,성수2가제3동 277-7번지,지식산업센터,서울 성동구 성수이로 144-29,37.5477016713796,127.059035636627
208,168,삼풍,성수2가제3동 284-50번지,지식산업센터,서울 성동구 성수일로10길 8,37.5477102587413,127.051466260849
209,122,대동아파트형공장,독산동 999-3,지식산업센터,서울 금천구 범안로9길 58,37.468804929751,126.889870514728
210,3,비젼타워관리조합,양천로57길26,지식산업센터,서울 강서구 양천로57길 26,37.5637547781595,126.853091955234
211,142,문정 현대지식산업센터Ｉ-2,서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL),지식산업센터,서울 송파구 법원로11길 7,37.4852991782959,127.119391411935

In [166]:
print(center_df['road_address'].str.contains('서울').sum())

not_seoul = center_df[~center_df['road_address'].str.contains('서울')]
not_seoul

210

     idx      fac_nm      address    type road_address  lat  lng
152   77  우림라이온스밸리1차   가산동 371-62  지식산업센터          NaN  NaN  NaN
194   48          천강  신도림동 402-3호  지식산업센터          NaN  NaN  NaN

In [168]:
'''
77	우림라이온스밸리1차	가산동 371-62
48	천강	신도림동 402-3호
두 주소는 이상치로 보고 제거.
'''
center_df.dropna(inplace=True)
len(center_df)

210

In [169]:
# idx 재설정 및 정렬
center_df.sort_values(by = 'idx', inplace=True)
center_df['idx'] = range(1, len(center_df) + 1) # idx 번호 재부여
center_df.reset_index(drop=True, inplace=True) # index 재설정
center_df

,idx,fac_nm,address,type,road_address,lat,lng
0,1,세종투자㈜,강동구 상일로10길 36 (상일동),지식산업센터,서울 강동구 상일로10길 36,37.5507989598659,127.174104292142
1,2,NICE그룹 지식산업센터,상일로6길 55 (상일동),지식산업센터,서울 강동구 상일로6길 55,37.5500039560221,127.176326474473
2,3,비젼타워관리조합,양천로57길26,지식산업센터,서울 강서구 양천로57길 26,37.5637547781595,126.853091955234
3,4,에이스테크노타워,강서로 468,지식산업센터,서울 강서구 강서로 468,37.5671848166792,126.841489818891
4,5,가양테크노타운,허준로 217,지식산업센터,서울 강서구 허준로 217,37.5609643758115,126.862889794292
...,...,...,...,...,...,...,...
205,206,강북전자공단,강북구 덕릉로40길 74(번동,지식산업센터,서울 강북구 덕릉로40길 74,37.634162368067,127.033671249468
206,207,강북유니온빌딩,강북구 한천로109길 10(번동,지식산업센터,서울 강북구 한천로109길 10,37.6288059246607,127.043312515269
207,208,아시아미디어타워,초동 42,지식산업센터,서울 중구 충무로 29,37.563836750265,126.992508328619
208,209,동대문패션비즈센터,신당동 251-160,지식산업센터,서울 중구 을지로45길 46,37.5663548952676,127.012362709547
209,210,산타플러스,난곡로 60,지식산업센터,서울 관악구 난곡로 60,37.4608681432511,126.919395468118

# 서울시 휴게음식점 인허가

## 데이터 불러오기

In [3]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "1000"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_072405/{start_index}/{end_index}/"

response = requests.get(url).json()
print(response)

{'LOCALDATA_072405': {'list_total_count': 143007, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}, 'row': [{'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00210', 'APVPERMYMD': '2016-09-21', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-04-26', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '31.17', 'SITEPOSTNO': '143-822', 'SITEWHLADDR': '서울특별시 광진구 구의동 212-3 1층 ', 'RDNWHLADDR': '서울특별시 광진구 아차산로 471, 1층 (구의동, CS프라자)', 'RDNPOSTNO': '05035', 'BPLCNM': '자연드림 구의점', 'LASTMODTS': '2023-04-26 16:50:33', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-04-28 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '208232.99266682     ', 'Y': '448688.329238784    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '31.17', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00212', 'APVPERMYMD': '2016-09-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-03-23', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-912', 'SITEWHLADDR': '서울특별시 광진구 중곡동 629-7번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 면목로 59, 1층 (중곡동)', 'RDNPOSTNO': '04920', 'BPLCNM': '커피뎁(coffee dep)', 'LASTMODTS': '2018-03-23 14:00:12', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '206769.405105326    ', 'Y': '450783.052530227    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '64', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00213', 'APVPERMYMD': '2016-09-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-11-02', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '10.00', 'SITEPOSTNO': '143-847', 'SITEWHLADDR': '서울특별시 광진구 능동 279-5 삼일빌딩 지하1층 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 290, 지1층 (능동, 삼일빌딩)', 'RDNPOSTNO': '04985', 'BPLCNM': '엔탑피씨방', 'LASTMODTS': '2023-11-02 10:31:12', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-11-04 02:40:00.0', 'UPTAENM': '일반조리판매', 'X': '206908.823781413    ', 'Y': '450372.530408586    ', 'SNTUPTAENM': '일반조리판매', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '10', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00214', 'APVPERMYMD': '2016-09-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2021-11-08', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-819', 'SITEWHLADDR': '서울특별시 광진구 구의동 65-10 1층 ', 'RDNWHLADDR': '서울특별시 광진구 광나루로37길 21, 1층 (구의동)', 'RDNPOSTNO': '04976', 'BPLCNM': '지에스25구의래미안', 'LASTMODTS': '2021-11-08 08:12:13', 'UPDATEGBN': 'U', 'UPDATEDT': '2021-11-10 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '207709.57658649     ', 'Y': '449302.624247538    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00033', 'APVPERMYMD': '2018-02-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-08-18', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '0234365657', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-896', 'SITEWHLADDR': '서울특별시 광진구 중곡동 150-160 종호빌딩1층 ', 'RDNWHLADDR': '서울특별시 광진구 긴고랑로25길 29, 종호빌딩 1층 (중곡동)', 'RDNPOSTNO': '04936', 'BPLCNM': '씨유중곡오거리점', 'LASTMODTS': '2023-08-18 13:20:53', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-08-20 02:40:00.0', 'UPTAENM': '편의점', 'X': '207551.031843332    ', 'Y': '451065.671267248    ', 'SNTUPTAENM': '편의점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00035', 'APVPERMYMD': '2018-02-05', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2020-02-10', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-960', 'SITEWHLADDR': '서울특별시 광진구 구의동 226-18번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 자양로30길 79, 1층 (구의동)', 'RDNPOSTNO': '05032', 'BPLCNM': '지에스(GS)25 구의창원점', 'LASTMODTS': '2020-02-10 10:32:45', 'UPDATEGBN': 'U', 'UPDATEDT': '2020-02-12 02:40:00.0', 'UPTAENM': '편의점', 'X': '207823.103191831    ', 'Y': '448979.694709608    ', 'SNTUPTAENM': '편의점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00036', 'APVPERMYMD': '2018-02-09', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-08-07', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '21.00', 'SITEPOSTNO': '143-839', 'SITEWHLADDR': '서울특별시 광진구 군자동 144-10번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 동일로54길 19, 1층 (군자동)', 'RDNPOSTNO': '05000', 'BPLCNM': '커피나라', 'LASTMODTS': '2018-08-07 15:10:01', 'UPDATEGBN': 'U', 'UPDATEDT': '2018-12-06 02:40:00.0', 'UPTAENM': '커피숍', 'X': '206359.54826389     ', 'Y': '450334.307546466    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '21', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00038', 'APVPERMYMD': '2018-02-19', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2020-04-29', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '27.16', 'SITEPOSTNO': '143-898', 'SITEWHLADDR': '서울특별시 광진구 중곡동 160-12번지 유정아트빌 ', 'RDNWHLADDR': '서울특별시 광진구 능동로40길 19, 1층 101호 (중곡동, 유정아트빌)', 'RDNPOSTNO': '04928', 'BPLCNM': '영희', 'LASTMODTS': '2020-04-29 17:57:12', 'UPDATEGBN': 'U', 'UPDATEDT': '2020-05-01 02:40:00.0', 'UPTAENM': '커피숍', 'X': '207110.10262802     ', 'Y': '450645.30992606     ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '27.16', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00135', 'APVPERMYMD': '2016-05-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2016-11-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-916', 'SITEWHLADDR': '서울특별시 광진구 화양동 32-4번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 능동로13길 106, 1층 (화양동)', 'RDNPOSTNO': '05012', 'BPLCNM': '라푸르타(La Frutta)', 'LASTMODTS': '2016-05-27 14:25:49', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '205949.051675131    ', 'Y': '449317.879371124    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '29.8', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00136', 'APVPERMYMD': '2016-05-30', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2022-01-14', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '0215770711', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-902', 'SITEWHLADDR': '서울특별시 광진구 중곡동 199-1 1층 ', 'RDNWHLADDR': '서울특별시 광진구 면목로 192, 1층 (중곡동)', 'RDNPOSTNO': '04903', 'BPLCNM': '바이더웨이중곡중앙점', 'LASTMODTS': '2022-01-14 14:57:02', 'UPDATEGBN': 'U', 'UPDATEDT': '2022-01-16 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '207302.075496997    ', 'Y': '451991.900378929    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00170', 'APVPERMYMD': '2017-11-07', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-06-12', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-866', 'SITEWHLADDR': '서울특별시 광진구 자양동 617-39번지 1층101호 ', 'RDNWHLADDR': '서울특별시 광진구 자양로13다길 8, 1층 101호 (자양동)', 'RDNPOSTNO': '05062', 'BPLCNM': '커피알렉스', 'LASTMODTS': '2018-06-12 13:20:28', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '기타 휴게음식점', 'X': '206958.796281621    ', 'Y': '447839.595007476    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '29.61', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00138', 'APVPERMYMD': '2016-06-03', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2016-06-30', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-758', 'SITEWHLADDR': '서울특별시 광진구 자양동 227-342번지 지하1층 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 92, 지1층 (자양동)', 'RDNPOSTNO': '05065', 'BPLCNM': '쉐어티', 'LASTMODTS': '2016-07-11 13:03:18', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '206217.434726027    ', 'Y': '448506.218743834    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '9.9', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00156', 'APVPERMYMD': '2017-10-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-06-01', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02  18997443', 'SITEAREA': '13.20', 'SITEPOSTNO': '143-758', 'SITEWHLADDR': '서울특별시 광진구 자양동 227-342 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 92, 지하1층 (자양동, 롯데백화점 스타시티점)', 'RDNPOSTNO': '05065', 'BPLCNM': '반반식당', 'LASTMODTS': '2023-06-01 17:48:02', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-06-03 02:40:00.0', 'UPTAENM': '패스트푸드', 'X': '206217.434726027    ', 'Y': '448506.218743834    ', 'SNTUPTAENM': '패스트푸드', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '13.2', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00157', 'APVPERMYMD': '2017-10-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2017-10-16', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-841', 'SITEWHLADDR': '서울특별시 광진구 자양동 7-25번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 아차산로 224, 1층 (자양동)', 'RDNPOSTNO': '05073', 'BPLCNM': '오닭꼬치', 'LASTMODTS': '2017-10-16 11:08:35', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '기타 휴게음식점', 'X': '205948.480566193    ', 'Y': '448701.947776139    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '26', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00158', 'APVPERMYMD': '2017-10-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2019-09-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02  456 3373', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-802', 'SITEWHLADDR': '서울특별시 광진구 광장동 121번지 ', 'RDNWHLADDR': '서울특별시 광진구 아차산로78길 7, 2층 B201호 (광장동, 유진스웰)', 'RDNPOSTNO': '04969', 'BPLCNM': '씨유광장유진점', 'LASTMODTS': '2019-09-04 09:30:58', 'UPDATEGBN': 'U', 'UPDATEDT': '2019-09-06 02:40:00.0', 'UPTAENM': '편의점', 'X': '209589.042548422    ', 'Y': '449798.08201875     ', 'SNTUPTAENM': '편의점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00159', 'APVPERMYMD': '2017-10-18', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2024-01-02', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '24.00', 'SITEPOSTNO': '143-891', 'SITEWHLADDR': '서울특별시 광진구 중곡동 134-1 1층 ', 'RDNWHLADDR': '서울특별시 광진구 용마산로3길 88, 1층 (중곡동)', 'RDNPOSTNO': '04925', 'BPLCNM': '삼보할인마트', 'LASTMODTS': '2024-01-02 14:48:41', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-01-04 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '207297.69930366     ', 'Y': '450547.957727534    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '24', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00161', 'APVPERMYMD': '2017-10-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-01-11', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-758', 'SITEWHLADDR': '서울특별시 광진구 자양동 227-342번지 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 92, 지하1층 (자양동, 롯데백화점 건대스타시티점)', 'RDNPOSTNO': '05065', 'BPLCNM': '88브레드', 'LASTMODTS': '2018-01-11 09:31:17', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '일반조리판매', 'X': '206217.434726027    ', 'Y': '448506.218743834    ', 'SNTUPTAENM': '일반조리판매', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '9', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3150000', 'MGTNO': '3150000-104-1987-00253', 'APVPERMYMD': '1987-09-17', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2004-07-26', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '41.76', 'SITEPOSTNO': '157-895', 'SITEWHLADDR': '서울특별시 강서구 화곡동 53-3번지 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '다미안제과', 'LASTMODTS': '2002-10-14 00:00:00', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '과자점', 'X': '186440.927851414    ', 'Y': '448962.142283183    ', 'SNTUPTAENM': '과자점', 'MANEIPCNT': '1', 'WMEIPCNT': '1', 'TRDPJUBNSENM': '주택가주변', 'LVSENM': '자율', 'WTRSPLYFACILSENM': '상수도전용', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '41.76', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00108', 'APVPERMYMD': '2016-04-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2019-10-25', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '16.50', 'SITEPOSTNO': '143-840', 'SITEWHLADDR': '서울특별시 광진구 군자동 359-15번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 동일로34길 26, 1층 (군자동)', 'RDNPOSTNO': '05003', 'BPLCNM': '아이싱온더케이크', 'LASTMODTS': '2019-10-25 14:37:57', 'UPDATEGBN': 'U', 'UPDATEDT': '2019-10-27 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '206115.760746843    ', 'Y': '449711.762168968    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '16.5', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00109', 'APVPERMYMD': '2016-04-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-02-27', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-826', 'SITEWHLADDR': '서울특별시 광진구 구의동 251-44번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 자양로22길 23, 1층 (구의동)', 'RDNPOSTNO': '05039', 'BPLCNM': '썸띵비터(Something Bitter)', 'LASTMODTS': '2018-02-27 13:48:48', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '207406.507088563    ', 'Y': '448606.98797732     ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '26', 'JTUPSOASGNNO': '',

In [4]:
# 'list_total_count': 142943 ⇒ 1000개씩 나눠서 가져와야 함
apikey = os.getenv("MJ_APIKEY")
service = "LOCALDATA_072405"
base = "http://openapi.seoul.go.kr:8088"

# 1) 전체 건수 확인
first = requests.get(f"{base}/{apikey}/json/{service}/1/1/").json()
total = first[service]["list_total_count"]

# 2) 분할 수집
batch = 1000   # 서비스 허용 범위 내에서 조절
all_rows = []

for start in range(1, total + 1, batch):
    end = min(start + batch - 1, total)
    url = f"{base}/{apikey}/json/{service}/{start}/{end}/"
    response = requests.get(url).json()
    rows = response.get(service, {}).get("row", [])
    all_rows.extend(rows)

print("total:", total)
print("fetched:", len(all_rows))

total: 143007
fetched: 143007

In [32]:
cafe_df = pd.DataFrame(all_rows)
cafe_df.head()

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,FCTYSILJOBEPCNT,FCTYPDTJOBEPCNT,BDNGOWNSENM,ISREAM,MONAM,MULTUSNUPSOYN,FACILTOTSCP,JTUPSOASGNNO,JTUPSOMAINEDF,HOMEPAGE
0,3040000,3040000-104-2016-00210,2016-09-21,,03,폐업,02,폐업,2023-04-26,,...,0,0,,0,0,N,31.17,,,
1,3040000,3040000-104-2016-00212,2016-09-27,,03,폐업,02,폐업,2018-03-23,,...,,,,,,N,64,,,
2,3040000,3040000-104-2016-00213,2016-09-28,,03,폐업,02,폐업,2023-11-02,,...,0,0,,0,0,N,10,,,
3,3040000,3040000-104-2016-00214,2016-09-29,,03,폐업,02,폐업,2021-11-08,,...,0,0,,0,0,N,6.6,,,
4,3040000,3040000-104-2018-00033,2018-02-01,,03,폐업,02,폐업,2023-08-18,,...,0,0,,0,0,N,6.6,,,

## 데이터 전처리

In [33]:
# 필요한 데이터만 추출하고, 열이름 모두 소문자로 통일
cafe_df = cafe_df[['BPLCNM', "UPTAENM", 'DTLSTATEGBN', "APVPERMYMD", "SITEWHLADDR", "RDNWHLADDR", "SITEAREA", "LASTMODTS"]]
cafe_df.columns = cafe_df.columns.str.lower()

cafe_df

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts
0,자연드림 구의점,기타 휴게음식점,02,2016-09-21,서울특별시 광진구 구의동 212-3 1층,"서울특별시 광진구 아차산로 471, 1층 (구의동, CS프라자)",31.17,2023-04-26 16:50:33
1,커피뎁(coffee dep),커피숍,02,2016-09-27,서울특별시 광진구 중곡동 629-7번지 1층,"서울특별시 광진구 면목로 59, 1층 (중곡동)",,2018-03-23 14:00:12
2,엔탑피씨방,일반조리판매,02,2016-09-28,서울특별시 광진구 능동 279-5 삼일빌딩 지하1층,"서울특별시 광진구 능동로 290, 지1층 (능동, 삼일빌딩)",10.00,2023-11-02 10:31:12
3,지에스25구의래미안,기타 휴게음식점,02,2016-09-29,서울특별시 광진구 구의동 65-10 1층,"서울특별시 광진구 광나루로37길 21, 1층 (구의동)",6.60,2021-11-08 08:12:13
4,씨유중곡오거리점,편의점,02,2018-02-01,서울특별시 광진구 중곡동 150-160 종호빌딩1층,"서울특별시 광진구 긴고랑로25길 29, 종호빌딩 1층 (중곡동)",6.60,2023-08-18 13:20:53
...,...,...,...,...,...,...,...,...
143002,하룻고양이,커피숍,01,2018-05-02,서울특별시 성북구 안암동4가 41-19,"서울특별시 성북구 안암로9가길 10, 1층 (안암동4가)",75.90,2026-02-25 13:47:05
143003,헬린이식단,커피숍,02,2018-03-29,서울특별시 중랑구 면목동 181-32,"서울특별시 중랑구 봉우재로14길 26, 1층 (면목동)",23.10,2026-02-25 15:40:44
143004,투썸플레이스 한양대 학생복지관점,일반조리판매,02,2015-08-21,서울특별시 성동구 행당동 17,"서울특별시 성동구 왕십리로 222, 1층 (행당동, 한양대학교 학생복지관)",86.00,2026-02-25 14:03:42
143005,달그락,패스트푸드,02,2014-07-08,서울특별시 금천구 시흥동 998-5 나인팰리스 지상1층 101일부호,"서울특별시 금천구 금하로5길 17, 지상1층 101호 (시흥동, 나인팰리스)",61.05,2026-02-25 15:09:12
143006,이디야커피 자양동점,커피숍,01,2013-04-26,서울특별시 광진구 자양동 681-15 101호,"서울특별시 광진구 자양로 46, 101호 (자양동)",66.00,2026-02-25 13:33:16

In [34]:
cafe_df['uptaenm'].unique()

<StringArray>
['기타 휴게음식점',      '커피숍',   '일반조리판매',      '편의점',    '패스트푸드',      '과자점',
     '푸드트럭',       '다방',     '관광호텔',      '유원지',    '철도역구내',      '백화점',
      '떡카페',    '아이스크림',     '키즈카페',     '전통찻집',       '극장',       '공항',
     '단란주점',    '호프/통닭',     '고속도로',       '기타',  '김밥(도시락)',      '룸살롱',
       '한식']
Length: 25, dtype: str

In [35]:
# 영업 중인 카페만 필터링
cafe_type = ['커피숍']
cond = (cafe_df['uptaenm'].isin(cafe_type)) & (cafe_df['dtlstategbn'] == '01')  # 01=영업

cafe_df = cafe_df.loc[cond, :]
cafe_df

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts
220,이디야답십리파크자이점,커피숍,01,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",85.00,2022-07-07 14:22:12
223,다락방 사주카페,커피숍,01,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),49.59,2019-04-03 15:45:38
225,빽다방 전농동전동초교점,커피숍,01,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",57.00,2024-02-02 13:26:49
241,커피상회,커피숍,01,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",9.90,2023-08-18 13:24:50
245,구하니 커피,커피숍,01,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",10.36,2024-09-11 10:45:00
...,...,...,...,...,...,...,...,...
142995,백억커피 논현점,커피숍,01,2022-04-11,서울특별시 강남구 논현동 149-2,"서울특별시 강남구 학동로20길 47, 지상1층 좌측호 (논현동)",33.09,2026-02-25 12:38:18
142998,필그림커피,커피숍,01,2020-03-10,서울특별시 영등포구 영등포동 631-48 승진빌딩,"서울특별시 영등포구 영신로9라길 12, 승진빌딩 1층 (영등포동)",46.50,2026-02-25 15:23:31
142999,요커(yo.kr) 신당점,커피숍,01,2020-03-05,서울특별시 중구 신당동 112-1,"서울특별시 중구 다산로42길 12, 1층 (신당동)",21.48,2026-02-25 15:59:16
143002,하룻고양이,커피숍,01,2018-05-02,서울특별시 성북구 안암동4가 41-19,"서울특별시 성북구 안암로9가길 10, 1층 (안암동4가)",75.90,2026-02-25 13:47:05
143006,이디야커피 자양동점,커피숍,01,2013-04-26,서울특별시 광진구 자양동 681-15 101호,"서울특별시 광진구 자양로 46, 101호 (자양동)",66.00,2026-02-25 13:33:16

In [36]:
cafe_df['type'] = '휴게음식점'
cafe_df.head()

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts,type
220,이디야답십리파크자이점,커피숍,01,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",85.00,2022-07-07 14:22:12,휴게음식점
223,다락방 사주카페,커피숍,01,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),49.59,2019-04-03 15:45:38,휴게음식점
225,빽다방 전농동전동초교점,커피숍,01,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",57.00,2024-02-02 13:26:49,휴게음식점
241,커피상회,커피숍,01,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",9.90,2023-08-18 13:24:50,휴게음식점
245,구하니 커피,커피숍,01,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",10.36,2024-09-11 10:45:00,휴게음식점

In [37]:
# 공백/빈문자열을 전부 NA로 통일
cafe_df = cafe_df.replace(r'^\s*$', pd.NA, regex=True)

In [38]:
# 결측치 확인
cafe_df.isna().sum()

bplcnm           0
uptaenm          0
dtlstategbn      0
apvpermymd       0
sitewhladdr     10
rdnwhladdr      72
sitearea       289
lastmodts        0
type             0
dtype: int64

In [39]:
# sitewhladdr가 NA인 곳만 rdnwhladdr 값으로 채워 결측치 없애기
cafe_df["sitewhladdr"] = cafe_df["sitewhladdr"].fillna(cafe_df["rdnwhladdr"])
cafe_df.isna().sum()

bplcnm           0
uptaenm          0
dtlstategbn      0
apvpermymd       0
sitewhladdr      0
rdnwhladdr      72
sitearea       289
lastmodts        0
type             0
dtype: int64

In [40]:
# 층수 추출하기
pat_block = re.compile(r'(지하|지상)?\s*(\d+(?:\s*,\s*\d+)*)\s*층')
pat_num = re.compile(r'\d+')
pat_ho = re.compile(r'(\d{3,4})\s*호')  # 101호, 1101호

def get_floor(addr):
    if pd.isna(addr):
        return pd.NA

    text = str(addr)
    vals = []

    # 1) 일반 층수 패턴
    for prefix, nums in pat_block.findall(text):
        for n in pat_num.findall(nums):
            v = int(n)
            vals.append(-v if prefix == '지하' else v)

    # 2) 층 정보가 없으면 호수에서 추정
    if not vals:
        for h in pat_ho.findall(text):
            if len(h) == 3:      # 101호 -> 1층
                vals.append(int(h[0]))
            elif len(h) == 4:    # 1101호 -> 11층
                vals.append(int(h[:2]))

    if not vals:
        return pd.NA
    if 1 in vals:
        return 1

    positives = any(v > 0 for v in vals)
    negatives = any(v < 0 for v in vals)
    if negatives and not positives:
        return -1

    return min(vals)

cafe_df["floor"] = cafe_df["sitewhladdr"].apply(get_floor).astype("Int64")
cafe_df["floor"] = cafe_df["floor"].fillna(
    cafe_df["rdnwhladdr"].apply(get_floor).astype("Int64")
)
cafe_df

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts,type,floor
220,이디야답십리파크자이점,커피숍,01,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",85.00,2022-07-07 14:22:12,휴게음식점,1
223,다락방 사주카페,커피숍,01,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),49.59,2019-04-03 15:45:38,휴게음식점,<NA>
225,빽다방 전농동전동초교점,커피숍,01,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",57.00,2024-02-02 13:26:49,휴게음식점,1
241,커피상회,커피숍,01,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",9.90,2023-08-18 13:24:50,휴게음식점,1
245,구하니 커피,커피숍,01,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",10.36,2024-09-11 10:45:00,휴게음식점,<NA>
...,...,...,...,...,...,...,...,...,...,...
142995,백억커피 논현점,커피숍,01,2022-04-11,서울특별시 강남구 논현동 149-2,"서울특별시 강남구 학동로20길 47, 지상1층 좌측호 (논현동)",33.09,2026-02-25 12:38:18,휴게음식점,1
142998,필그림커피,커피숍,01,2020-03-10,서울특별시 영등포구 영등포동 631-48 승진빌딩,"서울특별시 영등포구 영신로9라길 12, 승진빌딩 1층 (영등포동)",46.50,2026-02-25 15:23:31,휴게음식점,1
142999,요커(yo.kr) 신당점,커피숍,01,2020-03-05,서울특별시 중구 신당동 112-1,"서울특별시 중구 다산로42길 12, 1층 (신당동)",21.48,2026-02-25 15:59:16,휴게음식점,1
143002,하룻고양이,커피숍,01,2018-05-02,서울특별시 성북구 안암동4가 41-19,"서울특별시 성북구 안암로9가길 10, 1층 (안암동4가)",75.90,2026-02-25 13:47:05,휴게음식점,1
143006,이디야커피 자양동점,커피숍,01,2013-04-26,서울특별시 광진구 자양동 681-15 101호,"서울특별시 광진구 자양로 46, 101호 (자양동)",66.00,2026-02-25 13:33:16,휴게음식점,1

In [41]:
# 1) 열이름 변경
cafe_df = cafe_df.rename(columns={
    'bplcnm': 'cafe_nm',
    'uptaenm': 'detail_type',
    'dtlstategbn': 'stable',
    'apvpermymd': 'aprove_day',
    'sitewhladdr': 'address',
    'rdnwhladdr': 'rd_address',
    'lastmodts': 'last_updated',
})

# 2) 열 순서 재배치
cafe_df = cafe_df[['cafe_nm', 'type', 'detail_type', 'stable', 'aprove_day', 'address', 'rd_address', 'floor', 'sitearea', 'last_updated']]

In [42]:
# 결측치 확인
cafe_df.isna().sum()

cafe_nm           0
type              0
detail_type       0
stable            0
aprove_day        0
address           0
rd_address       72
floor           629
sitearea        289
last_updated      0
dtype: int64

In [ ]:
# 주소 이상치 제거
cafe_df["address"] = (
    cafe_df["address"]
    .str.replace(r"\s*(?:외\s*)?\d+\s*필지'?", "", regex=True)  # 외 2필지 / 2필지 / 2 필지 / 외2필지'
    .str.strip()
)
cafe_df

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated
220,이디야답십리파크자이점,휴게음식점,커피숍,01,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",1,85.00,2022-07-07 14:22:12
223,다락방 사주카페,휴게음식점,커피숍,01,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),<NA>,49.59,2019-04-03 15:45:38
225,빽다방 전농동전동초교점,휴게음식점,커피숍,01,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",1,57.00,2024-02-02 13:26:49
241,커피상회,휴게음식점,커피숍,01,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",1,9.90,2023-08-18 13:24:50
245,구하니 커피,휴게음식점,커피숍,01,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",<NA>,10.36,2024-09-11 10:45:00
...,...,...,...,...,...,...,...,...,...,...
142995,백억커피 논현점,휴게음식점,커피숍,01,2022-04-11,서울특별시 강남구 논현동 149-2,"서울특별시 강남구 학동로20길 47, 지상1층 좌측호 (논현동)",1,33.09,2026-02-25 12:38:18
142998,필그림커피,휴게음식점,커피숍,01,2020-03-10,서울특별시 영등포구 영등포동 631-48 승진빌딩,"서울특별시 영등포구 영신로9라길 12, 승진빌딩 1층 (영등포동)",1,46.50,2026-02-25 15:23:31
142999,요커(yo.kr) 신당점,휴게음식점,커피숍,01,2020-03-05,서울특별시 중구 신당동 112-1,"서울특별시 중구 다산로42길 12, 1층 (신당동)",1,21.48,2026-02-25 15:59:16
143002,하룻고양이,휴게음식점,커피숍,01,2018-05-02,서울특별시 성북구 안암동4가 41-19,"서울특별시 성북구 안암로9가길 10, 1층 (안암동4가)",1,75.90,2026-02-25 13:47:05
143006,이디야커피 자양동점,휴게음식점,커피숍,01,2013-04-26,서울특별시 광진구 자양동 681-15 101호,"서울특별시 광진구 자양로 46, 101호 (자양동)",1,66.00,2026-02-25 13:33:16

In [43]:
# 중복 확인
print(cafe_df.duplicated(subset=['cafe_nm', 'address']).sum()) 

dup_all_mask = cafe_df.duplicated(subset=['cafe_nm', 'address'], keep=False)
cafe_df[dup_all_mask].sort_values(['cafe_nm', 'address'])

13

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated
86225,공차 영등포역점,휴게음식점,커피숍,01,2022-07-12,서울특별시 영등포구 영등포동3가 9-51,"서울특별시 영등포구 영중로 10, 1층 (영등포동3가)",1,51.50,2025-02-25 13:33:03
86226,공차 영등포역점,휴게음식점,커피숍,01,2022-07-12,서울특별시 영등포구 영등포동3가 9-51,"서울특별시 영등포구 영중로 10, 2층 (영등포동3가)",2,51.50,2025-02-25 13:26:48
122650,누구나카페,휴게음식점,커피숍,01,2025-07-08,서울특별시 마포구 성산동 370 마포구청,"서울특별시 마포구 월드컵로 212, 마포구청 지하1층 (성산동)",-1,31.50,2025-07-08 17:21:46
141636,누구나카페,휴게음식점,커피숍,01,2026-01-08,서울특별시 마포구 성산동 370 마포구청,"서울특별시 마포구 월드컵로 212, 마포구보건소 1층 (성산동)",1,15.50,2026-01-08 14:04:52
78240,라이프플러스 카페(LIFEPLUS CAFE),휴게음식점,커피숍,01,2023-01-03,서울특별시 영등포구 여의도동 60 63한화생명빌딩,"서울특별시 영등포구 63로 50, 63한화생명빌딩 7층 (여의도동)",7,23.55,2025-08-18 14:34:18
78241,라이프플러스 카페(LIFEPLUS CAFE),휴게음식점,커피숍,01,2023-01-03,서울특별시 영등포구 여의도동 60 63한화생명빌딩,"서울특별시 영등포구 63로 50, 63한화생명빌딩 45층 (여의도동)",45,28.34,2025-08-18 14:35:12
86448,마이유(My U),휴게음식점,커피숍,01,2022-12-09,서울특별시 영등포구 신길동 51-1,"서울특별시 영등포구 영등포로 349, 1층 (신길동)",1,42.43,2022-12-09 15:52:39
86449,마이유(My U),휴게음식점,커피숍,01,2022-12-09,서울특별시 영등포구 신길동 51-1,"서울특별시 영등포구 영등포로 349, 2층 (신길동)",2,42.43,2022-12-09 15:56:25
139431,위펀 지에스강서엔타워점,휴게음식점,커피숍,01,2023-03-31,서울특별시 영등포구 양평동1가 5-1 GS강서N타워,"서울특별시 영등포구 선유로 82, GS강서N타워 8층 (양평동1가)",8,44.89,2025-09-09 10:59:04
139432,위펀 지에스강서엔타워점,휴게음식점,커피숍,01,2023-03-31,서울특별시 영등포구 양평동1가 5-1 GS강서N타워,"서울특별시 영등포구 선유로 82, GS강서N타워 1층 (양평동1가)",1,17.26,2025-09-09 10:58:01
86555,위펀 지에스강서점,휴게음식점,커피숍,01,2023-03-31,서울특별시 영등포구 문래동6가 10 GS강서타워,"서울특별시 영등포구 선유로 75, GS강서타워 5층 (문래동6가)",5,67.23,2025-09-09 10:53:18
139430,위펀 지에스강서점,휴게음식점,커피숍,01,2023-03-31,서울특별시 영등포구 문래동6가 10 GS강서타워,"서울특별시 영등포구 선유로 75, GS강서타워 1층 (문래동6가)",1,40.54,2025-09-09 10:52:30
92315,이디야 신림미성점,휴게음식점,커피숍,01,2013-06-28,서울특별시 관악구 신림동 587-122번지,"서울특별시 관악구 난곡로 250, 1층 (신림동)",1,47.76,2013-07-25 09:42:00
92316,이디야 신림미성점,휴게음식점,커피숍,01,2013-06-28,서울특별시 관악구 신림동 587-122번지,"서울특별시 관악구 난곡로 250, 2층 (신림동)",2,45.12,2013-06-28 13:59:21
8468,카페J(제이),휴게음식점,커피숍,01,2018-07-24,서울특별시 성북구 안암동5가 15-51 J리빙텔,"서울특별시 성북구 개운사길 36, J리빙텔 1층 (안암동5가)",1,99.00,2024-12-30 10:05:38
9047,카페J(제이),휴게음식점,커피숍,01,2018-08-01,서울특별시 성북구 안암동5가 15-51 J리빙텔,"서울특별시 성북구 개운사길 36, J리빙텔 지하1층 (안암동5가)",-1,57.00,2024-12-30 10:02:29
39006,카페메종,휴게음식점,커피숍,01,2022-08-03,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 3층 (능동)",3,169.22,2022-08-03 14:51:21
39063,카페메종,휴게음식점,커피숍,01,2022-05-02,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 꿈마루 지하1층 (능동)",-1,207.24,2022-05-02 15:35:26
914,카페쿠피,휴게음식점,커피숍,01,2016-08-25,서울특별시 동대문구 회기동 1-5,"서울특별시 동대문구 경희대로 26, 지상1층 (회기동, 푸른솔문화관)",1,46.15,2024-04-17 14:44:42
1127,카페쿠피,휴게음식점,커피숍,01,2015-03-11,서울특별시 동대문구 회기동 1-5,서울특별시 동대문구 경희대로 26 (회기동),<NA>,9.90,2024-04-17 14:51:17
119253,퍼스트커피랩 강남역점,휴게음식점,커피숍,01,2022-12-19,서울특별시 강남구 역삼동 618-18 리＆신,"서울특별시 강남구 봉은사로6길 39, 지하1층 (역삼동)",-1,243.59,2023-09-05 16:07:42
119254,퍼스트커피랩 강남역점,휴게음식점,커피숍,01,2022-12-19,서울특별시 강남구 역삼동 618-18 리＆신,"서울특별시 강남구 봉은사로6길 39, 지상1층 (역삼동)",1,223.69,2023-09-05 16:01:51
122414,피트 앤 브레드,휴게음식점,커피숍,01,2023-03-27,서울특별시 송파구 문정동 640-5 AJ빌딩,"서울특별시 송파구 정의로8길 9, 에이제이비전타워 1층 (문정동)",1,66.00,2023-03-27 16:32:13
122651,피트 앤 브레드,휴게음식점,커피숍,01,2021-05-25,서울특별시 송파구 문정동 640-5 AJ빌딩,"서울특별시 송파구 정의로8길 9, 에이제이비전타워 1층 (문정동)",1,231.00,2023-01-18 17:33:47
17947,할리스 종로5가점,휴게음식점,커피숍,01,2018-12-11,서울특별시 종로구 종로5가 398-2번지,"서울특별시 종로구 동호로 401, 2층 (종로5가)",2,95.00,2018-12-11 13:32:50
18005,할리스 종로5가점,휴게음식점,커피숍,01,2018-11-16,서울특별시 종로구 종로5가 398-2번지,"서울특별시 종로구 동호로 401, 1층 (종로5가)",1,NaN,2018-11-29 17:38:15

In [44]:
# 1) datetime 변환
cafe_df["last_updated"] = pd.to_datetime(cafe_df["last_updated"], errors="coerce")

# 2) 같은 (cafe_nm, address) 그룹에서 최신 last_updated만 남기기
cafe_df = (
    cafe_df.sort_values("last_updated")  # 오래된 -> 최신
           .drop_duplicates(subset=["cafe_nm", "address"], keep="last")
           .reset_index(drop=True)
)

# 확인
print(cafe_df.duplicated(subset=["cafe_nm", "address"]).sum())

0

In [46]:
# 중복 제거 잘 되었는지 케이스 하나 확인
cafe_df.loc[(cafe_df['cafe_nm'] == '누구나카페'), :]

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated
14112,누구나카페,휴게음식점,커피숍,01,2026-01-08,서울특별시 마포구 성산동 370 마포구청,"서울특별시 마포구 월드컵로 212, 마포구보건소 1층 (성산동)",1,15.50,2026-01-08 14:04:52

In [47]:
# index 재설정
cafe_df.reset_index(drop=True, inplace=True) # index 재설정
cafe_df

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated
0,베레베레,휴게음식점,커피숍,01,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19 (화양동),<NA>,NaN,2002-09-19 00:00:00
1,클럽알앤비,휴게음식점,커피숍,01,2002-11-05,서울특별시 중구 장충동2가 189-2번지 (동대입구역322-13),NaN,<NA>,17.00,2002-11-05 00:00:00
2,덕수궁전통차전문,휴게음식점,커피숍,01,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),"서울특별시 중구 서소문로 109 (서소문동,(2층))",2,46.28,2003-01-22 00:00:00
3,엘빠소,휴게음식점,커피숍,01,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18 (명륜2가),<NA>,NaN,2003-05-31 00:00:00
4,씨애틀즈베스트커피대사관점,휴게음식점,커피숍,01,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,"서울특별시 종로구 세종대로 188 (세종로,지상1층)",1,NaN,2003-11-21 00:00:00
...,...,...,...,...,...,...,...,...,...,...
14576,필그림커피,휴게음식점,커피숍,01,2020-03-10,서울특별시 영등포구 영등포동 631-48 승진빌딩,"서울특별시 영등포구 영신로9라길 12, 승진빌딩 1층 (영등포동)",1,46.50,2026-02-25 15:23:31
14577,요커(yo.kr) 신당점,휴게음식점,커피숍,01,2020-03-05,서울특별시 중구 신당동 112-1,"서울특별시 중구 다산로42길 12, 1층 (신당동)",1,21.48,2026-02-25 15:59:16
14578,커피의정원,휴게음식점,커피숍,01,2024-09-05,서울특별시 성북구 장위동 219-396 포레스트빌,"서울특별시 성북구 장위로11길 95 (장위동, 포레스트빌)",<NA>,142.00,2026-02-25 15:59:20
14579,우지커피 쌍문세라믹점,휴게음식점,커피숍,01,2026-02-25,서울특별시 도봉구 쌍문동 723 신원주상복합2차아파트,"서울특별시 도봉구 해등로 190, 지상1층 112, 113, 114호 (쌍문동, 신...",1,43.49,2026-02-25 16:04:22
14580,(주)학산 테라로사 용산아이파크몰점,휴게음식점,커피숍,01,2026-02-25,서울특별시 용산구 한강로3가 40-999 용산역,"서울특별시 용산구 한강대로23길 55, 용산아이파크몰 5층 (한강로3가)",5,195.37,2026-02-25 17:00:41

### 주소 → 위도, 경도

In [48]:
kakao_key  = os.getenv("KAKAO_REST_APIKEY")     # 인증키

In [49]:
cafe_df = add_kakao_geocode(cafe_df, kakao_key)
cafe_df

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated,road_address,lat,lng
0,베레베레,휴게음식점,커피숍,01,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19 (화양동),<NA>,NaN,2002-09-19 00:00:00,서울 광진구 능동로13길 19,37.5428852911237,127.070832253014
1,클럽알앤비,휴게음식점,커피숍,01,2002-11-05,서울특별시 중구 장충동2가 189-2번지 (동대입구역322-13),NaN,<NA>,17.00,2002-11-05 00:00:00,NaN,NaN,NaN
2,덕수궁전통차전문,휴게음식점,커피숍,01,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),"서울특별시 중구 서소문로 109 (서소문동,(2층))",2,46.28,2003-01-22 00:00:00,서울 중구 서소문로 109,37.5630615400711,126.97327976746
3,엘빠소,휴게음식점,커피숍,01,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18 (명륜2가),<NA>,NaN,2003-05-31 00:00:00,서울 종로구 성균관로 18,37.5844061348081,126.997641346393
4,씨애틀즈베스트커피대사관점,휴게음식점,커피숍,01,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,"서울특별시 종로구 세종대로 188 (세종로,지상1층)",1,NaN,2003-11-21 00:00:00,서울 종로구 세종대로 188,37.5731899442108,126.97783098563
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14576,필그림커피,휴게음식점,커피숍,01,2020-03-10,서울특별시 영등포구 영등포동 631-48 승진빌딩,"서울특별시 영등포구 영신로9라길 12, 승진빌딩 1층 (영등포동)",1,46.50,2026-02-25 15:23:31,서울 영등포구 영신로9라길 12,37.5131328574992,126.905585643683
14577,요커(yo.kr) 신당점,휴게음식점,커피숍,01,2020-03-05,서울특별시 중구 신당동 112-1,"서울특별시 중구 다산로42길 12, 1층 (신당동)",1,21.48,2026-02-25 15:59:16,서울 중구 다산로42길 12,37.5647185635747,127.016976522759
14578,커피의정원,휴게음식점,커피숍,01,2024-09-05,서울특별시 성북구 장위동 219-396 포레스트빌,"서울특별시 성북구 장위로11길 95 (장위동, 포레스트빌)",<NA>,142.00,2026-02-25 15:59:20,서울 성북구 장위로11길 95,37.6176246710799,127.043563598835
14579,우지커피 쌍문세라믹점,휴게음식점,커피숍,01,2026-02-25,서울특별시 도봉구 쌍문동 723 신원주상복합2차아파트,"서울특별시 도봉구 해등로 190, 지상1층 112, 113, 114호 (쌍문동, 신...",1,43.49,2026-02-25 16:04:22,서울 도봉구 해등로 190,37.6582166673064,127.035759433408
14580,(주)학산 테라로사 용산아이파크몰점,휴게음식점,커피숍,01,2026-02-25,서울특별시 용산구 한강로3가 40-999 용산역,"서울특별시 용산구 한강대로23길 55, 용산아이파크몰 5층 (한강로3가)",5,195.37,2026-02-25 17:00:41,서울 용산구 한강대로21나길 17,,

In [50]:
cafe_df[cafe_df["road_address"].isna()]

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated,road_address,lat,lng
1,클럽알앤비,휴게음식점,커피숍,01,2002-11-05,서울특별시 중구 장충동2가 189-2번지 (동대입구역322-13),NaN,<NA>,17.00,2002-11-05 00:00:00,NaN,NaN,NaN
8,썬휴게실,휴게음식점,커피숍,01,2004-08-16,서울특별시 중구 오장동 206-35번지 외1필지(지하1층),"서울특별시 중구 마른내로 126 (오장동,외1필지(지하1층))",-1,52.89,2004-10-27 00:00:00,NaN,NaN,NaN
10,루비콘플러스,휴게음식점,커피숍,01,2004-06-02,서울특별시 중구 을지로6가 18-12번지 외1필지 두산타워(지상8층),"서울특별시 중구 장충단로 275 (을지로6가,외1필지 두산타워(지상8층))",8,13.22,2005-02-04 00:00:00,NaN,NaN,NaN
11,구스토,휴게음식점,커피숍,01,2004-04-22,서울특별시 종로구 평동 108-1번지 외36필지 지상4층,"서울특별시 종로구 새문안로 29 (평동,외36필지 지상4층)",4,NaN,2005-03-29 00:00:00,NaN,NaN,NaN
13,할리스커피,휴게음식점,커피숍,01,2005-08-16,서울특별시 종로구 공평동 55번지 지상1층,"서울특별시 종로구 우정국로 24 (공평동,지상1층)",1,NaN,2005-08-16 00:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13938,투썸플레이스엔타워점,휴게음식점,커피숍,01,2005-12-08,서울특별시 용산구 용산동2가 산 1-3 외1필지(광장1층),NaN,1,19.60,2025-12-19 20:01:13,NaN,NaN,NaN
14023,(주)보나비아티제신용산역점,휴게음식점,커피숍,01,2017-11-03,서울특별시 용산구 한강로2가 342 래미안용산,"서울특별시 용산구 한강대로 95, 지상1층 104호 (한강로2가, 래미안용산)",1,131.30,2025-12-29 16:17:36,NaN,NaN,NaN
14255,스타벅스 그랜드센트럴,휴게음식점,커피숍,01,2020-08-12,서울특별시 중구 남대문로5가 253,"서울특별시 중구 세종대로 14, 지하1층 (남대문로5가)",-1,279.50,2026-01-22 11:46:55,NaN,NaN,NaN
14406,그랜드센트럴 이그제큐티브라운지,휴게음식점,커피숍,01,2021-04-28,서울특별시 중구 남대문로5가 253,"서울특별시 중구 세종대로 14, 4층 (남대문로5가)",4,139.57,2026-02-06 11:48:23,NaN,NaN,NaN
14551,쥬청과 강남세곡점,휴게음식점,커피숍,01,2019-05-29,서울특별시 강남구 자곡동 56-119 강남센터뷰,"서울특별시 강남구 밤고개로 223, 강남센터뷰 1층 5호 (자곡동)",1,36.92,2026-02-24 13:11:47,NaN,NaN,NaN

In [29]:
#결측치 값에 한해서 rd_address 로 다시 탐색하기
mask = cafe_df["road_address"].isna() & cafe_df["rd_address"].notna()

cafe_df.loc[mask, ["road_address", "lat", "lng"]] = (
    add_kakao_geocode(
        cafe_df.loc[mask, ["rd_address"]].rename(columns={"rd_address": "address"}),
        kakao_key
    )[["road_address", "lat", "lng"]]
    .to_numpy()
)

In [30]:
cafe_df[cafe_df["road_address"].isna()]

,cafe_nm,type,detail_type,stable,aprove_day,address,rd_address,floor,sitearea,last_updated,road_address,lat,lng
0,토정방,휴게음식점,다방,01,1999-04-15,서울특별시 종로구 청진동 237-1번지,NaN,<NA>,NaN,1999-04-15 00:00:00,NaN,NaN,NaN
6,궁노루,휴게음식점,다방,01,1999-11-05,서울특별시 강남구 역삼동 796-21번지,NaN,<NA>,18.70,1999-11-05 00:00:00,NaN,NaN,NaN
24,궁전,휴게음식점,다방,01,1970-04-20,서울특별시 영등포구 신길동 209-103번지,NaN,<NA>,72.73,2000-05-17 00:00:00,NaN,NaN,NaN
32,프라자,휴게음식점,다방,01,2000-08-07,서울특별시 중구 남창동 47-2번지 47-17,NaN,<NA>,75.19,2000-09-29 00:00:00,NaN,NaN,NaN
34,인터뷰,휴게음식점,다방,01,2000-09-08,서울특별시 종로구 청진동 231-0번지,NaN,<NA>,NaN,2000-11-06 00:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12513,커피 정중심,휴게음식점,커피숍,01,2012-03-14,"서울특별시 노원구 중계동 584-1 삼창프라자 106, 107, 108호","서울특별시 노원구 한글비석로 383, 106, 107, 108호 (중계동, 삼창프라자)",1,41.16,2025-02-12 14:02:17,NaN,NaN,NaN
13634,할리스 신촌점,휴게음식점,커피숍,01,2004-07-09,"서울특별시 서대문구 창천동 31-12 ,13 (1,2,3층)","서울특별시 서대문구 연세로 34, 1~3층 (창천동)",1,254.04,2025-06-18 15:35:24,NaN,NaN,NaN
13725,종로1971카페,휴게음식점,커피숍,01,2024-05-31,"서울특별시 종로구 충신동 204-2 지하1, 지상1 102호","서울특별시 종로구 율곡로14길 55, 지하1, 지상1층 102호 (충신동)",1,27.05,2025-06-27 13:14:28,NaN,NaN,NaN
13792,더벤티 수유역점,휴게음식점,커피숍,01,2025-07-04,"서울특별시 강북구 번동 418-13 101,102호","서울특별시 강북구 오패산로 414, 101,102호 (번동)",1,152.00,2025-07-04 11:29:37,NaN,NaN,NaN
14902,노원 두물마루 Coffee&Snack,휴게음식점,커피숍,01,2025-01-09,서울특별시 노원구 하계동 354-4 4필지,NaN,<NA>,14.28,2025-11-21 11:32:58,NaN,NaN,NaN

# 서울시 실시간 인구데이터

## 데이터 불러오기

In [10]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "300"  # 요청종료위치
region = ['신논현역·논현역', '강남역', '역삼역']

for r in region:
    url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/citydata_ppltn/{start_index}/{end_index}/{r}"
    response = requests.get(url).json()
    print(response)

{'SeoulRtd.citydata_ppltn': [{'AREA_NM': '신논현역·논현역', 'AREA_CD': 'POI037', 'AREA_CONGEST_LVL': '보통', 'AREA_CONGEST_MSG': '사람이 몰려있을 수 있지만 크게 붐비지는 않아요. 도보 이동에 큰 제약이 없어요.', 'AREA_PPLTN_MIN': '14000', 'AREA_PPLTN_MAX': '16000', 'MALE_PPLTN_RATE': '47.9', 'FEMALE_PPLTN_RATE': '52.1', 'PPLTN_RATE_0': '0.7', 'PPLTN_RATE_10': '3.3', 'PPLTN_RATE_20': '19.8', 'PPLTN_RATE_30': '26.3', 'PPLTN_RATE_40': '20.4', 'PPLTN_RATE_50': '14.9', 'PPLTN_RATE_60': '8.5', 'PPLTN_RATE_70': '6.2', 'RESNT_PPLTN_RATE': '47.0', 'NON_RESNT_PPLTN_RATE': '53.0', 'REPLACE_YN': 'N', 'PPLTN_TIME': '2026-02-25 12:55', 'FCST_YN': 'Y', 'FCST_PPLTN': [{'FCST_TIME': '2026-02-25 14:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 15:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 16:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 17:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 18:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 19:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '16000', 'FCST_PPLTN_MAX': '18000'}, {'FCST_TIME': '2026-02-25 20:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 21:00', 'FCST_CONGEST_LVL': '약간 붐빔', 'FCST_PPLTN_MIN': '12000', 'FCST_PPLTN_MAX': '14000'}, {'FCST_TIME': '2026-02-25 22:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '10000', 'FCST_PPLTN_MAX': '12000'}, {'FCST_TIME': '2026-02-25 23:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '10000', 'FCST_PPLTN_MAX': '12000'}, {'FCST_TIME': '2026-02-26 00:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '8000', 'FCST_PPLTN_MAX': '8500'}, {'FCST_TIME': '2026-02-26 01:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '6000', 'FCST_PPLTN_MAX': '6500'}]}], 'RESULT': {'RESULT.CODE': 'INFO-000', 'RESULT.MESSAGE': '정상 처리되었습니다.'}}
{'SeoulRtd.citydata_ppltn': [{'AREA_NM': '강남역', 'AREA_CD': 'POI014', 'AREA_CONGEST_LVL': '붐빔', 'AREA_CONGEST_MSG': '사람들이 몰려있을 가능성이 매우 크고 많이 붐빈다고 느낄 수 있어요. 인구밀도가 높은 구간에서는 도보 이동시 부딪힘이 발생할 수 있어요.', 'AREA_PPLTN_MIN': '96000', 'AREA_PPLTN_MAX': '98000', 'MALE_PPLTN_RATE': '48.7', 'FEMALE_PPLTN_RATE': '51.3', 'PPLTN_RATE_0': '0.5', 'PPLTN_RATE_10': '4.4', 'PPLTN_RATE_20': '23.3', 'PPLTN_RATE_30': '27.4', 'PPLTN_RATE_40': '20.6', 'PPLTN_RATE_50': '13.4', 'PPLTN_RATE_60': '6.3', 'PPLTN_RATE_70': '4.0', 'RESNT_PPLTN_RATE': '45.1', 'NON_RESNT_PPLTN_RATE': '54.9', 'REPLACE_YN': 'N', 'PPLTN_TIME': '2026-02-25 12:55', 'FCST_YN': 'Y', 'FCST_PPLTN': [{'FCST_TIME': '2026-02-25 14:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '94000', 'FCST_PPLTN_MAX': '96000'}, {'FCST_TIME': '2026-02-25 15:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '92000', 'FCST_PPLTN_MAX': '94000'}, {'FCST_TIME': '2026-02-25 16:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '92000', 'FCST_PPLTN_MAX': '94000'}, {'FCST_TIME': '2026-02-25 17:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '90000', 'FCST_PPLTN_MAX': '92000'}, {'FCST_TIME': '2026-02-25 18:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '88000', 'FCST_PPLTN_MAX': '90000'}, {'FCST_TIME': '2026-02-25 19:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '84000', 'FCST_PPLTN_MAX': '86000'}, {'FCST_TIME': '2026-02-25 20:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '78000', 'FCST_PPLTN_MAX': '80000'}, {'FCST_TIME': '2026-02-25 21:00', 'FCST_CONGEST_LVL': '약간 붐빔', 'FCST_PPLTN_MIN': '68000', 'FCST_PPLTN_MAX': '70000'}, {'FCST_TIME': '2026-02-25 22:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '58000', 'FCST_PPLTN_MAX': '60000'}, {'FCST_TIME': '2026-02-25 23:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '46000', 'FCST_PPLTN_MAX': '48000'}, {'FCST_TIME': '2026-02-26 00:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '34000', 'FCST_PPLTN_MAX': '36000'}, {'FCST_TIME': '2026-02-26 01:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '26000', 'FCST_PPLTN_MAX': '28000'}]}], 'RESULT': {'RESULT.CODE': 'INFO-000', 'RESULT.MESSAGE': '정상 처리되었습니다.'}}
{'SeoulRtd.citydata_ppltn': [{'AREA_NM': '역삼역', 'AREA_CD': 'POI042', 'AREA_CONGEST_LVL': '붐빔', 'AREA_CONGEST_MSG': '사람들이 몰려있을 가능성이 매우 크고 많이 붐빈다고 느낄 수 있어요. 인구밀도가 높은 구간에서는 도보 이동시 부딪힘이 발생할 수 있어요.', 'AREA_PPLTN_MIN': '52000', 'AREA_PPLTN_MAX': '54000', 'MALE_PPLTN_RATE': '52.3', 'FEMALE_PPLTN_RATE': '47.7', 'PPLTN_RATE_0': '0.4', 'PPLTN_RATE_10': '2.2', 'PPLTN_RATE_20': '19.6', 'PPLTN_RATE_30': '30.7', 'PPLTN_RATE_40': '23.1', 'PPLTN_RATE_50': '13.7', 'PPLTN_RATE_60': '6.3', 'PPLTN_RATE_70': '3.9', 'RESNT_PPLTN_RATE': '54.1', 'NON_RESNT_PPLTN_RATE': '45.9', 'REPLACE_YN': 'N', 'PPLTN_TIME': '2026-02-25 12:55', 'FCST_YN': 'Y', 'FCST_PPLTN': [{'FCST_TIME': '2026-02-25 14:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '52000', 'FCST_PPLTN_MAX': '54000'}, {'FCST_TIME': '2026-02-25 15:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '52000', 'FCST_PPLTN_MAX': '54000'}, {'FCST_TIME': '2026-02-25 16:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '52000', 'FCST_PPLTN_MAX': '54000'}, {'FCST_TIME': '2026-02-25 17:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '50000', 'FCST_PPLTN_MAX': '52000'}, {'FCST_TIME': '2026-02-25 18:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '46000', 'FCST_PPLTN_MAX': '48000'}, {'FCST_TIME': '2026-02-25 19:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '38000', 'FCST_PPLTN_MAX': '40000'}, {'FCST_TIME': '2026-02-25 20:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '30000', 'FCST_PPLTN_MAX': '32000'}, {'FCST_TIME': '2026-02-25 21:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '24000', 'FCST_PPLTN_MAX': '26000'}, {'FCST_TIME': '2026-02-25 22:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '22000', 'FCST_PPLTN_MAX': '24000'}, {'FCST_TIME': '2026-02-25 23:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '18000', 'FCST_PPLTN_MAX': '20000'}, {'FCST_TIME': '2026-02-26 00:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '16000', 'FCST_PPLTN_MAX': '18000'}, {'FCST_TIME': '2026-02-26 01:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}]}], 'RESULT': {'RESULT.CODE': 'INFO-000', 'RESULT.MESSAGE': '정상 처리되었습니다.'}}

In [6]:
rows = response['SeoulRtd.citydata_ppltn']
print(rows)

move_df = pd.DataFrame(rows)
move_df.head()

[{'AREA_NM': '신논현역·논현역', 'AREA_CD': 'POI037', 'AREA_CONGEST_LVL': '약간 붐빔', 'AREA_CONGEST_MSG': '사람들이 몰려있을 가능성이 크고 붐빈다고 느낄 수 있어요. 인구밀도가 높은 구간에서는 도보 이동시 부딪힘이 발생할 수 있어요.', 'AREA_PPLTN_MIN': '14000', 'AREA_PPLTN_MAX': '16000', 'MALE_PPLTN_RATE': '47.8', 'FEMALE_PPLTN_RATE': '52.2', 'PPLTN_RATE_0': '0.7', 'PPLTN_RATE_10': '3.2', 'PPLTN_RATE_20': '20.0', 'PPLTN_RATE_30': '26.3', 'PPLTN_RATE_40': '20.4', 'PPLTN_RATE_50': '14.7', 'PPLTN_RATE_60': '8.5', 'PPLTN_RATE_70': '6.3', 'RESNT_PPLTN_RATE': '45.8', 'NON_RESNT_PPLTN_RATE': '54.2', 'REPLACE_YN': 'N', 'PPLTN_TIME': '2026-02-25 12:50', 'FCST_YN': 'Y', 'FCST_PPLTN': [{'FCST_TIME': '2026-02-25 14:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 15:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 16:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 17:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 18:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 19:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '16000', 'FCST_PPLTN_MAX': '18000'}, {'FCST_TIME': '2026-02-25 20:00', 'FCST_CONGEST_LVL': '붐빔', 'FCST_PPLTN_MIN': '14000', 'FCST_PPLTN_MAX': '16000'}, {'FCST_TIME': '2026-02-25 21:00', 'FCST_CONGEST_LVL': '약간 붐빔', 'FCST_PPLTN_MIN': '12000', 'FCST_PPLTN_MAX': '14000'}, {'FCST_TIME': '2026-02-25 22:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '10000', 'FCST_PPLTN_MAX': '12000'}, {'FCST_TIME': '2026-02-25 23:00', 'FCST_CONGEST_LVL': '보통', 'FCST_PPLTN_MIN': '10000', 'FCST_PPLTN_MAX': '12000'}, {'FCST_TIME': '2026-02-26 00:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '8000', 'FCST_PPLTN_MAX': '8500'}, {'FCST_TIME': '2026-02-26 01:00', 'FCST_CONGEST_LVL': '여유', 'FCST_PPLTN_MIN': '6000', 'FCST_PPLTN_MAX': '6500'}]}]

,AREA_NM,AREA_CD,AREA_CONGEST_LVL,AREA_CONGEST_MSG,AREA_PPLTN_MIN,AREA_PPLTN_MAX,MALE_PPLTN_RATE,FEMALE_PPLTN_RATE,PPLTN_RATE_0,PPLTN_RATE_10,...,PPLTN_RATE_40,PPLTN_RATE_50,PPLTN_RATE_60,PPLTN_RATE_70,RESNT_PPLTN_RATE,NON_RESNT_PPLTN_RATE,REPLACE_YN,PPLTN_TIME,FCST_YN,FCST_PPLTN
0,신논현역·논현역,POI037,약간 붐빔,사람들이 몰려있을 가능성이 크고 붐빈다고 느낄 수 있어요. 인구밀도가 높은 구간에서...,14000,16000,47.8,52.2,0.7,3.2,...,20.4,14.7,8.5,6.3,45.8,54.2,N,2026-02-25 12:50,Y,"[{'FCST_TIME': '2026-02-25 14:00', 'FCST_CONGE..."

# csv로 내보내기

In [170]:
center_df.to_csv("center_df.csv", index=False, encoding="utf-8-sig")

In [31]:
cafe_df.to_csv("cafe_df.csv", index=False, encoding="utf-8-sig")