# settings

In [1]:
# 필요한 라이브러리 로드
import requests 
import os
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
import re
import time

In [2]:
# env 파일 로드
load_dotenv()

True

## 함수

In [3]:
# kakao API로 주소, 위도, 경도 가져오는 함수
def add_kakao_geocode(df, kakao_key, address_col="addr", out_col = "rd_addr", sleep_sec=0.03, max_retry=5):
    url = "https://dapi.kakao.com/v2/local/search/address.json"
    out = df.copy()

    for c in [out_col, "lat", "lng"]:
        if c not in out.columns:
            out[c] = pd.NA

    session = requests.Session()
    session.headers.update({"Authorization": f"KakaoAK {kakao_key}"})

    # 중복 주소 1회만 호출
    uniq_addrs = (
        out[address_col]
        .dropna()
        .astype(str)
        .str.strip()
    )
    uniq_addrs = uniq_addrs[uniq_addrs != ""].drop_duplicates()

    cache = {}  # {addr: (road_address, lat, lng)}

    for add in uniq_addrs:
        params = {"query": add}
        result = None

        for i in range(max_retry):
            try:
                r = session.get(url, params=params, timeout=10)

                if r.status_code == 429:  # rate limit
                    time.sleep((i + 1) * 0.8)
                    continue

                r.raise_for_status()
                result = r.json()
                break
            except requests.exceptions.RequestException:
                time.sleep((i + 1) * 0.8)

        if not result:
            cache[add] = (pd.NA, pd.NA, pd.NA)
            continue

        docs = result.get("documents", [])
        if not docs:
            cache[add] = (pd.NA, pd.NA, pd.NA)
            continue

        road = docs[0].get("road_address")
        if road:
            cache[add] = (road.get("address_name"), road.get("y"), road.get("x"))
        else:
            addr = docs[0].get("address") or {}
            cache[add] = (addr.get("address_name"), addr.get("y"), addr.get("x"))

        time.sleep(sleep_sec)

    mapped = out[address_col].astype(str).str.strip().map(cache)
    out[[out_col, "lat", "lng"]] = mapped.apply(pd.Series)

    out["lat"] = pd.to_numeric(out["lat"], errors="coerce")
    out["lng"] = pd.to_numeric(out["lng"], errors="coerce")

    return out

In [4]:
# 상권 및 행정동 코드 추출
def spatial_join_code(target_df, target_gdf, shp_path, shp_col, out_col):
    """
    target_gdf: 이미 만들어진 GeoDataFrame (EPSG:4326)
    shp_path: shp 또는 zip 경로
    shp_col: shp에서 가져올 컬럼명
    out_col: cafe_df에 붙일 컬럼명
    """
    # shp 로드 & 좌표계 통일
    gdf = gpd.read_file(shp_path)
    crs_5181_gdf = target_gdf.to_crs("EPSG:5181") 
    '''
    폴리곤(상권)은 꼭짓점이 많아서 변환 시 오차가 누적될 수 있으므로 shp(5181) 기준으로 맞춤
    '''
    
    # 공간조인
    joined = gpd.sjoin(
        crs_5181_gdf,
        gdf[[shp_col, "geometry"]],
        how="left",
        predicate="within"
    )

    # 결과 붙이기
    target_df = target_df.copy()
    target_df.loc[joined.index, out_col] = joined[shp_col].values

    return target_df

# 지식산업센터

## 데이터 불러오기

In [132]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "300"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/InfoBizcenterApply/{start_index}/{end_index}/"

response = requests.get(url)
print(response.content.decode('utf-8'))

{"InfoBizcenterApply":{"list_total_count":213,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"IDX":208.0,"FAC_NM":"신내테크노타운","ADDRESS":"봉화산로 123(상봉동)","TELEPHONE":"02)3423-0057","APPROVAL_DATE":"96.5.28","COMPLE_DATE":"99.10.18"},{"IDX":136.0,"FAC_NM":"월곡동아파트형공장","ADDRESS":"하월곡동 96-113","TELEPHONE":"02-090-8083","APPROVAL_DATE":"33289","COMPLE_DATE":"1990.12.31"},{"IDX":135.0,"FAC_NM":"월곡동아파트형공장","ADDRESS":"하월곡동 96-113","TELEPHONE":"02-912-1034","APPROVAL_DATE":"33289","COMPLE_DATE":"1990.12.31"},{"IDX":140.0,"FAC_NM":"문정아르페온 1차 지식산업센터","ADDRESS":"서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)","TELEPHONE":"031-706-8577","APPROVAL_DATE":"2016.06.27","COMPLE_DATE":"2016.06.27"},{"IDX":139.0,"FAC_NM":"문정 대명벨리온","ADDRESS":"서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)","TELEPHONE":"02-2222-7357","APPROVAL_DATE":"2016.03.23","COMPLE_DATE":"2016.03.23"},{"IDX":141.0,"FAC_NM":"문정 현대지식산업센터Ｉ-1","ADDRESS":"서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)","TELEPHONE":"02-3451-0100","APPROVAL_DATE":"2016.02.29","COMPLE_DATE":"2016.02.29"},{"IDX":138.0,"FAC_NM":"송파유탑테크밸리","ADDRESS":"서울특별시 송파구 문정동 651-14 (문정도시개발구역 3-12BL)","TELEPHONE":"062-526-8383","APPROVAL_DATE":"2015.12.18","COMPLE_DATE":"2015.12.18"},{"IDX":207.0,"FAC_NM":"포휴","ADDRESS":"성수동1가 656-3","TELEPHONE":"3416-1500","APPROVAL_DATE":"2013.08.30","COMPLE_DATE":"2016.5.3"},{"IDX":117.0,"FAC_NM":"에이스하이엔드타워 10차","ADDRESS":"가산동 660","TELEPHONE":"6309-6045","APPROVAL_DATE":"2013.08.29","COMPLE_DATE":"2015.10.28"},{"IDX":206.0,"FAC_NM":"BY센터","ADDRESS":"성수동2가 301-51,301-38","TELEPHONE":"(02) 467-2247","APPROVAL_DATE":"2013.08.12","COMPLE_DATE":"2015.12.04"},{"IDX":205.0,"FAC_NM":"신한IT타워","ADDRESS":"성수동1가 656-603","TELEPHONE":"","APPROVAL_DATE":"2013.07.02","COMPLE_DATE":"2015.06.04"},{"IDX":116.0,"FAC_NM":"에스비즈니스센터","ADDRESS":"가산동 343-8","TELEPHONE":"2163-6749","APPROVAL_DATE":"2013.03.26","COMPLE_DATE":"2015.06.01"},{"IDX":165.0,"FAC_NM":"선유도역2차 아이에스비즈타워","ADDRESS":"선유로49길 23(양평동4가)","TELEPHONE":"6123-4100","APPROVAL_DATE":"2012.12.18","COMPLE_DATE":"2014.11.19"},{"IDX":115.0,"FAC_NM":"대륭테크노타운17차","ADDRESS":"가산동 670","TELEPHONE":"3466-0051","APPROVAL_DATE":"2012.12.10","COMPLE_DATE":"2015.05.15"},{"IDX":204.0,"FAC_NM":"서울숲\n드림타워(삼공)","ADDRESS":"성수동2가 323, 309-51","TELEPHONE":"(02)6222-8114","APPROVAL_DATE":"2012.10.31","COMPLE_DATE":"2015.03.23"},{"IDX":164.0,"FAC_NM":"에이스하이테크시티 2","ADDRESS":"선유로13길 25(문래동6가)","TELEPHONE":"2257-8114","APPROVAL_DATE":"2012.08.27","COMPLE_DATE":"2014.10.24"},{"IDX":2.0,"FAC_NM":"NICE그룹 지식산업센터","ADDRESS":"상일로6길 55 (상일동)","TELEPHONE":"2122-4415","APPROVAL_DATE":"2012.06.29","COMPLE_DATE":"2014.02.28"},{"IDX":166.0,"FAC_NM":"SK V1 center","ADDRESS":"당산로41길 11(당산동4가)","TELEPHONE":"6121-8100","APPROVAL_DATE":"2012.06.19","COMPLE_DATE":"2015.02.17"},{"IDX":203.0,"FAC_NM":"서울숲IT캐슬","ADDRESS":"성수동1가 671-6, -41 외 4필지","TELEPHONE":"(02) 2086-3346","APPROVAL_DATE":"2012.05.10","COMPLE_DATE":"2014.06.17"},{"IDX":1.0,"FAC_NM":"세종투자㈜","ADDRESS":"강동구 상일로10길 36 (상일동)","TELEPHONE":"3415-4971","APPROVAL_DATE":"2011.11.30","COMPLE_DATE":"2013.09.13"},{"IDX":202.0,"FAC_NM":"에이스하이앤드\n 성수타워","ADDRESS":"성수동2가 269-25,269-51,\n269-115,328-5","TELEPHONE":"(02) 2112-6491","APPROVAL_DATE":"2011.11.15","COMPLE_DATE":"2015.06.19"},{"IDX":201.0,"FAC_NM":"에이스성수타워1차","ADDRESS":"성수2가 280-15,19","TELEPHONE":"(02) 591-0607","APPROVAL_DATE":"2011.10.20","COMPLE_DATE":"2014.03.11"},{"IDX":52.0,"FAC_NM":"G플러스 코오롱 디지털타워","ADDRESS":"구로동 222-31","TELEPHONE":"858-3650","APPROVAL_DATE":"2011.06.09","COMPLE_DATE":"2013.7.24"},{"IDX":163.0,"FAC_NM":"선유도역1차 아이에스비즈타워","ADDRESS":"양평로21길 26(양평동5가)","TELEPHONE":"6968-1004","APPROVAL_DATE":"2011.04.21","COMPLE_DATE":"2013.5.27"},{"IDX":200.0,"FAC_NM":"서울숲\n한라시그마밸리II","ADDRESS":"성수동2가 333-15","TELEPHONE":"(02) 4199-5621","APPROVAL_DATE":"2011.02.25","COMPLE_DATE":"2013.03.28"},{"IDX":51.0,"FAC_NM":"대륭포스트타워7차","ADDRESS":"구로동 170-10 외 2필지","TELEPHONE":"6942-9500","APPROVAL_DATE":"2011.02.21","COMPLE_DATE":"2012.12.11"},{"IDX":10.0,"FAC_NM":"강서IT밸리","ADDRESS":"화곡로68길 82","TELEPHONE":"6961-5111","APPROVAL_DATE":"2010.3.9","COMPLE_DATE":"2012.2.6"},{"IDX":11.0,"FAC_NM":"강서한강자이","ADDRESS":"양천로 401","TELEPHONE":"6968-5801~2","APPROVAL_DATE":"2010.10.15","COMPLE_DATE":"2013.6.7"},{"IDX":199.0,"FAC_NM":"서울숲 \n한라에코벨리","ADDRESS":"성수동1가 656-36\n656-1222","TELEPHONE":"(02) 549-6693","APPROVAL_DATE":"2010.09.09","COMPLE_DATE":"2012.09.06"},{"IDX":198.0,"FAC_NM":"성수동\n아이에스비즈타워","ADDRESS":"성수동2가289-319,327,328","TELEPHONE":"(02) 3218-6643","APPROVAL_DATE":"2010.08.28","COMPLE_DATE":"2012.07.23"},{"IDX":162.0,"FAC_NM":"KnK디지털타워","ADDRESS":"영신로 220(영등포동8가)","TELEPHONE":"2675-6060","APPROVAL_DATE":"2010.08.27","COMPLE_DATE":"2012.12.07"},{"IDX":167.0,"FAC_NM":"문래동 하우스디 비즈","ADDRESS":"선유로3길 10(문래동5가)","TELEPHONE":"2112-6339","APPROVAL_DATE":"2010.08.10","COMPLE_DATE":"2016.05.09"},{"IDX":160.0,"FAC_NM":"선유도코오롱디지털타워","ADDRESS":"양평로22길21(양평동5가)","TELEPHONE":"2062-5996","APPROVAL_DATE":"2010.07.13","COMPLE_DATE":"2012.03.23"},{"IDX":197.0,"FAC_NM":"성수에이팩센터","ADDRESS":"성수동2가 289-5\n289-334,289-335","TELEPHONE":"(02) 3416-1541","APPROVAL_DATE":"2010.06.24","COMPLE_DATE":"2012.08.24"},{"IDX":196.0,"FAC_NM":"아연디지털타워","ADDRESS":"성수동2가314-37","TELEPHONE":"(02) 499-2275","APPROVAL_DATE":"2010.06.01","COMPLE_DATE":"2012.08.31"},{"IDX":195.0,"FAC_NM":"서울숲 SK V1 타워","ADDRESS":"성수동2가284-55, 284-107","TELEPHONE":"(02) 6233-8000","APPROVAL_DATE":"2010.04.13","COMPLE_DATE":"2014.07.18"},{"IDX":114.0,"FAC_NM":"에이스하이엔드9차","ADDRESS":"가산동 481-2","TELEPHONE":"6309-6051","APPROVAL_DATE":"2010.04","COMPLE_DATE":"2012.07.20"},{"IDX":194.0,"FAC_NM":"서울숲\nIT 밸리","ADDRESS":"성수동1가 13-170\n외9필지(13-170,13-166,13-472,13-169,13-256,13-164,13-253,13-171,13-255,13-167)","TELEPHONE":"(02) 2090-8202","APPROVAL_DATE":"2010.03.24.","COMPLE_DATE":"2013.02.08"},{"IDX":50.0,"FAC_NM":"JnK 디지털타워","ADDRESS":"구로3동 222-3","TELEPHONE":"6124-6611","APPROVAL_DATE":"2010.01.20","COMPLE_DATE":"2012.2.15"},{"IDX":121.0,"FAC_NM":"대성D-POLIS","ADDRESS":"가산동 543-1","TELEPHONE":"861-9114","APPROVAL_DATE":"2009.12","COMPLE_DATE":"2012.09"},{"IDX":159.0,"FAC_NM":"동아프라임밸리","ADDRESS":"영등포로5길19(양평동2가)","TELEPHONE":"6210-7201","APPROVAL_DATE":"2009.10.21","COMPLE_DATE":"2011.11.25"},{"IDX":161.0,"FAC_NM":"솔버스 비즈타워","ADDRESS":"선유서로31길3(양평동3가)","TELEPHONE":"6963-8080","APPROVAL_DATE":"2009.10.19","COMPLE_DATE":"2012.09.05"},{"IDX":212.0,"FAC_NM":"동대문패션비즈센터 ","ADDRESS":"신당동 251-160","TELEPHONE":"070-8895-7347","APPROVAL_DATE":"2009.05.14","COMPLE_DATE":"2012.03.07"},{"IDX":129.0,"FAC_NM":"현대지식산업센터","ADDRESS":"독산동 291-1 ","TELEPHONE":"858-3080","APPROVAL_DATE":"2009.04","COMPLE_DATE":"2014.03.04"},{"IDX":193.0,"FAC_NM":"이레타워","ADDRESS":"성수동2가 277-175번지","TELEPHONE":"(02) 466-2663","APPROVAL_DATE":"2009.01.22","COMPLE_DATE":"2009.08.07"},{"IDX":9.0,"FAC_NM":"강서한화비즈메트로2차","ADDRESS":"양천로551-24","TELEPHONE":"6957-1990","APPROVAL_DATE":"2008.7.25","COMPLE_DATE":"2012.1.16"},{"IDX":8.0,"FAC_NM":"강서한화비즈메트로1차","ADDRESS":"양천로551-17","TELEPHONE":"6957-1990","APPROVAL_DATE":"2008.7.25","COMPLE_DATE":"2012.1.13"},{"IDX":113.0,"FAC_NM":"알에스엠타워","ADDRESS":"가산동 327-29","TELEPHONE":"2112-6300","APPROVAL_DATE":"2008.12.03","COMPLE_DATE":"2012.12.18"},{"IDX":137.0,"FAC_NM":"가든파이브웍스","ADDRESS":"충민로52(문정동)","TELEPHONE":"02-2047-1014","APPROVAL_DATE":"2008.11.12","COMPLE_DATE":"2008.10.16"},{"IDX":47.0,"FAC_NM":"STX-W 타워","ADDRESS":"구로동 615-3외 4필지","TELEPHONE":"6124-3333","APPROVAL_DATE":"2008.10.23","COMPLE_DATE":"2011.10.30"},{"IDX":192.0,"FAC_NM":"서울숲 코오롱\n디지털타워2차","ADDRESS":"성수동2가 333-140번지","TELEPHONE":"(031) 727-1461","APPROVAL_DATE":"2008.10.21","COMPLE_DATE":"2010.09.10"},{"IDX":110.0,"FAC_NM":"에이스하이엔드7차","ADDRESS":"가산동 345-33","TELEPHONE":"6111-1500","APPROVAL_DATE":"2008.10.10","COMPLE_DATE":"2010.07"},{"IDX":191.0,"FAC_NM":"서울숲 코오롱\n디지털타워3차","ADDRESS":"성수동1가 14-18번지 외 1 필지","TELEPHONE":"(02) 499-0430","APPROVAL_DATE":"2008.10.02","COMPLE_DATE":"2010.11.24"},{"IDX":69.0,"FAC_NM":"엘리시아","ADDRESS":"가산동 60-69","TELEPHONE":"890-8888","APPROVAL_DATE":"2008.09.23","COMPLE_DATE":"2011.03"},{"IDX":190.0,"FAC_NM":"휴먼테코","ADDRESS":"성수동2가 281-16 번지 외 1 필지","TELEPHONE":"02)6466-5000","APPROVAL_DATE":"2008.09.12","COMPLE_DATE":"2010.06.07"},{"IDX":112.0,"FAC_NM":"KCC웰츠밸리","ADDRESS":"가산동 470-8","TELEPHONE":"6111-8100","APPROVAL_DATE":"2008.09.09","COMPLE_DATE":"2010.12"},{"IDX":68.0,"FAC_NM":"대륭포스트타워6차","ADDRESS":"가산동 50-3","TELEPHONE":"2083-5114","APPROVAL_DATE":"2008.09.05","COMPLE_DATE":"2010.08"},{"IDX":189.0,"FAC_NM":"서울숲 \n한라시그마밸리","ADDRESS":"성수동2가 325-2 번지 외 12 필지","TELEPHONE":"(02) 6466-8114","APPROVAL_DATE":"2008.09.03","COMPLE_DATE":"2011.02.16"},{"IDX":111.0,"FAC_NM":"더루벤스밸리","ADDRESS":"가산동 691-3","TELEPHONE":"2109-9800","APPROVAL_DATE":"2008.08.14","COMPLE_DATE":"2011.09"},{"IDX":49.0,"FAC_NM":"파트너스타워2차","ADDRESS":"구로동 1128-3","TELEPHONE":"2028-3993","APPROVAL_DATE":"2008.07.28","COMPLE_DATE":"2010.02.16"},{"IDX":108.0,"FAC_NM":"STX V-TOWER","ADDRESS":"가산동 371-37","TELEPHONE":"8111-3102","APPROVAL_DATE":"2008.07","COMPLE_DATE":"2010.11"},{"IDX":188.0,"FAC_NM":"한신 아크밸리","ADDRESS":"성수동2가 277-43번지","TELEPHONE":"(02) 421-2367","APPROVAL_DATE":"2008.05.26","COMPLE_DATE":"2010.05.27"},{"IDX":158.0,"FAC_NM":"양평동이노플렉스","ADDRESS":"양산로57-5(양평동3가)","TELEPHONE":"2675-0134","APPROVAL_DATE":"2008.05.14","COMPLE_DATE":"2010.01.20"},{"IDX":67.0,"FAC_NM":"갑을아파트형공장","ADDRESS":"가산동60-5","TELEPHONE":"3397-7705","APPROVAL_DATE":"2008.05.09","COMPLE_DATE":"2010.07"},{"IDX":107.0,"FAC_NM":"IT프리미어타워","ADDRESS":"가산동 345-50","TELEPHONE":"2621-1991","APPROVAL_DATE":"2008.04.24","COMPLE_DATE":"2010.02"},{"IDX":106.0,"FAC_NM":"에이스하이엔드8차","ADDRESS":"가산동 345-4","TELEPHONE":"6123-5000","APPROVAL_DATE":"2008.03.20","COMPLE_DATE":"2010.09"},{"IDX":105.0,"FAC_NM":"BYC하이씨티","ADDRESS":"가산동 371-17","TELEPHONE":"6947-3100","APPROVAL_DATE":"2008.03.12","COMPLE_DATE":"2012.02"},{"IDX":104.0,"FAC_NM":"INNOPLEX 2차","ADDRESS":"가산동 371-59","TELEPHONE":"6111-0123","APPROVAL_DATE":"2008.02.20","COMPLE_DATE":"2010.03"},{"IDX":66.0,"FAC_NM":"대륭포스트타워5차","ADDRESS":"가산동 60-3","TELEPHONE":"2624-4116","APPROVAL_DATE":"2008.02.19","COMPLE_DATE":"2010.01"},{"IDX":103.0,"FAC_NM":"파트너스타워","ADDRESS":"가산동 345-13","TELEPHONE":"859-5641","APPROVAL_DATE":"2008.02.12","COMPLE_DATE":"2009.10"},{"IDX":102.0,"FAC_NM":"한라시그마밸리","ADDRESS":"가산동 345-90 ","TELEPHONE":"6343-6800","APPROVAL_DATE":"2008.01.17","COMPLE_DATE":"2009.12"},{"IDX":101.0,"FAC_NM":"백상스타타워2차","ADDRESS":"가산동 459-22","TELEPHONE":"6111-6100","APPROVAL_DATE":"2007.12.06","COMPLE_DATE":"2010.07"},{"IDX":65.0,"FAC_NM":"백상스타타워1차","ADDRESS":"가산동 60-17","TELEPHONE":"6111-7116","APPROVAL_DATE":"2007.11.29","COMPLE_DATE":"2010.07"},{"IDX":46.0,"FAC_NM":"한화비즈 메트로1차","ADDRESS":"구로동 851외 2필지","TELEPHONE":"2621-2490","APPROVAL_DATE":"2007.11.20","COMPLE_DATE":"2010.12.28"},{"IDX":211.0,"FAC_NM":"아시아미디어타워","ADDRESS":"초동 42","TELEPHONE":"2275-3332","APPROVAL_DATE":"2007.11.13","COMPLE_DATE":"2009.12.01"},{"IDX":99.0,"FAC_NM":"디지털엠파이어","ADDRESS":"가산동 685","TELEPHONE":"2624-2121","APPROVAL_DATE":"2007.10.17","COMPLE_DATE":"2009.02"},{"IDX":98.0,"FAC_NM":"LG아파트형공장","ADDRESS":"가산동 459-9","TELEPHONE":"6945-4455","APPROVAL_DATE":"2007.10.12","COMPLE_DATE":"2009.04"},{"IDX":154.0,"FAC_NM":"선유도우림라이온스밸리A","ADDRESS":"양평로 149(양평동5가)","TELEPHONE":"2638-7114","APPROVAL_DATE":"2007.09.17","COMPLE_DATE":"2009.08.07"},{"IDX":155.0,"FAC_NM":"선유도우림라이온스밸리B","ADDRESS":"양평로21가길19(양평동5가)","TELEPHONE":"2638-7114","APPROVAL_DATE":"2007.09.17","COMPLE_DATE":"2009.08.07"},{"IDX":64.0,"FAC_NM":"에이스하이엔드6차","ADDRESS":"가산동 60-25","TELEPHONE":"6299-5100","APPROVAL_DATE":"2007.08.24","COMPLE_DATE":"2009.08"},{"IDX":157.0,"FAC_NM":"벽산디지털밸리","ADDRESS":"경인로71길 70(문래동5가)","TELEPHONE":"6098-5114","APPROVAL_DATE":"2007.08.24","COMPLE_DATE":"2009.12.17"},{"IDX":97.0,"FAC_NM":"에이스하이엔드5차","ADDRESS":"가산동 505-18","TELEPHONE":"6340-0200","APPROVAL_DATE":"2007.08.23","COMPLE_DATE":"2009.07"},{"IDX":96.0,"FAC_NM":"이앤씨드림타워8차","ADDRESS":"가산동 327-27","TELEPHONE":"6277-8200","APPROVAL_DATE":"2007.08.16","COMPLE_DATE":"2009.02"},{"IDX":109.0,"FAC_NM":"가산비즈니스센터","ADDRESS":"가산동 371-6 ","TELEPHONE":"3289-9114","APPROVAL_DATE":"2007.08.16","COMPLE_DATE":"2011.09"},{"IDX":100.0,"FAC_NM":"한국전자협동APT공장","ADDRESS":"가산동 371-51","TELEPHONE":"858-9261","APPROVAL_DATE":"2007.08.13","COMPLE_DATE":"2007.12.06"},{"IDX":156.0,"FAC_NM":"금강펜테리움IT타워","ADDRESS":"당산로 171(당산동4가)","TELEPHONE":"2638-8585","APPROVAL_DATE":"2007.07.24","COMPLE_DATE":"2010.01.08"},{"IDX":44.0,"FAC_NM":"벽산디지털밸리7차","ADDRESS":"구로동 170-13","TELEPHONE":"839-3152","APPROVAL_DATE":"2007.07.23","COMPLE_DATE":"2009.06.23"},{"IDX":95.0,"FAC_NM":"에이스하이엔드3차","ADDRESS":"가산동 371-51","TELEPHONE":"2624-1100","APPROVAL_DATE":"2007.06.13","COMPLE_DATE":"2009.07"},{"IDX":86.0,"FAC_NM":"INNOPLEX 1차","ADDRESS":"가산동 371-47","TELEPHONE":"6679-0007","APPROVAL_DATE":"2007.04.13","COMPLE_DATE":"2008.08.14"},{"IDX":94.0,"FAC_NM":"벽산디지털밸리6차","ADDRESS":"가산동 481-4","TELEPHONE":"869-1166","APPROVAL_DATE":"2007.04.04","COMPLE_DATE":"2009.03"},{"IDX":187.0,"FAC_NM":"서울숲 코오롱 1차","ADDRESS":"성수동2가 308-4번지","TELEPHONE":"시행사:2115-8899","APPROVAL_DATE":"2007.02.11","COMPLE_DATE":"2010.06.10"},{"IDX":7.0,"FAC_NM":"우림블루나인비즈니스센터","ADDRESS":"양천로 583","TELEPHONE":"2093-1011","APPROVAL_DATE":"2006.4.26","COMPLE_DATE":"2008.9.26"},{"IDX":93.0,"FAC_NM":"롯데IT캐슬2차","ADDRESS":"가산동 371-16","TELEPHONE":"2627-8114","APPROVAL_DATE":"2006.11.21","COMPLE_DATE":"2008.09"},{"IDX":63.0,"FAC_NM":"이앤씨드림타워7차","ADDRESS":"가산동 60-44","TELEPHONE":"6277-8200","APPROVAL_DATE":"2006.11.06","COMPLE_DATE":"2008.01"},{"IDX":43.0,"FAC_NM":"에이스하이엔드타워2차","ADDRESS":"구로동 222-14","TELEPHONE":"6340-5555","APPROVAL_DATE":"2006.08.17","COMPLE_DATE":"2008.04.15"},{"IDX":186.0,"FAC_NM":"아주디지털타워","ADDRESS":"성수동2가 284-56번지","TELEPHONE":"(02) 462-2235","APPROVAL_DATE":"2006.07.27","COMPLE_DATE":"2010.01.08"},{"IDX":213.0,"FAC_NM":"산타플러스","ADDRESS":"난곡로 60","TELEPHONE":"02-865-6976","APPROVAL_DATE":"2005.11.28","COMPLE_DATE":"2006.7.26"},{"IDX":92.0,"FAC_NM":"㈜동광인터내셔날","ADDRESS":"가산동 459-14","TELEPHONE":"3479-2700","APPROVAL_DATE":"2005.11.23","COMPLE_DATE":"2006.01"},{"IDX":152.0,"FAC_NM":"월드메르디앙비즈센터","ADDRESS":"양산로 53(양평동3가)","TELEPHONE":"2165-8980","APPROVAL_DATE":"2005.10.05","COMPLE_DATE":"2007.02.14"},{"IDX":61.0,"FAC_NM":"(주)한섬임대아파트형공장","ADDRESS":"가산동 60-42","TELEPHONE":"838-0146","APPROVAL_DATE":"2005.09.28","COMPLE_DATE":"2006.09"},{"IDX":41.0,"FAC_NM":"㈜대양디앤티","ADDRESS":"구로동 197-47","TELEPHONE":"858-2111","APPROVAL_DATE":"2005.09.09","COMPLE_DATE":"2007.08.07"},{"IDX":91.0,"FAC_NM":"승일벤쳐타워","ADDRESS":"가산동 371-42","TELEPHONE":"862-2351","APPROVAL_DATE":"2005.06.18","COMPLE_DATE":"2006.12"},{"IDX":42.0,"FAC_NM":"대륭포스트타워3차","ADDRESS":"구로동 182-4","TELEPHONE":"2028-0114","APPROVAL_DATE":"2005.06.10","COMPLE_DATE":"2007.06.07"},{"IDX":153.0,"FAC_NM":"에이스하이테크시티","ADDRESS":"경인로 775(문래동3가)","TELEPHONE":"6309-6112","APPROVAL_DATE":"2005.05.15","COMPLE_DATE":"2007.04.13"},{"IDX":90.0,"FAC_NM":"롯데정보통신","ADDRESS":"가산동 533-2","TELEPHONE":"2626-4000","APPROVAL_DATE":"2005.05.11","COMPLE_DATE":"2007.03"},{"IDX":134.0,"FAC_NM":"DMC 첨단산업센터","ADDRESS":"마포구 상암동 1580 \n첨단산업센터","TELEPHONE":"2171-2847","APPROVAL_DATE":"2004.11.03","COMPLE_DATE":"2008.03.31"},{"IDX":62.0,"FAC_NM":"IT미래타워","ADDRESS":"가산동 60-21","TELEPHONE":"2027-5757","APPROVAL_DATE":"2004.10.27","COMPLE_DATE":"2007.04.30"},{"IDX":89.0,"FAC_NM":"뉴티캐슬","ADDRESS":"가산동 429-1","TELEPHONE":"2626-9960","APPROVAL_DATE":"2004.08.11","COMPLE_DATE":"2006.12"},{"IDX":88.0,"FAC_NM":"대륭테크노타운13차","ADDRESS":"가산동 664","TELEPHONE":"2029-5600","APPROVAL_DATE":"2004.07.28","COMPLE_DATE":"2008.05"},{"IDX":185.0,"FAC_NM":"성수동\n 우림e-BIZ Center","ADDRESS":"성수동2가 280-21번지","TELEPHONE":"(02)2024-2110","APPROVAL_DATE":"2004.07.26","COMPLE_DATE":"2006.10.18"},{"IDX":132.0,"FAC_NM":"중계제1공단","ADDRESS":"노원구 노원로19길 31(중계동)\n[중계동 511-2]","TELEPHONE":"948-2846","APPROVAL_DATE":"2004.07.13","COMPLE_DATE":"1991.12.07"},{"IDX":130.0,"FAC_NM":"월계테크노타운","ADDRESS":"노원구 월계로45길 28(월계동)\n[월계동 562번지]","TELEPHONE":"990-2727","APPROVAL_DATE":"2004.07.08","COMPLE_DATE":"1994.12.19"},{"IDX":87.0,"FAC_NM":"대륭테크노타운12차","ADDRESS":"가산동 327-32","TELEPHONE":"2029-6114","APPROVAL_DATE":"2004.07.08","COMPLE_DATE":"2008.05"},{"IDX":131.0,"FAC_NM":"하계테크노타운","ADDRESS":"노원구 노원로15길 10(하계동)\n[하계동 250-3]","TELEPHONE":"6235-3500","APPROVAL_DATE":"2004.07.07","COMPLE_DATE":"1998.11.17"},{"IDX":184.0,"FAC_NM":"풍림테크원","ADDRESS":"성수동2가 273-10번지","TELEPHONE":"(02) 468-9319/464-0133","APPROVAL_DATE":"2004.05.31","COMPLE_DATE":"2005.09.15"},{"IDX":31.0,"FAC_NM":"이앤씨드림타워6차","ADDRESS":"구로동 197-28","TELEPHONE":"801-8603","APPROVAL_DATE":"2004.05.10","COMPLE_DATE":"2005.12.21"},{"IDX":39.0,"FAC_NM":"대륭포스트타워2차","ADDRESS":"구로동 182-13","TELEPHONE":"2082-0114","APPROVAL_DATE":"2004.03.24","COMPLE_DATE":"2005.10.06"},{"IDX":60.0,"FAC_NM":"스타밸리","ADDRESS":"가산동 60-11","TELEPHONE":"2027-0114","APPROVAL_DATE":"2004.02.27","COMPLE_DATE":"2006.04"},{"IDX":37.0,"FAC_NM":"코오롱빌란트2차","ADDRESS":"구로동 222-8","TELEPHONE":"2081-1111","APPROVAL_DATE":"2004.02.25","COMPLE_DATE":"2006.12.28"},{"IDX":38.0,"FAC_NM":"대륭포스트타워1차","ADDRESS":"구로동 212-8","TELEPHONE":"2082-2331","APPROVAL_DATE":"2004.01.10","COMPLE_DATE":"2005.10.18"},{"IDX":36.0,"FAC_NM":"코오롱싸이언스밸리2차","ADDRESS":"구로동 811","TELEPHONE":"850-3150","APPROVAL_DATE":"2003.12.30","COMPLE_DATE":"2005.12.13"},{"IDX":34.0,"FAC_NM":"에이스하이엔드1차","ADDRESS":"구로동 235-2","TELEPHONE":"6220-2010","APPROVAL_DATE":"2003.12.30","COMPLE_DATE":"2005.09.30"},{"IDX":150.0,"FAC_NM":"메가벤처타워","ADDRESS":"문래로20길60(문래동3가)","TELEPHONE":"2632-4438","APPROVAL_DATE":"2003.12.22","COMPLE_DATE":"2005.12.27"},{"IDX":79.0,"FAC_NM":"롯데IT캐슬","ADDRESS":"가산동 550-1","TELEPHONE":"2026-8970","APPROVAL_DATE":"2003.12.20","COMPLE_DATE":"2005.09"},{"IDX":30.0,"FAC_NM":"이앤씨드림타워5차","ADDRESS":"구로동 197-13","TELEPHONE":"6336-3591","APPROVAL_DATE":"2003.12.19","COMPLE_DATE":"2004.12.14"},{"IDX":59.0,"FAC_NM":"벽산디지털밸리5차","ADDRESS":"가산동 60-73","TELEPHONE":"2082-5990","APPROVAL_DATE":"2003.11.05","COMPLE_DATE":"2005.10"},{"IDX":33.0,"FAC_NM":"마리오디지털밸리","ADDRESS":"구로동 222-12","TELEPHONE":"890-8498","APPROVAL_DATE":"2003.10.13","COMPLE_DATE":"2005.10.25"},{"IDX":85.0,"FAC_NM":"코오롱디지털타워애스톤","ADDRESS":"가산동 505-14","TELEPHONE":"2082-8114","APPROVAL_DATE":"2003.09.26","COMPLE_DATE":"2005.09"},{"IDX":84.0,"FAC_NM":"에이스테크노타워10차","ADDRESS":"가산동 470-5","TELEPHONE":"6670-5300","APPROVAL_DATE":"2003.09.16","COMPLE_DATE":"2005.07"},{"IDX":35.0,"FAC_NM":"코오롱싸이언스밸리1차","ADDRESS":"구로동 187-10","TELEPHONE":"2025-4580","APPROVAL_DATE":"2003.08.08","COMPLE_DATE":"2005.07.05"},{"IDX":40.0,"FAC_NM":"삼성IT밸리","ADDRESS":"구로동 197-5","TELEPHONE":"2028-2363","APPROVAL_DATE":"2003.07.20","COMPLE_DATE":"2007.03.30"},{"IDX":149.0,"FAC_NM":"문래동빅토리테크노타워","ADDRESS":"선유서로 17(문래동5가)","TELEPHONE":"2068-8212","APPROVAL_DATE":"2003.07.08","COMPLE_DATE":"2004.10.08"},{"IDX":183.0,"FAC_NM":"(주)삼우","ADDRESS":"성수동2가 272-38번지","TELEPHONE":"(02) 2274-2734","APPROVAL_DATE":"2003.06.30","COMPLE_DATE":"2003.12.17"},{"IDX":83.0,"FAC_NM":"에이스테크노타워9차","ADDRESS":"가산동 345-30","TELEPHONE":"2026-1900","APPROVAL_DATE":"2003.06.30","COMPLE_DATE":"2005.07"},{"IDX":181.0,"FAC_NM":"영동테크노타워","ADDRESS":"성수동2가 300-4번지","TELEPHONE":"(02) 2118-7012","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2003.06.20"},{"IDX":182.0,"FAC_NM":"삼환디지털\n벤처타워","ADDRESS":"성수동2가 280-13번지","TELEPHONE":"2024-0020(관리실)","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2006.01.19"},{"IDX":82.0,"FAC_NM":"제이플라츠","ADDRESS":"가산동 459-11 ","TELEPHONE":"2028-5000","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2007.04"},{"IDX":29.0,"FAC_NM":"이앤씨드림타워3차","ADDRESS":"구로동 197-33","TELEPHONE":"6330-2302","APPROVAL_DATE":"2003.06.13","COMPLE_DATE":"2004.09.08"},{"IDX":81.0,"FAC_NM":"우림라이온스밸리2차","ADDRESS":"가산동 680","TELEPHONE":"2027-2114","APPROVAL_DATE":"2003.05.28","COMPLE_DATE":"2006.05"},{"IDX":28.0,"FAC_NM":"이앤씨드림타워2차","ADDRESS":"구로동 197-10","TELEPHONE":"6330-2200","APPROVAL_DATE":"2003.05.07","COMPLE_DATE":"2004.09.08"},{"IDX":80.0,"FAC_NM":"호서대벤처타워","ADDRESS":"가산동 319","TELEPHONE":"2627-5980","APPROVAL_DATE":"2003.04.24.","COMPLE_DATE":"2008.10.07"},{"IDX":58.0,"FAC_NM":"SJ테크노빌","ADDRESS":"가산동 60-19","

In [133]:
data = response.json()
rows = data['InfoBizcenterApply']['row']
print(rows)

center_df = pd.DataFrame(rows)
center_df

[{'IDX': 208.0, 'FAC_NM': '신내테크노타운', 'ADDRESS': '봉화산로 123(상봉동)', 'TELEPHONE': '02)3423-0057', 'APPROVAL_DATE': '96.5.28', 'COMPLE_DATE': '99.10.18'}, {'IDX': 136.0, 'FAC_NM': '월곡동아파트형공장', 'ADDRESS': '하월곡동 96-113', 'TELEPHONE': '02-090-8083', 'APPROVAL_DATE': '33289', 'COMPLE_DATE': '1990.12.31'}, {'IDX': 135.0, 'FAC_NM': '월곡동아파트형공장', 'ADDRESS': '하월곡동 96-113', 'TELEPHONE': '02-912-1034', 'APPROVAL_DATE': '33289', 'COMPLE_DATE': '1990.12.31'}, {'IDX': 140.0, 'FAC_NM': '문정아르페온 1차 지식산업센터', 'ADDRESS': '서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)', 'TELEPHONE': '031-706-8577', 'APPROVAL_DATE': '2016.06.27', 'COMPLE_DATE': '2016.06.27'}, {'IDX': 139.0, 'FAC_NM': '문정 대명벨리온', 'ADDRESS': '서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)', 'TELEPHONE': '02-2222-7357', 'APPROVAL_DATE': '2016.03.23', 'COMPLE_DATE': '2016.03.23'}, {'IDX': 141.0, 'FAC_NM': '문정 현대지식산업센터Ｉ-1', 'ADDRESS': '서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)', 'TELEPHONE': '02-3451-0100', 'APPROVAL_DATE': '2016.02.29', 'COMPLE_DATE': '2016.02.29'}, {'IDX': 138.0, 'FAC_NM': '송파유탑테크밸리', 'ADDRESS': '서울특별시 송파구 문정동 651-14 (문정도시개발구역 3-12BL)', 'TELEPHONE': '062-526-8383', 'APPROVAL_DATE': '2015.12.18', 'COMPLE_DATE': '2015.12.18'}, {'IDX': 207.0, 'FAC_NM': '포휴', 'ADDRESS': '성수동1가 656-3', 'TELEPHONE': '3416-1500', 'APPROVAL_DATE': '2013.08.30', 'COMPLE_DATE': '2016.5.3'}, {'IDX': 117.0, 'FAC_NM': '에이스하이엔드타워 10차', 'ADDRESS': '가산동 660', 'TELEPHONE': '6309-6045', 'APPROVAL_DATE': '2013.08.29', 'COMPLE_DATE': '2015.10.28'}, {'IDX': 206.0, 'FAC_NM': 'BY센터', 'ADDRESS': '성수동2가 301-51,301-38', 'TELEPHONE': '(02) 467-2247', 'APPROVAL_DATE': '2013.08.12', 'COMPLE_DATE': '2015.12.04'}, {'IDX': 205.0, 'FAC_NM': '신한IT타워', 'ADDRESS': '성수동1가 656-603', 'TELEPHONE': '', 'APPROVAL_DATE': '2013.07.02', 'COMPLE_DATE': '2015.06.04'}, {'IDX': 116.0, 'FAC_NM': '에스비즈니스센터', 'ADDRESS': '가산동 343-8', 'TELEPHONE': '2163-6749', 'APPROVAL_DATE': '2013.03.26', 'COMPLE_DATE': '2015.06.01'}, {'IDX': 165.0, 'FAC_NM': '선유도역2차 아이에스비즈타워', 'ADDRESS': '선유로49길 23(양평동4가)', 'TELEPHONE': '6123-4100', 'APPROVAL_DATE': '2012.12.18', 'COMPLE_DATE': '2014.11.19'}, {'IDX': 115.0, 'FAC_NM': '대륭테크노타운17차', 'ADDRESS': '가산동 670', 'TELEPHONE': '3466-0051', 'APPROVAL_DATE': '2012.12.10', 'COMPLE_DATE': '2015.05.15'}, {'IDX': 204.0, 'FAC_NM': '서울숲\n드림타워(삼공)', 'ADDRESS': '성수동2가 323, 309-51', 'TELEPHONE': '(02)6222-8114', 'APPROVAL_DATE': '2012.10.31', 'COMPLE_DATE': '2015.03.23'}, {'IDX': 164.0, 'FAC_NM': '에이스하이테크시티 2', 'ADDRESS': '선유로13길 25(문래동6가)', 'TELEPHONE': '2257-8114', 'APPROVAL_DATE': '2012.08.27', 'COMPLE_DATE': '2014.10.24'}, {'IDX': 2.0, 'FAC_NM': 'NICE그룹 지식산업센터', 'ADDRESS': '상일로6길 55 (상일동)', 'TELEPHONE': '2122-4415', 'APPROVAL_DATE': '2012.06.29', 'COMPLE_DATE': '2014.02.28'}, {'IDX': 166.0, 'FAC_NM': 'SK V1 center', 'ADDRESS': '당산로41길 11(당산동4가)', 'TELEPHONE': '6121-8100', 'APPROVAL_DATE': '2012.06.19', 'COMPLE_DATE': '2015.02.17'}, {'IDX': 203.0, 'FAC_NM': '서울숲IT캐슬', 'ADDRESS': '성수동1가 671-6, -41 외 4필지', 'TELEPHONE': '(02) 2086-3346', 'APPROVAL_DATE': '2012.05.10', 'COMPLE_DATE': '2014.06.17'}, {'IDX': 1.0, 'FAC_NM': '세종투자㈜', 'ADDRESS': '강동구 상일로10길 36 (상일동)', 'TELEPHONE': '3415-4971', 'APPROVAL_DATE': '2011.11.30', 'COMPLE_DATE': '2013.09.13'}, {'IDX': 202.0, 'FAC_NM': '에이스하이앤드\n 성수타워', 'ADDRESS': '성수동2가 269-25,269-51,\n269-115,328-5', 'TELEPHONE': '(02) 2112-6491', 'APPROVAL_DATE': '2011.11.15', 'COMPLE_DATE': '2015.06.19'}, {'IDX': 201.0, 'FAC_NM': '에이스성수타워1차', 'ADDRESS': '성수2가 280-15,19', 'TELEPHONE': '(02) 591-0607', 'APPROVAL_DATE': '2011.10.20', 'COMPLE_DATE': '2014.03.11'}, {'IDX': 52.0, 'FAC_NM': 'G플러스 코오롱 디지털타워', 'ADDRESS': '구로동 222-31', 'TELEPHONE': '858-3650', 'APPROVAL_DATE': '2011.06.09', 'COMPLE_DATE': '2013.7.24'}, {'IDX': 163.0, 'FAC_NM': '선유도역1차 아이에스비즈타워', 'ADDRESS': '양평로21길 26(양평동5가)', 'TELEPHONE': '6968-1004', 'APPROVAL_DATE': '2011.04.21', 'COMPLE_DATE': '2013.5.27'}, {'IDX': 200.0, 'FAC_NM': '서울숲\n한라시그마밸리II', 'ADDRESS': '성수동2가 333-15', 'TELEPHONE': '(02) 4199-5621', 'APPROVAL_DATE': '2011.02.25', 'COMPLE_DATE': '2013.03.28'}, {'IDX': 51.0, 'FAC_NM': '대륭포스트타워7차', 'ADDRESS': '구로동 170-10 외 2필지', 'TELEPHONE': '6942-9500', 'APPROVAL_DATE': '2011.02.21', 'COMPLE_DATE': '2012.12.11'}, {'IDX': 10.0, 'FAC_NM': '강서IT밸리', 'ADDRESS': '화곡로68길 82', 'TELEPHONE': '6961-5111', 'APPROVAL_DATE': '2010.3.9', 'COMPLE_DATE': '2012.2.6'}, {'IDX': 11.0, 'FAC_NM': '강서한강자이', 'ADDRESS': '양천로 401', 'TELEPHONE': '6968-5801~2', 'APPROVAL_DATE': '2010.10.15', 'COMPLE_DATE': '2013.6.7'}, {'IDX': 199.0, 'FAC_NM': '서울숲 \n한라에코벨리', 'ADDRESS': '성수동1가 656-36\n656-1222', 'TELEPHONE': '(02) 549-6693', 'APPROVAL_DATE': '2010.09.09', 'COMPLE_DATE': '2012.09.06'}, {'IDX': 198.0, 'FAC_NM': '성수동\n아이에스비즈타워', 'ADDRESS': '성수동2가289-319,327,328', 'TELEPHONE': '(02) 3218-6643', 'APPROVAL_DATE': '2010.08.28', 'COMPLE_DATE': '2012.07.23'}, {'IDX': 162.0, 'FAC_NM': 'KnK디지털타워', 'ADDRESS': '영신로 220(영등포동8가)', 'TELEPHONE': '2675-6060', 'APPROVAL_DATE': '2010.08.27', 'COMPLE_DATE': '2012.12.07'}, {'IDX': 167.0, 'FAC_NM': '문래동 하우스디 비즈', 'ADDRESS': '선유로3길 10(문래동5가)', 'TELEPHONE': '2112-6339', 'APPROVAL_DATE': '2010.08.10', 'COMPLE_DATE': '2016.05.09'}, {'IDX': 160.0, 'FAC_NM': '선유도코오롱디지털타워', 'ADDRESS': '양평로22길21(양평동5가)', 'TELEPHONE': '2062-5996', 'APPROVAL_DATE': '2010.07.13', 'COMPLE_DATE': '2012.03.23'}, {'IDX': 197.0, 'FAC_NM': '성수에이팩센터', 'ADDRESS': '성수동2가 289-5\n289-334,289-335', 'TELEPHONE': '(02) 3416-1541', 'APPROVAL_DATE': '2010.06.24', 'COMPLE_DATE': '2012.08.24'}, {'IDX': 196.0, 'FAC_NM': '아연디지털타워', 'ADDRESS': '성수동2가314-37', 'TELEPHONE': '(02) 499-2275', 'APPROVAL_DATE': '2010.06.01', 'COMPLE_DATE': '2012.08.31'}, {'IDX': 195.0, 'FAC_NM': '서울숲 SK V1 타워', 'ADDRESS': '성수동2가284-55, 284-107', 'TELEPHONE': '(02) 6233-8000', 'APPROVAL_DATE': '2010.04.13', 'COMPLE_DATE': '2014.07.18'}, {'IDX': 114.0, 'FAC_NM': '에이스하이엔드9차', 'ADDRESS': '가산동 481-2', 'TELEPHONE': '6309-6051', 'APPROVAL_DATE': '2010.04', 'COMPLE_DATE': '2012.07.20'}, {'IDX': 194.0, 'FAC_NM': '서울숲\nIT 밸리', 'ADDRESS': '성수동1가 13-170\n외9필지(13-170,13-166,13-472,13-169,13-256,13-164,13-253,13-171,13-255,13-167)', 'TELEPHONE': '(02) 2090-8202', 'APPROVAL_DATE': '2010.03.24.', 'COMPLE_DATE': '2013.02.08'}, {'IDX': 50.0, 'FAC_NM': 'JnK 디지털타워', 'ADDRESS': '구로3동 222-3', 'TELEPHONE': '6124-6611', 'APPROVAL_DATE': '2010.01.20', 'COMPLE_DATE': '2012.2.15'}, {'IDX': 121.0, 'FAC_NM': '대성D-POLIS', 'ADDRESS': '가산동 543-1', 'TELEPHONE': '861-9114', 'APPROVAL_DATE': '2009.12', 'COMPLE_DATE': '2012.09'}, {'IDX': 159.0, 'FAC_NM': '동아프라임밸리', 'ADDRESS': '영등포로5길19(양평동2가)', 'TELEPHONE': '6210-7201', 'APPROVAL_DATE': '2009.10.21', 'COMPLE_DATE': '2011.11.25'}, {'IDX': 161.0, 'FAC_NM': '솔버스 비즈타워', 'ADDRESS': '선유서로31길3(양평동3가)', 'TELEPHONE': '6963-8080', 'APPROVAL_DATE': '2009.10.19', 'COMPLE_DATE': '2012.09.05'}, {'IDX': 212.0, 'FAC_NM': '동대문패션비즈센터 ', 'ADDRESS': '신당동 251-160', 'TELEPHONE': '070-8895-7347', 'APPROVAL_DATE': '2009.05.14', 'COMPLE_DATE': '2012.03.07'}, {'IDX': 129.0, 'FAC_NM': '현대지식산업센터', 'ADDRESS': '독산동 291-1 ', 'TELEPHONE': '858-3080', 'APPROVAL_DATE': '2009.04', 'COMPLE_DATE': '2014.03.04'}, {'IDX': 193.0, 'FAC_NM': '이레타워', 'ADDRESS': '성수동2가 277-175번지', 'TELEPHONE': '(02) 466-2663', 'APPROVAL_DATE': '2009.01.22', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 9.0, 'FAC_NM': '강서한화비즈메트로2차', 'ADDRESS': '양천로551-24', 'TELEPHONE': '6957-1990', 'APPROVAL_DATE': '2008.7.25', 'COMPLE_DATE': '2012.1.16'}, {'IDX': 8.0, 'FAC_NM': '강서한화비즈메트로1차', 'ADDRESS': '양천로551-17', 'TELEPHONE': '6957-1990', 'APPROVAL_DATE': '2008.7.25', 'COMPLE_DATE': '2012.1.13'}, {'IDX': 113.0, 'FAC_NM': '알에스엠타워', 'ADDRESS': '가산동 327-29', 'TELEPHONE': '2112-6300', 'APPROVAL_DATE': '2008.12.03', 'COMPLE_DATE': '2012.12.18'}, {'IDX': 137.0, 'FAC_NM': '가든파이브웍스', 'ADDRESS': '충민로52(문정동)', 'TELEPHONE': '02-2047-1014', 'APPROVAL_DATE': '2008.11.12', 'COMPLE_DATE': '2008.10.16'}, {'IDX': 47.0, 'FAC_NM': 'STX-W 타워', 'ADDRESS': '구로동 615-3외 4필지', 'TELEPHONE': '6124-3333', 'APPROVAL_DATE': '2008.10.23', 'COMPLE_DATE': '2011.10.30'}, {'IDX': 192.0, 'FAC_NM': '서울숲 코오롱\n디지털타워2차', 'ADDRESS': '성수동2가 333-140번지', 'TELEPHONE': '(031) 727-1461', 'APPROVAL_DATE': '2008.10.21', 'COMPLE_DATE': '2010.09.10'}, {'IDX': 110.0, 'FAC_NM': '에이스하이엔드7차', 'ADDRESS': '가산동 345-33', 'TELEPHONE': '6111-1500', 'APPROVAL_DATE': '2008.10.10', 'COMPLE_DATE': '2010.07'}, {'IDX': 191.0, 'FAC_NM': '서울숲 코오롱\n디지털타워3차', 'ADDRESS': '성수동1가 14-18번지 외 1 필지', 'TELEPHONE': '(02) 499-0430', 'APPROVAL_DATE': '2008.10.02', 'COMPLE_DATE': '2010.11.24'}, {'IDX': 69.0, 'FAC_NM': '엘리시아', 'ADDRESS': '가산동 60-69', 'TELEPHONE': '890-8888', 'APPROVAL_DATE': '2008.09.23', 'COMPLE_DATE': '2011.03'}, {'IDX': 190.0, 'FAC_NM': '휴먼테코', 'ADDRESS': '성수동2가 281-16 번지 외 1 필지', 'TELEPHONE': '02)6466-5000', 'APPROVAL_DATE': '2008.09.12', 'COMPLE_DATE': '2010.06.07'}, {'IDX': 112.0, 'FAC_NM': 'KCC웰츠밸리', 'ADDRESS': '가산동 470-8', 'TELEPHONE': '6111-8100', 'APPROVAL_DATE': '2008.09.09', 'COMPLE_DATE': '2010.12'}, {'IDX': 68.0, 'FAC_NM': '대륭포스트타워6차', 'ADDRESS': '가산동 50-3', 'TELEPHONE': '2083-5114', 'APPROVAL_DATE': '2008.09.05', 'COMPLE_DATE': '2010.08'}, {'IDX': 189.0, 'FAC_NM': '서울숲 \n한라시그마밸리', 'ADDRESS': '성수동2가 325-2 번지 외 12 필지', 'TELEPHONE': '(02) 6466-8114', 'APPROVAL_DATE': '2008.09.03', 'COMPLE_DATE': '2011.02.16'}, {'IDX': 111.0, 'FAC_NM': '더루벤스밸리', 'ADDRESS': '가산동 691-3', 'TELEPHONE': '2109-9800', 'APPROVAL_DATE': '2008.08.14', 'COMPLE_DATE': '2011.09'}, {'IDX': 49.0, 'FAC_NM': '파트너스타워2차', 'ADDRESS': '구로동 1128-3', 'TELEPHONE': '2028-3993', 'APPROVAL_DATE': '2008.07.28', 'COMPLE_DATE': '2010.02.16'}, {'IDX': 108.0, 'FAC_NM': 'STX V-TOWER', 'ADDRESS': '가산동 371-37', 'TELEPHONE': '8111-3102', 'APPROVAL_DATE': '2008.07', 'COMPLE_DATE': '2010.11'}, {'IDX': 188.0, 'FAC_NM': '한신 아크밸리', 'ADDRESS': '성수동2가 277-43번지', 'TELEPHONE': '(02) 421-2367', 'APPROVAL_DATE': '2008.05.26', 'COMPLE_DATE': '2010.05.27'}, {'IDX': 158.0, 'FAC_NM': '양평동이노플렉스', 'ADDRESS': '양산로57-5(양평동3가)', 'TELEPHONE': '2675-0134', 'APPROVAL_DATE': '2008.05.14', 'COMPLE_DATE': '2010.01.20'}, {'IDX': 67.0, 'FAC_NM': '갑을아파트형공장', 'ADDRESS': '가산동60-5', 'TELEPHONE': '3397-7705', 'APPROVAL_DATE': '2008.05.09', 'COMPLE_DATE': '2010.07'}, {'IDX': 107.0, 'FAC_NM': 'IT프리미어타워', 'ADDRESS': '가산동 345-50', 'TELEPHONE': '2621-1991', 'APPROVAL_DATE': '2008.04.24', 'COMPLE_DATE': '2010.02'}, {'IDX': 106.0, 'FAC_NM': '에이스하이엔드8차', 'ADDRESS': '가산동 345-4', 'TELEPHONE': '6123-5000', 'APPROVAL_DATE': '2008.03.20', 'COMPLE_DATE': '2010.09'}, {'IDX': 105.0, 'FAC_NM': 'BYC하이씨티', 'ADDRESS': '가산동 371-17', 'TELEPHONE': '6947-3100', 'APPROVAL_DATE': '2008.03.12', 'COMPLE_DATE': '2012.02'}, {'IDX': 104.0, 'FAC_NM': 'INNOPLEX 2차', 'ADDRESS': '가산동 371-59', 'TELEPHONE': '6111-0123', 'APPROVAL_DATE': '2008.02.20', 'COMPLE_DATE': '2010.03'}, {'IDX': 66.0, 'FAC_NM': '대륭포스트타워5차', 'ADDRESS': '가산동 60-3', 'TELEPHONE': '2624-4116', 'APPROVAL_DATE': '2008.02.19', 'COMPLE_DATE': '2010.01'}, {'IDX': 103.0, 'FAC_NM': '파트너스타워', 'ADDRESS': '가산동 345-13', 'TELEPHONE': '859-5641', 'APPROVAL_DATE': '2008.02.12', 'COMPLE_DATE': '2009.10'}, {'IDX': 102.0, 'FAC_NM': '한라시그마밸리', 'ADDRESS': '가산동 345-90 ', 'TELEPHONE': '6343-6800', 'APPROVAL_DATE': '2008.01.17', 'COMPLE_DATE': '2009.12'}, {'IDX': 101.0, 'FAC_NM': '백상스타타워2차', 'ADDRESS': '가산동 459-22', 'TELEPHONE': '6111-6100', 'APPROVAL_DATE': '2007.12.06', 'COMPLE_DATE': '2010.07'}, {'IDX': 65.0, 'FAC_NM': '백상스타타워1차', 'ADDRESS': '가산동 60-17', 'TELEPHONE': '6111-7116', 'APPROVAL_DATE': '2007.11.29', 'COMPLE_DATE': '2010.07'}, {'IDX': 46.0, 'FAC_NM': '한화비즈 메트로1차', 'ADDRESS': '구로동 851외 2필지', 'TELEPHONE': '2621-2490', 'APPROVAL_DATE': '2007.11.20', 'COMPLE_DATE': '2010.12.28'}, {'IDX': 211.0, 'FAC_NM': '아시아미디어타워', 'ADDRESS': '초동 42', 'TELEPHONE': '2275-3332', 'APPROVAL_DATE': '2007.11.13', 'COMPLE_DATE': '2009.12.01'}, {'IDX': 99.0, 'FAC_NM': '디지털엠파이어', 'ADDRESS': '가산동 685', 'TELEPHONE': '2624-2121', 'APPROVAL_DATE': '2007.10.17', 'COMPLE_DATE': '2009.02'}, {'IDX': 98.0, 'FAC_NM': 'LG아파트형공장', 'ADDRESS': '가산동 459-9', 'TELEPHONE': '6945-4455', 'APPROVAL_DATE': '2007.10.12', 'COMPLE_DATE': '2009.04'}, {'IDX': 154.0, 'FAC_NM': '선유도우림라이온스밸리A', 'ADDRESS': '양평로 149(양평동5가)', 'TELEPHONE': '2638-7114', 'APPROVAL_DATE': '2007.09.17', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 155.0, 'FAC_NM': '선유도우림라이온스밸리B', 'ADDRESS': '양평로21가길19(양평동5가)', 'TELEPHONE': '2638-7114', 'APPROVAL_DATE': '2007.09.17', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 64.0, 'FAC_NM': '에이스하이엔드6차', 'ADDRESS': '가산동 60-25', 'TELEPHONE': '6299-5100', 'APPROVAL_DATE': '2007.08.24', 'COMPLE_DATE': '2009.08'}, {'IDX': 157.0, 'FAC_NM': '벽산디지털밸리', 'ADDRESS': '경인로71길 70(문래동5가)', 'TELEPHONE': '6098-5114', 'APPROVAL_DATE': '2007.08.24', 'COMPLE_DATE': '2009.12.17'}, {'IDX': 97.0, 'FAC_NM': '에이스하이엔드5차', 'ADDRESS': '가산동 505-18', 'TELEPHONE': '6340-0200', 'APPROVAL_DATE': '2007.08.23', 'COMPLE_DATE': '2009.07'}, {'IDX': 96.0, 'FAC_NM': '이앤씨드림타워8차', 'ADDRESS': '가산동 327-27', 'TELEPHONE': '6277-8200', 'APPROVAL_DATE': '2007.08.16', 'COMPLE_DATE': '2009.02'}, {'IDX': 109.0, 'FAC_NM': '가산비즈니스센터', 'ADDRESS': '가산동 371-6 ', 'TELEPHONE': '3289-9114', 'APPROVAL_DATE': '2007.08.16', 'COMPLE_DATE': '2011.09'}, {'IDX': 100.0, 'FAC_NM': '한국전자협동APT공장', 'ADDRESS': '가산동 371-51', 'TELEPHONE': '858-9261', 'APPROVAL_DATE': '2007.08.13', 'COMPLE_DATE': '2007.12.06'}, {'IDX': 156.0, 'FAC_NM': '금강펜테리움IT타워', 'ADDRESS': '당산로 171(당산동4가)', 'TELEPHONE': '2638-8585', 'APPROVAL_DATE': '2007.07.24', 'COMPLE_DATE': '2010.01.08'}, {'IDX': 44.0, 'FAC_NM': '벽산디지털밸리7차', 'ADDRESS': '구로동 170-13', 'TELEPHONE': '839-3152', 'APPROVAL_DATE': '2007.07.23', 'COMPLE_DATE': '2009.06.23'}, {'IDX': 95.0, 'FAC_NM': '에이스하이엔드3차', 'ADDRESS': '가산동 371-51', 'TELEPHONE': '2624-1100', 'APPROVAL_DATE': '2007.06.13', 'COMPLE_DATE': '2009.07'}, {'IDX': 86.0, 'FAC_NM': 'INNOPLEX 1차', 'ADDRESS': '가산동 371-47', 'TELEPHONE': '6679-0007', 'APPROVAL_DATE': '2007.04.13', 'COMPLE_DATE': '2008.08.14'}, {'IDX': 94.0, 'FAC_NM': '벽산디지털밸리6차', 'ADDRESS': '가산동 481-4', 'TELEPHONE': '869-1166', 'APPROVAL_DATE': '2007.04.04', 'COMPLE_DATE': '2009.03'}, {'IDX': 187.0, 'FAC_NM': '서울숲 코오롱 1차', 'ADDRESS': '성수동2가 308-4번지', 'TELEPHONE': '시행사:2115-8899', 'APPROVAL_DATE': '2007.02.11', 'COMPLE_DATE': '2010.06.10'}, {'IDX': 7.0, 'FAC_NM': '우림블루나인비즈니스센터', 'ADDRESS': '양천로 583', 'TELEPHONE': '2093-1011', 'APPROVAL_DATE': '2006.4.26', 'COMPLE_DATE': '2008.9.26'}, {'IDX': 93.0, 'FAC_NM': '롯데IT캐슬2차', 'ADDRESS': '가산동 371-16', 'TELEPHONE': '2627-8114', 'APPROVAL_DATE': '2006.11.21', 'COMPLE_DATE': '2008.09'}, {'IDX': 63.0, 'FAC_NM': '이앤씨드림타워7차', 'ADDRESS': '가산동 60-44', 'TELEPHONE': '6277-8200', 'APPROVAL_DATE': '2006.11.06', 'COMPLE_DATE': '2008.01'}, {'IDX': 43.0, 'FAC_NM': '에이스하이엔드타워2차', 'ADDRESS': '구로동 222-14', 'TELEPHONE': '6340-5555', 'APPROVAL_DATE': '2006.08.17', 'COMPLE_DATE': '2008.04.15'}, {'IDX': 186.0, 'FAC_NM': '아주디지털타워', 'ADDRESS': '성수동2가 284-56번지', 'TELEPHONE': '(02) 462-2235', 'APPROVAL_DATE': '2006.07.27', 'COMPLE_DATE': '2010.01.08'}, {'IDX': 213.0, 'FAC_NM': '산타플러스', 'ADDRESS': '난곡로 60', 'TELEPHONE': '02-865-6976', 'APPROVAL_DATE': '2005.11.28', 'COMPLE_DATE': '2006.7.26'}, {'IDX': 92.0, 'FAC_NM': '㈜동광인터내셔날', 'ADDRESS': '가산동 459-14', 'TELEPHONE': '3479-2700', 'APPROVAL_DATE': '2005.11.23', 'COMPLE_DATE': '2006.01'}, {'IDX': 152.0, 'FAC_NM': '월드메르디앙비즈센터', 'ADDRESS': '양산로 53(양평동3가)', 'TELEPHONE': '2165-8980', 'APPROVAL_DATE': '2005.10.05', 'COMPLE_DATE': '2007.02.14'}, {'IDX': 61.0, 'FAC_NM': '(주)한섬임대아파트형공장', 'ADDRESS': '가산동 60-42', 'TELEPHONE': '838-0146', 'APPROVAL_DATE': '2005.09.28', 'COMPLE_DATE': '2006.09'}, {'IDX': 41.0, 'FAC_NM': '㈜대양디앤티', 'ADDRESS': '구로동 197-47', 'TELEPHONE': '858-2111', 'APPROVAL_DATE': '2005.09.09', 'COMPLE_DATE': '2007.08.07'}, {'IDX': 91.0, 'FAC_NM': '승일벤쳐타워', 'ADDRESS': '가산동 371-42', 'TELEPHONE': '862-2351', 'APPROVAL_DATE': '2005.06.18', 'COMPLE_DATE': '2006.12'}, {'IDX': 42.0, 'FAC_NM': '대륭포스트타워3차', 'ADDRESS': '구로동 182-4', 'TELEPHONE': '2028-0114', 'APPROVAL_DATE': '2005.06.10', 'COMPLE_DATE': '2007.06.07'}, {'IDX': 153.0, 'FAC_NM': '에이스하이테크시티', 'ADDRESS': '경인로 775(문래동3가)', 'TELEPHONE': '6309-6112', 'APPROVAL_DATE': '2005.05.15', 'COMPLE_DATE': '2007.04.13'}, {'IDX': 90.0, 'FAC_NM': '롯데정보통신', 'ADDRESS': '가산동 533-2', 'TELEPHONE': '2626-4000', 'APPROVAL_DATE': '2005.05.11', 'COMPLE_DATE': '2007.03'}, {'IDX': 134.0, 'FAC_NM': 'DMC 첨단산업센터', 'ADDRESS': '마포구 상암동 1580 \n첨단산업센터', 'TELEPHONE': '2171-2847', 'APPROVAL_DATE': '2004.11.03', 'COMPLE_DATE': '2008.03.31'}, {'IDX': 62.0, 'FAC_NM': 'IT미래타워', 'ADDRESS': '가산동 60-21', 'TELEPHONE': '2027-5757', 'APPROVAL_DATE': '2004.10.27', 'COMPLE_DATE': '2007.04.30'}, {'IDX': 89.0, 'FAC_NM': '뉴티캐슬', 'ADDRESS': '가산동 429-1', 'TELEPHONE': '2626-9960', 'APPROVAL_DATE': '2004.08.11', 'COMPLE_DATE': '2006.12'}, {'IDX': 88.0, 'FAC_NM': '대륭테크노타운13차', 'ADDRESS': '가산동 664', 'TELEPHONE': '2029-5600', 'APPROVAL_DATE': '2004.07.28', 'COMPLE_DATE': '2008.05'}, {'IDX': 185.0, 'FAC_NM': '성수동\n 우림e-BIZ Center', 'ADDRESS': '성수동2가 280-21번지', 'TELEPHONE': '(02)2024-2110', 'APPROVAL_DATE': '2004.07.26', 'COMPLE_DATE': '2006.10.18'}, {'IDX': 132.0, 'FAC_NM': '중계제1공단', 'ADDRESS': '노원구 노원로19길 31(중계동)\n[중계동 511-2]', 'TELEPHONE': '948-2846', 'APPROVAL_DATE': '2004.07.13', 'COMPLE_DATE': '1991.12.07'}, {'IDX': 130.0, 'FAC_NM': '월계테크노타운', 'ADDRESS': '노원구 월계로45길 28(월계동)\n[월계동 562번지]', 'TELEPHONE': '990-2727', 'APPROVAL_DATE': '2004.07.08', 'COMPLE_DATE': '1994.12.19'}, {'IDX': 87.0, 'FAC_NM': '대륭테크노타운12차', 'ADDRESS': '가산동 327-32', 'TELEPHONE': '2029-6114', 'APPROVAL_DATE': '2004.07.08', 'COMPLE_DATE': '2008.05'}, {'IDX': 131.0, 'FAC_NM': '하계테크노타운', 'ADDRESS': '노원구 노원로15길 10(하계동)\n[하계동 250-3]', 'TELEPHONE': '6235-3500', 'APPROVAL_DATE': '2004.07.07', 'COMPLE_DATE': '1998.11.17'}, {'IDX': 184.0, 'FAC_NM': '풍림테크원', 'ADDRESS': '성수동2가 273-10번지', 'TELEPHONE': '(02) 468-9319/464-0133', 'APPROVAL_DATE': '2004.05.31', 'COMPLE_DATE': '2005.09.15'}, {'IDX': 31.0, 'FAC_NM': '이앤씨드림타워6차', 'ADDRESS': '구로동 197-28', 'TELEPHONE': '801-8603', 'APPROVAL_DATE': '2004.05.10', 'COMPLE_DATE': '2005.12.21'}, {'IDX': 39.0, 'FAC_NM': '대륭포스트타워2차', 'ADDRESS': '구로동 182-13', 'TELEPHONE': '2082-0114', 'APPROVAL_DATE': '2004.03.24', 'COMPLE_DATE': '2005.10.06'}, {'IDX': 60.0, 'FAC_NM': '스타밸리', 'ADDRESS': '가산동 60-11', 'TELEPHONE': '2027-0114', 'APPROVAL_DATE': '2004.02.27', 'COMPLE_DATE': '2006.04'}, {'IDX': 37.0, 'FAC_NM': '코오롱빌란트2차', 'ADDRESS': '구로동 222-8', 'TELEPHONE': '2081-1111', 'APPROVAL_DATE': '2004.02.25', 'COMPLE_DATE': '2006.12.28'}, {'IDX': 38.0, 'FAC_NM': '대륭포스트타워1차', 'ADDRESS': '구로동 212-8', 'TELEPHONE': '2082-2331', 'APPROVAL_DATE': '2004.01.10', 'COMPLE_DATE': '2005.10.18'}, {'IDX': 36.0, 'FAC_NM': '코오롱싸이언스밸리2차', 'ADDRESS': '구로동 811', 'TELEPHONE': '850-3150', 'APPROVAL_DATE': '2003.12.30', 'COMPLE_DATE': '2005.12.13'}, {'IDX': 34.0, 'FAC_NM': '에이스하이엔드1차', 'ADDRESS': '구로동 235-2', 'TELEPHONE': '6220-2010', 'APPROVAL_DATE': '2003.12.30', 'COMPLE_DATE': '2005.09.30'}, {'IDX': 150.0, 'FAC_NM': '메가벤처타워', 'ADDRESS': '문래로20길60(문래동3가)', 'TELEPHONE': '2632-4438', 'APPROVAL_DATE': '2003.12.22', 'COMPLE_DATE': '2005.12.27'}, {'IDX': 79.0, 'FAC_NM': '롯데IT캐슬', 'ADDRESS': '가산동 550-1', 'TELEPHONE': '2026-8970', 'APPROVAL_DATE': '2003.12.20', 'COMPLE_DATE': '2005.09'}, {'IDX': 30.0, 'FAC_NM': '이앤씨드림타워5차', 'ADDRESS': '구로동 197-13', 'TELEPHONE': '6336-3591', 'APPROVAL_DATE': '2003.12.19', 'COMPLE_DATE': '2004.12.14'}, {'IDX': 59.0, 'FAC_NM': '벽산디지털밸리5차', 'ADDRESS': '가산동 60-73', 'TELEPHONE': '2082-5990', 'APPROVAL_DATE': '2003.11.05', 'COMPLE_DATE': '2005.10'}, {'IDX': 33.0, 'FAC_NM': '마리오디지털밸리', 'ADDRESS': '구로동 222-12', 'TELEPHONE': '890-8498', 'APPROVAL_DATE': '2003.10.13', 'COMPLE_DATE': '2005.10.25'}, {'IDX': 85.0, 'FAC_NM': '코오롱디지털타워애스톤', 'ADDRESS': '가산동 505-14', 'TELEPHONE': '2082-8114', 'APPROVAL_DATE': '2003.09.26', 'COMPLE_DATE': '2005.09'}, {'IDX': 84.0, 'FAC_NM': '에이스테크노타워10차', 'ADDRESS': '가산동 470-5', 'TELEPHONE': '6670-5300', 'APPROVAL_DATE': '2003.09.16', 'COMPLE_DATE': '2005.07'}, {'IDX': 35.0, 'FAC_NM': '코오롱싸이언스밸리1차', 'ADDRESS': '구로동 187-10', 'TELEPHONE': '2025-4580', 'APPROVAL_DATE': '2003.08.08', 'COMPLE_DATE': '2005.07.05'}, {'IDX': 40.0, 'FAC_NM': '삼성IT밸리', 'ADDRESS': '구로동 197-5', 'TELEPHONE': '2028-2363', 'APPROVAL_DATE': '2003.07.20', 

,IDX,FAC_NM,ADDRESS,TELEPHONE,APPROVAL_DATE,COMPLE_DATE
0,208.0,신내테크노타운,봉화산로 123(상봉동),02)3423-0057,96.5.28,99.10.18
1,136.0,월곡동아파트형공장,하월곡동 96-113,02-090-8083,33289,1990.12.31
2,135.0,월곡동아파트형공장,하월곡동 96-113,02-912-1034,33289,1990.12.31
3,140.0,문정아르페온 1차 지식산업센터,서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL),031-706-8577,2016.06.27,2016.06.27
4,139.0,문정 대명벨리온,서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL),02-2222-7357,2016.03.23,2016.03.23
...,...,...,...,...,...,...
208,169.0,서울제일인쇄협동조합,성수2가제3동 277-7번지,(02) 498-8727,1992.02.06,1993.05.08
209,168.0,삼풍,성수2가제3동 284-50번지,(02) 466-4515,1991.01.31,1992.08.03
210,122.0,대동아파트형공장,독산동 999-3,804-3362,1990.12,1992.02
211,3.0,비젼타워관리조합,양천로57길26,2659-0360,1990.10.31,1992.11.30
212,142.0,문정 현대지식산업센터Ｉ-2,서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL),02-3451-0100,2016.02.29,2016.02.29

## 데이터 전처리

In [134]:
# 필요한 데이터만 추출하고, 열이름 모두 소문자로 통일 및 변경
# 1) 소문자로 변경
center_df = center_df[['IDX', 'FAC_NM', "ADDRESS"]]
center_df.columns = center_df.columns.str.lower()

center_df

# 2) 열이름 변경
center_df = center_df.rename(columns={
    'fac_nm': 'nm',
    'address': 'addr',
})

In [135]:
# 열 타입 변경
center_df['idx'] = center_df['idx'].astype("int")
center_df

     idx                nm                                   addr
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    135         월곡동아파트형공장                            하월곡동 96-113
3    140  문정아르페온 1차 지식산업센터    서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)
4    139          문정 대명벨리온  서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)
..   ...               ...                                    ...
208  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
209  168                삼풍                       성수2가제3동 284-50번지
210  122          대동아파트형공장                              독산동 999-3
211    3          비젼타워관리조합                               양천로57길26
212  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[213 rows x 3 columns]

In [136]:
# 공장 이름과 주소가 모두 같은 행이 있는지 확인
print(center_df.duplicated(subset=['nm', 'addr']).sum()) # 1

dup_all_mask = center_df.duplicated(subset=['nm', 'addr'], keep=False)
center_df[dup_all_mask].sort_values(['nm', 'addr'])

1

   idx         nm         addr
1  136  월곡동아파트형공장  하월곡동 96-113
2  135  월곡동아파트형공장  하월곡동 96-113

In [137]:
# 공장 이름과 주소 중복 행 제거
center_df = center_df.drop_duplicates(subset=['nm', 'addr'], keep='first').reset_index(drop=True)
center_df

     idx                nm                                   addr
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    140  문정아르페온 1차 지식산업센터    서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)
3    139          문정 대명벨리온  서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)
..   ...               ...                                    ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
208  168                삼풍                       성수2가제3동 284-50번지
209  122          대동아파트형공장                              독산동 999-3
210    3          비젼타워관리조합                               양천로57길26
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[212 rows x 3 columns]

In [138]:
# 주소 이상치 제거
center_df["addr"] = (
    center_df["addr"]
    .str.replace(r"(,|\n|외).*$", "", regex=True)  # 첫 , 또는 \n 또는 외 이후 전부 삭제
    .str.strip()
)

center_df

     idx                nm                                   addr
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    140  문정아르페온 1차 지식산업센터                      서울특별시 송파구 문정동 640
3    139          문정 대명벨리온                    서울특별시 송파구 문정동 641-4
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)
..   ...               ...                                    ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
208  168                삼풍                       성수2가제3동 284-50번지
209  122          대동아파트형공장                              독산동 999-3
210    3          비젼타워관리조합                               양천로57길26
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[212 rows x 3 columns]

In [139]:
print(center_df['addr'].str.contains(',').sum()) # 외 = 0, \n = 0, , = 1
print(center_df[center_df['addr'].str.contains(',', na=False)]) # idx = 202

cond = center_df['idx'] == 202
center_df.loc[cond, 'addr'] = '성수동2가 269-25' # 첫 주소로 대체

center_df.loc[cond, :]

1
    idx              nm                  addr
19  202  에이스하이앤드\n 성수타워  성수동2가 269-25,269-51,

    idx              nm          addr
19  202  에이스하이앤드\n 성수타워  성수동2가 269-25

In [140]:
# type 변수 추가
center_df['type'] = '지식산업센터'
center_df

     idx                nm                                   addr    type
0    208           신내테크노타운                          봉화산로 123(상봉동)  지식산업센터
1    136         월곡동아파트형공장                            하월곡동 96-113  지식산업센터
2    140  문정아르페온 1차 지식산업센터                      서울특별시 송파구 문정동 640  지식산업센터
3    139          문정 대명벨리온                    서울특별시 송파구 문정동 641-4  지식산업센터
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)  지식산업센터
..   ...               ...                                    ...     ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지  지식산업센터
208  168                삼풍                       성수2가제3동 284-50번지  지식산업센터
209  122          대동아파트형공장                              독산동 999-3  지식산업센터
210    3          비젼타워관리조합                               양천로57길26  지식산업센터
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)  지식산업센터

[212 rows x 4 columns]

### 주소 → 위도, 경도

In [21]:
kakao_key  = os.getenv("KAKAO_REST_APIKEY")     # 인증키

In [52]:
# test
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)
params = {"query": "성수동2가 269-25"}  # 입력할 주소
resp = requests.get(url,headers=headers, params=params).json() #카카오 API 요청
                      
print(resp) #API 결과 출력
resp['documents'][0]['road_address']

{'documents': [{'address': {'address_name': '서울 성동구 성수동2가 269-25', 'b_code': '1120011500', 'h_code': '1120067000', 'main_address_no': '269', 'mountain_yn': 'N', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_h_name': '성수2가1동', 'region_3depth_name': '성수동2가', 'sub_address_no': '25', 'x': '127.056741837461', 'y': '37.5402196364231'}, 'address_name': '서울 성동구 성수동2가 269-25', 'address_type': 'REGION_ADDR', 'road_address': {'address_name': '서울 성동구 성수이로10길 14', 'building_name': '에이스 하이엔드 성수타워', 'main_building_no': '14', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_name': '성수동2가', 'road_name': '성수이로10길', 'sub_building_no': '', 'underground_yn': 'N', 'x': '127.056789858953', 'y': '37.5401307747523', 'zone_no': '04784'}, 'x': '127.056741837461', 'y': '37.5402196364231'}], 'meta': {'is_end': True, 'pageable_count': 1, 'total_count': 1}}

{'address_name': '서울 성동구 성수이로10길 14',
 'building_name': '에이스 하이엔드 성수타워',
 'main_building_no': '14',
 'region_1depth_name': '서울',
 'region_2depth_name': '성동구',
 'region_3depth_name': '성수동2가',
 'road_name': '성수이로10길',
 'sub_building_no': '',
 'underground_yn': 'N',
 'x': '127.056789858953',
 'y': '37.5401307747523',
 'zone_no': '04784'}

In [141]:
center_df = add_kakao_geocode(center_df, kakao_key)

In [142]:
print(center_df['rd_addr'].str.contains('서울').sum())

not_seoul = center_df[~center_df['rd_addr'].str.contains('서울')]
not_seoul

210

     idx          nm         addr    type rd_addr  lat  lng
152   77  우림라이온스밸리1차   가산동 371-62  지식산업센터     NaN  NaN  NaN
194   48          천강  신도림동 402-3호  지식산업센터     NaN  NaN  NaN

In [143]:
'''
77	우림라이온스밸리1차	가산동 371-62
48	천강	신도림동 402-3호
두 주소는 이상치로 보고 제거.
'''
center_df.dropna(inplace=True)
len(center_df)

210

In [145]:
# lat, lng 결측치 확인. coerce: 변환 불가 시 NaN으로 바뀜
center_df["lat"] = pd.to_numeric(center_df["lat"], errors="coerce")
center_df["lng"] = pd.to_numeric(center_df["lng"], errors="coerce")
center_df[["lat", "lng"]].isna().sum()

lat    0
lng    0
dtype: int64

In [146]:
# 저장할 데이터 재추출
save_center_df = center_df[['nm', 'type', 'rd_addr', 'lat', 'lng']]

# 열이름 변경
save_center_df = save_center_df.rename(columns={'rd_addr': 'addr'})

# index 재설정
save_center_df.reset_index(drop=True, inplace=True) 

save_center_df.head()

                 nm    type              addr        lat         lng
0           신내테크노타운  지식산업센터   서울 중랑구 봉화산로 123  37.604027  127.087796
1         월곡동아파트형공장  지식산업센터    서울 성북구 오패산로 21  37.604119  127.037068
2  문정아르페온 1차 지식산업센터  지식산업센터     서울 송파구 정의로 70  37.486048  127.115468
3          문정 대명벨리온  지식산업센터    서울 송파구 법원로 127  37.486316  127.118783
4    문정 현대지식산업센터Ｉ-1  지식산업센터  서울 송파구 법원로11길 11  37.484630  127.118322

# 서울시 휴게음식점 인허가

## 데이터 불러오기

In [5]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "1000"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_072405/{start_index}/{end_index}/"

response = requests.get(url).json()
print(response)

{'LOCALDATA_072405': {'list_total_count': 143069, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}, 'row': [{'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00210', 'APVPERMYMD': '2016-09-21', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-04-26', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '31.17', 'SITEPOSTNO': '143-822', 'SITEWHLADDR': '서울특별시 광진구 구의동 212-3 1층 ', 'RDNWHLADDR': '서울특별시 광진구 아차산로 471, 1층 (구의동, CS프라자)', 'RDNPOSTNO': '05035', 'BPLCNM': '자연드림 구의점', 'LASTMODTS': '2023-04-26 16:50:33', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-04-28 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '208232.99266682     ', 'Y': '448688.329238784    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '31.17', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00212', 'APVPERMYMD': '2016-09-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-03-23', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-912', 'SITEWHLADDR': '서울특별시 광진구 중곡동 629-7번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 면목로 59, 1층 (중곡동)', 'RDNPOSTNO': '04920', 'BPLCNM': '커피뎁(coffee dep)', 'LASTMODTS': '2018-03-23 14:00:12', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '206769.405105326    ', 'Y': '450783.052530227    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '64', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00213', 'APVPERMYMD': '2016-09-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-11-02', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '10.00', 'SITEPOSTNO': '143-847', 'SITEWHLADDR': '서울특별시 광진구 능동 279-5 삼일빌딩 지하1층 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 290, 지1층 (능동, 삼일빌딩)', 'RDNPOSTNO': '04985', 'BPLCNM': '엔탑피씨방', 'LASTMODTS': '2023-11-02 10:31:12', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-11-04 02:40:00.0', 'UPTAENM': '일반조리판매', 'X': '206908.823781413    ', 'Y': '450372.530408586    ', 'SNTUPTAENM': '일반조리판매', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '10', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00214', 'APVPERMYMD': '2016-09-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2021-11-08', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-819', 'SITEWHLADDR': '서울특별시 광진구 구의동 65-10 1층 ', 'RDNWHLADDR': '서울특별시 광진구 광나루로37길 21, 1층 (구의동)', 'RDNPOSTNO': '04976', 'BPLCNM': '지에스25구의래미안', 'LASTMODTS': '2021-11-08 08:12:13', 'UPDATEGBN': 'U', 'UPDATEDT': '2021-11-10 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '207709.57658649     ', 'Y': '449302.624247538    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00033', 'APVPERMYMD': '2018-02-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-08-18', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '0234365657', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-896', 'SITEWHLADDR': '서울특별시 광진구 중곡동 150-160 종호빌딩1층 ', 'RDNWHLADDR': '서울특별시 광진구 긴고랑로25길 29, 종호빌딩 1층 (중곡동)', 'RDNPOSTNO': '04936', 'BPLCNM': '씨유중곡오거리점', 'LASTMODTS': '2023-08-18 13:20:53', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-08-20 02:40:00.0', 'UPTAENM': '편의점', 'X': '207551.031843332    ', 'Y': '451065.671267248    ', 'SNTUPTAENM': '편의점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00035', 'APVPERMYMD': '2018-02-05', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2020-02-10', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-960', 'SITEWHLADDR': '서울특별시 광진구 구의동 226-18번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 자양로30길 79, 1층 (구의동)', 'RDNPOSTNO': '05032', 'BPLCNM': '지에스(GS)25 구의창원점', 'LASTMODTS': '2020-02-10 10:32:45', 'UPDATEGBN': 'U', 'UPDATEDT': '2020-02-12 02:40:00.0', 'UPTAENM': '편의점', 'X': '207823.103191831    ', 'Y': '448979.694709608    ', 'SNTUPTAENM': '편의점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00036', 'APVPERMYMD': '2018-02-09', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-08-07', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '21.00', 'SITEPOSTNO': '143-839', 'SITEWHLADDR': '서울특별시 광진구 군자동 144-10번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 동일로54길 19, 1층 (군자동)', 'RDNPOSTNO': '05000', 'BPLCNM': '커피나라', 'LASTMODTS': '2018-08-07 15:10:01', 'UPDATEGBN': 'U', 'UPDATEDT': '2018-12-06 02:40:00.0', 'UPTAENM': '커피숍', 'X': '206359.54826389     ', 'Y': '450334.307546466    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '21', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2018-00038', 'APVPERMYMD': '2018-02-19', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2020-04-29', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '27.16', 'SITEPOSTNO': '143-898', 'SITEWHLADDR': '서울특별시 광진구 중곡동 160-12번지 유정아트빌 ', 'RDNWHLADDR': '서울특별시 광진구 능동로40길 19, 1층 101호 (중곡동, 유정아트빌)', 'RDNPOSTNO': '04928', 'BPLCNM': '영희', 'LASTMODTS': '2020-04-29 17:57:12', 'UPDATEGBN': 'U', 'UPDATEDT': '2020-05-01 02:40:00.0', 'UPTAENM': '커피숍', 'X': '207110.10262802     ', 'Y': '450645.30992606     ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '27.16', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00135', 'APVPERMYMD': '2016-05-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2016-11-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-916', 'SITEWHLADDR': '서울특별시 광진구 화양동 32-4번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 능동로13길 106, 1층 (화양동)', 'RDNPOSTNO': '05012', 'BPLCNM': '라푸르타(La Frutta)', 'LASTMODTS': '2016-05-27 14:25:49', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '205949.051675131    ', 'Y': '449317.879371124    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '29.8', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00136', 'APVPERMYMD': '2016-05-30', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2022-01-14', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '0215770711', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-902', 'SITEWHLADDR': '서울특별시 광진구 중곡동 199-1 1층 ', 'RDNWHLADDR': '서울특별시 광진구 면목로 192, 1층 (중곡동)', 'RDNPOSTNO': '04903', 'BPLCNM': '바이더웨이중곡중앙점', 'LASTMODTS': '2022-01-14 14:57:02', 'UPDATEGBN': 'U', 'UPDATEDT': '2022-01-16 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '207302.075496997    ', 'Y': '451991.900378929    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00170', 'APVPERMYMD': '2017-11-07', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-06-12', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-866', 'SITEWHLADDR': '서울특별시 광진구 자양동 617-39번지 1층101호 ', 'RDNWHLADDR': '서울특별시 광진구 자양로13다길 8, 1층 101호 (자양동)', 'RDNPOSTNO': '05062', 'BPLCNM': '커피알렉스', 'LASTMODTS': '2018-06-12 13:20:28', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '기타 휴게음식점', 'X': '206958.796281621    ', 'Y': '447839.595007476    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '29.61', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00138', 'APVPERMYMD': '2016-06-03', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2016-06-30', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-758', 'SITEWHLADDR': '서울특별시 광진구 자양동 227-342번지 지하1층 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 92, 지1층 (자양동)', 'RDNPOSTNO': '05065', 'BPLCNM': '쉐어티', 'LASTMODTS': '2016-07-11 13:03:18', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '206217.434726027    ', 'Y': '448506.218743834    ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '9.9', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00156', 'APVPERMYMD': '2017-10-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2023-06-01', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02  18997443', 'SITEAREA': '13.20', 'SITEPOSTNO': '143-758', 'SITEWHLADDR': '서울특별시 광진구 자양동 227-342 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 92, 지하1층 (자양동, 롯데백화점 스타시티점)', 'RDNPOSTNO': '05065', 'BPLCNM': '반반식당', 'LASTMODTS': '2023-06-01 17:48:02', 'UPDATEGBN': 'U', 'UPDATEDT': '2023-06-03 02:40:00.0', 'UPTAENM': '패스트푸드', 'X': '206217.434726027    ', 'Y': '448506.218743834    ', 'SNTUPTAENM': '패스트푸드', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '13.2', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00157', 'APVPERMYMD': '2017-10-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2017-10-16', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-841', 'SITEWHLADDR': '서울특별시 광진구 자양동 7-25번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 아차산로 224, 1층 (자양동)', 'RDNPOSTNO': '05073', 'BPLCNM': '오닭꼬치', 'LASTMODTS': '2017-10-16 11:08:35', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '기타 휴게음식점', 'X': '205948.480566193    ', 'Y': '448701.947776139    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '26', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00158', 'APVPERMYMD': '2017-10-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2019-09-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02  456 3373', 'SITEAREA': '6.60', 'SITEPOSTNO': '143-802', 'SITEWHLADDR': '서울특별시 광진구 광장동 121번지 ', 'RDNWHLADDR': '서울특별시 광진구 아차산로78길 7, 2층 B201호 (광장동, 유진스웰)', 'RDNPOSTNO': '04969', 'BPLCNM': '씨유광장유진점', 'LASTMODTS': '2019-09-04 09:30:58', 'UPDATEGBN': 'U', 'UPDATEDT': '2019-09-06 02:40:00.0', 'UPTAENM': '편의점', 'X': '209589.042548422    ', 'Y': '449798.08201875     ', 'SNTUPTAENM': '편의점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '6.6', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00159', 'APVPERMYMD': '2017-10-18', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2024-01-02', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '24.00', 'SITEPOSTNO': '143-891', 'SITEWHLADDR': '서울특별시 광진구 중곡동 134-1 1층 ', 'RDNWHLADDR': '서울특별시 광진구 용마산로3길 88, 1층 (중곡동)', 'RDNPOSTNO': '04925', 'BPLCNM': '삼보할인마트', 'LASTMODTS': '2024-01-02 14:48:41', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-01-04 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '207297.69930366     ', 'Y': '450547.957727534    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '0', 'WMEIPCNT': '0', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '0', 'HOFFEPCNT': '0', 'FCTYOWKEPCNT': '0', 'FCTYSILJOBEPCNT': '0', 'FCTYPDTJOBEPCNT': '0', 'BDNGOWNSENM': '', 'ISREAM': '0', 'MONAM': '0', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '24', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2017-00161', 'APVPERMYMD': '2017-10-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-01-11', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-758', 'SITEWHLADDR': '서울특별시 광진구 자양동 227-342번지 ', 'RDNWHLADDR': '서울특별시 광진구 능동로 92, 지하1층 (자양동, 롯데백화점 건대스타시티점)', 'RDNPOSTNO': '05065', 'BPLCNM': '88브레드', 'LASTMODTS': '2018-01-11 09:31:17', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '일반조리판매', 'X': '206217.434726027    ', 'Y': '448506.218743834    ', 'SNTUPTAENM': '일반조리판매', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '9', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3150000', 'MGTNO': '3150000-104-1987-00253', 'APVPERMYMD': '1987-09-17', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2004-07-26', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '41.76', 'SITEPOSTNO': '157-895', 'SITEWHLADDR': '서울특별시 강서구 화곡동 53-3번지 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '다미안제과', 'LASTMODTS': '2002-10-14 00:00:00', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '과자점', 'X': '186440.927851414    ', 'Y': '448962.142283183    ', 'SNTUPTAENM': '과자점', 'MANEIPCNT': '1', 'WMEIPCNT': '1', 'TRDPJUBNSENM': '주택가주변', 'LVSENM': '자율', 'WTRSPLYFACILSENM': '상수도전용', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '41.76', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00108', 'APVPERMYMD': '2016-04-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2019-10-25', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '16.50', 'SITEPOSTNO': '143-840', 'SITEWHLADDR': '서울특별시 광진구 군자동 359-15번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 동일로34길 26, 1층 (군자동)', 'RDNPOSTNO': '05003', 'BPLCNM': '아이싱온더케이크', 'LASTMODTS': '2019-10-25 14:37:57', 'UPDATEGBN': 'U', 'UPDATEDT': '2019-10-27 02:40:00.0', 'UPTAENM': '기타 휴게음식점', 'X': '206115.760746843    ', 'Y': '449711.762168968    ', 'SNTUPTAENM': '기타 휴게음식점', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '16.5', 'JTUPSOASGNNO': '', 'JTUPSOMAINEDF': '', 'HOMEPAGE': ''}, {'OPNSFTEAMCODE': '3040000', 'MGTNO': '3040000-104-2016-00109', 'APVPERMYMD': '2016-04-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '02', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-02-27', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '143-826', 'SITEWHLADDR': '서울특별시 광진구 구의동 251-44번지 1층 ', 'RDNWHLADDR': '서울특별시 광진구 자양로22길 23, 1층 (구의동)', 'RDNPOSTNO': '05039', 'BPLCNM': '썸띵비터(Something Bitter)', 'LASTMODTS': '2018-02-27 13:48:48', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '커피숍', 'X': '207406.507088563    ', 'Y': '448606.98797732     ', 'SNTUPTAENM': '커피숍', 'MANEIPCNT': '', 'WMEIPCNT': '', 'TRDPJUBNSENM': '', 'LVSENM': '', 'WTRSPLYFACILSENM': '', 'TOTEPNUM': '', 'HOFFEPCNT': '', 'FCTYOWKEPCNT': '', 'FCTYSILJOBEPCNT': '', 'FCTYPDTJOBEPCNT': '', 'BDNGOWNSENM': '', 'ISREAM': '', 'MONAM': '', 'MULTUSNUPSOYN': 'N', 'FACILTOTSCP': '26', 'JTUPSOASGNNO': '',

In [6]:
# 'list_total_count': 142943 ⇒ 1000개씩 나눠서 가져와야 함
apikey = os.getenv("MJ_APIKEY")
service = "LOCALDATA_072405"
base = "http://openapi.seoul.go.kr:8088"

# 1) 전체 건수 확인
first = requests.get(f"{base}/{apikey}/json/{service}/1/1/").json()
total = first[service]["list_total_count"]

# 2) 분할 수집
batch = 1000   # 서비스 허용 범위 내에서 조절
all_rows = []

for start in range(1, total + 1, batch):
    end = min(start + batch - 1, total)
    url = f"{base}/{apikey}/json/{service}/{start}/{end}/"
    response = requests.get(url).json()
    rows = response.get(service, {}).get("row", [])
    all_rows.extend(rows)

print("total:", total)
print("fetched:", len(all_rows))

total: 143069
fetched: 143069

In [7]:
cafe_df = pd.DataFrame(all_rows)
cafe_df.head()

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,FCTYSILJOBEPCNT,FCTYPDTJOBEPCNT,BDNGOWNSENM,ISREAM,MONAM,MULTUSNUPSOYN,FACILTOTSCP,JTUPSOASGNNO,JTUPSOMAINEDF,HOMEPAGE
0,3040000,3040000-104-2016-00210,2016-09-21,,03,폐업,02,폐업,2023-04-26,,...,0,0,,0,0,N,31.17,,,
1,3040000,3040000-104-2016-00212,2016-09-27,,03,폐업,02,폐업,2018-03-23,,...,,,,,,N,64,,,
2,3040000,3040000-104-2016-00213,2016-09-28,,03,폐업,02,폐업,2023-11-02,,...,0,0,,0,0,N,10,,,
3,3040000,3040000-104-2016-00214,2016-09-29,,03,폐업,02,폐업,2021-11-08,,...,0,0,,0,0,N,6.6,,,
4,3040000,3040000-104-2018-00033,2018-02-01,,03,폐업,02,폐업,2023-08-18,,...,0,0,,0,0,N,6.6,,,

## 데이터 전처리

In [8]:
# 필요한 데이터만 추출하고, 열이름 모두 소문자로 통일
cafe_df = cafe_df[['BPLCNM', "UPTAENM", 'DTLSTATEGBN', "APVPERMYMD", "SITEWHLADDR", "RDNWHLADDR", "SITEAREA", "LASTMODTS"]]
cafe_df.columns = cafe_df.columns.str.lower()

cafe_df

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts
0,자연드림 구의점,기타 휴게음식점,02,2016-09-21,서울특별시 광진구 구의동 212-3 1층,"서울특별시 광진구 아차산로 471, 1층 (구의동, CS프라자)",31.17,2023-04-26 16:50:33
1,커피뎁(coffee dep),커피숍,02,2016-09-27,서울특별시 광진구 중곡동 629-7번지 1층,"서울특별시 광진구 면목로 59, 1층 (중곡동)",,2018-03-23 14:00:12
2,엔탑피씨방,일반조리판매,02,2016-09-28,서울특별시 광진구 능동 279-5 삼일빌딩 지하1층,"서울특별시 광진구 능동로 290, 지1층 (능동, 삼일빌딩)",10.00,2023-11-02 10:31:12
3,지에스25구의래미안,기타 휴게음식점,02,2016-09-29,서울특별시 광진구 구의동 65-10 1층,"서울특별시 광진구 광나루로37길 21, 1층 (구의동)",6.60,2021-11-08 08:12:13
4,씨유중곡오거리점,편의점,02,2018-02-01,서울특별시 광진구 중곡동 150-160 종호빌딩1층,"서울특별시 광진구 긴고랑로25길 29, 종호빌딩 1층 (중곡동)",6.60,2023-08-18 13:20:53
...,...,...,...,...,...,...,...,...
143064,뎁스Depth,커피숍,01,2020-09-15,서울특별시 강서구 화곡동 55-59 1층,"서울특별시 강서구 초록마을로 56, 1층 (화곡동)",94.84,2026-02-27 09:00:48
143065,부산빨간어묵포차 수색점,일반조리판매,02,2019-07-12,서울특별시 은평구 수색동 75 디엠씨 자이1단지(DMC 자이1) 2층,"서울특별시 은평구 수색로 217, 2층 (수색동, 디엠씨 자이1단지(DMC 자이1))",15.84,2026-02-27 14:58:11
143066,계순네 닭강정,기타 휴게음식점,01,2016-12-26,,"서울특별시 마포구 백범로 68 (신수동, 1층일부)",9.90,2026-02-27 14:55:08
143067,장손족발(영등포점),일반조리판매,02,2015-04-07,서울특별시 영등포구 문래동3가 55-3 홈플러스영등포점 지하 1층,"서울특별시 영등포구 당산로 42 (문래동3가, 홈플러스영등포점 지하 1층)",8.20,2026-02-27 10:13:04
143068,제이제이 디저트,기타 휴게음식점,02,2026-02-05,서울특별시 영등포구 영등포동 618-496 영등포 민자역사,"서울특별시 영등포구 경인로 846, 롯데백화점 영등포점 1층 (영등포동)",3.30,2026-03-01 04:15:09

In [8]:
cafe_df['uptaenm'].unique()

<StringArray>
['기타 휴게음식점',      '커피숍',   '일반조리판매',      '편의점',    '패스트푸드',      '과자점',
     '푸드트럭',       '다방',     '관광호텔',      '유원지',    '철도역구내',      '백화점',
      '떡카페',    '아이스크림',     '키즈카페',     '전통찻집',       '극장',       '공항',
     '단란주점',    '호프/통닭',     '고속도로',       '기타',  '김밥(도시락)',      '룸살롱',
       '한식']
Length: 25, dtype: str

In [9]:
# '영업' 중이면서 '커피숍'인 데이터만 필터링
cafe_type = ['커피숍']
cond = (cafe_df['uptaenm'].isin(cafe_type)) & (cafe_df['dtlstategbn'] == '01')  # 01=영업

cafe_df = cafe_df.loc[cond, :]
cafe_df

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts
220,이디야답십리파크자이점,커피숍,01,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",85.00,2022-07-07 14:22:12
223,다락방 사주카페,커피숍,01,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),49.59,2019-04-03 15:45:38
225,빽다방 전농동전동초교점,커피숍,01,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",57.00,2024-02-02 13:26:49
241,커피상회,커피숍,01,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",9.90,2023-08-18 13:24:50
245,구하니 커피,커피숍,01,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",10.36,2024-09-11 10:45:00
...,...,...,...,...,...,...,...,...
143030,CornerStone Espresso Bar,커피숍,01,2026-02-27,서울특별시 강서구 마곡동 771-3 보타닉파크타워3,"서울특별시 강서구 마곡중앙6로 11, 보타닉파크타워3 1층 107호 (마곡동)",39.90,2026-02-27 10:35:12
143041,매머드커피 익스프레스 선릉501스퀘어점,커피숍,01,2026-02-27,서울특별시 강남구 삼성동 143-32,"서울특별시 강남구 삼성로91길 32, 1층 (삼성동)",72.54,2026-02-27 12:30:31
143060,카페 선공간,커피숍,01,2023-05-17,서울특별시 동작구 신대방동 686,"서울특별시 동작구 대림로 61, 1층 (신대방동)",26.44,2026-02-27 11:52:07
143061,포트캔커피 상일동역점,커피숍,01,2022-07-21,서울특별시 강동구 고덕동 693 고덕그라시움(제1상가),"서울특별시 강동구 고덕로 353, 고덕그라시움(제1상가) 1층 에이137호 (고덕동)",27.55,2026-02-27 14:39:07
143064,뎁스Depth,커피숍,01,2020-09-15,서울특별시 강서구 화곡동 55-59 1층,"서울특별시 강서구 초록마을로 56, 1층 (화곡동)",94.84,2026-02-27 09:00:48

In [10]:
# 공백/빈문자열을 전부 NA로 통일
cafe_df = cafe_df.replace(r'^\s*$', pd.NA, regex=True)

In [11]:
# 결측치 확인
cafe_df.isna().sum()

bplcnm           0
uptaenm          0
dtlstategbn      0
apvpermymd       0
sitewhladdr     10
rdnwhladdr      72
sitearea       286
lastmodts        0
dtype: int64

In [12]:
# sitewhladdr(지번주소)가 NA인 곳만 rdnwhladdr(도로명주소)값으로 채워 결측치 없애기
cafe_df["sitewhladdr"] = cafe_df["sitewhladdr"].fillna(cafe_df["rdnwhladdr"])
cafe_df.isna().sum()

bplcnm           0
uptaenm          0
dtlstategbn      0
apvpermymd       0
sitewhladdr      0
rdnwhladdr      72
sitearea       286
lastmodts        0
dtype: int64

In [13]:
# 층수 추출하기
pat_block = re.compile(r'(지하|지상)?\s*(\d+(?:\s*,\s*\d+)*)\s*층')
pat_num = re.compile(r'\d+')
pat_ho = re.compile(r'(\d{3,4})\s*호')  # 101호, 1101호

def get_floor(addr):
    if pd.isna(addr):
        return pd.NA

    text = str(addr)
    vals = []

    # 1) 일반 층수 패턴
    for prefix, nums in pat_block.findall(text):
        for n in pat_num.findall(nums):
            v = int(n)
            vals.append(-v if prefix == '지하' else v)

    # 2) 층 정보가 없으면 호수에서 추정
    if not vals:
        for h in pat_ho.findall(text):
            if len(h) == 3:      # 101호 -> 1층
                vals.append(int(h[0]))
            elif len(h) == 4:    # 1101호 -> 11층
                vals.append(int(h[:2]))

    if not vals:
        return pd.NA
    if 1 in vals:
        return 1

    positives = any(v > 0 for v in vals)
    negatives = any(v < 0 for v in vals)
    if negatives and not positives:
        return -1

    return min(vals)

cafe_df["floor"] = cafe_df["sitewhladdr"].apply(get_floor).astype("Int64")
cafe_df["floor"] = cafe_df["floor"].fillna(
    cafe_df["rdnwhladdr"].apply(get_floor).astype("Int64")
)
cafe_df

,bplcnm,uptaenm,dtlstategbn,apvpermymd,sitewhladdr,rdnwhladdr,sitearea,lastmodts,floor
220,이디야답십리파크자이점,커피숍,01,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",85.00,2022-07-07 14:22:12,1
223,다락방 사주카페,커피숍,01,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),49.59,2019-04-03 15:45:38,<NA>
225,빽다방 전농동전동초교점,커피숍,01,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",57.00,2024-02-02 13:26:49,1
241,커피상회,커피숍,01,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",9.90,2023-08-18 13:24:50,1
245,구하니 커피,커피숍,01,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",10.36,2024-09-11 10:45:00,<NA>
...,...,...,...,...,...,...,...,...,...
143030,CornerStone Espresso Bar,커피숍,01,2026-02-27,서울특별시 강서구 마곡동 771-3 보타닉파크타워3,"서울특별시 강서구 마곡중앙6로 11, 보타닉파크타워3 1층 107호 (마곡동)",39.90,2026-02-27 10:35:12,1
143041,매머드커피 익스프레스 선릉501스퀘어점,커피숍,01,2026-02-27,서울특별시 강남구 삼성동 143-32,"서울특별시 강남구 삼성로91길 32, 1층 (삼성동)",72.54,2026-02-27 12:30:31,1
143060,카페 선공간,커피숍,01,2023-05-17,서울특별시 동작구 신대방동 686,"서울특별시 동작구 대림로 61, 1층 (신대방동)",26.44,2026-02-27 11:52:07,1
143061,포트캔커피 상일동역점,커피숍,01,2022-07-21,서울특별시 강동구 고덕동 693 고덕그라시움(제1상가),"서울특별시 강동구 고덕로 353, 고덕그라시움(제1상가) 1층 에이137호 (고덕동)",27.55,2026-02-27 14:39:07,1
143064,뎁스Depth,커피숍,01,2020-09-15,서울특별시 강서구 화곡동 55-59 1층,"서울특별시 강서구 초록마을로 56, 1층 (화곡동)",94.84,2026-02-27 09:00:48,1

In [14]:
# 1) 열이름 변경
cafe_df = cafe_df.rename(columns={
    'bplcnm': 'nm',
    'uptaenm': 'type',
    'dtlstategbn': 'stable',
    'apvpermymd': 'apv_date',
    'sitewhladdr': 'addr',
    'rdnwhladdr': 'rd_addr',
    'lastmodts': 'last_updated',
})

# 2) 열 순서 재배치
cafe_df = cafe_df[['nm', 'type', 'apv_date', 'addr', 'rd_addr', 'floor', 'sitearea', 'last_updated']]

In [15]:
# 결측치 확인
cafe_df.isna().sum()

nm                0
type              0
apv_date          0
addr              0
rd_addr          72
floor           626
sitearea        286
last_updated      0
dtype: int64

In [16]:
# 주소 이상치 제거 for 위도, 경도 탐색
cafe_df["addr"] = (
    cafe_df["addr"]
    .str.replace(r"\s*(?:외\s*)?\d+\s*필지'?", "", regex=True)  # 외 2필지 / 2필지 / 2 필지 / 외2필지'
    .str.strip()
)
cafe_df

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated
220,이디야답십리파크자이점,커피숍,2019-03-11,서울특별시 동대문구 답십리동 12-18 영진빌딩,"서울특별시 동대문구 한천로 55, 영진빌딩 1층 (답십리동)",1,85.00,2022-07-07 14:22:12
223,다락방 사주카페,커피숍,2014-04-09,서울특별시 동대문구 휘경동 320-5번지,서울특별시 동대문구 회기로 185 (휘경동),<NA>,49.59,2019-04-03 15:45:38
225,빽다방 전농동전동초교점,커피숍,2023-08-23,서울특별시 동대문구 전농동 38-112,"서울특별시 동대문구 사가정로 145, 1층 (전농동)",1,57.00,2024-02-02 13:26:49
241,커피상회,커피숍,2023-08-18,서울특별시 동대문구 청량리동 225-4,"서울특별시 동대문구 약령시로 133, 1층 (청량리동)",1,9.90,2023-08-18 13:24:50
245,구하니 커피,커피숍,2023-08-04,서울특별시 동대문구 전농동 295-431,"서울특별시 동대문구 전농로15길 21, 남동 2호 (전농동)",<NA>,10.36,2024-09-11 10:45:00
...,...,...,...,...,...,...,...,...
143030,CornerStone Espresso Bar,커피숍,2026-02-27,서울특별시 강서구 마곡동 771-3 보타닉파크타워3,"서울특별시 강서구 마곡중앙6로 11, 보타닉파크타워3 1층 107호 (마곡동)",1,39.90,2026-02-27 10:35:12
143041,매머드커피 익스프레스 선릉501스퀘어점,커피숍,2026-02-27,서울특별시 강남구 삼성동 143-32,"서울특별시 강남구 삼성로91길 32, 1층 (삼성동)",1,72.54,2026-02-27 12:30:31
143060,카페 선공간,커피숍,2023-05-17,서울특별시 동작구 신대방동 686,"서울특별시 동작구 대림로 61, 1층 (신대방동)",1,26.44,2026-02-27 11:52:07
143061,포트캔커피 상일동역점,커피숍,2022-07-21,서울특별시 강동구 고덕동 693 고덕그라시움(제1상가),"서울특별시 강동구 고덕로 353, 고덕그라시움(제1상가) 1층 에이137호 (고덕동)",1,27.55,2026-02-27 14:39:07
143064,뎁스Depth,커피숍,2020-09-15,서울특별시 강서구 화곡동 55-59 1층,"서울특별시 강서구 초록마을로 56, 1층 (화곡동)",1,94.84,2026-02-27 09:00:48

In [17]:
# 중복 확인
print(cafe_df.duplicated(subset=['nm', 'addr']).sum()) 

dup_all_mask = cafe_df.duplicated(subset=['nm', 'addr'], keep=False)
cafe_df[dup_all_mask].sort_values(['nm', 'addr'])

15

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated
86218,공차 영등포역점,커피숍,2022-07-12,서울특별시 영등포구 영등포동3가 9-51,"서울특별시 영등포구 영중로 10, 1층 (영등포동3가)",1,51.50,2025-02-25 13:33:03
86219,공차 영등포역점,커피숍,2022-07-12,서울특별시 영등포구 영등포동3가 9-51,"서울특별시 영등포구 영중로 10, 2층 (영등포동3가)",2,51.50,2025-02-25 13:26:48
122639,누구나카페,커피숍,2025-07-08,서울특별시 마포구 성산동 370 마포구청,"서울특별시 마포구 월드컵로 212, 마포구청 지하1층 (성산동)",-1,31.50,2025-07-08 17:21:46
141619,누구나카페,커피숍,2026-01-08,서울특별시 마포구 성산동 370 마포구청,"서울특별시 마포구 월드컵로 212, 마포구보건소 1층 (성산동)",1,15.50,2026-01-08 14:04:52
78234,라이프플러스 카페(LIFEPLUS CAFE),커피숍,2023-01-03,서울특별시 영등포구 여의도동 60 63한화생명빌딩,"서울특별시 영등포구 63로 50, 63한화생명빌딩 7층 (여의도동)",7,23.55,2025-08-18 14:34:18
78235,라이프플러스 카페(LIFEPLUS CAFE),커피숍,2023-01-03,서울특별시 영등포구 여의도동 60 63한화생명빌딩,"서울특별시 영등포구 63로 50, 63한화생명빌딩 45층 (여의도동)",45,28.34,2025-08-18 14:35:12
86441,마이유(My U),커피숍,2022-12-09,서울특별시 영등포구 신길동 51-1,"서울특별시 영등포구 영등포로 349, 1층 (신길동)",1,42.43,2022-12-09 15:52:39
86442,마이유(My U),커피숍,2022-12-09,서울특별시 영등포구 신길동 51-1,"서울특별시 영등포구 영등포로 349, 2층 (신길동)",2,42.43,2022-12-09 15:56:25
121382,산체스커피,커피숍,2024-08-09,서울특별시 송파구 오금동 61-10 동성빌딩,"서울특별시 송파구 성내천로8길 3, 동성빌딩 1층 1,2호 (오금동)",1,62.00,2024-10-11 17:35:40
122491,산체스커피,커피숍,2023-02-28,서울특별시 송파구 오금동 61-10 동성빌딩,"서울특별시 송파구 성내천로8길 3, 동성빌딩 1층 3호 (오금동)",1,25.00,2025-10-02 09:16:29
139415,위펀 지에스강서엔타워점,커피숍,2023-03-31,서울특별시 영등포구 양평동1가 5-1 GS강서N타워,"서울특별시 영등포구 선유로 82, GS강서N타워 8층 (양평동1가)",8,44.89,2025-09-09 10:59:04
139416,위펀 지에스강서엔타워점,커피숍,2023-03-31,서울특별시 영등포구 양평동1가 5-1 GS강서N타워,"서울특별시 영등포구 선유로 82, GS강서N타워 1층 (양평동1가)",1,17.26,2025-09-09 10:58:01
86548,위펀 지에스강서점,커피숍,2023-03-31,서울특별시 영등포구 문래동6가 10 GS강서타워,"서울특별시 영등포구 선유로 75, GS강서타워 5층 (문래동6가)",5,67.23,2025-09-09 10:53:18
139414,위펀 지에스강서점,커피숍,2023-03-31,서울특별시 영등포구 문래동6가 10 GS강서타워,"서울특별시 영등포구 선유로 75, GS강서타워 1층 (문래동6가)",1,40.54,2025-09-09 10:52:30
92305,이디야 신림미성점,커피숍,2013-06-28,서울특별시 관악구 신림동 587-122번지,"서울특별시 관악구 난곡로 250, 1층 (신림동)",1,47.76,2013-07-25 09:42:00
92306,이디야 신림미성점,커피숍,2013-06-28,서울특별시 관악구 신림동 587-122번지,"서울특별시 관악구 난곡로 250, 2층 (신림동)",2,45.12,2013-06-28 13:59:21
8466,카페J(제이),커피숍,2018-07-24,서울특별시 성북구 안암동5가 15-51 J리빙텔,"서울특별시 성북구 개운사길 36, J리빙텔 1층 (안암동5가)",1,99.00,2024-12-30 10:05:38
9044,카페J(제이),커피숍,2018-08-01,서울특별시 성북구 안암동5가 15-51 J리빙텔,"서울특별시 성북구 개운사길 36, J리빙텔 지하1층 (안암동5가)",-1,57.00,2024-12-30 10:02:29
39005,카페메종,커피숍,2022-08-03,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 3층 (능동)",3,169.22,2022-08-03 14:51:21
39062,카페메종,커피숍,2022-05-02,서울특별시 광진구 능동 18 어린이대공원,"서울특별시 광진구 능동로 216, 어린이대공원 꿈마루 지하1층 (능동)",-1,207.24,2022-05-02 15:35:26
914,카페쿠피,커피숍,2016-08-25,서울특별시 동대문구 회기동 1-5,"서울특별시 동대문구 경희대로 26, 지상1층 (회기동, 푸른솔문화관)",1,46.15,2024-04-17 14:44:42
1127,카페쿠피,커피숍,2015-03-11,서울특별시 동대문구 회기동 1-5,서울특별시 동대문구 경희대로 26 (회기동),<NA>,9.90,2024-04-17 14:51:17
119242,퍼스트커피랩 강남역점,커피숍,2022-12-19,서울특별시 강남구 역삼동 618-18 리＆신,"서울특별시 강남구 봉은사로6길 39, 지하1층 (역삼동)",-1,243.59,2023-09-05 16:07:42
119243,퍼스트커피랩 강남역점,커피숍,2022-12-19,서울특별시 강남구 역삼동 618-18 리＆신,"서울특별시 강남구 봉은사로6길 39, 지상1층 (역삼동)",1,223.69,2023-09-05 16:01:51
122449,프렛티 롯데월드몰,커피숍,2024-02-29,서울특별시 송파구 신천동 29 롯데월드타워앤드롯데월드몰,"서울특별시 송파구 올림픽로 300, 롯데월드타워앤드롯데월드몰 지하1층 일부호 (신천동)",-1,28.17,2024-04-11 10:00:24
136740,프렛티 롯데월드몰,커피숍,2025-03-21,서울특별시 송파구 신천동 29 롯데월드타워앤드롯데월드몰,"서울특별시 송파구 올림픽로 300, 롯데월드타워앤드롯데월드몰 지하1층 (신천동)",-1,28.00,2025-03-21 17:11:21
122403,피트 앤 브레드,커피숍,2023-03-27,서울특별시 송파구 문정동 640-5 AJ빌딩,"서울특별시 송파구 정의로8길 9, 에이제이비전타워 1층 (문정동)",1,66.00,2023-03-27 16:32:13
122640,피트 앤 브레드,커피숍,2021-05-25,서울특별시 송파구 문정동 640-5 AJ빌딩,"서울특별시 송파구 정의로8길 9, 에이제이비전타워 1층 (문정동)",1,231.00,2023-01-18 17:33:47
17942,할리스 종로5가점,커피숍,2018-12-11,서울특별시 종로구 종로5가 398-2번지,"서울특별시 종로구 동호로 401, 2층 (종로5가)",2,95.00,2018-12-11 13:32:50
18000,할리스 종로5가점,커피숍,2018-11-16,서울특별시 종로구 종로5가 398-2번지,"서울특별시 종로구 동호로 401, 1층 (종로5가)",1,NaN,2018-11-29 17:38:15

In [18]:
# 최신 업데이트 정보 기준으로 중복제거
# 1) datetime 변환
cafe_df["last_updated"] = pd.to_datetime(cafe_df["last_updated"], errors="coerce")

# 2) 같은 (cafe_nm, address) 그룹에서 최신 last_updated만 남기기
cafe_df = (
    cafe_df.sort_values("last_updated")  # 오래된 -> 최신
           .drop_duplicates(subset=["nm", "addr"], keep="last")
           .reset_index(drop=True)
)

# 확인
print(cafe_df.duplicated(subset=["nm", "addr"]).sum())

0

In [19]:
# 중복 제거 잘 되었는지 케이스 하나 확인
cafe_df.loc[(cafe_df['nm'] == '누구나카페'), :]

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated
14076,누구나카페,커피숍,2026-01-08,서울특별시 마포구 성산동 370 마포구청,"서울특별시 마포구 월드컵로 212, 마포구보건소 1층 (성산동)",1,15.50,2026-01-08 14:04:52

### 주소 → 위도, 경도

In [20]:
kakao_key  = os.getenv("KAKAO_REST_APIKEY")     # 인증키

In [21]:
cafe_df = add_kakao_geocode(cafe_df, kakao_key, address_col="addr", out_col="kakao_addr")
cafe_df

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated,kakao_addr,lat,lng
0,베레베레,커피숍,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19 (화양동),<NA>,NaN,2002-09-19 00:00:00,서울 광진구 능동로13길 19,37.542885,127.070832
1,클럽알앤비,커피숍,2002-11-05,서울특별시 중구 장충동2가 189-2번지 (동대입구역322-13),NaN,<NA>,17.00,2002-11-05 00:00:00,NaN,NaN,NaN
2,덕수궁전통차전문,커피숍,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),"서울특별시 중구 서소문로 109 (서소문동,(2층))",2,46.28,2003-01-22 00:00:00,서울 중구 서소문로 109,37.563062,126.973280
3,엘빠소,커피숍,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18 (명륜2가),<NA>,NaN,2003-05-31 00:00:00,서울 종로구 성균관로 18,37.584406,126.997641
4,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,"서울특별시 종로구 세종대로 188 (세종로,지상1층)",1,NaN,2003-11-21 00:00:00,서울 종로구 세종대로 188,37.573190,126.977831
...,...,...,...,...,...,...,...,...,...,...,...
14567,카페 라희,커피숍,2026-02-27,서울특별시 강동구 길동 474 GS강동자이아파트,"서울특별시 강동구 천호대로199길 10, 1층 103호 (길동, GS강동자이아파트)",1,25.20,2026-02-27 15:32:32,서울 강동구 천호대로 1239,37.537861,127.148277
14568,달콤한 오늘,커피숍,2026-02-27,서울특별시 강서구 마곡동 739-3 에스비타운,"서울특별시 강서구 마곡중앙5로 81, 에스비타운 1층 115호 (마곡동)",1,62.33,2026-02-27 16:28:56,서울 강서구 마곡서1로 111-12,37.566787,126.817788
14569,쿠즈코커피 마포성산점,커피숍,2026-02-23,서울특별시 마포구 성산동 231-4,"서울특별시 마포구 월드컵북로 73, 1층 (성산동)",1,35.43,2026-02-27 16:46:41,서울 마포구 월드컵북로 73,37.560317,126.915972
14570,푸디스트(주)서울시중구청카페,커피숍,2026-02-27,서울특별시 중구 예관동 120-1 중구청,"서울특별시 중구 창경궁로 17, 중구청 1층 (예관동)",1,11.94,2026-02-27 17:15:09,서울 중구 창경궁로 17,37.564120,126.998010
14571,로우키,커피숍,2018-04-23,서울특별시 성동구 성수동2가 302-16,"서울특별시 성동구 연무장3길 6, 1층 (성수동2가)",1,34.48,2026-02-27 18:04:45,서울 성동구 연무장3길 6,37.544196,127.051579

In [22]:
# 결측치 확인. coerce: 변환 불가 시 NaN으로 바뀜
cafe_df["lat"] = pd.to_numeric(cafe_df["lat"], errors="coerce")
cafe_df["lng"] = pd.to_numeric(cafe_df["lng"], errors="coerce")
cafe_df[["kakao_addr", "lat", "lng"]].isna().sum()

kakao_addr    243
lat           282
lng           282
dtype: int64

In [23]:
# rd_addr 주소 이상치 제거 for 안정적인 위도, 경도 탐색
cafe_df["rd_addr"] = (
    cafe_df["rd_addr"]
    .str.replace(r"[,()].*$", "", regex=True) # rd_addr에서 ',' 또는 '('가 처음 나오는 지점부터 끝까지 삭제
    .str.strip()
)
cafe_df

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated,kakao_addr,lat,lng
0,베레베레,커피숍,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19,<NA>,NaN,2002-09-19 00:00:00,서울 광진구 능동로13길 19,37.542885,127.070832
1,클럽알앤비,커피숍,2002-11-05,서울특별시 중구 장충동2가 189-2번지 (동대입구역322-13),NaN,<NA>,17.00,2002-11-05 00:00:00,NaN,NaN,NaN
2,덕수궁전통차전문,커피숍,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),서울특별시 중구 서소문로 109,2,46.28,2003-01-22 00:00:00,서울 중구 서소문로 109,37.563062,126.973280
3,엘빠소,커피숍,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18,<NA>,NaN,2003-05-31 00:00:00,서울 종로구 성균관로 18,37.584406,126.997641
4,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,서울특별시 종로구 세종대로 188,1,NaN,2003-11-21 00:00:00,서울 종로구 세종대로 188,37.573190,126.977831
...,...,...,...,...,...,...,...,...,...,...,...
14567,카페 라희,커피숍,2026-02-27,서울특별시 강동구 길동 474 GS강동자이아파트,서울특별시 강동구 천호대로199길 10,1,25.20,2026-02-27 15:32:32,서울 강동구 천호대로 1239,37.537861,127.148277
14568,달콤한 오늘,커피숍,2026-02-27,서울특별시 강서구 마곡동 739-3 에스비타운,서울특별시 강서구 마곡중앙5로 81,1,62.33,2026-02-27 16:28:56,서울 강서구 마곡서1로 111-12,37.566787,126.817788
14569,쿠즈코커피 마포성산점,커피숍,2026-02-23,서울특별시 마포구 성산동 231-4,서울특별시 마포구 월드컵북로 73,1,35.43,2026-02-27 16:46:41,서울 마포구 월드컵북로 73,37.560317,126.915972
14570,푸디스트(주)서울시중구청카페,커피숍,2026-02-27,서울특별시 중구 예관동 120-1 중구청,서울특별시 중구 창경궁로 17,1,11.94,2026-02-27 17:15:09,서울 중구 창경궁로 17,37.564120,126.998010
14571,로우키,커피숍,2018-04-23,서울특별시 성동구 성수동2가 302-16,서울특별시 성동구 연무장3길 6,1,34.48,2026-02-27 18:04:45,서울 성동구 연무장3길 6,37.544196,127.051579

In [25]:
# 결측치 값에 한해서 lat, lng 다시 채우기 
mask = cafe_df["lat"].isna() & cafe_df["rd_addr"].notna()

cafe_df.loc[mask, ["kakao_addr", "lat", "lng"]] = (
    add_kakao_geocode(
        cafe_df.loc[mask, ["rd_addr"]].copy(),   # (조회 기준은 rd_addr)
        kakao_key,
        address_col="rd_addr",
        out_col = "kakao_addr"
    )[["kakao_addr", "lat", "lng"]]
    .to_numpy()
)

In [26]:
# 결측치 재확인
cafe_df["lat"] = pd.to_numeric(cafe_df["lat"], errors="coerce")
cafe_df["lng"] = pd.to_numeric(cafe_df["lng"], errors="coerce")
cafe_df[["kakao_addr", "lat", "lng"]].isna().sum()

kakao_addr    39
lat           39
lng           39
dtype: int64

In [27]:
cafe_df[cafe_df["lat"].isna()]

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated,kakao_addr,lat,lng
1,클럽알앤비,커피숍,2002-11-05,서울특별시 중구 장충동2가 189-2번지 (동대입구역322-13),NaN,<NA>,17.00,2002-11-05 00:00:00,NaN,NaN,NaN
13,할리스커피,커피숍,2005-08-16,서울특별시 종로구 공평동 55번지 지상1층,서울특별시 종로구 우정국로 24,1,NaN,2005-08-16 00:00:00,NaN,NaN,NaN
27,원타임편의점,커피숍,2007-07-25,서울특별시 용산구 한강로2가 351번지 (지상1층),NaN,1,3.30,2007-07-25 11:07:04,NaN,NaN,NaN
28,이디야중대용산병원점,커피숍,2007-08-13,서울특별시 용산구 한강로3가 65-207번지 (지상1층),NaN,1,7.70,2007-08-13 16:57:29,NaN,NaN,NaN
66,이디야커피동국대점,커피숍,2009-08-27,서울특별시 중구 충무로5가 79-2번지 (지상1층),서울특별시 중구 서애로 7,1,24.00,2009-08-27 13:38:53,NaN,NaN,NaN
128,로뎀나무,커피숍,2010-08-13,서울특별시 노원구 월계동 287-11번지,서울특별시 노원구 월계로 337,<NA>,33.93,2011-03-17 10:39:19,NaN,NaN,NaN
139,함초美,커피숍,2011-03-18,"서울특별시 동작구 대방동 501번지 대림쇼핑상가동 1-21,24호",NaN,<NA>,16.50,2011-05-20 10:50:14,NaN,NaN,NaN
141,커피향,커피숍,2007-03-06,"서울특별시 금천구 시흥동 999번지 - 29,31,51 지상2층 (시흥대로 446)",서울특별시 금천구 시흥대로71길 7,2,26.45,2011-06-08 10:29:44,NaN,NaN,NaN
158,훼미리마트(이화사거리점),커피숍,2011-07-26,서울특별시 종로구 연건동 196-11번지 1층,NaN,1,NaN,2011-07-26 16:27:15,NaN,NaN,NaN
159,와플반트 제일병원점,커피숍,2011-08-01,서울특별시 중구 묵정동 1-2번지 외래센터건물 지상3층,서울특별시 중구 서애로1길 17,3,12.87,2011-08-01 14:15:07,NaN,NaN,NaN
174,커피 콩콩,커피숍,2011-10-05,서울특별시 종로구 무악동 46-1418번지 (1층),서울특별시 종로구 통일로 238,1,NaN,2011-10-10 17:30:12,NaN,NaN,NaN
187,미스터브리즈(Mr. Breeze),커피숍,2011-09-28,서울특별시 서초구 양재동 14-19번지 1층,서울특별시 서초구 강남대로34길 6,1,91.95,2012-01-30 10:38:09,NaN,NaN,NaN
243,Coffee Farm(커피팜),커피숍,2012-07-23,서울특별시 종로구 숭인동 65-13번지,NaN,<NA>,NaN,2012-07-23 14:52:26,NaN,NaN,NaN
316,아지트,커피숍,2011-05-13,서울특별시 노원구 월계동 633-61번지 지상1층,서울특별시 노원구 월계로49길 28,1,26.40,2013-04-10 13:30:53,NaN,NaN,NaN
388,에스카페,커피숍,2013-03-21,서울특별시 동대문구 이문동 292-191번지 292-190,서울특별시 동대문구 이문로30길 11,1,12.80,2013-11-26 15:07:42,NaN,NaN,NaN
499,See U Bean,커피숍,2010-09-13,서울특별시 서초구 반포동 75번지 도시철도9호선 고속터미널역 B2층(반포19-11이...,NaN,2,34.57,2014-07-23 13:31:39,NaN,NaN,NaN
500,아로마리즈허브티하우스,커피숍,2009-11-09,서울특별시 서초구 반포동 75번지 9호선 고속터미널역사내 B2층(반포19-11이 맞음),NaN,2,21.36,2014-07-23 13:33:01,NaN,NaN,NaN
518,미로(MIRO),커피숍,2009-04-09,서울특별시 중구 신당동 294번지 청구역 지하3층,NaN,-1,18.00,2014-08-26 13:59:28,NaN,NaN,NaN
611,더베이크,커피숍,2011-02-10,서울특별시 중구 을지로1가 89-1번지 2호선 을리로입구역상가 지하1층,NaN,-1,17.57,2015-03-03 10:15:16,NaN,NaN,NaN
662,스윗 스토니,커피숍,2013-01-29,서울특별시 서초구 서초동 1335번지 무지개상가 1층 18호,서울특별시 서초구 효령로 401,1,30.46,2015-05-13 13:46:01,NaN,NaN,NaN
1221,젤라리소 경희궁자이점,커피숍,2017-04-11,서울특별시 종로구 평동 43번지 경희궁자이상가3블럭3112호,NaN,31,NaN,2017-04-11 16:09:30,NaN,NaN,NaN
1485,모스토니,커피숍,2016-04-28,서울특별시 중랑구 면목동 54-1번지,서울특별시 중랑구 용마산로86길 24,1,18.93,2017-12-06 09:43:22,NaN,NaN,NaN
1538,위드미 구로디지털역,커피숍,2012-08-03,서울특별시 구로구 구로동 124번지 구로디지털역 전기실 옆 2호선 지상1층 232-...,NaN,1,11.00,2018-01-17 12:51:36,NaN,NaN,NaN
1600,GS25 경희궁자이점,커피숍,2018-03-08,서울특별시 종로구 교남동 62-1번지 팰리스에비뉴4BL 4123호,NaN,41,NaN,2018-03-08 11:02:10,NaN,NaN,NaN
1999,백년두유,커피숍,2018-09-19,서울특별시 종로구 교남동 62-1번지 경희궁자이 팰리스에비뉴 4103호,NaN,41,NaN,2018-11-15 13:44:04,NaN,NaN,NaN
2319,휘경아뜰리에,커피숍,2019-06-12,서울특별시 동대문구 휘경동 268-1번지,서울특별시 동대문구 망우로 지하 55,-1,47.52,2019-06-12 10:01:17,NaN,NaN,NaN
4170,쉴만한물가,커피숍,2011-05-11,서울특별시 중랑구 면목동 584-34 1층,서울특별시 중랑구 면목로49길 71,1,76.36,2021-08-06 17:08:29,NaN,NaN,NaN
4544,바닷속 은하수,커피숍,2018-09-11,서울특별시 서대문구 홍은동 48-84 유진상가 내 서대문50플러스센터 2층,NaN,2,39.47,2021-11-15 13:29:44,NaN,NaN,NaN
5598,카페64(CAFE64),커피숍,2022-08-31,서울특별시 노원구 공릉동 산 230-30,서울특별시 노원구 화랑로 574,2,71.43,2022-08-31 15:30:02,NaN,NaN,NaN
6189,J.s coffee&snack (제이스 커피앤스낵),커피숍,2021-03-04,서울특별시 양천구 신월동 33-1 1층,서울특별시 양천구 남부순환로 284,1,24.00,2023-01-20 08:04:58,NaN,NaN,NaN
7204,더치프레소,커피숍,2023-03-17,서울특별시 용산구 용산동3가 1,서울특별시 용산구 이태원로 22,10,31.00,2023-05-16 10:15:09,NaN,NaN,NaN
9094,Cafe꽃,커피숍,2024-04-03,서울특별시 양천구 신월동 438-3,서울특별시 양천구 오목로 1,1,33.00,2024-04-03 17:01:06,NaN,NaN,NaN
9986,제이스카페(J.s cafe),커피숍,2024-07-26,서울특별시 강서구 외발산동 254-161층,NaN,1,21.00,2024-07-26 14:44:45,NaN,NaN,NaN
10044,더베이크,커피숍,2012-07-20,서울특별시 중구 을지로1가 89-1 지하철2호선 지하1층 을지로입구역 202-10호,NaN,-1,32.20,2024-08-02 11:20:15,NaN,NaN,NaN
10311,밥#,커피숍,2011-12-28,서울특별시 중구 을지로1가 89-1 지하철2호선 을지로입구역 지하1층,NaN,-1,21.18,2024-09-11 14:50:08,NaN,NaN,NaN
10337,카페 베리타스,커피숍,2013-03-20,서울특별시 중구 저동2가 82-1 1층,서울특별시 중구 삼일대로10길 28,1,18.00,2024-09-11 15:24:11,NaN,NaN,NaN
10425,아이갓에브리씽 용산점,커피숍,2023-02-20,서울특별시 용산구 용산동3가 1,서울특별시 용산구 이태원로 22,-1,20.30,2024-09-26 09:42:39,NaN,NaN,NaN
11902,카페어울림(스템커피),커피숍,2023-04-21,서울특별시 용산구 용산동5가 2-1,서울특별시 용산구 한강대로38길 21,1,339.15,2025-04-21 16:52:04,NaN,NaN,NaN
12959,프레델 한전남서울카페,커피숍,2025-08-26,서울특별시 영등포구 여의도동 21,서울특별시 영등포구 여의동로7길 5,5,22.80,2025-08-26 11:24:32,NaN,NaN,NaN

In [28]:
cafe_df.dropna(subset=["kakao_addr"], inplace=True)
cafe_df

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated,kakao_addr,lat,lng
0,베레베레,커피숍,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19,<NA>,NaN,2002-09-19 00:00:00,서울 광진구 능동로13길 19,37.542885,127.070832
2,덕수궁전통차전문,커피숍,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),서울특별시 중구 서소문로 109,2,46.28,2003-01-22 00:00:00,서울 중구 서소문로 109,37.563062,126.973280
3,엘빠소,커피숍,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18,<NA>,NaN,2003-05-31 00:00:00,서울 종로구 성균관로 18,37.584406,126.997641
4,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,서울특별시 종로구 세종대로 188,1,NaN,2003-11-21 00:00:00,서울 종로구 세종대로 188,37.573190,126.977831
5,본솔카페,커피숍,2004-01-17,서울특별시 용산구 청파동2가 64-13번지 청파3가 115-12 (지상1층),서울특별시 용산구 청파로47길 71,1,13.80,2004-01-17 00:00:00,서울 용산구 청파로47길 71,37.544840,126.966455
...,...,...,...,...,...,...,...,...,...,...,...
14567,카페 라희,커피숍,2026-02-27,서울특별시 강동구 길동 474 GS강동자이아파트,서울특별시 강동구 천호대로199길 10,1,25.20,2026-02-27 15:32:32,서울 강동구 천호대로 1239,37.537861,127.148277
14568,달콤한 오늘,커피숍,2026-02-27,서울특별시 강서구 마곡동 739-3 에스비타운,서울특별시 강서구 마곡중앙5로 81,1,62.33,2026-02-27 16:28:56,서울 강서구 마곡서1로 111-12,37.566787,126.817788
14569,쿠즈코커피 마포성산점,커피숍,2026-02-23,서울특별시 마포구 성산동 231-4,서울특별시 마포구 월드컵북로 73,1,35.43,2026-02-27 16:46:41,서울 마포구 월드컵북로 73,37.560317,126.915972
14570,푸디스트(주)서울시중구청카페,커피숍,2026-02-27,서울특별시 중구 예관동 120-1 중구청,서울특별시 중구 창경궁로 17,1,11.94,2026-02-27 17:15:09,서울 중구 창경궁로 17,37.564120,126.998010
14571,로우키,커피숍,2018-04-23,서울특별시 성동구 성수동2가 302-16,서울특별시 성동구 연무장3길 6,1,34.48,2026-02-27 18:04:45,서울 성동구 연무장3길 6,37.544196,127.051579

### 유동인구 데이터 활용을 위한 지역 코드 추가

#### 상권 코드 추가
- 상권/상권 배후지/행정동 코드는 유동인구를 파악하기 위함
- 유동인구 데이터가 없다면, 카페 입지 분석이 어려움.
- 따라서 결측이가 있을 경우, **상권 → 상권 배후지 → 행정동** 순으로 유동 인구 정보를 활용해야 함

In [ ]:
# 결측치 확인
cafe_df[["lat", "lng"]].isna().sum()

lat    0
lng    0
dtype: int64

In [ ]:
# 1) cafe_df -> GeoDataFrame (실제 좌표계: WGS84)
cafe_gdf = gpd.GeoDataFrame(
    cafe_df.copy(),
    geometry=gpd.points_from_xy(cafe_df["lng"], cafe_df["lat"]),
    crs="EPSG:4326"
)

# 2) 상권 shp 로드 (좌표계: EPSG:5181)
trdar_gdf = gpd.read_file(
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-상권).zip"
)
# → 이 파일은 EPSG:5181이 이미 설정되어 있어야 함

# 3) 좌표계 통일 (cafe를 5181로 변환)
'''
폴리곤(상권)은 꼭짓점이 많아서 변환 시 오차가 누적될 수 있으므로 shp(5181) 기준으로 맞춤
'''
cafe_gdf = cafe_gdf.to_crs("EPSG:5181")  # shp 기준으로 맞춤

# 4) 공간조인
trdar_cols = ["TRDAR_CD", "geometry"]
joined = gpd.sjoin(
    cafe_gdf,
    trdar_gdf[trdar_cols],
    how="left",
    predicate="within"
)

# 5) 원본 인덱스 기준으로 TRDAR_CD 붙이기
cafe_df = cafe_df.copy()
cafe_df.loc[joined.index, "trdar_cd"] = joined["TRDAR_CD"].values

In [ ]:
cafe_df.head()

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated,kakao_addr,lat,lng,alley_trda,trdar_cd,adstrd_cd,flpop_type
0,베레베레,커피숍,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19,<NA>,NaN,2002-09-19,서울 광진구 능동로13길 19,37.542885,127.070832,NaN,3120053,11215710,T
1,덕수궁전통차전문,커피숍,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),서울특별시 중구 서소문로 109,2,46.28,2003-01-22,서울 중구 서소문로 109,37.563062,126.973280,NaN,3120020,11140520,T
2,엘빠소,커피숍,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18,<NA>,NaN,2003-05-31,서울 종로구 성균관로 18,37.584406,126.997641,3110021,3110021,11110650,T
3,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,서울특별시 종로구 세종대로 188,1,NaN,2003-11-21,서울 종로구 세종대로 188,37.573190,126.977831,NaN,NaN,11110615,A
4,본솔카페,커피숍,2004-01-17,서울특별시 용산구 청파동2가 64-13번지 청파3가 115-12 (지상1층),서울특별시 용산구 청파로47길 71,1,13.80,2004-01-17,서울 용산구 청파로47길 71,37.544840,126.966455,3110064,3110069,11170555,T

In [106]:
# NaN 비율 확인
null_cnt = cafe_df["trdar_cd"].isna().sum()
total = len(cafe_df)
print(f"상권 미매칭: {null_cnt}/{total} ({null_cnt/total*100:.1f}%)")

상권 미매칭: 3603/14536 (24.8%)

#### 상권배후지 코드 추가

In [111]:
print(trdar_gdf.columns.tolist())

['ALLEY_TRDA', 'ALLEY_TR_1', 'XCNTS_VALU', 'YDNTS_VALU', 'SIGNGU_CD', 'SIGNGU_CD_', 'ADSTRD_CD', 'ADSTRD_CD_', 'RELM_AR', 'geometry']

In [ ]:
# # 1) cafe_df -> GeoDataFrame (실제 좌표계: WGS84)
# cafe_gdf = gpd.GeoDataFrame(
#     cafe_df.copy(),
#     geometry=gpd.points_from_xy(cafe_df["lng"], cafe_df["lat"]),
#     crs="EPSG:4326"
# )

# 2) 상권 shp 로드 (좌표계: EPSG:5181)
trdar_gdf = gpd.read_file(
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-상권배후지).zip"
)
# → 이 파일은 EPSG:5181이 이미 설정되어 있어야 함

# 3) 좌표계 통일 (cafe를 5181로 변환)
'''
폴리곤(상권)은 꼭짓점이 많아서 변환 시 오차가 누적될 수 있으므로 shp(5181) 기준으로 맞춤
'''
cafe_gdf = cafe_gdf.to_crs("EPSG:5181")  # shp 기준으로 맞춤

# 4) 공간조인
trdar_cols = ["ALLEY_TRDA", "geometry"]
joined = gpd.sjoin(
    cafe_gdf,
    trdar_gdf[trdar_cols],
    how="left",
    predicate="within"
)

# 5) 원본 인덱스 기준으로 TRDAR_CD 붙이기
cafe_df = cafe_df.copy()
cafe_df.loc[joined.index, "alley_trda"] = joined["ALLEY_TRDA"].values

#### 행정동 코드 추가

In [ ]:
# # 1) cafe_df -> GeoDataFrame (실제 좌표계: WGS84)
# cafe_gdf = gpd.GeoDataFrame(
#     cafe_df.copy(),
#     geometry=gpd.points_from_xy(cafe_df["lng"], cafe_df["lat"]),
#     crs="EPSG:4326"
# )

# 2) 상권 shp 로드 (좌표계: EPSG:5181)
trdar_gdf = gpd.read_file(
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-행정동).zip"
)
# → 이 파일은 EPSG:5181이 이미 설정되어 있어야 함

# 3) 좌표계 통일 (cafe를 5181로 변환)
'''
폴리곤(상권)은 꼭짓점이 많아서 변환 시 오차가 누적될 수 있으므로 shp(5181) 기준으로 맞춤
'''
cafe_gdf = cafe_gdf.to_crs("EPSG:5181")  # shp 기준으로 맞춤

# 4) 공간조인
trdar_cols = ["ADSTRD_CD", "geometry"]
joined = gpd.sjoin(
    cafe_gdf,
    trdar_gdf[trdar_cols],
    how="left",
    predicate="within"
)

# 5) 원본 인덱스 기준으로 adstrd_cd 붙이기
cafe_df.loc[joined.index, "adstrd_cd"] = joined["ADSTRD_CD"].values
cafe_df.head()

,nm,type,apv_date,addr,rd_addr,floor,sitearea,last_updated,kakao_addr,lat,lng,alley_trda,trdar_cd,adstrd_cd
0,베레베레,커피숍,2002-09-19,서울특별시 광진구 화양동 11-2번지,서울특별시 광진구 능동로13길 19,<NA>,NaN,2002-09-19,서울 광진구 능동로13길 19,37.542885,127.070832,NaN,3120053,11215710
2,덕수궁전통차전문,커피숍,2003-01-16,서울특별시 중구 서소문동 54-1번지 (2층),서울특별시 중구 서소문로 109,2,46.28,2003-01-22,서울 중구 서소문로 109,37.563062,126.973280,NaN,3120020,11140520
3,엘빠소,커피숍,2003-05-31,서울특별시 종로구 명륜2가 143-9번지,서울특별시 종로구 성균관로 18,<NA>,NaN,2003-05-31,서울 종로구 성균관로 18,37.584406,126.997641,3110021,3110021,11110650
4,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울특별시 종로구 세종로 82-14번지 지상1층,서울특별시 종로구 세종대로 188,1,NaN,2003-11-21,서울 종로구 세종대로 188,37.573190,126.977831,NaN,NaN,11110615
5,본솔카페,커피숍,2004-01-17,서울특별시 용산구 청파동2가 64-13번지 청파3가 115-12 (지상1층),서울특별시 용산구 청파로47길 71,1,13.80,2004-01-17,서울 용산구 청파로47길 71,37.544840,126.966455,3110064,3110069,11170555

#### 한 번에 추가하기

In [29]:
# GeoDataFrame 한 번만 생성
cafe_gdf = gpd.GeoDataFrame(
    cafe_df.copy(),
    geometry=gpd.points_from_xy(cafe_df["lng"], cafe_df["lat"]),
    crs="EPSG:4326"
)

# 각각 호출
cafe_df = spatial_join_code(cafe_df, cafe_gdf,
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-상권).zip",
    "TRDAR_CD", "trdar_cd")

cafe_df = spatial_join_code(cafe_df, cafe_gdf,
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-상권배후지).zip",
    "ALLEY_TRDA", "alley_trda")

cafe_df = spatial_join_code(cafe_df, cafe_gdf,
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-행정동).zip",
    "ADSTRD_CD", "adstrd_cd")

In [30]:
cafe_df[["trdar_cd", "alley_trda", "adstrd_cd"]].isna().sum()

trdar_cd      3601
alley_trda    4194
adstrd_cd        0
dtype: int64

#### 코드 type 추가 및 코드 값 처리

In [31]:
# 1) flpop_type 컬럼 생성
cafe_df["flpop_type"] = "A"  # 기본값
cafe_df.loc[cafe_df["alley_trda"].notna(), "flpop_type"] = "T"
cafe_df.loc[cafe_df["trdar_cd"].notna(), "flpop_type"] = "T"

# 2) trdar_cd 빈 값을 alley_trda로 대체
'''
상권-유동인구데이터, 상권배후지-유동인구데이터는 같은 API를 사용하므로 별도로 구분할 필요가 없음
'''
mask = cafe_df["trdar_cd"].isna() & cafe_df["alley_trda"].notna()
cafe_df.loc[mask, "trdar_cd"] = cafe_df.loc[mask, "alley_trda"]

### 저장 용도 dataframe 생성

In [32]:
# 1) 저장할 데이터만 추출
save_cafe_df = cafe_df[['nm', 'type', 'apv_date', 'kakao_addr', 'floor', 'sitearea',
                        'lat', 'lng', 'flpop_type', 'trdar_cd', 'adstrd_cd']]

# 2) 열이름 재변경
save_cafe_df = save_cafe_df.rename(columns={'kakao_addr': 'addr'})
save_cafe_df.head()

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,adstrd_cd
0,베레베레,커피숍,2002-09-19,서울 광진구 능동로13길 19,<NA>,NaN,37.542885,127.070832,T,3120053,11215710
2,덕수궁전통차전문,커피숍,2003-01-16,서울 중구 서소문로 109,2,46.28,37.563062,126.973280,T,3120020,11140520
3,엘빠소,커피숍,2003-05-31,서울 종로구 성균관로 18,<NA>,NaN,37.584406,126.997641,T,3110021,11110650
4,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울 종로구 세종대로 188,1,NaN,37.573190,126.977831,A,NaN,11110615
5,본솔카페,커피숍,2004-01-17,서울 용산구 청파로47길 71,1,13.80,37.544840,126.966455,T,3110069,11170555

In [33]:
# index 재설정
save_cafe_df.reset_index(drop=True, inplace=True) # index 재설정
save_cafe_df

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,adstrd_cd
0,베레베레,커피숍,2002-09-19,서울 광진구 능동로13길 19,<NA>,NaN,37.542885,127.070832,T,3120053,11215710
1,덕수궁전통차전문,커피숍,2003-01-16,서울 중구 서소문로 109,2,46.28,37.563062,126.973280,T,3120020,11140520
2,엘빠소,커피숍,2003-05-31,서울 종로구 성균관로 18,<NA>,NaN,37.584406,126.997641,T,3110021,11110650
3,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울 종로구 세종대로 188,1,NaN,37.573190,126.977831,A,NaN,11110615
4,본솔카페,커피숍,2004-01-17,서울 용산구 청파로47길 71,1,13.80,37.544840,126.966455,T,3110069,11170555
...,...,...,...,...,...,...,...,...,...,...,...
14528,카페 라희,커피숍,2026-02-27,서울 강동구 천호대로 1239,1,25.20,37.537861,127.148277,T,3111077,11740685
14529,달콤한 오늘,커피숍,2026-02-27,서울 강서구 마곡서1로 111-12,1,62.33,37.566787,126.817788,T,3110639,11500630
14530,쿠즈코커피 마포성산점,커피숍,2026-02-23,서울 마포구 월드컵북로 73,1,35.43,37.560317,126.915972,T,3110557,11440720
14531,푸디스트(주)서울시중구청카페,커피숍,2026-02-27,서울 중구 창경궁로 17,1,11.94,37.564120,126.998010,T,3120034,11140590
14532,로우키,커피숍,2018-04-23,서울 성동구 연무장3길 6,1,34.48,37.544196,127.051579,T,3110131,11200690

# 서울시 상권분석서비스(길단위인구-상권/상권배후지)
카페 데이터(cafe.csv)에서 flpop_type이 T 인 경우 사용

## 데이터 불러오기

In [148]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "300"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/VwsmTrdarFlpopQq/{start_index}/{end_index}/"

response = requests.get(url)
print(response.content.decode('utf-8'))

{"VwsmTrdarFlpopQq":{"list_total_count":44536,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120196","TRDAR_CD_NM":"서울세관","TOT_FLPOP_CO":700352.0,"ML_FLPOP_CO":359756.0,"FML_FLPOP_CO":340594.0,"AGRDE_10_FLPOP_CO":44888.0,"AGRDE_20_FLPOP_CO":140916.0,"AGRDE_30_FLPOP_CO":182543.0,"AGRDE_40_FLPOP_CO":136481.0,"AGRDE_50_FLPOP_CO":80938.0,"AGRDE_60_ABOVE_FLPOP_CO":114586.0,"TMZON_00_06_FLPOP_CO":104869.0,"TMZON_06_11_FLPOP_CO":139300.0,"TMZON_11_14_FLPOP_CO":125560.0,"TMZON_14_17_FLPOP_CO":124427.0,"TMZON_17_21_FLPOP_CO":136567.0,"TMZON_21_24_FLPOP_CO":69630.0,"MON_FLPOP_CO":105462.0,"TUES_FLPOP_CO":106420.0,"WED_FLPOP_CO":110506.0,"THUR_FLPOP_CO":115069.0,"FRI_FLPOP_CO":111466.0,"SAT_FLPOP_CO":80262.0,"SUN_FLPOP_CO":71166.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120197","TRDAR_CD_NM":"역삼역","TOT_FLPOP_CO":5123674.0,"ML_FLPOP_CO":2802851.0,"FML_FLPOP_CO":2320823.0,"AGRDE_10_FLPOP_CO":189741.0,"AGRDE_20_FLPOP_CO":1248859.0,"AGRDE_30_FLPOP_CO":1489998.0,"AGRDE_40_FLPOP_CO":979780.0,"AGRDE_50_FLPOP_CO":573746.0,"AGRDE_60_ABOVE_FLPOP_CO":641551.0,"TMZON_00_06_FLPOP_CO":616055.0,"TMZON_06_11_FLPOP_CO":1030772.0,"TMZON_11_14_FLPOP_CO":1009349.0,"TMZON_14_17_FLPOP_CO":1029695.0,"TMZON_17_21_FLPOP_CO":1002107.0,"TMZON_21_24_FLPOP_CO":435697.0,"MON_FLPOP_CO":824944.0,"TUES_FLPOP_CO":821220.0,"WED_FLPOP_CO":856904.0,"THUR_FLPOP_CO":902709.0,"FRI_FLPOP_CO":858099.0,"SAT_FLPOP_CO":480318.0,"SUN_FLPOP_CO":379483.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120198","TRDAR_CD_NM":"구역삼세무서","TOT_FLPOP_CO":2735527.0,"ML_FLPOP_CO":1437771.0,"FML_FLPOP_CO":1297755.0,"AGRDE_10_FLPOP_CO":170295.0,"AGRDE_20_FLPOP_CO":663373.0,"AGRDE_30_FLPOP_CO":738048.0,"AGRDE_40_FLPOP_CO":472682.0,"AGRDE_50_FLPOP_CO":291801.0,"AGRDE_60_ABOVE_FLPOP_CO":399329.0,"TMZON_00_06_FLPOP_CO":586259.0,"TMZON_06_11_FLPOP_CO":572563.0,"TMZON_11_14_FLPOP_CO":414724.0,"TMZON_14_17_FLPOP_CO":406033.0,"TMZON_17_21_FLPOP_CO":459925.0,"TMZON_21_24_FLPOP_CO":296022.0,"MON_FLPOP_CO":414386.0,"TUES_FLPOP_CO":410294.0,"WED_FLPOP_CO":421127.0,"THUR_FLPOP_CO":434270.0,"FRI_FLPOP_CO":419333.0,"SAT_FLPOP_CO":323450.0,"SUN_FLPOP_CO":312668.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120199","TRDAR_CD_NM":"경복아파트교차로","TOT_FLPOP_CO":505522.0,"ML_FLPOP_CO":259538.0,"FML_FLPOP_CO":245984.0,"AGRDE_10_FLPOP_CO":27105.0,"AGRDE_20_FLPOP_CO":109292.0,"AGRDE_30_FLPOP_CO":147631.0,"AGRDE_40_FLPOP_CO":93738.0,"AGRDE_50_FLPOP_CO":54341.0,"AGRDE_60_ABOVE_FLPOP_CO":73416.0,"TMZON_00_06_FLPOP_CO":97271.0,"TMZON_06_11_FLPOP_CO":107730.0,"TMZON_11_14_FLPOP_CO":82266.0,"TMZON_14_17_FLPOP_CO":80078.0,"TMZON_17_21_FLPOP_CO":87825.0,"TMZON_21_24_FLPOP_CO":50350.0,"MON_FLPOP_CO":75708.0,"TUES_FLPOP_CO":74958.0,"WED_FLPOP_CO":77918.0,"THUR_FLPOP_CO":79473.0,"FRI_FLPOP_CO":77901.0,"SAT_FLPOP_CO":62424.0,"SUN_FLPOP_CO":57140.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120200","TRDAR_CD_NM":"학동사거리","TOT_FLPOP_CO":1349117.0,"ML_FLPOP_CO":632069.0,"FML_FLPOP_CO":717048.0,"AGRDE_10_FLPOP_CO":97382.0,"AGRDE_20_FLPOP_CO":326760.0,"AGRDE_30_FLPOP_CO":360568.0,"AGRDE_40_FLPOP_CO":232187.0,"AGRDE_50_FLPOP_CO":138687.0,"AGRDE_60_ABOVE_FLPOP_CO":193534.0,"TMZON_00_06_FLPOP_CO":177072.0,"TMZON_06_11_FLPOP_CO":237250.0,"TMZON_11_14_FLPOP_CO":249002.0,"TMZON_14_17_FLPOP_CO":256961.0,"TMZON_17_21_FLPOP_CO":289717.0,"TMZON_21_24_FLPOP_CO":139114.0,"MON_FLPOP_CO":181562.0,"TUES_FLPOP_CO":193744.0,"WED_FLPOP_CO":203127.0,"THUR_FLPOP_CO":212952.0,"FRI_FLPOP_CO":214384.0,"SAT_FLPOP_CO":195706.0,"SUN_FLPOP_CO":147642.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120201","TRDAR_CD_NM":"도곡1동","TOT_FLPOP_CO":1129303.0,"ML_FLPOP_CO":549882.0,"FML_FLPOP_CO":579421.0,"AGRDE_10_FLPOP_CO":132362.0,"AGRDE_20_FLPOP_CO":194417.0,"AGRDE_30_FLPOP_CO":247036.0,"AGRDE_40_FLPOP_CO":195621.0,"AGRDE_50_FLPOP_CO":149719.0,"AGRDE_60_ABOVE_FLPOP_CO":210148.0,"TMZON_00_06_FLPOP_CO":218657.0,"TMZON_06_11_FLPOP_CO":239613.0,"TMZON_11_14_FLPOP_CO":174725.0,"TMZON_14_17_FLPOP_CO":176279.0,"TMZON_17_21_FLPOP_CO":200328.0,"TMZON_21_24_FLPOP_CO":119699.0,"MON_FLPOP_CO":171045.0,"TUES_FLPOP_CO":166836.0,"WED_FLPOP_CO":169560.0,"THUR_FLPOP_CO":172982.0,"FRI_FLPOP_CO":169667.0,"SAT_FLPOP_CO":142769.0,"SUN_FLPOP_CO":136440.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120202","TRDAR_CD_NM":"압구정로데오역(압구정로데오)","TOT_FLPOP_CO":2473598.0,"ML_FLPOP_CO":1088368.0,"FML_FLPOP_CO":1385231.0,"AGRDE_10_FLPOP_CO":215005.0,"AGRDE_20_FLPOP_CO":546096.0,"AGRDE_30_FLPOP_CO":576031.0,"AGRDE_40_FLPOP_CO":423511.0,"AGRDE_50_FLPOP_CO":278967.0,"AGRDE_60_ABOVE_FLPOP_CO":433988.0,"TMZON_00_06_FLPOP_CO":329995.0,"TMZON_06_11_FLPOP_CO":417106.0,"TMZON_11_14_FLPOP_CO":446124.0,"TMZON_14_17_FLPOP_CO":476893.0,"TMZON_17_21_FLPOP_CO":547326.0,"TMZON_21_24_FLPOP_CO":256154.0,"MON_FLPOP_CO":342477.0,"TUES_FLPOP_CO":353803.0,"WED_FLPOP_CO":368909.0,"THUR_FLPOP_CO":386306.0,"FRI_FLPOP_CO":397977.0,"SAT_FLPOP_CO":349380.0,"SUN_FLPOP_CO":274748.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120203","TRDAR_CD_NM":"강남구청역","TOT_FLPOP_CO":2297199.0,"ML_FLPOP_CO":1105923.0,"FML_FLPOP_CO":1191278.0,"AGRDE_10_FLPOP_CO":233278.0,"AGRDE_20_FLPOP_CO":437673.0,"AGRDE_30_FLPOP_CO":544747.0,"AGRDE_40_FLPOP_CO":425190.0,"AGRDE_50_FLPOP_CO":266973.0,"AGRDE_60_ABOVE_FLPOP_CO":389338.0,"TMZON_00_06_FLPOP_CO":345495.0,"TMZON_06_11_FLPOP_CO":446015.0,"TMZON_11_14_FLPOP_CO":390014.0,"TMZON_14_17_FLPOP_CO":401324.0,"TMZON_17_21_FLPOP_CO":472838.0,"TMZON_21_24_FLPOP_CO":241513.0,"MON_FLPOP_CO":338437.0,"TUES_FLPOP_CO":342967.0,"WED_FLPOP_CO":356364.0,"THUR_FLPOP_CO":369122.0,"FRI_FLPOP_CO":360033.0,"SAT_FLPOP_CO":280016.0,"SUN_FLPOP_CO":250260.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120204","TRDAR_CD_NM":"르네상스호텔사거리","TOT_FLPOP_CO":2000759.0,"ML_FLPOP_CO":1034732.0,"FML_FLPOP_CO":966027.0,"AGRDE_10_FLPOP_CO":118611.0,"AGRDE_20_FLPOP_CO":376811.0,"AGRDE_30_FLPOP_CO":526348.0,"AGRDE_40_FLPOP_CO":403488.0,"AGRDE_50_FLPOP_CO":262467.0,"AGRDE_60_ABOVE_FLPOP_CO":313031.0,"TMZON_00_06_FLPOP_CO":227499.0,"TMZON_06_11_FLPOP_CO":433721.0,"TMZON_11_14_FLPOP_CO":400595.0,"TMZON_14_17_FLPOP_CO":396622.0,"TMZON_17_21_FLPOP_CO":379969.0,"TMZON_21_24_FLPOP_CO":162354.0,"MON_FLPOP_CO":323266.0,"TUES_FLPOP_CO":318785.0,"WED_FLPOP_CO":331863.0,"THUR_FLPOP_CO":347475.0,"FRI_FLPOP_CO":330368.0,"SAT_FLPOP_CO":198932.0,"SUN_FLPOP_CO":150070.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120210","TRDAR_CD_NM":"선릉역","TOT_FLPOP_CO":5144960.0,"ML_FLPOP_CO":2583895.0,"FML_FLPOP_CO":2561065.0,"AGRDE_10_FLPOP_CO":412881.0,"AGRDE_20_FLPOP_CO":1006240.0,"AGRDE_30_FLPOP_CO":1301794.0,"AGRDE_40_FLPOP_CO":1008881.0,"AGRDE_50_FLPOP_CO":653742.0,"AGRDE_60_ABOVE_FLPOP_CO":761423.0,"TMZON_00_06_FLPOP_CO":785031.0,"TMZON_06_11_FLPOP_CO":1043334.0,"TMZON_11_14_FLPOP_CO":923143.0,"TMZON_14_17_FLPOP_CO":909763.0,"TMZON_17_21_FLPOP_CO":983641.0,"TMZON_21_24_FLPOP_CO":500047.0,"MON_FLPOP_CO":791877.0,"TUES_FLPOP_CO":789641.0,"WED_FLPOP_CO":818092.0,"THUR_FLPOP_CO":858679.0,"FRI_FLPOP_CO":830563.0,"SAT_FLPOP_CO":584174.0,"SUN_FLPOP_CO":471935.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120205","TRDAR_CD_NM":"매봉역","TOT_FLPOP_CO":574866.0,"ML_FLPOP_CO":280923.0,"FML_FLPOP_CO":293944.0,"AGRDE_10_FLPOP_CO":45130.0,"AGRDE_20_FLPOP_CO":91702.0,"AGRDE_30_FLPOP_CO":114648.0,"AGRDE_40_FLPOP_CO":101655.0,"AGRDE_50_FLPOP_CO":85834.0,"AGRDE_60_ABOVE_FLPOP_CO":135899.0,"TMZON_00_06_FLPOP_CO":85738.0,"TMZON_06_11_FLPOP_CO":115763.0,"TMZON_11_14_FLPOP_CO":100724.0,"TMZON_14_17_FLPOP_CO":103593.0,"TMZON_17_21_FLPOP_CO":113585.0,"TMZON_21_24_FLPOP_CO":55466.0,"MON_FLPOP_CO":87380.0,"TUES_FLPOP_CO":87473.0,"WED_FLPOP_CO":89380.0,"THUR_FLPOP_CO":92839.0,"FRI_FLPOP_CO":90039.0,"SAT_FLPOP_CO":66422.0,"SUN_FLPOP_CO":61333.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120206","TRDAR_CD_NM":"개나리아파트","TOT_FLPOP_CO":1245072.0,"ML_FLPOP_CO":586476.0,"FML_FLPOP_CO":658595.0,"AGRDE_10_FLPOP_CO":156621.0,"AGRDE_20_FLPOP_CO":196199.0,"AGRDE_30_FLPOP_CO":257267.0,"AGRDE_40_FLPOP_CO":244887.0,"AGRDE_50_FLPOP_CO":159149.0,"AGRDE_60_ABOVE_FLPOP_CO":230948.0,"TMZON_00_06_FLPOP_CO":270157.0,"TMZON_06_11_FLPOP_CO":279194.0,"TMZON_11_14_FLPOP_CO":192617.0,"TMZON_14_17_FLPOP_CO":182734.0,"TMZON_17_21_FLPOP_CO":193363.0,"TMZON_21_24_FLPOP_CO":127007.0,"MON_FLPOP_CO":186636.0,"TUES_FLPOP_CO":184513.0,"WED_FLPOP_CO":189866.0,"THUR_FLPOP_CO":192114.0,"FRI_FLPOP_CO":185400.0,"SAT_FLPOP_CO":154633.0,"SUN_FLPOP_CO":151910.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120207","TRDAR_CD_NM":"선정릉역","TOT_FLPOP_CO":2385287.0,"ML_FLPOP_CO":1159427.0,"FML_FLPOP_CO":1225859.0,"AGRDE_10_FLPOP_CO":294646.0,"AGRDE_20_FLPOP_CO":421930.0,"AGRDE_30_FLPOP_CO":553319.0,"AGRDE_40_FLPOP_CO":448401.0,"AGRDE_50_FLPOP_CO":260511.0,"AGRDE_60_ABOVE_FLPOP_CO":406482.0,"TMZON_00_06_FLPOP_CO":505544.0,"TMZON_06_11_FLPOP_CO":498933.0,"TMZON_11_14_FLPOP_CO":357299.0,"TMZON_14_17_FLPOP_CO":359542.0,"TMZON_17_21_FLPOP_CO":409171.0,"TMZON_21_24_FLPOP_CO":254799.0,"MON_FLPOP_CO":353598.0,"TUES_FLPOP_CO":353634.0,"WED_FLPOP_CO":362133.0,"THUR_FLPOP_CO":370893.0,"FRI_FLPOP_CO":361237.0,"SAT_FLPOP_CO":302676.0,"SUN_FLPOP_CO":281115.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120208","TRDAR_CD_NM":"청담사거리(청담동명품거리)","TOT_FLPOP_CO":1538034.0,"ML_FLPOP_CO":701404.0,"FML_FLPOP_CO":836630.0,"AGRDE_10_FLPOP_CO":162280.0,"AGRDE_20_FLPOP_CO":281386.0,"AGRDE_30_FLPOP_CO":341582.0,"AGRDE_40_FLPOP_CO":270096.0,"AGRDE_50_FLPOP_CO":193522.0,"AGRDE_60_ABOVE_FLPOP_CO":289169.0,"TMZON_00_06_FLPOP_CO":283065.0,"TMZON_06_11_FLPOP_CO":309176.0,"TMZON_11_14_FLPOP_CO":250326.0,"TMZON_14_17_FLPOP_CO":253256.0,"TMZON_17_21_FLPOP_CO":279746.0,"TMZON_21_24_FLPOP_CO":162464.0,"MON_FLPOP_CO":214608.0,"TUES_FLPOP_CO":223755.0,"WED_FLPOP_CO":230292.0,"THUR_FLPOP_CO":238288.0,"FRI_FLPOP_CO":240993.0,"SAT_FLPOP_CO":211144.0,"SUN_FLPOP_CO":178954.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120209","TRDAR_CD_NM":"강남구청(청담역_8번, 강남세무서)","TOT_FLPOP_CO":852322.0,"ML_FLPOP_CO":372920.0,"FML_FLPOP_CO":479402.0,"AGRDE_10_FLPOP_CO":129631.0,"AGRDE_20_FLPOP_CO":108131.0,"AGRDE_30_FLPOP_CO":156914.0,"AGRDE_40_FLPOP_CO":154616.0,"AGRDE_50_FLPOP_CO":109587.0,"AGRDE_60_ABOVE_FLPOP_CO":193442.0,"TMZON_00_06_FLPOP_CO":139014.0,"TMZON_06_11_FLPOP_CO":176396.0,"TMZON_11_14_FLPOP_CO":144460.0,"TMZON_14_17_FLPOP_CO":148179.0,"TMZON_17_21_FLPOP_CO":163673.0,"TMZON_21_24_FLPOP_CO":80601.0,"MON_FLPOP_CO":126333.0,"TUES_FLPOP_CO":126251.0,"WED_FLPOP_CO":129374.0,"THUR_FLPOP_CO":132577.0,"FRI_FLPOP_CO":130374.0,"SAT_FLPOP_CO":110709.0,"SUN_FLPOP_CO":96702.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120216","TRDAR_CD_NM":"경기고교사거리(경기고교앞사거리)","TOT_FLPOP_CO":223780.0,"ML_FLPOP_CO":111682.0,"FML_FLPOP_CO":112098.0,"AGRDE_10_FLPOP_CO":22803.0,"AGRDE_20_FLPOP_CO":30724.0,"AGRDE_30_FLPOP_CO":47824.0,"AGRDE_40_FLPOP_CO":41231.0,"AGRDE_50_FLPOP_CO":32882.0,"AGRDE_60_ABOVE_FLPOP_CO":48314.0,"TMZON_00_06_FLPOP_CO":24810.0,"TMZON_06_11_FLPOP_CO":44708.0,"TMZON_11_14_FLPOP_CO":42290.0,"TMZON_14_17_FLPOP_CO":42950.0,"TMZON_17_21_FLPOP_CO":48519.0,"TMZON_21_24_FLPOP_CO":20499.0,"MON_FLPOP_CO":33719.0,"TUES_FLPOP_CO":33873.0,"WED_FLPOP_CO":34912.0,"THUR_FLPOP_CO":35816.0,"FRI_FLPOP_CO":35251.0,"SAT_FLPOP_CO":27558.0,"SUN_FLPOP_CO":22652.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120211","TRDAR_CD_NM":"도성초등학교","TOT_FLPOP_CO":700638.0,"ML_FLPOP_CO":306060.0,"FML_FLPOP_CO":394578.0,"AGRDE_10_FLPOP_CO":168015.0,"AGRDE_20_FLPOP_CO":98409.0,"AGRDE_30_FLPOP_CO":106880.0,"AGRDE_40_FLPOP_CO":133174.0,"AGRDE_50_FLPOP_CO":82761.0,"AGRDE_60_ABOVE_FLPOP_CO":111399.0,"TMZON_00_06_FLPOP_CO":107830.0,"TMZON_06_11_FLPOP_CO":138437.0,"TMZON_11_14_FLPOP_CO":113318.0,"TMZON_14_17_FLPOP_CO":119026.0,"TMZON_17_21_FLPOP_CO":148510.0,"TMZON_21_24_FLPOP_CO":73516.0,"MON_FLPOP_CO":100483.0,"TUES_FLPOP_CO":98824.0,"WED_FLPOP_CO":101865.0,"THUR_FLPOP_CO":103850.0,"FRI_FLPOP_CO":103929.0,"SAT_FLPOP_CO":101479.0,"SUN_FLPOP_CO":90208.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120212","TRDAR_CD_NM":"한티역","TOT_FLPOP_CO":1023481.0,"ML_FLPOP_CO":451920.0,"FML_FLPOP_CO":571561.0,"AGRDE_10_FLPOP_CO":291185.0,"AGRDE_20_FLPOP_CO":112755.0,"AGRDE_30_FLPOP_CO":117269.0,"AGRDE_40_FLPOP_CO":207005.0,"AGRDE_50_FLPOP_CO":141242.0,"AGRDE_60_ABOVE_FLPOP_CO":154026.0,"TMZON_00_06_FLPOP_CO":155626.0,"TMZON_06_11_FLPOP_CO":172532.0,"TMZON_11_14_FLPOP_CO":156693.0,"TMZON_14_17_FLPOP_CO":178970.0,"TMZON_17_21_FLPOP_CO":235172.0,"TMZON_21_24_FLPOP_CO":124490.0,"MON_FLPOP_CO":139081.0,"TUES_FLPOP_CO":138112.0,"WED_FLPOP_CO":143969.0,"THUR_FLPOP_CO":145494.0,"FRI_FLPOP_CO":149058.0,"SAT_FLPOP_CO":159810.0,"SUN_FLPOP_CO":147958.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120213","TRDAR_CD_NM":"삼성중앙역","TOT_FLPOP_CO":2106438.0,"ML_FLPOP_CO":1065625.0,"FML_FLPOP_CO":1040814.0,"AGRDE_10_FLPOP_CO":153616.0,"AGRDE_20_FLPOP_CO":401058.0,"AGRDE_30_FLPOP_CO":563098.0,"AGRDE_40_FLPOP_CO":428613.0,"AGRDE_50_FLPOP_CO":249678.0,"AGRDE_60_ABOVE_FLPOP_CO":310376.0,"TMZON_00_06_FLPOP_CO":401870.0,"TMZON_06_11_FLPOP_CO":417695.0,"TMZON_11_14_FLPOP_CO":347431.0,"TMZON_14_17_FLPOP_CO":349811.0,"TMZON_17_21_FLPOP_CO":376836.0,"TMZON_21_24_FLPOP_CO":212795.0,"MON_FLPOP_CO":308118.0,"TUES_FLPOP_CO":312073.0,"WED_FLPOP_CO":323631.0,"THUR_FLPOP_CO":336842.0,"FRI_FLPOP_CO":327149.0,"SAT_FLPOP_CO":260784.0,"SUN_FLPOP_CO":237840.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120214","TRDAR_CD_NM":"영동대교남단교차로","TOT_FLPOP_CO":385537.0,"ML_FLPOP_CO":194399.0,"FML_FLPOP_CO":191137.0,"AGRDE_10_FLPOP_CO":32896.0,"AGRDE_20_FLPOP_CO":56128.0,"AGRDE_30_FLPOP_CO":88724.0,"AGRDE_40_FLPOP_CO":73165.0,"AGRDE_50_FLPOP_CO":57053.0,"AGRDE_60_ABOVE_FLPOP_CO":77570.0,"TMZON_00_06_FLPOP_CO":66206.0,"TMZON_06_11_FLPOP_CO":78397.0,"TMZON_11_14_FLPOP_CO":62654.0,"TMZON_14_17_FLPOP_CO":64126.0,"TMZON_17_21_FLPOP_CO":73192.0,"TMZON_21_24_FLPOP_CO":40963.0,"MON_FLPOP_CO":56459.0,"TUES_FLPOP_CO":57567.0,"WED_FLPOP_CO":58623.0,"THUR_FLPOP_CO":60257.0,"FRI_FLPOP_CO":59849.0,"SAT_FLPOP_CO":50207.0,"SUN_FLPOP_CO":42575.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120215","TRDAR_CD_NM":"포스코사거리","TOT_FLPOP_CO":3393292.0,"ML_FLPOP_CO":1857656.0,"FML_FLPOP_CO":1535637.0,"AGRDE_10_FLPOP_CO":258754.0,"AGRDE_20_FLPOP_CO":646731.0,"AGRDE_30_FLPOP_CO":935664.0,"AGRDE_40_FLPOP_CO":733146.0,"AGRDE_50_FLPOP_CO":410161.0,"AGRDE_60_ABOVE_FLPOP_CO":408838.0,"TMZON_00_06_FLPOP_CO":498438.0,"TMZON_06_11_FLPOP_CO":695079.0,"TMZON_11_14_FLPOP_CO":627329.0,"TMZON_14_17_FLPOP_CO":630293.0,"TMZON_17_21_FLPOP_CO":634171.0,"TMZON_21_24_FLPOP_CO":307983.0,"MON_FLPOP_CO":531178.0,"TUES_FLPOP_CO":529896.0,"WED_FLPOP_CO":550658.0,"THUR_FLPOP_CO":578791.0,"FRI_FLPOP_CO":551637.0,"SAT_FLPOP_CO":349582.0,"SUN_FLPOP_CO":301550.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120222","TRDAR_CD_NM":"삼성역","TOT_FLPOP_CO":1105514.0,"ML_FLPOP_CO":579935.0,"FML_FLPOP_CO":525580.0,"AGRDE_10_FLPOP_CO":83180.0,"AGRDE_20_FLPOP_CO":239981.0,"AGRDE_30_FLPOP_CO":307369.0,"AGRDE_40_FLPOP_CO":214180.0,"AGRDE_50_FLPOP_CO":125254.0,"AGRDE_60_ABOVE_FLPOP_CO":135551.0,"TMZON_00_06_FLPOP_CO":70943.0,"TMZON_06_11_FLPOP_CO":243668.0,"TMZON_11_14_FLPOP_CO":242601.0,"TMZON_14_17_FLPOP_CO":247364.0,"TMZON_17_21_FLPOP_CO":229585.0,"TMZON_21_24_FLPOP_CO":71353.0,"MON_FLPOP_CO":177053.0,"TUES_FLPOP_CO":176517.0,"WED_FLPOP_CO":184032.0,"THUR_FLPOP_CO":195613.0,"FRI_FLPOP_CO":184025.0,"SAT_FLPOP_CO":103074.0,"SUN_FLPOP_CO":85200.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120217","TRDAR_CD_NM":"대치사거리","TOT_FLPOP_CO":1732918.0,"ML_FLPOP_CO":916654.0,"FML_FLPOP_CO":816265.0,"AGRDE_10_FLPOP_CO":427366.0,"AGRDE_20_FLPOP_CO":238691.0,"AGRDE_30_FLPOP_CO":304190.0,"AGRDE_40_FLPOP_CO":332937.0,"AGRDE_50_FLPOP_CO":209195.0,"AGRDE_60_ABOVE_FLPOP_CO":220539.0,"TMZON_00_06_FLPOP_CO":307441.0,"TMZON_06_11_FLPOP_CO":340125.0,"TMZON_11_14_FLPOP_CO":274033.0,"TMZON_14_17_FLPOP_CO":288579.0,"TMZON_17_21_FLPOP_CO":342003.0,"TMZON_21_24_FLPOP_CO":180738.0,"MON_FLPOP_CO":253839.0,"TUES_FLPOP_CO":251392.0,"WED_FLPOP_CO":256828.0,"THUR_FLPOP_CO":264607.0,"FRI_FLPOP_CO":261742.0,"SAT_FLPOP_CO":227117.0,"SUN_FLPOP_CO":217394.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120218","TRDAR_CD_NM":"코엑스","TOT_FLPOP_CO":51429.0,"ML_FLPOP_CO":24616.0,"FML_FLPOP_CO":26814.0,"AGRDE_10_FLPOP_CO":3751.0,"AGRDE_20_FLPOP_CO":12442.0,"AGRDE_30_FLPOP_CO":13952.0,"AGRDE_40_FLPOP_CO":10002.0,"AGRDE_50_FLPOP_CO":5630.0,"AGRDE_60_ABOVE_FLPOP_CO":5652.0,"TMZON_00_06_FLPOP_CO":2984.0,"TMZON_06_11_FLPOP_CO":8216.0,"TMZON_11_14_FLPOP_CO":11812.0,"TMZON_14_17_FLPOP_CO":12979.0,"TMZON_17_21_FLPOP_CO":12211.0,"TMZON_21_24_FLPOP_CO":3227.0,"MON_FLPOP_CO":6881.0,"TUES_FLPOP_CO":7038.0,"WED_FLPOP_CO":7609.0,"THUR_FLPOP_CO":8285.0,"FRI_FLPOP_CO":8314.0,"SAT_FLPOP_CO":7097.0,"SUN_FLPOP_CO":6204.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120219","TRDAR_CD_NM":"은마아파트","TOT_FLPOP_CO":1040194.0,"ML_FLPOP_CO":518399.0,"FML_FLPOP_CO":521796.0,"AGRDE_10_FLPOP_CO":406054.0,"AGRDE_20_FLPOP_CO":104317.0,"AGRDE_30_FLPOP_CO":89833.0,"AGRDE_40_FLPOP_CO":187540.0,"AGRDE_50_FLPOP_CO":123335.0,"AGRDE_60_ABOVE_FLPOP_CO":129114.0,"TMZON_00_06_FLPOP_CO":158661.0,"TMZON_06_11_FLPOP_CO":171344.0,"TMZON_11_14_FLPOP_CO":151990.0,"TMZON_14_17_FLPOP_CO":179500.0,"TMZON_17_21_FLPOP_CO":250852.0,"TMZON_21_24_FLPOP_CO":127848.0,"MON_FLPOP_CO":140213.0,"TUES_FLPOP_CO":136830.0,"WED_FLPOP_CO":140873.0,"THUR_FLPOP_CO":142587.0,"FRI_FLPOP_CO":147304.0,"SAT_FLPOP_CO":172879.0,"SUN_FLPOP_CO":159508.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120220","TRDAR_CD_NM":"대치역","TOT_FLPOP_CO":567234.0,"ML_FLPOP_CO":257281.0,"FML_FLPOP_CO":309954.0,"AGRDE_10_FLPOP_CO":177464.0,"AGRDE_20_FLPOP_CO":49395.0,"AGRDE_30_FLPOP_CO":49138.0,"AGRDE_40_FLPOP_CO":110295.0,"AGRDE_50_FLPOP_CO":77535.0,"AGRDE_60_ABOVE_FLPOP_CO":103408.0,"TMZON_00_06_FLPOP_CO":108359.0,"TMZON_06_11_FLPOP_CO":104022.0,"TMZON_11_14_FLPOP_CO":78871.0,"TMZON_14_17_FLPOP_CO":89073.0,"TMZON_17_21_FLPOP_CO":119087.0,"TMZON_21_24_FLPOP_CO":67824.0,"MON_FLPOP_CO":80258.0,"TUES_FLPOP_CO":79794.0,"WED_FLPOP_CO":80679.0,"THUR_FLPOP_CO":82883.0,"FRI_FLPOP_CO":83375.0,"SAT_FLPOP_CO":84135.0,"SUN_FLPOP_CO":76111.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120221","TRDAR_CD_NM":"봉은사역","TOT_FLPOP_CO":688118.0,"ML_FLPOP_CO":355484.0,"FML_FLPOP_CO":332633.0,"AGRDE_10_FLPOP_CO":57288.0,"AGRDE_20_FLPOP_CO":119987.0,"AGRDE_30_FLPOP_CO":171476.0,"AGRDE_40_FLPOP_CO":141719.0,"AGRDE_50_FLPOP_CO":88662.0,"AGRDE_60_ABOVE_FLPOP_CO":108985.0,"TMZON_00_06_FLPOP_CO":81543.0,"TMZON_06_11_FLPOP_CO":149140.0,"TMZON_11_14_FLPOP_CO":130238.0,"TMZON_14_17_FLPOP_CO":133288.0,"TMZON_17_21_FLPOP_CO":134989.0,"TMZON_21_24_FLPOP_CO":58917.0,"MON_FLPOP_CO":107603.0,"TUES_FLPOP_CO":106725.0,"WED_FLPOP_CO":109054.0,"THUR_FLPOP_CO":114966.0,"FRI_FLPOP_CO":110035.0,"SAT_FLPOP_CO":75154.0,"SUN_FLPOP_CO":64580.0},{"STDR_YYQU_CD":"20191","TRDAR_SE_CD":"D","TRDAR_SE_CD_NM":"발달상권","TRDAR_CD":"3120228","TRDAR_CD_NM":"석촌역(석촌호수)","TOT_FLPOP_CO":2224316.0,"ML_FLPOP_CO":1004562.0,"FML_FLPOP_CO":1219754.0,"AGRDE_10_FLPOP_CO":283142.0,"AGRDE_20_FLPOP_CO":380868.0,"AGRDE_30_FLPOP_CO":460858.0,"AGRDE_40_FLPOP_CO":328689.0,"AGRDE_50_FLPOP_CO":308071.0,"AGRDE_60_ABOVE_FLPOP_CO":462687.0,"TMZON_00_06_FLPOP_CO":472149.0,"TMZON_06_11_FLPOP_CO":4348

In [149]:
# "list_total_count":44536 ⇒ 1000개씩 나눠서 가져와야 함
apikey = os.getenv("MJ_APIKEY")
service = "VwsmTrdarFlpopQq"
base = "http://openapi.seoul.go.kr:8088"

# 1) 전체 건수 확인
first = requests.get(f"{base}/{apikey}/json/{service}/1/1/").json()
total = first[service]["list_total_count"]

# 2) 분할 수집
batch = 1000   # 서비스 허용 범위 내에서 조절
all_rows = []

for start in range(1, total + 1, batch):
    end = min(start + batch - 1, total)
    url = f"{base}/{apikey}/json/{service}/{start}/{end}/"
    response = requests.get(url).json()
    rows = response.get(service, {}).get("row", [])
    all_rows.extend(rows)

print("total:", total)
print("fetched:", len(all_rows))

total: 44536
fetched: 44536

In [150]:
flpop_tr_df = pd.DataFrame(all_rows)
flpop_tr_df.head()

,STDR_YYQU_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,TOT_FLPOP_CO,ML_FLPOP_CO,FML_FLPOP_CO,AGRDE_10_FLPOP_CO,AGRDE_20_FLPOP_CO,...,TMZON_14_17_FLPOP_CO,TMZON_17_21_FLPOP_CO,TMZON_21_24_FLPOP_CO,MON_FLPOP_CO,TUES_FLPOP_CO,WED_FLPOP_CO,THUR_FLPOP_CO,FRI_FLPOP_CO,SAT_FLPOP_CO,SUN_FLPOP_CO
0,20191,D,발달상권,3120196,서울세관,700352.0,359756.0,340594.0,44888.0,140916.0,...,124427.0,136567.0,69630.0,105462.0,106420.0,110506.0,115069.0,111466.0,80262.0,71166.0
1,20191,D,발달상권,3120197,역삼역,5123674.0,2802851.0,2320823.0,189741.0,1248859.0,...,1029695.0,1002107.0,435697.0,824944.0,821220.0,856904.0,902709.0,858099.0,480318.0,379483.0
2,20191,D,발달상권,3120198,구역삼세무서,2735527.0,1437771.0,1297755.0,170295.0,663373.0,...,406033.0,459925.0,296022.0,414386.0,410294.0,421127.0,434270.0,419333.0,323450.0,312668.0
3,20191,D,발달상권,3120199,경복아파트교차로,505522.0,259538.0,245984.0,27105.0,109292.0,...,80078.0,87825.0,50350.0,75708.0,74958.0,77918.0,79473.0,77901.0,62424.0,57140.0
4,20191,D,발달상권,3120200,학동사거리,1349117.0,632069.0,717048.0,97382.0,326760.0,...,256961.0,289717.0,139114.0,181562.0,193744.0,203127.0,212952.0,214384.0,195706.0,147642.0

## 데이터 전처리

In [151]:
# 필요한 데이터만 추출하고, 열이름 모두 소문자로 통일
flpop_tr_df = flpop_tr_df.drop(columns=["TRDAR_SE_CD"], errors="ignore")  # 해당 열 제거
flpop_tr_df.columns = flpop_tr_df.columns.str.lower()            # flpop_df 기준으로 소문자화

flpop_tr_df

,stdr_yyqu_cd,trdar_se_cd_nm,trdar_cd,trdar_cd_nm,tot_flpop_co,ml_flpop_co,fml_flpop_co,agrde_10_flpop_co,agrde_20_flpop_co,agrde_30_flpop_co,...,tmzon_14_17_flpop_co,tmzon_17_21_flpop_co,tmzon_21_24_flpop_co,mon_flpop_co,tues_flpop_co,wed_flpop_co,thur_flpop_co,fri_flpop_co,sat_flpop_co,sun_flpop_co
0,20191,발달상권,3120196,서울세관,700352.0,359756.0,340594.0,44888.0,140916.0,182543.0,...,124427.0,136567.0,69630.0,105462.0,106420.0,110506.0,115069.0,111466.0,80262.0,71166.0
1,20191,발달상권,3120197,역삼역,5123674.0,2802851.0,2320823.0,189741.0,1248859.0,1489998.0,...,1029695.0,1002107.0,435697.0,824944.0,821220.0,856904.0,902709.0,858099.0,480318.0,379483.0
2,20191,발달상권,3120198,구역삼세무서,2735527.0,1437771.0,1297755.0,170295.0,663373.0,738048.0,...,406033.0,459925.0,296022.0,414386.0,410294.0,421127.0,434270.0,419333.0,323450.0,312668.0
3,20191,발달상권,3120199,경복아파트교차로,505522.0,259538.0,245984.0,27105.0,109292.0,147631.0,...,80078.0,87825.0,50350.0,75708.0,74958.0,77918.0,79473.0,77901.0,62424.0,57140.0
4,20191,발달상권,3120200,학동사거리,1349117.0,632069.0,717048.0,97382.0,326760.0,360568.0,...,256961.0,289717.0,139114.0,181562.0,193744.0,203127.0,212952.0,214384.0,195706.0,147642.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44531,20252,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,6952851.0,3278243.0,3674608.0,287579.0,1200664.0,1661817.0,...,1702240.0,1300602.0,344642.0,1096780.0,1095901.0,1183241.0,1155247.0,1105066.0,721777.0,594838.0
44532,20252,관광특구,3001493,동대문패션타운 관광특구,3489708.0,1624950.0,1864757.0,196001.0,649607.0,775338.0,...,551648.0,660777.0,416430.0,536087.0,541289.0,557366.0,555502.0,516952.0,392095.0,390417.0
44533,20252,관광특구,3001494,종로·청계 관광특구,8537311.0,4476428.0,4060884.0,322168.0,1533817.0,1665463.0,...,1786024.0,1686973.0,684131.0,1318020.0,1311528.0,1399371.0,1376796.0,1329573.0,1005568.0,796454.0
44534,20252,관광특구,3001495,잠실 관광특구,4116967.0,1951388.0,2165578.0,407384.0,949932.0,1026832.0,...,658382.0,900623.0,483598.0,565714.0,570891.0,574479.0,589440.0,616438.0,619744.0,580259.0
44535,20252,관광특구,3001496,강남 마이스 관광특구,106928.0,52435.0,54493.0,7088.0,21778.0,29242.0,...,27043.0,21393.0,5266.0,15044.0,15308.0,17475.0,18170.0,17152.0,13095.0,10684.0

In [159]:
flpop_tr_df['stdr_yyqu_cd'].unique()

<StringArray>
['20191', '20241', '20214', '20211', '20222', '20231', '20234', '20203',
 '20232', '20252', '20221', '20213', '20192', '20242', '20251', '20201',
 '20204', '20243', '20233', '20193', '20223', '20212', '20244', '20194',
 '20202', '20224', '20253']
Length: 27, dtype: str

In [160]:
flpop_tr_df = (
    flpop_tr_df
    .sort_values(["stdr_yyqu_cd", "trdar_cd"], ascending=[True, True])
    .reset_index(drop=True)
)
flpop_tr_df

,stdr_yyqu_cd,trdar_se_cd_nm,trdar_cd,trdar_cd_nm,tot_flpop_co,ml_flpop_co,fml_flpop_co,agrde_10_flpop_co,agrde_20_flpop_co,agrde_30_flpop_co,...,tmzon_14_17_flpop_co,tmzon_17_21_flpop_co,tmzon_21_24_flpop_co,mon_flpop_co,tues_flpop_co,wed_flpop_co,thur_flpop_co,fri_flpop_co,sat_flpop_co,sun_flpop_co
0,20191,관광특구,3001491,이태원 관광특구,2418524.0,1227335.0,1191188.0,142554.0,722271.0,562230.0,...,338263.0,514860.0,349263.0,301439.0,304054.0,306360.0,317331.0,363506.0,438229.0,387605.0
1,20191,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,7851811.0,3804599.0,4047212.0,295027.0,1475672.0,1880623.0,...,1997410.0,1573937.0,411649.0,1218293.0,1204925.0,1259889.0,1340506.0,1317245.0,875006.0,635949.0
2,20191,관광특구,3001493,동대문패션타운 관광특구,3779788.0,1827835.0,1951954.0,188911.0,747125.0,880198.0,...,589953.0,672029.0,465172.0,560580.0,556120.0,571025.0,595428.0,601168.0,501537.0,393931.0
3,20191,관광특구,3001494,종로·청계 관광특구,10936954.0,5904661.0,5032294.0,447361.0,2032682.0,1943111.0,...,2437343.0,2319158.0,916464.0,1636435.0,1633361.0,1688397.0,1783350.0,1802017.0,1425047.0,968348.0
4,20191,관광특구,3001495,잠실 관광특구,3853206.0,1842185.0,2011021.0,394695.0,776760.0,830510.0,...,614804.0,800989.0,448744.0,527554.0,540737.0,550151.0,561649.0,570399.0,574518.0,528198.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44531,20253,전통시장,3130323,둔촌역전통시장,301735.0,142627.0,159109.0,38870.0,35722.0,41641.0,...,32695.0,48635.0,39718.0,43350.0,42974.0,42971.0,42651.0,43291.0,43850.0,42648.0
44532,20253,전통시장,3130324,길동복조리시장,533011.0,235646.0,297366.0,73020.0,57427.0,73982.0,...,53013.0,80821.0,76017.0,75837.0,76541.0,76326.0,75458.0,76812.0,75707.0,76330.0
44533,20253,전통시장,3130325,명일전통시장,294819.0,131330.0,163490.0,52824.0,31347.0,37791.0,...,40989.0,62090.0,37379.0,41220.0,40976.0,42073.0,40997.0,41958.0,42827.0,44770.0
44534,20253,전통시장,3130326,고덕 골목형상점가,88556.0,39833.0,48725.0,16548.0,7576.0,14690.0,...,10922.0,16408.0,11142.0,12458.0,12520.0,12663.0,12545.0,12667.0,13037.0,12667.0
44535,20253,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",57448.0,26584.0,30864.0,2246.0,8089.0,12740.0,...,8085.0,9097.0,7443.0,9171.0,9384.0,9292.0,9405.0,8333.0,5671.0,6192.0

# 서울시 상권분석서비스(길단위인구-행정동)
카페 데이터(cafe.csv)에서 flpop_type이 A 인 경우 사용

## 데이터 불러오기

In [163]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "300"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/VwsmAdstrdFlpopW/{start_index}/{end_index}/"

response = requests.get(url)
print(response.content.decode('utf-8'))

{"VwsmAdstrdFlpopW":{"list_total_count":11475,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320515","ADSTRD_CD_NM":"창5동","TOT_FLPOP_CO":4263862.0,"ML_FLPOP_CO":1929777.0,"FML_FLPOP_CO":2334085.0,"AGRDE_10_FLPOP_CO":678202.0,"AGRDE_20_FLPOP_CO":541171.0,"AGRDE_30_FLPOP_CO":608372.0,"AGRDE_40_FLPOP_CO":616520.0,"AGRDE_50_FLPOP_CO":695087.0,"AGRDE_60_ABOVE_FLPOP_CO":1124511.0,"TMZON_00_06_FLPOP_CO":954982.0,"TMZON_06_11_FLPOP_CO":861032.0,"TMZON_11_14_FLPOP_CO":538239.0,"TMZON_14_17_FLPOP_CO":558731.0,"TMZON_17_21_FLPOP_CO":806202.0,"TMZON_21_24_FLPOP_CO":544678.0,"MON_FLPOP_CO":602886.0,"TUES_FLPOP_CO":597483.0,"WED_FLPOP_CO":596701.0,"THUR_FLPOP_CO":597592.0,"FRI_FLPOP_CO":602498.0,"SAT_FLPOP_CO":634238.0,"SUN_FLPOP_CO":632462.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320521","ADSTRD_CD_NM":"도봉1동","TOT_FLPOP_CO":3625772.0,"ML_FLPOP_CO":1774866.0,"FML_FLPOP_CO":1850906.0,"AGRDE_10_FLPOP_CO":407131.0,"AGRDE_20_FLPOP_CO":355605.0,"AGRDE_30_FLPOP_CO":408412.0,"AGRDE_40_FLPOP_CO":484567.0,"AGRDE_50_FLPOP_CO":622516.0,"AGRDE_60_ABOVE_FLPOP_CO":1347541.0,"TMZON_00_06_FLPOP_CO":951103.0,"TMZON_06_11_FLPOP_CO":751308.0,"TMZON_11_14_FLPOP_CO":423955.0,"TMZON_14_17_FLPOP_CO":430102.0,"TMZON_17_21_FLPOP_CO":602094.0,"TMZON_21_24_FLPOP_CO":467208.0,"MON_FLPOP_CO":507631.0,"TUES_FLPOP_CO":505812.0,"WED_FLPOP_CO":498030.0,"THUR_FLPOP_CO":504924.0,"FRI_FLPOP_CO":508073.0,"SAT_FLPOP_CO":541035.0,"SUN_FLPOP_CO":560267.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320522","ADSTRD_CD_NM":"도봉2동","TOT_FLPOP_CO":3404141.0,"ML_FLPOP_CO":1613793.0,"FML_FLPOP_CO":1790348.0,"AGRDE_10_FLPOP_CO":506139.0,"AGRDE_20_FLPOP_CO":343526.0,"AGRDE_30_FLPOP_CO":441671.0,"AGRDE_40_FLPOP_CO":491399.0,"AGRDE_50_FLPOP_CO":551184.0,"AGRDE_60_ABOVE_FLPOP_CO":1070222.0,"TMZON_00_06_FLPOP_CO":906708.0,"TMZON_06_11_FLPOP_CO":725272.0,"TMZON_11_14_FLPOP_CO":385310.0,"TMZON_14_17_FLPOP_CO":377885.0,"TMZON_17_21_FLPOP_CO":552874.0,"TMZON_21_24_FLPOP_CO":456093.0,"MON_FLPOP_CO":488117.0,"TUES_FLPOP_CO":484012.0,"WED_FLPOP_CO":479359.0,"THUR_FLPOP_CO":481832.0,"FRI_FLPOP_CO":481692.0,"SAT_FLPOP_CO":490190.0,"SUN_FLPOP_CO":498941.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320660","ADSTRD_CD_NM":"쌍문1동","TOT_FLPOP_CO":5148281.0,"ML_FLPOP_CO":2292513.0,"FML_FLPOP_CO":2855768.0,"AGRDE_10_FLPOP_CO":894616.0,"AGRDE_20_FLPOP_CO":716270.0,"AGRDE_30_FLPOP_CO":614891.0,"AGRDE_40_FLPOP_CO":722306.0,"AGRDE_50_FLPOP_CO":793887.0,"AGRDE_60_ABOVE_FLPOP_CO":1406313.0,"TMZON_00_06_FLPOP_CO":1451087.0,"TMZON_06_11_FLPOP_CO":1078225.0,"TMZON_11_14_FLPOP_CO":579862.0,"TMZON_14_17_FLPOP_CO":562128.0,"TMZON_17_21_FLPOP_CO":796422.0,"TMZON_21_24_FLPOP_CO":680556.0,"MON_FLPOP_CO":737177.0,"TUES_FLPOP_CO":730866.0,"WED_FLPOP_CO":721639.0,"THUR_FLPOP_CO":726841.0,"FRI_FLPOP_CO":717698.0,"SAT_FLPOP_CO":741625.0,"SUN_FLPOP_CO":772434.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320670","ADSTRD_CD_NM":"쌍문2동","TOT_FLPOP_CO":4539787.0,"ML_FLPOP_CO":2089232.0,"FML_FLPOP_CO":2450556.0,"AGRDE_10_FLPOP_CO":713920.0,"AGRDE_20_FLPOP_CO":536325.0,"AGRDE_30_FLPOP_CO":632059.0,"AGRDE_40_FLPOP_CO":653006.0,"AGRDE_50_FLPOP_CO":745558.0,"AGRDE_60_ABOVE_FLPOP_CO":1258920.0,"TMZON_00_06_FLPOP_CO":1219776.0,"TMZON_06_11_FLPOP_CO":932949.0,"TMZON_11_14_FLPOP_CO":524512.0,"TMZON_14_17_FLPOP_CO":519171.0,"TMZON_17_21_FLPOP_CO":745124.0,"TMZON_21_24_FLPOP_CO":598256.0,"MON_FLPOP_CO":648956.0,"TUES_FLPOP_CO":640168.0,"WED_FLPOP_CO":638320.0,"THUR_FLPOP_CO":641386.0,"FRI_FLPOP_CO":639705.0,"SAT_FLPOP_CO":658679.0,"SUN_FLPOP_CO":672574.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320680","ADSTRD_CD_NM":"쌍문3동","TOT_FLPOP_CO":5449579.0,"ML_FLPOP_CO":2434169.0,"FML_FLPOP_CO":3015410.0,"AGRDE_10_FLPOP_CO":851541.0,"AGRDE_20_FLPOP_CO":744384.0,"AGRDE_30_FLPOP_CO":766661.0,"AGRDE_40_FLPOP_CO":789967.0,"AGRDE_50_FLPOP_CO":844448.0,"AGRDE_60_ABOVE_FLPOP_CO":1452577.0,"TMZON_00_06_FLPOP_CO":1463590.0,"TMZON_06_11_FLPOP_CO":1140131.0,"TMZON_11_14_FLPOP_CO":615809.0,"TMZON_14_17_FLPOP_CO":607554.0,"TMZON_17_21_FLPOP_CO":894125.0,"TMZON_21_24_FLPOP_CO":728372.0,"MON_FLPOP_CO":776765.0,"TUES_FLPOP_CO":770015.0,"WED_FLPOP_CO":764159.0,"THUR_FLPOP_CO":768187.0,"FRI_FLPOP_CO":766644.0,"SAT_FLPOP_CO":791600.0,"SUN_FLPOP_CO":812211.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320681","ADSTRD_CD_NM":"쌍문4동","TOT_FLPOP_CO":2531903.0,"ML_FLPOP_CO":1159118.0,"FML_FLPOP_CO":1372785.0,"AGRDE_10_FLPOP_CO":533008.0,"AGRDE_20_FLPOP_CO":245592.0,"AGRDE_30_FLPOP_CO":293017.0,"AGRDE_40_FLPOP_CO":379761.0,"AGRDE_50_FLPOP_CO":400621.0,"AGRDE_60_ABOVE_FLPOP_CO":679904.0,"TMZON_00_06_FLPOP_CO":721837.0,"TMZON_06_11_FLPOP_CO":535758.0,"TMZON_11_14_FLPOP_CO":272862.0,"TMZON_14_17_FLPOP_CO":273045.0,"TMZON_17_21_FLPOP_CO":395512.0,"TMZON_21_24_FLPOP_CO":332888.0,"MON_FLPOP_CO":360458.0,"TUES_FLPOP_CO":358205.0,"WED_FLPOP_CO":348111.0,"THUR_FLPOP_CO":355282.0,"FRI_FLPOP_CO":353598.0,"SAT_FLPOP_CO":370238.0,"SUN_FLPOP_CO":386011.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320690","ADSTRD_CD_NM":"방학1동","TOT_FLPOP_CO":6573670.0,"ML_FLPOP_CO":3105178.0,"FML_FLPOP_CO":3468492.0,"AGRDE_10_FLPOP_CO":923161.0,"AGRDE_20_FLPOP_CO":737751.0,"AGRDE_30_FLPOP_CO":822200.0,"AGRDE_40_FLPOP_CO":998161.0,"AGRDE_50_FLPOP_CO":1202132.0,"AGRDE_60_ABOVE_FLPOP_CO":1890265.0,"TMZON_00_06_FLPOP_CO":1598804.0,"TMZON_06_11_FLPOP_CO":1332804.0,"TMZON_11_14_FLPOP_CO":807438.0,"TMZON_14_17_FLPOP_CO":837294.0,"TMZON_17_21_FLPOP_CO":1162572.0,"TMZON_21_24_FLPOP_CO":834755.0,"MON_FLPOP_CO":929623.0,"TUES_FLPOP_CO":917327.0,"WED_FLPOP_CO":915479.0,"THUR_FLPOP_CO":917004.0,"FRI_FLPOP_CO":923807.0,"SAT_FLPOP_CO":979972.0,"SUN_FLPOP_CO":990456.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320700","ADSTRD_CD_NM":"방학2동","TOT_FLPOP_CO":3115427.0,"ML_FLPOP_CO":1488345.0,"FML_FLPOP_CO":1627084.0,"AGRDE_10_FLPOP_CO":395930.0,"AGRDE_20_FLPOP_CO":305971.0,"AGRDE_30_FLPOP_CO":344109.0,"AGRDE_40_FLPOP_CO":441352.0,"AGRDE_50_FLPOP_CO":558738.0,"AGRDE_60_ABOVE_FLPOP_CO":1069328.0,"TMZON_00_06_FLPOP_CO":835745.0,"TMZON_06_11_FLPOP_CO":627348.0,"TMZON_11_14_FLPOP_CO":355309.0,"TMZON_14_17_FLPOP_CO":358525.0,"TMZON_17_21_FLPOP_CO":521631.0,"TMZON_21_24_FLPOP_CO":416872.0,"MON_FLPOP_CO":442385.0,"TUES_FLPOP_CO":435458.0,"WED_FLPOP_CO":429641.0,"THUR_FLPOP_CO":433090.0,"FRI_FLPOP_CO":436430.0,"SAT_FLPOP_CO":465579.0,"SUN_FLPOP_CO":472846.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11320710","ADSTRD_CD_NM":"방학3동","TOT_FLPOP_CO":3430146.0,"ML_FLPOP_CO":1583828.0,"FML_FLPOP_CO":1846319.0,"AGRDE_10_FLPOP_CO":703324.0,"AGRDE_20_FLPOP_CO":305027.0,"AGRDE_30_FLPOP_CO":372801.0,"AGRDE_40_FLPOP_CO":502383.0,"AGRDE_50_FLPOP_CO":525734.0,"AGRDE_60_ABOVE_FLPOP_CO":1020878.0,"TMZON_00_06_FLPOP_CO":1046126.0,"TMZON_06_11_FLPOP_CO":718692.0,"TMZON_11_14_FLPOP_CO":353655.0,"TMZON_14_17_FLPOP_CO":332959.0,"TMZON_17_21_FLPOP_CO":505362.0,"TMZON_21_24_FLPOP_CO":473355.0,"MON_FLPOP_CO":484766.0,"TUES_FLPOP_CO":484998.0,"WED_FLPOP_CO":473481.0,"THUR_FLPOP_CO":482743.0,"FRI_FLPOP_CO":479847.0,"SAT_FLPOP_CO":500874.0,"SUN_FLPOP_CO":523437.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350560","ADSTRD_CD_NM":"월계1동","TOT_FLPOP_CO":4624573.0,"ML_FLPOP_CO":2389463.0,"FML_FLPOP_CO":2235110.0,"AGRDE_10_FLPOP_CO":765524.0,"AGRDE_20_FLPOP_CO":1011723.0,"AGRDE_30_FLPOP_CO":568920.0,"AGRDE_40_FLPOP_CO":646588.0,"AGRDE_50_FLPOP_CO":592585.0,"AGRDE_60_ABOVE_FLPOP_CO":1039236.0,"TMZON_00_06_FLPOP_CO":1147985.0,"TMZON_06_11_FLPOP_CO":940775.0,"TMZON_11_14_FLPOP_CO":571906.0,"TMZON_14_17_FLPOP_CO":576760.0,"TMZON_17_21_FLPOP_CO":800711.0,"TMZON_21_24_FLPOP_CO":586436.0,"MON_FLPOP_CO":665798.0,"TUES_FLPOP_CO":664386.0,"WED_FLPOP_CO":661463.0,"THUR_FLPOP_CO":661061.0,"FRI_FLPOP_CO":645593.0,"SAT_FLPOP_CO":663306.0,"SUN_FLPOP_CO":662965.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350570","ADSTRD_CD_NM":"월계2동","TOT_FLPOP_CO":3764218.0,"ML_FLPOP_CO":1703648.0,"FML_FLPOP_CO":2060569.0,"AGRDE_10_FLPOP_CO":708382.0,"AGRDE_20_FLPOP_CO":421430.0,"AGRDE_30_FLPOP_CO":436939.0,"AGRDE_40_FLPOP_CO":580789.0,"AGRDE_50_FLPOP_CO":565060.0,"AGRDE_60_ABOVE_FLPOP_CO":1051619.0,"TMZON_00_06_FLPOP_CO":1253816.0,"TMZON_06_11_FLPOP_CO":818644.0,"TMZON_11_14_FLPOP_CO":357116.0,"TMZON_14_17_FLPOP_CO":320943.0,"TMZON_17_21_FLPOP_CO":485491.0,"TMZON_21_24_FLPOP_CO":528206.0,"MON_FLPOP_CO":541084.0,"TUES_FLPOP_CO":543809.0,"WED_FLPOP_CO":526617.0,"THUR_FLPOP_CO":540094.0,"FRI_FLPOP_CO":530566.0,"SAT_FLPOP_CO":531070.0,"SUN_FLPOP_CO":550978.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350580","ADSTRD_CD_NM":"월계3동","TOT_FLPOP_CO":2623967.0,"ML_FLPOP_CO":1200092.0,"FML_FLPOP_CO":1423876.0,"AGRDE_10_FLPOP_CO":447658.0,"AGRDE_20_FLPOP_CO":280103.0,"AGRDE_30_FLPOP_CO":366734.0,"AGRDE_40_FLPOP_CO":407134.0,"AGRDE_50_FLPOP_CO":394631.0,"AGRDE_60_ABOVE_FLPOP_CO":727705.0,"TMZON_00_06_FLPOP_CO":749172.0,"TMZON_06_11_FLPOP_CO":556070.0,"TMZON_11_14_FLPOP_CO":277777.0,"TMZON_14_17_FLPOP_CO":276693.0,"TMZON_17_21_FLPOP_CO":411275.0,"TMZON_21_24_FLPOP_CO":352981.0,"MON_FLPOP_CO":372096.0,"TUES_FLPOP_CO":367140.0,"WED_FLPOP_CO":359236.0,"THUR_FLPOP_CO":367221.0,"FRI_FLPOP_CO":367150.0,"SAT_FLPOP_CO":391686.0,"SUN_FLPOP_CO":399439.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350595","ADSTRD_CD_NM":"공릉1동","TOT_FLPOP_CO":1.1101265E7,"ML_FLPOP_CO":5191146.0,"FML_FLPOP_CO":5910120.0,"AGRDE_10_FLPOP_CO":1697269.0,"AGRDE_20_FLPOP_CO":2019459.0,"AGRDE_30_FLPOP_CO":1522037.0,"AGRDE_40_FLPOP_CO":1625051.0,"AGRDE_50_FLPOP_CO":1572532.0,"AGRDE_60_ABOVE_FLPOP_CO":2664919.0,"TMZON_00_06_FLPOP_CO":2971903.0,"TMZON_06_11_FLPOP_CO":2268194.0,"TMZON_11_14_FLPOP_CO":1255076.0,"TMZON_14_17_FLPOP_CO":1260131.0,"TMZON_17_21_FLPOP_CO":1863223.0,"TMZON_21_24_FLPOP_CO":1482741.0,"MON_FLPOP_CO":1572725.0,"TUES_FLPOP_CO":1557937.0,"WED_FLPOP_CO":1558494.0,"THUR_FLPOP_CO":1567318.0,"FRI_FLPOP_CO":1572054.0,"SAT_FLPOP_CO":1633371.0,"SUN_FLPOP_CO":1639366.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350600","ADSTRD_CD_NM":"공릉2동","TOT_FLPOP_CO":8243905.0,"ML_FLPOP_CO":3941348.0,"FML_FLPOP_CO":4302558.0,"AGRDE_10_FLPOP_CO":1619190.0,"AGRDE_20_FLPOP_CO":1543001.0,"AGRDE_30_FLPOP_CO":1061067.0,"AGRDE_40_FLPOP_CO":1225555.0,"AGRDE_50_FLPOP_CO":1117913.0,"AGRDE_60_ABOVE_FLPOP_CO":1677178.0,"TMZON_00_06_FLPOP_CO":2259568.0,"TMZON_06_11_FLPOP_CO":1726897.0,"TMZON_11_14_FLPOP_CO":925707.0,"TMZON_14_17_FLPOP_CO":911470.0,"TMZON_17_21_FLPOP_CO":1328123.0,"TMZON_21_24_FLPOP_CO":1092141.0,"MON_FLPOP_CO":1166134.0,"TUES_FLPOP_CO":1172558.0,"WED_FLPOP_CO":1161028.0,"THUR_FLPOP_CO":1174479.0,"FRI_FLPOP_CO":1159679.0,"SAT_FLPOP_CO":1192816.0,"SUN_FLPOP_CO":1217212.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350611","ADSTRD_CD_NM":"하계1동","TOT_FLPOP_CO":3734624.0,"ML_FLPOP_CO":1741953.0,"FML_FLPOP_CO":1992670.0,"AGRDE_10_FLPOP_CO":655776.0,"AGRDE_20_FLPOP_CO":536736.0,"AGRDE_30_FLPOP_CO":390153.0,"AGRDE_40_FLPOP_CO":544596.0,"AGRDE_50_FLPOP_CO":630853.0,"AGRDE_60_ABOVE_FLPOP_CO":976508.0,"TMZON_00_06_FLPOP_CO":963856.0,"TMZON_06_11_FLPOP_CO":796089.0,"TMZON_11_14_FLPOP_CO":473159.0,"TMZON_14_17_FLPOP_CO":455722.0,"TMZON_17_21_FLPOP_CO":587247.0,"TMZON_21_24_FLPOP_CO":458550.0,"MON_FLPOP_CO":532732.0,"TUES_FLPOP_CO":534931.0,"WED_FLPOP_CO":534322.0,"THUR_FLPOP_CO":531336.0,"FRI_FLPOP_CO":528662.0,"SAT_FLPOP_CO":528926.0,"SUN_FLPOP_CO":543714.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350612","ADSTRD_CD_NM":"하계2동","TOT_FLPOP_CO":2819564.0,"ML_FLPOP_CO":1257083.0,"FML_FLPOP_CO":1562482.0,"AGRDE_10_FLPOP_CO":486488.0,"AGRDE_20_FLPOP_CO":328247.0,"AGRDE_30_FLPOP_CO":359701.0,"AGRDE_40_FLPOP_CO":474072.0,"AGRDE_50_FLPOP_CO":470566.0,"AGRDE_60_ABOVE_FLPOP_CO":700488.0,"TMZON_00_06_FLPOP_CO":801919.0,"TMZON_06_11_FLPOP_CO":601310.0,"TMZON_11_14_FLPOP_CO":303234.0,"TMZON_14_17_FLPOP_CO":299583.0,"TMZON_17_21_FLPOP_CO":438441.0,"TMZON_21_24_FLPOP_CO":375079.0,"MON_FLPOP_CO":402476.0,"TUES_FLPOP_CO":396305.0,"WED_FLPOP_CO":393890.0,"THUR_FLPOP_CO":394444.0,"FRI_FLPOP_CO":392465.0,"SAT_FLPOP_CO":415735.0,"SUN_FLPOP_CO":424248.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350619","ADSTRD_CD_NM":"중계본동","TOT_FLPOP_CO":4122434.0,"ML_FLPOP_CO":1902238.0,"FML_FLPOP_CO":2220196.0,"AGRDE_10_FLPOP_CO":1351148.0,"AGRDE_20_FLPOP_CO":393275.0,"AGRDE_30_FLPOP_CO":278986.0,"AGRDE_40_FLPOP_CO":750892.0,"AGRDE_50_FLPOP_CO":676246.0,"AGRDE_60_ABOVE_FLPOP_CO":671887.0,"TMZON_00_06_FLPOP_CO":981641.0,"TMZON_06_11_FLPOP_CO":802434.0,"TMZON_11_14_FLPOP_CO":503581.0,"TMZON_14_17_FLPOP_CO":547337.0,"TMZON_17_21_FLPOP_CO":774034.0,"TMZON_21_24_FLPOP_CO":513406.0,"MON_FLPOP_CO":574409.0,"TUES_FLPOP_CO":581687.0,"WED_FLPOP_CO":578648.0,"THUR_FLPOP_CO":582797.0,"FRI_FLPOP_CO":571950.0,"SAT_FLPOP_CO":618616.0,"SUN_FLPOP_CO":614328.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350621","ADSTRD_CD_NM":"중계1동","TOT_FLPOP_CO":3820017.0,"ML_FLPOP_CO":1748874.0,"FML_FLPOP_CO":2071143.0,"AGRDE_10_FLPOP_CO":1236209.0,"AGRDE_20_FLPOP_CO":365125.0,"AGRDE_30_FLPOP_CO":291880.0,"AGRDE_40_FLPOP_CO":670075.0,"AGRDE_50_FLPOP_CO":587583.0,"AGRDE_60_ABOVE_FLPOP_CO":669147.0,"TMZON_00_06_FLPOP_CO":1023687.0,"TMZON_06_11_FLPOP_CO":768431.0,"TMZON_11_14_FLPOP_CO":433533.0,"TMZON_14_17_FLPOP_CO":449508.0,"TMZON_17_21_FLPOP_CO":655107.0,"TMZON_21_24_FLPOP_CO":489750.0,"MON_FLPOP_CO":543116.0,"TUES_FLPOP_CO":547573.0,"WED_FLPOP_CO":542521.0,"THUR_FLPOP_CO":546395.0,"FRI_FLPOP_CO":539745.0,"SAT_FLPOP_CO":551939.0,"SUN_FLPOP_CO":548726.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350624","ADSTRD_CD_NM":"중계4동","TOT_FLPOP_CO":2991847.0,"ML_FLPOP_CO":1378594.0,"FML_FLPOP_CO":1613254.0,"AGRDE_10_FLPOP_CO":558008.0,"AGRDE_20_FLPOP_CO":333259.0,"AGRDE_30_FLPOP_CO":284864.0,"AGRDE_40_FLPOP_CO":430992.0,"AGRDE_50_FLPOP_CO":513210.0,"AGRDE_60_ABOVE_FLPOP_CO":871515.0,"TMZON_00_06_FLPOP_CO":797936.0,"TMZON_06_11_FLPOP_CO":600084.0,"TMZON_11_14_FLPOP_CO":344872.0,"TMZON_14_17_FLPOP_CO":345342.0,"TMZON_17_21_FLPOP_CO":502220.0,"TMZON_21_24_FLPOP_CO":401395.0,"MON_FLPOP_CO":425385.0,"TUES_FLPOP_CO":423556.0,"WED_FLPOP_CO":418893.0,"THUR_FLPOP_CO":423038.0,"FRI_FLPOP_CO":424438.0,"SAT_FLPOP_CO":437042.0,"SUN_FLPOP_CO":439494.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350625","ADSTRD_CD_NM":"중계2·3동","TOT_FLPOP_CO":4294718.0,"ML_FLPOP_CO":1912170.0,"FML_FLPOP_CO":2382548.0,"AGRDE_10_FLPOP_CO":826963.0,"AGRDE_20_FLPOP_CO":462741.0,"AGRDE_30_FLPOP_CO":521361.0,"AGRDE_40_FLPOP_CO":702926.0,"AGRDE_50_FLPOP_CO":678039.0,"AGRDE_60_ABOVE_FLPOP_CO":1102687.0,"TMZON_00_06_FLPOP_CO":1214231.0,"TMZON_06_11_FLPOP_CO":904823.0,"TMZON_11_14_FLPOP_CO":477031.0,"TMZON_14_17_FLPOP_CO":465183.0,"TMZON_17_21_FLPOP_CO":659488.0,"TMZON_21_24_FLPOP_CO":573963.0,"MON_FLPOP_CO":612149.0,"TUES_FLPOP_CO":610100.0,"WED_FLPOP_CO":606078.0,"THUR_FLPOP_CO":606748.0,"FRI_FLPOP_CO":604042.0,"SAT_FLPOP_CO":618090.0,"SUN_FLPOP_CO":637512.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350630","ADSTRD_CD_NM":"상계1동","TOT_FLPOP_CO":7548700.0,"ML_FLPOP_CO":3513692.0,"FML_FLPOP_CO":4035008.0,"AGRDE_10_FLPOP_CO":1240399.0,"AGRDE_20_FLPOP_CO":799118.0,"AGRDE_30_FLPOP_CO":912714.0,"AGRDE_40_FLPOP_CO":1096182.0,"AGRDE_50_FLPOP_CO":1241209.0,"AGRDE_60_ABOVE_FLPOP_CO":2259077.0,"TMZON_00_06_FLPOP_CO":2011831.0,"TMZON_06_11_FLPOP_CO":1533825.0,"TMZON_11_14_FLPOP_CO":875932.0,"TMZON_14_17_FLPOP_CO":873985.0,"TMZON_17_21_FLPOP_CO":1271626.0,"TMZON_21_24_FLPOP_CO":981501.0,"MON_FLPOP_CO":1062828.0,"TUES_FLPOP_CO":1048533.0,"WED_FLPOP_CO":1036013.0,"THUR_FLPOP_CO":1048452.0,"FRI_FLPOP_CO":1055886.0,"SAT_FLPOP_CO":1134668.0,"SUN_FLPOP_CO":1162320.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350640","ADSTRD_CD_NM":"상계2동","TOT_FLPOP_CO":1.0659895E7,"ML_FLPOP_CO":4854806.0,"FML_FLPOP_CO":5805088.0,"AGRDE_10_FLPOP_CO":1662479.0,"AGRDE_20_FLPOP_CO":1667120.0,"AGRDE_30_FLPOP_CO":1357326.0,"AGRDE_40_FLPOP_CO":1507127.0,"AGRDE_50_FLPOP_CO":1784617.0,"AGRDE_60_ABOVE_FLPOP_CO":2681228.0,"TMZON_00_06_FLPOP_CO":2484131.0,"TMZON_06_11_FLPOP_CO":2069660.0,"TMZON_11_14_FLPOP_CO":1330794.0,"TMZON_14_17_FLPOP_CO":1395115.0,"TMZON_17_21_FLPOP_CO":2009319.0,"TMZON_21_24_FLPOP_CO":1370875.0,"MON_FLPOP_CO":1486479.0,"TUES_FLPOP_CO":1474423.0,"WED_FLPOP_CO":1480899.0,"THUR_FLPOP_CO":1482369.0,"FRI_FLPOP_CO":1519603.0,"SAT_FLPOP_CO":1606955.0,"SUN_FLPOP_CO":1609165.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350665","ADSTRD_CD_NM":"상계3·4동","TOT_FLPOP_CO":8561257.0,"ML_FLPOP_CO":3978425.0,"FML_FLPOP_CO":4582833.0,"AGRDE_10_FLPOP_CO":1247964.0,"AGRDE_20_FLPOP_CO":883892.0,"AGRDE_30_FLPOP_CO":931800.0,"AGRDE_40_FLPOP_CO":1292674.0,"AGRDE_50_FLPOP_CO":1552559.0,"AGRDE_60_ABOVE_FLPOP_CO":2652368.0,"TMZON_00_06_FLPOP_CO":2264112.0,"TMZON_06_11_FLPOP_CO":1785931.0,"TMZON_11_14_FLPOP_CO":967561.0,"TMZON_14_17_FLPOP_CO":976149.0,"TMZON_17_21_FLPOP_CO":1453883.0,"TMZON_21_24_FLPOP_CO":1113622.0,"MON_FLPOP_CO":1200656.0,"TUES_FLPOP_CO":1187071.0,"WED_FLPOP_CO":1171862.0,"THUR_FLPOP_CO":1183950.0,"FRI_FLPOP_CO":1183664.0,"SAT_FLPOP_CO":1295641.0,"SUN_FLPOP_CO":1338414.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350670","ADSTRD_CD_NM":"상계5동","TOT_FLPOP_CO":6469230.0,"ML_FLPOP_CO":2923894.0,"FML_FLPOP_CO":3545335.0,"AGRDE_10_FLPOP_CO":979496.0,"AGRDE_20_FLPOP_CO":751796.0,"AGRDE_30_FLPOP_CO":728941.0,"AGRDE_40_FLPOP_CO":895190.0,"AGRDE_50_FLPOP_CO":1113013.0,"AGRDE_60_ABOVE_FLPOP_CO":2000796.0,"TMZON_00_06_FLPOP_CO":1755884.0,"TMZON_06_11_FLPOP_CO":1322884.0,"TMZON_11_14_FLPOP_CO":718649.0,"TMZON_14_17_FLPOP_CO":727334.0,"TMZON_17_21_FLPOP_CO":1081744.0,"TMZON_21_24_FLPOP_CO":862734.0,"MON_FLPOP_CO":920291.0,"TUES_FLPOP_CO":907399.0,"WED_FLPOP_CO":892476.0,"THUR_FLPOP_CO":903241.0,"FRI_FLPOP_CO":908651.0,"SAT_FLPOP_CO":957432.0,"SUN_FLPOP_CO":979739.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350695","ADSTRD_CD_NM":"상계6·7동","TOT_FLPOP_CO":6491745.0,"ML_FLPOP_CO":2816335.0,"FML_FLPOP_CO":3675411.0,"AGRDE_10_FLPOP_CO":1111889.0,"AGRDE_20_FLPOP_CO":896314.0,"AGRDE_30_FLPOP_CO":937790.0,"AGRDE_40_FLPOP_CO":993517.0,"AGRDE_50_FLPOP_CO":1060380.0,"AGRDE_60_ABOVE_FLPOP_CO":1491855.0,"TMZON_00_06_FLPOP_CO":1478574.0,"TMZON_06_11_FLPOP_CO":1296923.0,"TMZON_11_14_FLPOP_CO":867227.0,"TMZON_14_17_FLPOP_CO":888336.0,"TMZON_17_21_FLPOP_CO":1155992.0,"TMZON_21_24_FLPOP_CO":804696.0,"MON_FLPOP_CO":927575.0,"TUES_FLPOP_CO":925309.0,"WED_FLPOP_CO":937259.0,"THUR_FLPOP_CO":933734.0,"FRI_FLPOP_CO":937257.0,"SAT_FLPOP_CO":926723.0,"SUN_FLPOP_CO":903887.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350700","ADSTRD_CD_NM":"상계8동","TOT_FLPOP_CO":1012974.0,"ML_FLPOP_CO":450872.0,"FML_FLPOP_CO":562103.0,"AGRDE_10_FLPOP_CO":221028.0,"AGRDE_20_FLPOP_CO":97577.0,"AGRDE_30_FLPOP_CO":179880.0,"AGRDE_40_FLPOP_CO":162055.0,"AGRDE_50_FLPOP_CO":138562.0,"AGRDE_60_ABOVE_FLPOP_CO":213873.0,"TMZON_00_06_FLPOP_CO":319270.0,"TMZON_06_11_FLPOP_CO":211716.0,"TMZON_11_14_FLPOP_CO":98676.0,"TMZON_14_17_FLPOP_CO":93493.0,"TMZON_17_21_FLPOP_CO":146080.0,"TMZON_21_24_FLPOP_CO":143738.0,"MON_FLPOP_CO":145955.0,"TUES_FLPOP_CO":144959.0,"WED_FLPOP_CO":143228.0,"THUR_FLPOP_CO":144326.0,"FRI_FLPOP_CO":143068.0,"SAT_FLPOP_CO":144147.0,"SUN_FLPOP_CO":147289.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350710","ADSTRD_CD_NM":"상계9동","TOT_FLPOP_CO":1878527.0,"ML_FLPOP_CO":825640.0,"FML_FLPOP_CO":1052887.0,"AGRDE_10_FLPOP_CO":392104.0,"AGRDE_20_FLPOP_CO":197626.0,"AGRDE_30_FLPOP_CO":266362.0,"AGRDE_40_FLPOP_CO":267789.0,"AGRDE_50_FLPOP_CO":276998.0,"AGRDE_60_ABOVE_FLPOP_CO":477649.0,"TMZON_00_06_FLPOP_CO":534897.0,"TMZON_06_11_FLPOP_CO":390903.0,"TMZON_11_14_FLPOP_CO":201894.0,"TMZON_14_17_FLPOP_CO":198410.0,"TMZON_17_21_FLPOP_CO":297547.0,"TMZON_21_24_FLPOP_CO":254877.0,"MON_FLPOP_CO":271367.0,"TUES_FLPOP_CO":266722.0,"WED_FLPOP_CO":264981.0,"THUR_FLPOP_CO":264872.0,"FRI_FLPOP_CO":263407.0,"SAT_FLPOP_CO":270436.0,"SUN_FLPOP_CO":276742.0},{"STDR_YYQU_CD":"20241","ADSTRD_CD":"11350720","ADSTRD_CD_NM":"상계10동","TOT_FLPOP_CO":1980841.0,"ML_FLPOP_CO":875613.0,"FML_FLPOP_CO":1105227.0,"AGRDE_10_FLPOP_CO":326284.0,"AGRDE_20_FLPOP_CO":271830.0,"AGRDE_30_FLPOP_CO":295736.0,"AGRDE_40_FLPOP_CO":295726.0,"AGRDE_50_FLPOP_CO":321779.0,"AGRDE_60_ABOVE_FLPOP_CO":469487.0,"TMZON_00_06_FLPOP_CO":511705.0,"TMZON_06_11_FLPOP_CO":402174.0,"TMZON_11_14_FLPOP_CO":231232.0,"TMZON_14_17_FLPOP_CO":239600.0,"TMZON_17_21_FLPOP_CO":341291.0,"TMZON_21_24_FLPOP_CO":254839.0,"MON_FLPOP_CO":278383.0,"TUES_FLPOP_CO":27673

In [164]:
# "list_total_count":11475 ⇒ 1000개씩 나눠서 가져와야 함
apikey = os.getenv("MJ_APIKEY")
service = "VwsmAdstrdFlpopW"
base = "http://openapi.seoul.go.kr:8088"

# 1) 전체 건수 확인
first = requests.get(f"{base}/{apikey}/json/{service}/1/1/").json()
total = first[service]["list_total_count"]

# 2) 분할 수집
batch = 1000   # 서비스 허용 범위 내에서 조절
all_rows = []

for start in range(1, total + 1, batch):
    end = min(start + batch - 1, total)
    url = f"{base}/{apikey}/json/{service}/{start}/{end}/"
    response = requests.get(url).json()
    rows = response.get(service, {}).get("row", [])
    all_rows.extend(rows)

print("total:", total)
print("fetched:", len(all_rows))

total: 11475
fetched: 11475

In [165]:
flpop_ad_df = pd.DataFrame(all_rows)
flpop_ad_df.head()

,STDR_YYQU_CD,ADSTRD_CD,ADSTRD_CD_NM,TOT_FLPOP_CO,ML_FLPOP_CO,FML_FLPOP_CO,AGRDE_10_FLPOP_CO,AGRDE_20_FLPOP_CO,AGRDE_30_FLPOP_CO,AGRDE_40_FLPOP_CO,...,TMZON_14_17_FLPOP_CO,TMZON_17_21_FLPOP_CO,TMZON_21_24_FLPOP_CO,MON_FLPOP_CO,TUES_FLPOP_CO,WED_FLPOP_CO,THUR_FLPOP_CO,FRI_FLPOP_CO,SAT_FLPOP_CO,SUN_FLPOP_CO
0,20241,11320515,창5동,4263862.0,1929777.0,2334085.0,678202.0,541171.0,608372.0,616520.0,...,558731.0,806202.0,544678.0,602886.0,597483.0,596701.0,597592.0,602498.0,634238.0,632462.0
1,20241,11320521,도봉1동,3625772.0,1774866.0,1850906.0,407131.0,355605.0,408412.0,484567.0,...,430102.0,602094.0,467208.0,507631.0,505812.0,498030.0,504924.0,508073.0,541035.0,560267.0
2,20241,11320522,도봉2동,3404141.0,1613793.0,1790348.0,506139.0,343526.0,441671.0,491399.0,...,377885.0,552874.0,456093.0,488117.0,484012.0,479359.0,481832.0,481692.0,490190.0,498941.0
3,20241,11320660,쌍문1동,5148281.0,2292513.0,2855768.0,894616.0,716270.0,614891.0,722306.0,...,562128.0,796422.0,680556.0,737177.0,730866.0,721639.0,726841.0,717698.0,741625.0,772434.0
4,20241,11320670,쌍문2동,4539787.0,2089232.0,2450556.0,713920.0,536325.0,632059.0,653006.0,...,519171.0,745124.0,598256.0,648956.0,640168.0,638320.0,641386.0,639705.0,658679.0,672574.0

## 데이터 전처리

In [166]:
# 열이름 모두 소문자로 통일
flpop_ad_df.columns = flpop_ad_df.columns.str.lower() 

# 정렬
flpop_ad_df = (
    flpop_ad_df
    .sort_values(["stdr_yyqu_cd", "adstrd_cd"], ascending=[True, True])
    .reset_index(drop=True)
)

flpop_ad_df.head()

,stdr_yyqu_cd,adstrd_cd,adstrd_cd_nm,tot_flpop_co,ml_flpop_co,fml_flpop_co,agrde_10_flpop_co,agrde_20_flpop_co,agrde_30_flpop_co,agrde_40_flpop_co,...,tmzon_14_17_flpop_co,tmzon_17_21_flpop_co,tmzon_21_24_flpop_co,mon_flpop_co,tues_flpop_co,wed_flpop_co,thur_flpop_co,fri_flpop_co,sat_flpop_co,sun_flpop_co
0,20191,11110515,청운효자동,3668225.0,1693148.0,1975079.0,604553.0,542715.0,581784.0,682867.0,...,460874.0,558750.0,434296.0,528566.0,528092.0,533157.0,540482.0,534862.0,505661.0,497404.0
1,20191,11110530,사직동,4628956.0,2290446.0,2338512.0,403260.0,752637.0,920942.0,904937.0,...,820984.0,887499.0,442738.0,682476.0,685164.0,709260.0,729241.0,717359.0,570596.0,534862.0
2,20191,11110540,삼청동,1010831.0,486563.0,524268.0,97480.0,152090.0,189542.0,182516.0,...,186331.0,173031.0,87952.0,142143.0,144846.0,146730.0,150008.0,152319.0,144807.0,129977.0
3,20191,11110550,부암동,1053668.0,468695.0,584973.0,169130.0,143980.0,124425.0,159491.0,...,125124.0,164822.0,132619.0,152370.0,152256.0,152123.0,150560.0,147122.0,148571.0,150668.0
4,20191,11110560,평창동,1139144.0,497078.0,642067.0,188796.0,119637.0,120384.0,165176.0,...,127608.0,173849.0,148127.0,161708.0,162637.0,161310.0,161151.0,159959.0,164827.0,167552.0

# 직방(매물) 데이터에 유동인구 데이터 코드 추가하기

In [191]:
# 데이터 불러오기
listing_df = pd.read_csv(r"C:\vs_code_prj\brewmap\data\mj\test_zigbang.csv")
listing_df.head()

,listing_id,listing_status,address,lat,lng,business_type,transaction_type,sale_price,key_money,deposit,monthly_rent,maintenance_fee,size_m2,floor
0,575115,open,서울특별시 강남구 논현동,37.519306,127.029262,사무실,월세,0,NaN,30000000,2000000,0,82.60,4층
1,703777,open,서울특별시 서초구 잠원동,37.511775,127.020540,카페/커피,월세,0,40000000.0,50000000,3000000,0,33.06,1층
2,701846,open,서울특별시 강남구 논현동,37.512658,127.021577,사무실,월세,0,NaN,35000000,3000000,0,49.59,2층
3,455221,open,서울특별시 강남구 논현동,37.509032,127.023453,한식/고기집,월세,0,220000000.0,80000000,5500000,1200000,264.50,2층
4,394623,open,서울특별시 강남구 논현동,37.515856,127.030844,가구/가전,월세,0,200000000.0,50000000,3100000,600000,165.00,1층

In [192]:
# 코드 추가
# GeoDataFrame 한 번만 생성
listing_gdf = gpd.GeoDataFrame(
    listing_df.copy(),
    geometry=gpd.points_from_xy(listing_df["lng"], listing_df["lat"]),
    crs="EPSG:4326"
)

# 각각 호출
listing_df = spatial_join_code(listing_df, listing_gdf,
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-상권).zip",
    "TRDAR_CD", "trdar_cd")

listing_df = spatial_join_code(listing_df, listing_gdf,
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-상권배후지).zip",
    "ALLEY_TRDA", "alley_trda")

listing_df = spatial_join_code(listing_df, listing_gdf,
    r"C:\vs_code_prj\brewmap\data\mj\서울시 상권분석서비스(영역-행정동).zip",
    "ADSTRD_CD", "adstrd_cd")

listing_df.head()

,listing_id,listing_status,address,lat,lng,business_type,transaction_type,sale_price,key_money,deposit,monthly_rent,maintenance_fee,size_m2,floor,trdar_cd,alley_trda,adstrd_cd
0,575115,open,서울특별시 강남구 논현동,37.519306,127.029262,사무실,월세,0,NaN,30000000,2000000,0,82.60,4층,3120190,3110957,11680531
1,703777,open,서울특별시 서초구 잠원동,37.511775,127.020540,카페/커피,월세,0,40000000.0,50000000,3000000,0,33.06,1층,3120185,3110950,11650540
2,701846,open,서울특별시 강남구 논현동,37.512658,127.021577,사무실,월세,0,NaN,35000000,3000000,0,49.59,2층,3120185,3110950,11680521
3,455221,open,서울특별시 강남구 논현동,37.509032,127.023453,한식/고기집,월세,0,220000000.0,80000000,5500000,1200000,264.50,2층,3130303,NaN,11680521
4,394623,open,서울특별시 강남구 논현동,37.515856,127.030844,가구/가전,월세,0,200000000.0,50000000,3100000,600000,165.00,1층,3120191,3110957,11680531

#### 코드 type 추가 및 코드 값 처리

In [193]:
# 1) flpop_type 컬럼 생성
listing_df["flpop_type"] = "A"  # 기본값
listing_df.loc[listing_df["alley_trda"].notna(), "flpop_type"] = "T"
listing_df.loc[listing_df["trdar_cd"].notna(), "flpop_type"] = "T"

# 2) trdar_cd 빈 값을 alley_trda로 대체
'''
상권-유동인구데이터, 상권배후지-유동인구데이터는 같은 API를 사용하므로 별도로 구분할 필요가 없음
'''
mask = listing_df["trdar_cd"].isna() & listing_df["alley_trda"].notna()
listing_df.loc[mask, "trdar_cd"] = listing_df.loc[mask, "alley_trda"]
listing_df.head()

,listing_id,listing_status,address,lat,lng,business_type,transaction_type,sale_price,key_money,deposit,monthly_rent,maintenance_fee,size_m2,floor,trdar_cd,alley_trda,adstrd_cd,flpop_type
0,575115,open,서울특별시 강남구 논현동,37.519306,127.029262,사무실,월세,0,NaN,30000000,2000000,0,82.60,4층,3120190,3110957,11680531,T
1,703777,open,서울특별시 서초구 잠원동,37.511775,127.020540,카페/커피,월세,0,40000000.0,50000000,3000000,0,33.06,1층,3120185,3110950,11650540,T
2,701846,open,서울특별시 강남구 논현동,37.512658,127.021577,사무실,월세,0,NaN,35000000,3000000,0,49.59,2층,3120185,3110950,11680521,T
3,455221,open,서울특별시 강남구 논현동,37.509032,127.023453,한식/고기집,월세,0,220000000.0,80000000,5500000,1200000,264.50,2층,3130303,NaN,11680521,T
4,394623,open,서울특별시 강남구 논현동,37.515856,127.030844,가구/가전,월세,0,200000000.0,50000000,3100000,600000,165.00,1층,3120191,3110957,11680531,T

## 저장용 dataframe 생성

In [ ]:
# 저장 전 결측치 확인 → key_money 전처리 필요
listing_df.isna().sum()

listing_id            0
listing_status        0
address               0
lat                   0
lng                   0
business_type         0
transaction_type      0
sale_price            0
key_money           465
deposit               0
monthly_rent          0
maintenance_fee       0
size_m2               0
floor                 0
trdar_cd              0
alley_trda          223
adstrd_cd             0
flpop_type            0
dtype: int64

### 데이터 전처리

In [194]:
listing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   listing_id        1319 non-null   int64
 1   listing_status    1319 non-null   str
 2   address           1319 non-null   str
 3   lat               1319 non-null   float64
 4   lng               1319 non-null   float64
 5   business_type     1319 non-null   str
 6   transaction_type  1319 non-null   str
 7   sale_price        1319 non-null   int64
 8   key_money         854 non-null    float64
 9   deposit           1319 non-null   int64
 10  monthly_rent      1319 non-null   int64
 11  maintenance_fee   1319 non-null   int64
 12  size_m2           1319 non-null   float64
 13  floor             1319 non-null   str
 14  trdar_cd          1319 non-null   str
 15  alley_trda        1096 non-null   str
 16  adstrd_cd         1319 non-null   str
 17  flpop_type        1319 non-null   str
dtypes: float64(4), int64(5), str(9)
memory usage: 185.6 KB

In [199]:
# key_money 타입 변경 및 결측치 0으로 변경
listing_df["key_money"] = listing_df["key_money"].fillna(0).astype(int)

In [200]:
listing_df["key_money"].isna().sum(), listing_df["key_money"].dtype

(np.int64(0), dtype('int64'))

In [205]:
print(listing_df['listing_status'].unique())
print(listing_df['transaction_type'].unique())

<StringArray>
['open']
Length: 1, dtype: str
<StringArray>
['월세', '매매', '전세']
Length: 3, dtype: str

### 필요한 데이터만 추출

In [204]:
save_listing_df = (
    listing_df
    .drop(columns=["listing_status", "alley_trda"])
    .rename(columns={"address": "addr"})
)

# 마지막 컬럼 순서 지정
front_cols = [c for c in save_listing_df.columns if c not in ["flpop_type", "trdar_cd", "adstrd_cd"]]
save_listing_df = save_listing_df[front_cols + ["flpop_type", "trdar_cd", "adstrd_cd"]]

save_listing_df.head()

,listing_id,addr,lat,lng,business_type,transaction_type,sale_price,key_money,deposit,monthly_rent,maintenance_fee,size_m2,floor,flpop_type,trdar_cd,adstrd_cd
0,575115,서울특별시 강남구 논현동,37.519306,127.029262,사무실,월세,0,0,30000000,2000000,0,82.60,4층,T,3120190,11680531
1,703777,서울특별시 서초구 잠원동,37.511775,127.020540,카페/커피,월세,0,40000000,50000000,3000000,0,33.06,1층,T,3120185,11650540
2,701846,서울특별시 강남구 논현동,37.512658,127.021577,사무실,월세,0,0,35000000,3000000,0,49.59,2층,T,3120185,11680521
3,455221,서울특별시 강남구 논현동,37.509032,127.023453,한식/고기집,월세,0,220000000,80000000,5500000,1200000,264.50,2층,T,3130303,11680521
4,394623,서울특별시 강남구 논현동,37.515856,127.030844,가구/가전,월세,0,200000000,50000000,3100000,600000,165.00,1층,T,3120191,11680531

# csv로 내보내기

In [147]:
save_center_df.to_csv("industry_center.csv", index=False, encoding="utf-8-sig")

In [34]:
save_cafe_df.to_csv("cafe.csv", index=False, encoding="utf-8-sig")

In [168]:
flpop_tr_df.to_csv("flpop_t.csv", index=False, encoding="utf-8-sig")
flpop_ad_df.to_csv("flpop_a.csv", index=False, encoding="utf-8-sig")

In [206]:
save_listing_df.to_csv("listing.csv", index=False, encoding="utf-8-sig")