# 라이브러리 불러오기

In [29]:
import requests        # API 호출할 때 사용하는 라이브러리
import os              # 환경변수(.env) 읽어올 때 사용
from dotenv import load_dotenv  # .env 파일 로드하는 함수
import pandas as pd    # 데이터 처리 라이브러리

In [30]:
# env 파일 로드
load_dotenv()

True

# 서울 학교 기본 정보
## 데이터 불러오기

In [3]:
import time
import json

apikey = os.getenv("MY_API_KEY")
all_data = [] # 모든 데이터를 모아둘 리스트

# 1. 전체 데이터 개수 확인
first_url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/neisSchoolInfo/1/1/"
response = requests.get(first_url).json()
total_count = response['neisSchoolInfo']['list_total_count']
print(f"총 데이터 개수: {total_count}")

# 2. 500개씩 끊어서 반복문(for)을 돌립니다.
step = 500
for i in range(1, total_count + 1, step):
    start_index = i
    end_index = i + step - 1
    
    # 마지막 데이터 범위를 넘지 않게 조절
    if end_index > total_count:
        end_index = total_count
        
    url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/neisSchoolInfo/{start_index}/{end_index}/"
    
    try:
        response = requests.get(url).json()
        # 데이터가 있는 경우 리스트에 추가
        if 'neisSchoolInfo' in response and 'row' in response['neisSchoolInfo']:
            all_data.extend(response['neisSchoolInfo']['row'])
            print(f"성공: {start_index} ~ {end_index} 가져오기 완료!")
        
        # 서버에 무리가 가지 않게 아주 잠깐 멈춰주는 센스!
        time.sleep(0.1) 
        
    except Exception as e:
        print(f"에러 발생: {e}")

print(f"최종적으로 가져온 데이터 개수: {len(all_data)}")

총 데이터 개수: 3960
성공: 1 ~ 500 가져오기 완료!
성공: 501 ~ 1000 가져오기 완료!
성공: 1001 ~ 1500 가져오기 완료!
성공: 1501 ~ 2000 가져오기 완료!
성공: 2001 ~ 2500 가져오기 완료!
성공: 2501 ~ 3000 가져오기 완료!
성공: 3001 ~ 3500 가져오기 완료!
성공: 3501 ~ 3960 가져오기 완료!
최종적으로 가져온 데이터 개수: 3960

In [4]:
apikey  = os.getenv("MY_API_KEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "500"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/neisSchoolInfo/{start_index}/{end_index}/" #샘플 URL

response = requests.get(url)
print(response.content.decode('utf-8'))

{"neisSchoolInfo":{"list_total_count":3960,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134161","SCHUL_NM":"동국대학교사범대학부속가람중학교","ENG_SCHUL_NM":"Garam Middle School Attached to College of Education, Dongguk University","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"05038","ORG_RDNMA":"서울특별시 광진구 광나루로36길 47","ORG_RDNDA":", 동국대학교사범대학부속가람중학교 (구의동)","ORG_TELNO":"02-6948-2280","HMPG_ADRES":"https://garam.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-6948-2288","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19300620","FOAS_MEMRD":"19300620","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20250302"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134155","SCHUL_NM":"선화예술중학교","ENG_SCHUL_NM":"Sunhwa Arts Middle School","SCHUL_KND_SC_NM":"각종학교(중)","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"04991","ORG_RDNMA":"서울특별시 광진구 천호대로 664","ORG_RDNDA":"/ 선화예술중고등학교 (능동)","ORG_TELNO":"02-2204-1100","HMPG_ADRES":"https://sunhwaarts.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-453-4641","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19731201","FOAS_MEMRD":"19730705","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230627"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134150","SCHUL_NM":"서울숭신초등학교","ENG_SCHUL_NM":"Seoul Soongshin Elementary School","SCHUL_KND_SC_NM":"초등학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04702","ORG_RDNMA":"서울특별시 성동구 마장로 161","ORG_RDNDA":"(하왕십리동)","ORG_TELNO":"02-2252-5950","HMPG_ADRES":"http://soongshin.sen.es.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2236-6134","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19590403","FOAS_MEMRD":"19590403","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134142","SCHUL_NM":"행당중학교","ENG_SCHUL_NM":"Haengdang Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04764","ORG_RDNMA":"서울특별시 성동구 왕십리로 189","ORG_RDNDA":"(행당동/행당중학교)","ORG_TELNO":"02-2292-2721","HMPG_ADRES":"http://www.haengdang.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2293-0473","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19680806","FOAS_MEMRD":"19681002","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134141","SCHUL_NM":"한양대학교사범대학부속중학교","ENG_SCHUL_NM":"Hanyang University Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"04761","ORG_RDNMA":"서울특별시 성동구 마조로 42","ORG_RDNDA":"(사근동/한양사대부속중·고등학교)","ORG_TELNO":"02-2200-3700","HMPG_ADRES":"https://hyu.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2298-3173","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19600118","FOAS_MEMRD":"19600118","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134140","SCHUL_NM":"자양중학교","ENG_SCHUL_NM":"Jayang Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"05069","ORG_RDNMA":"서울특별시 광진구 뚝섬로41길 33","ORG_RDNDA":"(자양동/서울자양중학교)","ORG_TELNO":"02-446-0365","HMPG_ADRES":"http://jayang.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-458-7047","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19840301","FOAS_MEMRD":"19840301","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134139","SCHUL_NM":"용곡중학교","ENG_SCHUL_NM":"Yong-gok Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04940","ORG_RDNMA":"서울특별시 광진구 용마산로22길 76","ORG_RDNDA":"(중곡동/용곡중학교)","ORG_TELNO":"02-452-2622","HMPG_ADRES":"http://yonggok.sen.ms.kr/index.do","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-458-8566","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19821209","FOAS_MEMRD":"19830504","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134138","SCHUL_NM":"옥정중학교","ENG_SCHUL_NM":"Ok-Jung Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04734","ORG_RDNMA":"서울특별시 성동구 한림말길 11","ORG_RDNDA":"/ 옥정중학교 (옥수동)","ORG_TELNO":"02-6021-2100","HMPG_ADRES":"http://okjung.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2298-1303","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19840109","FOAS_MEMRD":"19840511","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134137","SCHUL_NM":"양진중학교","ENG_SCHUL_NM":"Yangjin Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04982","ORG_RDNMA":"서울특별시 광진구 워커힐로 32","ORG_RDNDA":"/ 양진중학교","ORG_TELNO":"02-2049-1200","HMPG_ADRES":"http://www.yangjin.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2049-1208/1220","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"해당없음","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"20051229","FOAS_MEMRD":"20060514","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134136","SCHUL_NM":"신양중학교","ENG_SCHUL_NM":"Shinyang Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"05087","ORG_RDNMA":"서울특별시 광진구 자양강변길 73","ORG_RDNDA":"/ 신양중학교 (자양동)","ORG_TELNO":"02-461-1070","HMPG_ADRES":"http://shinyang.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-469-8386","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19840109","FOAS_MEMRD":"19840509","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134135","SCHUL_NM":"성원중학교","ENG_SCHUL_NM":"Sungwon Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04775","ORG_RDNMA":"서울특별시 성동구 성덕정9가길 13","ORG_RDNDA":"(성수동2가/ 성원중학교)","ORG_TELNO":"02-3408-2558","HMPG_ADRES":"http://www.sungwon.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-463-0676","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19680806","FOAS_MEMRD":"19681002","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134134","SCHUL_NM":"성수중학교","ENG_SCHUL_NM":"Seongsu Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04768","ORG_RDNMA":"서울특별시 성동구 서울숲길 18","ORG_RDNDA":"(성수동1가/ 성수중학교)","ORG_TELNO":"02-463-4786","HMPG_ADRES":"http://seongsu.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-469-5292","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19671027","FOAS_MEMRD":"19671027","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134132","SCHUL_NM":"무학중학교","ENG_SCHUL_NM":"Muhak Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04716","ORG_RDNMA":"서울특별시 성동구 행당로 120","ORG_RDNDA":"(행당동)","ORG_TELNO":"02-2298-6141","HMPG_ADRES":"http://muhakg.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2281-5821","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19681001","FOAS_MEMRD":"19681001","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134131","SCHUL_NM":"마장중학교","ENG_SCHUL_NM":"Majang Junior High School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04753","ORG_RDNMA":"서울특별시 성동구 마장로35나길 31","ORG_RDNDA":"/ 마장중학교 (마장동)","ORG_TELNO":"02-2282-2933","HMPG_ADRES":"http://mj.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2282-2656","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"해당없음","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"20050301","FOAS_MEMRD":"20050405","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134130","SCHUL_NM":"대원국제중학교","ENG_SCHUL_NM":"Daewon International Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"04939","ORG_RDNMA":"서울특별시 광진구 용마산로22길 26","ORG_RDNDA":"/ 대원국제중학교 (중곡동)","ORG_TELNO":"02-2204-1592","HMPG_ADRES":"http://daewon.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2204-1583","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19770520","FOAS_MEMRD":"19770520","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134129","SCHUL_NM":"동마중학교","ENG_SCHUL_NM":"Dongma Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04759","ORG_RDNMA":"서울특별시 성동구 마조로11길 18","ORG_RDNDA":"(마장동)","ORG_TELNO":"02-2294-6085","HMPG_ADRES":"http://www.dongma.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2298-0413","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19841208","FOAS_MEMRD":"19850426","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134127","SCHUL_NM":"구의중학교","ENG_SCHUL_NM":"Guui Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"05022","ORG_RDNMA":"서울특별시 광진구 광나루로30길 80","ORG_RDNDA":"(화양동)","ORG_TELNO":"02-447-4798","HMPG_ADRES":"http://www.guui.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-455-5061","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19840430","FOAS_MEMRD":"19840430","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134126","SCHUL_NM":"광희중학교","ENG_SCHUL_NM":"Kwanghee Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04742","ORG_RDNMA":"서울특별시 성동구 독서당로62길 46","ORG_RDNDA":"/ 광희중학교 (응봉동)","ORG_TELNO":"02-2298-0250","HMPG_ADRES":"http://www.kwanghee.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2298-0252","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19370521","FOAS_MEMRD":"19370521","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134125","SCHUL_NM":"광진중학교","ENG_SCHUL_NM":"Gwangjin Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"05114","ORG_RDNMA":"서울특별시 광진구 뚝섬로64길 45","ORG_RDNDA":"(자양동/광진중학교)","ORG_TELNO":"02-447-2886","HMPG_ADRES":"http://gwangjin.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-3436-1508","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19790901","FOAS_MEMRD":"19791010","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20250406"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134124","SCHUL_NM":"광장중학교","ENG_SCHUL_NM":"Gwangjang Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04966","ORG_RDNMA":"서울특별시 광진구 광장로1길 1","ORG_RDNDA":"/ 광장중학교 (광장동)","ORG_TELNO":"02-452-0745","HMPG_ADRES":"http://www.gwangjang.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-444-5692","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19821209","FOAS_MEMRD":"19830406","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134123","SCHUL_NM":"광양중학교","ENG_SCHUL_NM":"Kwangyang Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"05104","ORG_RDNMA":"서울특별시 광진구 자양로3길 7","ORG_RDNDA":"(자양동)","ORG_TELNO":"02-452-6922","HMPG_ADRES":"http://kwangyang.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-452-6923","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19860129","FOAS_MEMRD":"19860418","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134122","SCHUL_NM":"광남중학교","ENG_SCHUL_NM":"Gwangnam Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04973","ORG_RDNMA":"서울특별시 광진구 아차산로70길 17-62","ORG_RDNDA":"/ 광남중학교 (광장동)","ORG_TELNO":"02-456-8792","HMPG_ADRES":"http://www.gwangnam.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-455-0161/453-2818","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19930116","FOAS_MEMRD":"19930504","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134121","SCHUL_NM":"경일중학교","ENG_SCHUL_NM":"Kyungil Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04779","ORG_RDNMA":"서울특별시 성동구 성수일로 27","ORG_RDNDA":"(성수동1가)","ORG_TELNO":"02-468-0651","HMPG_ADRES":"http://kyungil.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-468-2766","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"해당없음","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"20031230","FOAS_MEMRD":"20040506","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134120","SCHUL_NM":"경수중학교","ENG_SCHUL_NM":"Gyeongsu Middle School","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04785","ORG_RDNMA":"서울특별시 성동구 뚝섬로13길 14","ORG_RDNDA":"(성수동2가)","ORG_TELNO":"02-464-0675","HMPG_ADRES":"http://www.gsu.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-497-0296","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19801227","FOAS_MEMRD":"19810504","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134119","SCHUL_NM":"건국대학교사범대학부속중학교","ENG_SCHUL_NM":"Middle School Attached To College of Education, KONKUK University","SCHUL_KND_SC_NM":"중학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"05025","ORG_RDNMA":"서울특별시 광진구 자양로 145-1","ORG_RDNDA":"건국대학교사범대학부속중학교","ORG_TELNO":"02-457-0318","HMPG_ADRES":"http://konkuk.sen.ms.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-458-7427","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19671230","FOAS_MEMRD":"19680515","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134118","SCHUL_NM":"한양초등학교","ENG_SCHUL_NM":"Hanyang Elementary School","SCHUL_KND_SC_NM":"초등학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"04763","ORG_RDNMA":"서울특별시 성동구 살곶이길 208","ORG_RDNDA":"/ 한양초등학교 (사근동)","ORG_TELNO":"02-2293-8732","HMPG_ADRES":"http://www.hye.or.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-2299-3492","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19660220","FOAS_MEMRD":"19660515","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134117","SCHUL_NM":"세종초등학교","ENG_SCHUL_NM":"Sejong Elementary School","SCHUL_KND_SC_NM":"초등학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"05006","ORG_RDNMA":"서울특별시 광진구 군자로 114","ORG_RDNDA":"/ 세종초등학교 (군자동)","ORG_TELNO":"02-466-0045","HMPG_ADRES":"http://sje.sejong.ac.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-499-3513","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19621004","FOAS_MEMRD":"19621004","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134116","SCHUL_NM":"성동초등학교","ENG_SCHUL_NM":"Sungdong Elementary School","SCHUL_KND_SC_NM":"초등학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"사립","ORG_RDNZC":"05114","ORG_RDNMA":"서울특별시 광진구 자양로4길 63","ORG_RDNDA":"(자양동)","ORG_TELNO":"02-447-2642","HMPG_ADRES":"http://www.sungdong.es.kr","COEDU_SC_NM":"남여공학","ORG_FAXNO":"02-454-4322","HS_SC_NM":"","INDST_SPECL_CCCCL_EXST_YN":"N","HS_GNRL_BUSNS_SC_NM":"일반계","SPCLY_PURPS_HS_ORD_NM":"","ENE_BFE_SEHF_SC_NM":"전기","DGHT_SC_NM":"주간","FOND_YMD":"19661216","FOAS_MEMRD":"19670320","DGHT_CRSE_SC_NM":"","ORD_SC_NM":"","DDDEP_NM":"","LOAD_DTM":"20230615"},{"ATPT_OFCDC_SC_CODE":"B10","ATPT_OFCDC_SC_NM":"서울특별시교육청","SD_SCHUL_CODE":"7134114","SCHUL_NM":"서울행현초등학교","ENG_SCHUL_NM":"Seoul Haenghyun Elementary School","SCHUL_KND_SC_NM":"초등학교","LCTN_SC_NM":"서울특별시","JU_ORG_NM":"서울특별시성동광진교육지원청","FOND_SC_NM":"공립","ORG_RDNZC":"04713","ORG_RDNMA":"서울특별시 성동구 행당로 95","ORG_RDNDA":"(행당동)","ORG_TE

In [5]:
response = requests.get(url)
data = response.json()

# 전체 데이터 개수 확인
total = data["neisSchoolInfo"]["list_total_count"]
print(total)

3960

In [6]:
# ① API 응답을 JSON으로 변환
data = response.json()

# ② 실제 데이터(row)만 추출
rows = data['neisSchoolInfo']['row']

# ③ 확인용 출력
print(rows)

# ④ DataFrame으로 변환
school_df = pd.DataFrame(rows)

# ⑤ DataFrame 출력 
school_df

[{'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134161', 'SCHUL_NM': '동국대학교사범대학부속가람중학교', 'ENG_SCHUL_NM': 'Garam Middle School Attached to College of Education, Dongguk University', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '05038', 'ORG_RDNMA': '서울특별시 광진구 광나루로36길 47', 'ORG_RDNDA': ', 동국대학교사범대학부속가람중학교 (구의동)', 'ORG_TELNO': '02-6948-2280', 'HMPG_ADRES': 'https://garam.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-6948-2288', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19300620', 'FOAS_MEMRD': '19300620', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20250302'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134155', 'SCHUL_NM': '선화예술중학교', 'ENG_SCHUL_NM': 'Sunhwa Arts Middle School', 'SCHUL_KND_SC_NM': '각종학교(중)', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '04991', 'ORG_RDNMA': '서울특별시 광진구 천호대로 664', 'ORG_RDNDA': '/ 선화예술중고등학교 (능동)', 'ORG_TELNO': '02-2204-1100', 'HMPG_ADRES': 'https://sunhwaarts.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-453-4641', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19731201', 'FOAS_MEMRD': '19730705', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230627'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134150', 'SCHUL_NM': '서울숭신초등학교', 'ENG_SCHUL_NM': 'Seoul Soongshin Elementary School', 'SCHUL_KND_SC_NM': '초등학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04702', 'ORG_RDNMA': '서울특별시 성동구 마장로 161', 'ORG_RDNDA': '(하왕십리동)', 'ORG_TELNO': '02-2252-5950', 'HMPG_ADRES': 'http://soongshin.sen.es.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2236-6134', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19590403', 'FOAS_MEMRD': '19590403', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134142', 'SCHUL_NM': '행당중학교', 'ENG_SCHUL_NM': 'Haengdang Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04764', 'ORG_RDNMA': '서울특별시 성동구 왕십리로 189', 'ORG_RDNDA': '(행당동/행당중학교)', 'ORG_TELNO': '02-2292-2721', 'HMPG_ADRES': 'http://www.haengdang.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2293-0473', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19680806', 'FOAS_MEMRD': '19681002', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134141', 'SCHUL_NM': '한양대학교사범대학부속중학교', 'ENG_SCHUL_NM': 'Hanyang University Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '04761', 'ORG_RDNMA': '서울특별시 성동구 마조로 42', 'ORG_RDNDA': '(사근동/한양사대부속중·고등학교)', 'ORG_TELNO': '02-2200-3700', 'HMPG_ADRES': 'https://hyu.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2298-3173', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19600118', 'FOAS_MEMRD': '19600118', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134140', 'SCHUL_NM': '자양중학교', 'ENG_SCHUL_NM': 'Jayang Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '05069', 'ORG_RDNMA': '서울특별시 광진구 뚝섬로41길 33', 'ORG_RDNDA': '(자양동/서울자양중학교)', 'ORG_TELNO': '02-446-0365', 'HMPG_ADRES': 'http://jayang.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-458-7047', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19840301', 'FOAS_MEMRD': '19840301', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134139', 'SCHUL_NM': '용곡중학교', 'ENG_SCHUL_NM': 'Yong-gok Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04940', 'ORG_RDNMA': '서울특별시 광진구 용마산로22길 76', 'ORG_RDNDA': '(중곡동/용곡중학교)', 'ORG_TELNO': '02-452-2622', 'HMPG_ADRES': 'http://yonggok.sen.ms.kr/index.do', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-458-8566', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19821209', 'FOAS_MEMRD': '19830504', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134138', 'SCHUL_NM': '옥정중학교', 'ENG_SCHUL_NM': 'Ok-Jung Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04734', 'ORG_RDNMA': '서울특별시 성동구 한림말길 11', 'ORG_RDNDA': '/ 옥정중학교 (옥수동)', 'ORG_TELNO': '02-6021-2100', 'HMPG_ADRES': 'http://okjung.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2298-1303', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19840109', 'FOAS_MEMRD': '19840511', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134137', 'SCHUL_NM': '양진중학교', 'ENG_SCHUL_NM': 'Yangjin Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04982', 'ORG_RDNMA': '서울특별시 광진구 워커힐로 32', 'ORG_RDNDA': '/ 양진중학교', 'ORG_TELNO': '02-2049-1200', 'HMPG_ADRES': 'http://www.yangjin.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2049-1208/1220', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '해당없음', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '20051229', 'FOAS_MEMRD': '20060514', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134136', 'SCHUL_NM': '신양중학교', 'ENG_SCHUL_NM': 'Shinyang Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '05087', 'ORG_RDNMA': '서울특별시 광진구 자양강변길 73', 'ORG_RDNDA': '/ 신양중학교 (자양동)', 'ORG_TELNO': '02-461-1070', 'HMPG_ADRES': 'http://shinyang.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-469-8386', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19840109', 'FOAS_MEMRD': '19840509', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134135', 'SCHUL_NM': '성원중학교', 'ENG_SCHUL_NM': 'Sungwon Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04775', 'ORG_RDNMA': '서울특별시 성동구 성덕정9가길 13', 'ORG_RDNDA': '(성수동2가/ 성원중학교)', 'ORG_TELNO': '02-3408-2558', 'HMPG_ADRES': 'http://www.sungwon.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-463-0676', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19680806', 'FOAS_MEMRD': '19681002', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134134', 'SCHUL_NM': '성수중학교', 'ENG_SCHUL_NM': 'Seongsu Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04768', 'ORG_RDNMA': '서울특별시 성동구 서울숲길 18', 'ORG_RDNDA': '(성수동1가/ 성수중학교)', 'ORG_TELNO': '02-463-4786', 'HMPG_ADRES': 'http://seongsu.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-469-5292', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19671027', 'FOAS_MEMRD': '19671027', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134132', 'SCHUL_NM': '무학중학교', 'ENG_SCHUL_NM': 'Muhak Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04716', 'ORG_RDNMA': '서울특별시 성동구 행당로 120', 'ORG_RDNDA': '(행당동)', 'ORG_TELNO': '02-2298-6141', 'HMPG_ADRES': 'http://muhakg.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2281-5821', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19681001', 'FOAS_MEMRD': '19681001', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134131', 'SCHUL_NM': '마장중학교', 'ENG_SCHUL_NM': 'Majang Junior High School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04753', 'ORG_RDNMA': '서울특별시 성동구 마장로35나길 31', 'ORG_RDNDA': '/ 마장중학교 (마장동)', 'ORG_TELNO': '02-2282-2933', 'HMPG_ADRES': 'http://mj.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2282-2656', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '해당없음', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '20050301', 'FOAS_MEMRD': '20050405', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134130', 'SCHUL_NM': '대원국제중학교', 'ENG_SCHUL_NM': 'Daewon International Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '04939', 'ORG_RDNMA': '서울특별시 광진구 용마산로22길 26', 'ORG_RDNDA': '/ 대원국제중학교 (중곡동)', 'ORG_TELNO': '02-2204-1592', 'HMPG_ADRES': 'http://daewon.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2204-1583', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19770520', 'FOAS_MEMRD': '19770520', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134129', 'SCHUL_NM': '동마중학교', 'ENG_SCHUL_NM': 'Dongma Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04759', 'ORG_RDNMA': '서울특별시 성동구 마조로11길 18', 'ORG_RDNDA': '(마장동)', 'ORG_TELNO': '02-2294-6085', 'HMPG_ADRES': 'http://www.dongma.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2298-0413', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19841208', 'FOAS_MEMRD': '19850426', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134127', 'SCHUL_NM': '구의중학교', 'ENG_SCHUL_NM': 'Guui Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '05022', 'ORG_RDNMA': '서울특별시 광진구 광나루로30길 80', 'ORG_RDNDA': '(화양동)', 'ORG_TELNO': '02-447-4798', 'HMPG_ADRES': 'http://www.guui.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-455-5061', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19840430', 'FOAS_MEMRD': '19840430', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134126', 'SCHUL_NM': '광희중학교', 'ENG_SCHUL_NM': 'Kwanghee Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04742', 'ORG_RDNMA': '서울특별시 성동구 독서당로62길 46', 'ORG_RDNDA': '/ 광희중학교 (응봉동)', 'ORG_TELNO': '02-2298-0250', 'HMPG_ADRES': 'http://www.kwanghee.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2298-0252', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19370521', 'FOAS_MEMRD': '19370521', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134125', 'SCHUL_NM': '광진중학교', 'ENG_SCHUL_NM': 'Gwangjin Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '05114', 'ORG_RDNMA': '서울특별시 광진구 뚝섬로64길 45', 'ORG_RDNDA': '(자양동/광진중학교)', 'ORG_TELNO': '02-447-2886', 'HMPG_ADRES': 'http://gwangjin.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-3436-1508', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19790901', 'FOAS_MEMRD': '19791010', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20250406'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134124', 'SCHUL_NM': '광장중학교', 'ENG_SCHUL_NM': 'Gwangjang Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04966', 'ORG_RDNMA': '서울특별시 광진구 광장로1길 1', 'ORG_RDNDA': '/ 광장중학교 (광장동)', 'ORG_TELNO': '02-452-0745', 'HMPG_ADRES': 'http://www.gwangjang.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-444-5692', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19821209', 'FOAS_MEMRD': '19830406', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134123', 'SCHUL_NM': '광양중학교', 'ENG_SCHUL_NM': 'Kwangyang Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '05104', 'ORG_RDNMA': '서울특별시 광진구 자양로3길 7', 'ORG_RDNDA': '(자양동)', 'ORG_TELNO': '02-452-6922', 'HMPG_ADRES': 'http://kwangyang.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-452-6923', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19860129', 'FOAS_MEMRD': '19860418', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134122', 'SCHUL_NM': '광남중학교', 'ENG_SCHUL_NM': 'Gwangnam Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04973', 'ORG_RDNMA': '서울특별시 광진구 아차산로70길 17-62', 'ORG_RDNDA': '/ 광남중학교 (광장동)', 'ORG_TELNO': '02-456-8792', 'HMPG_ADRES': 'http://www.gwangnam.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-455-0161/453-2818', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19930116', 'FOAS_MEMRD': '19930504', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134121', 'SCHUL_NM': '경일중학교', 'ENG_SCHUL_NM': 'Kyungil Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04779', 'ORG_RDNMA': '서울특별시 성동구 성수일로 27', 'ORG_RDNDA': '(성수동1가)', 'ORG_TELNO': '02-468-0651', 'HMPG_ADRES': 'http://kyungil.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-468-2766', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '해당없음', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '20031230', 'FOAS_MEMRD': '20040506', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134120', 'SCHUL_NM': '경수중학교', 'ENG_SCHUL_NM': 'Gyeongsu Middle School', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '공립', 'ORG_RDNZC': '04785', 'ORG_RDNMA': '서울특별시 성동구 뚝섬로13길 14', 'ORG_RDNDA': '(성수동2가)', 'ORG_TELNO': '02-464-0675', 'HMPG_ADRES': 'http://www.gsu.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-497-0296', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19801227', 'FOAS_MEMRD': '19810504', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134119', 'SCHUL_NM': '건국대학교사범대학부속중학교', 'ENG_SCHUL_NM': 'Middle School Attached To College of Education, KONKUK University', 'SCHUL_KND_SC_NM': '중학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '05025', 'ORG_RDNMA': '서울특별시 광진구 자양로 145-1', 'ORG_RDNDA': '건국대학교사범대학부속중학교', 'ORG_TELNO': '02-457-0318', 'HMPG_ADRES': 'http://konkuk.sen.ms.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-458-7427', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19671230', 'FOAS_MEMRD': '19680515', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134118', 'SCHUL_NM': '한양초등학교', 'ENG_SCHUL_NM': 'Hanyang Elementary School', 'SCHUL_KND_SC_NM': '초등학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '04763', 'ORG_RDNMA': '서울특별시 성동구 살곶이길 208', 'ORG_RDNDA': '/ 한양초등학교 (사근동)', 'ORG_TELNO': '02-2293-8732', 'HMPG_ADRES': 'http://www.hye.or.kr', 'COEDU_SC_NM': '남여공학', 'ORG_FAXNO': '02-2299-3492', 'HS_SC_NM': '', 'INDST_SPECL_CCCCL_EXST_YN': 'N', 'HS_GNRL_BUSNS_SC_NM': '일반계', 'SPCLY_PURPS_HS_ORD_NM': '', 'ENE_BFE_SEHF_SC_NM': '전기', 'DGHT_SC_NM': '주간', 'FOND_YMD': '19660220', 'FOAS_MEMRD': '19660515', 'DGHT_CRSE_SC_NM': '', 'ORD_SC_NM': '', 'DDDEP_NM': '', 'LOAD_DTM': '20230615'}, {'ATPT_OFCDC_SC_CODE': 'B10', 'ATPT_OFCDC_SC_NM': '서울특별시교육청', 'SD_SCHUL_CODE': '7134117', 'SCHUL_NM': '세종초등학교', 'ENG_SCHUL_NM': 'Sejong Elementary School', 'SCHUL_KND_SC_NM': '초등학교', 'LCTN_SC_NM': '서울특별시', 'JU_ORG_NM': '서울특별시성동광진교육지원청', 'FOND_SC_NM': '사립', 'ORG_RDNZC': '05006', 'ORG_RDNMA': '서울특별시 광진구 군자로 114', 'ORG_RDNDA': '/ 세종초등학교 (군자동)', 'ORG_TELNO': '02-

,ATPT_OFCDC_SC_CODE,ATPT_OFCDC_SC_NM,SD_SCHUL_CODE,SCHUL_NM,ENG_SCHUL_NM,SCHUL_KND_SC_NM,LCTN_SC_NM,JU_ORG_NM,FOND_SC_NM,ORG_RDNZC,...,HS_GNRL_BUSNS_SC_NM,SPCLY_PURPS_HS_ORD_NM,ENE_BFE_SEHF_SC_NM,DGHT_SC_NM,FOND_YMD,FOAS_MEMRD,DGHT_CRSE_SC_NM,ORD_SC_NM,DDDEP_NM,LOAD_DTM
0,B10,서울특별시교육청,7134161,동국대학교사범대학부속가람중학교,Garam Middle School Attached to College of Edu...,중학교,서울특별시,서울특별시성동광진교육지원청,사립,05038,...,일반계,,전기,주간,19300620,19300620,,,,20250302
1,B10,서울특별시교육청,7134155,선화예술중학교,Sunhwa Arts Middle School,각종학교(중),서울특별시,서울특별시성동광진교육지원청,사립,04991,...,일반계,,전기,주간,19731201,19730705,,,,20230627
2,B10,서울특별시교육청,7134150,서울숭신초등학교,Seoul Soongshin Elementary School,초등학교,서울특별시,서울특별시성동광진교육지원청,공립,04702,...,일반계,,전기,주간,19590403,19590403,,,,20230615
3,B10,서울특별시교육청,7134142,행당중학교,Haengdang Middle School,중학교,서울특별시,서울특별시성동광진교육지원청,공립,04764,...,일반계,,전기,주간,19680806,19681002,,,,20230615
4,B10,서울특별시교육청,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,중학교,서울특별시,서울특별시성동광진교육지원청,사립,04761,...,일반계,,전기,주간,19600118,19600118,,,,20230615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,B10,서울특별시교육청,7081460,서울양명초등학교,Seoul Yangmyeong Elementary School,초등학교,서울특별시,서울특별시강서양천교육지원청,공립,08091,...,일반계,,전기,주간,19821110,19830511,,,,20230615
496,B10,서울특별시교육청,7081459,서울양동초등학교,Seoul Yangdong Elementary School,초등학교,서울특별시,서울특별시강서양천교육지원청,공립,07942,...,일반계,,전기,주간,19720811,19720811,,,,20230615
497,B10,서울특별시교육청,7081458,서울양강초등학교,Seoul Yang-gang Elementary School,초등학교,서울특별시,서울특별시강서양천교육지원청,공립,07935,...,일반계,,전기,주간,19870423,19870423,,,,20230615
498,B10,서울특별시교육청,7081457,서울신정초등학교,Seoul Sinjeong Elementary School,초등학교,서울특별시,서울특별시강서양천교육지원청,공립,07746,...,일반계,,전기,주간,19491001,19491001,,,,20230615
499,B10,서울특별시교육청,7081456,서울신월초등학교,Seoul Sinwol Elementary School,초등학교,서울특별시,서울특별시강서양천교육지원청,공립,07716,...,일반계,,전기,주간,19750311,19750311,,,,20230628

# 데이터 전처리

In [7]:
### 데이터 전처리 전 확인 할 부분

df = pd.DataFrame(rows)
df.shape        # 행, 열 개수
df.info()       # 컬럼명, 데이터 타입, 결측값 확인
df.describe()   # 숫자 컬럼 통계 요약
df.head()       # 상위 5개 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ATPT_OFCDC_SC_CODE         500 non-null    object
 1   ATPT_OFCDC_SC_NM           500 non-null    object
 2   SD_SCHUL_CODE              500 non-null    object
 3   SCHUL_NM                   500 non-null    object
 4   ENG_SCHUL_NM               500 non-null    object
 5   SCHUL_KND_SC_NM            500 non-null    object
 6   LCTN_SC_NM                 500 non-null    object
 7   JU_ORG_NM                  500 non-null    object
 8   FOND_SC_NM                 500 non-null    object
 9   ORG_RDNZC                  500 non-null    object
 10  ORG_RDNMA                  500 non-null    object
 11  ORG_RDNDA                  500 non-null    object
 12  ORG_TELNO                  500 non-null    object
 13  HMPG_ADRES                 500 non-null    object
 14  COEDU_SC_NM                500 non-null    object
 15  ORG_FAXNO                  500 non-null    object
 16  HS_SC_NM                   500 non-null    object
 17  INDST_SPECL_CCCCL_EXST_YN  500 non-null    object
 18  HS_GNRL_BUSNS_SC_NM        500 non-null    object
 19  SPCLY_PURPS_HS_ORD_NM      500 non-null    object
 20  ENE_BFE_SEHF_SC_NM         500 non-null    object
 21  DGHT_SC_NM                 500 non-null    object
 22  FOND_YMD                   500 non-null    object
 23  FOAS_MEMRD                 500 non-null    object
 24  DGHT_CRSE_SC_NM            500 non-null    object
 25  ORD_SC_NM                  500 non-null    object
 26  DDDEP_NM                   500 non-null    object
 27  LOAD_DTM                   500 non-null    object
dtypes: object(28)
memory usage: 109.5+ KB

,ATPT_OFCDC_SC_CODE,ATPT_OFCDC_SC_NM,SD_SCHUL_CODE,SCHUL_NM,ENG_SCHUL_NM,SCHUL_KND_SC_NM,LCTN_SC_NM,JU_ORG_NM,FOND_SC_NM,ORG_RDNZC,...,HS_GNRL_BUSNS_SC_NM,SPCLY_PURPS_HS_ORD_NM,ENE_BFE_SEHF_SC_NM,DGHT_SC_NM,FOND_YMD,FOAS_MEMRD,DGHT_CRSE_SC_NM,ORD_SC_NM,DDDEP_NM,LOAD_DTM
0,B10,서울특별시교육청,7134161,동국대학교사범대학부속가람중학교,Garam Middle School Attached to College of Edu...,중학교,서울특별시,서울특별시성동광진교육지원청,사립,05038,...,일반계,,전기,주간,19300620,19300620,,,,20250302
1,B10,서울특별시교육청,7134155,선화예술중학교,Sunhwa Arts Middle School,각종학교(중),서울특별시,서울특별시성동광진교육지원청,사립,04991,...,일반계,,전기,주간,19731201,19730705,,,,20230627
2,B10,서울특별시교육청,7134150,서울숭신초등학교,Seoul Soongshin Elementary School,초등학교,서울특별시,서울특별시성동광진교육지원청,공립,04702,...,일반계,,전기,주간,19590403,19590403,,,,20230615
3,B10,서울특별시교육청,7134142,행당중학교,Haengdang Middle School,중학교,서울특별시,서울특별시성동광진교육지원청,공립,04764,...,일반계,,전기,주간,19680806,19681002,,,,20230615
4,B10,서울특별시교육청,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,중학교,서울특별시,서울특별시성동광진교육지원청,사립,04761,...,일반계,,전기,주간,19600118,19600118,,,,20230615

In [12]:
# ① 필요한 컬럼만 선택
school_df = school_df[["SCHUL_NM","ORG_RDNMA"]]

# ② 컬럼명 소문자로 변환
school_df.columns = school_df.columns.str.lower()

# ③ 그 다음에 idx 추가
school_df["idx"] = range(1, len(school_df) + 1)

# ④ idx 맨 앞으로
school_df = school_df[["idx", "schul_nm", "org_rdnma"]]
school_df

C:\Users\user\AppData\Local\Temp\ipykernel_2156\2703526613.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school_df["idx"] = range(1, len(school_df) + 1)

     idx          schul_nm              org_rdnma
0      1  동국대학교사범대학부속가람중학교   서울특별시 광진구 광나루로36길 47
1      2           선화예술중학교     서울특별시 광진구 천호대로 664
2      3          서울숭신초등학교      서울특별시 성동구 마장로 161
3      4             행당중학교     서울특별시 성동구 왕십리로 189
4      5    한양대학교사범대학부속중학교       서울특별시 성동구 마조로 42
..   ...               ...                    ...
495  496          서울양명초등학교      서울특별시 양천구 중앙로 204
496  497          서울양동초등학교    서울특별시 양천구 오목로23길 24
497  498          서울양강초등학교      서울특별시 양천구 오목로 101
498  499          서울신정초등학교  서울특별시 강서구 곰달래로31가길 27
499  500          서울신월초등학교    서울특별시 강서구 강서로31길 48

[500 rows x 3 columns]

In [13]:
# type 변수 추가
school_df['type'] = '학교'
school_df

     idx          schul_nm              org_rdnma type
0      1  동국대학교사범대학부속가람중학교   서울특별시 광진구 광나루로36길 47   학교
1      2           선화예술중학교     서울특별시 광진구 천호대로 664   학교
2      3          서울숭신초등학교      서울특별시 성동구 마장로 161   학교
3      4             행당중학교     서울특별시 성동구 왕십리로 189   학교
4      5    한양대학교사범대학부속중학교       서울특별시 성동구 마조로 42   학교
..   ...               ...                    ...  ...
495  496          서울양명초등학교      서울특별시 양천구 중앙로 204   학교
496  497          서울양동초등학교    서울특별시 양천구 오목로23길 24   학교
497  498          서울양강초등학교      서울특별시 양천구 오목로 101   학교
498  499          서울신정초등학교  서울특별시 강서구 곰달래로31가길 27   학교
499  500          서울신월초등학교    서울특별시 강서구 강서로31길 48   학교

[500 rows x 4 columns]

In [14]:
# 컬럼명 nm,addr 변경
school_df.rename(columns={'schul_nm': 'nm', 'org_rdnma': 'addr'}, inplace=True)

# 확인하기
print(school_df.columns)

Index(['idx', 'nm', 'addr', 'type'], dtype='object')

In [46]:
# 주소지 중복 확인 -> 없음

print(school_df.duplicated(subset=['nm', 'addr']).sum()) # 1

dup_all_mask = school_df.duplicated(subset=['nm', 'addr'], keep=False)
school_df[dup_all_mask].sort_values(['nm', 'addr'])

0

Empty DataFrame
Columns: [idx, nm, addr, type, road_address, lat, lng]
Index: []

# 주소 위도 경도
카카오맵 API 사용

In [47]:
kakao_key  = os.getenv("KAKAO_API_KEY")

In [48]:
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)
params = {"query": "성수동2가 269-25"}  # 입력할 주소
resp = requests.get(url,headers=headers, params=params).json() #카카오 API 요청
                      
print(resp) #API 결과 출력
resp['documents'][0]['road_address']

{'documents': [{'address': {'address_name': '서울 성동구 성수동2가 269-25', 'b_code': '1120011500', 'h_code': '1120067000', 'main_address_no': '269', 'mountain_yn': 'N', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_h_name': '성수2가1동', 'region_3depth_name': '성수동2가', 'sub_address_no': '25', 'x': '127.056741837461', 'y': '37.5402196364231'}, 'address_name': '서울 성동구 성수동2가 269-25', 'address_type': 'REGION_ADDR', 'road_address': {'address_name': '서울 성동구 성수이로10길 14', 'building_name': '에이스 하이엔드 성수타워', 'main_building_no': '14', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_name': '성수동2가', 'road_name': '성수이로10길', 'sub_building_no': '', 'underground_yn': 'N', 'x': '127.056789858953', 'y': '37.5401307747523', 'zone_no': '04784'}, 'x': '127.056741837461', 'y': '37.5402196364231'}], 'meta': {'is_end': True, 'pageable_count': 1, 'total_count': 1}}

{'address_name': '서울 성동구 성수이로10길 14',
 'building_name': '에이스 하이엔드 성수타워',
 'main_building_no': '14',
 'region_1depth_name': '서울',
 'region_2depth_name': '성동구',
 'region_3depth_name': '성수동2가',
 'road_name': '성수이로10길',
 'sub_building_no': '',
 'underground_yn': 'N',
 'x': '127.056789858953',
 'y': '37.5401307747523',
 'zone_no': '04784'}

In [49]:
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)

for idx, add in school_df['addr'].items():
    params = {"query": add}
    resp = requests.get(url, headers=headers, params=params).json()

    docs = resp.get('documents', [])
    if not docs:
        continue

    road = docs[0].get('road_address')  # 없을 수도 있음

    if road:
        school_df.loc[idx, 'road_address'] = road.get('addr')
        school_df.loc[idx, 'lat'] = road.get('y') # Y 좌표값, 경위도인 경우 위도(latitude)
        school_df.loc[idx, 'lng'] = road.get('x') # X 좌표값, 경위도인 경우 경도(longitude)
    else:
        # road_address가 없으면 지번주소(address) 기준으로라도 좌표 저장
        addr = docs[0].get('addr')
        if addr:
            school_df.loc[idx, 'road_address'] = addr.get('addr')
            school_df.loc[idx, 'lat'] = addr.get('y')
            school_df.loc[idx, 'lng'] = addr.get('x')

school_df

,idx,nm,addr,type,road_address,lat,lng
0,1,동국대학교사범대학부속가람중학교,서울특별시 광진구 광나루로36길 47,학교,None,37.5419210650592,127.086977917618
1,2,선화예술중학교,서울특별시 광진구 천호대로 664,학교,None,37.5509798002896,127.087095159462
2,3,서울숭신초등학교,서울특별시 성동구 마장로 161,학교,None,37.5676883077439,127.028005141452
3,4,행당중학교,서울특별시 성동구 왕십리로 189,학교,None,37.5545540364985,127.041963387397
4,5,한양대학교사범대학부속중학교,서울특별시 성동구 마조로 42,학교,None,37.5619188387132,127.042324044658
...,...,...,...,...,...,...,...
495,496,서울양명초등학교,서울특별시 양천구 중앙로 204,학교,None,37.516374951495,126.856634868655
496,497,서울양동초등학교,서울특별시 양천구 오목로23길 24,학교,None,37.5258482641162,126.851240194989
497,498,서울양강초등학교,서울특별시 양천구 오목로 101,학교,None,37.5241103465762,126.847375305566
498,499,서울신정초등학교,서울특별시 강서구 곰달래로31가길 27,학교,None,37.5330611210515,126.852593386106
499,500,서울신월초등학교,서울특별시 강서구 강서로31길 48,학교,None,37.5403655143855,126.839455478388

In [50]:
# 있을 때만 삭제
if "road_address" in school_df.columns:
    school_df.drop(columns=["road_address"], inplace=True)

school_df.to_csv("school.csv", index=False, encoding="utf-8-sig")
print("저장 완료!")

저장 완료!

In [51]:
# 저장 전 확인
school_df.head()

,idx,nm,addr,type,lat,lng
0,1,동국대학교사범대학부속가람중학교,서울특별시 광진구 광나루로36길 47,학교,37.5419210650592,127.086977917618
1,2,선화예술중학교,서울특별시 광진구 천호대로 664,학교,37.5509798002896,127.087095159462
2,3,서울숭신초등학교,서울특별시 성동구 마장로 161,학교,37.5676883077439,127.028005141452
3,4,행당중학교,서울특별시 성동구 왕십리로 189,학교,37.5545540364985,127.041963387397
4,5,한양대학교사범대학부속중학교,서울특별시 성동구 마조로 42,학교,37.5619188387132,127.042324044658

# 서울 병원 인허가 데이터

1. 데이터 불러오기

In [3]:
import time
import json

apikey = os.getenv("HOSPITAL_API_KEY")
all_data = [] # 모든 데이터를 모아둘 리스트

# 1. 전체 데이터 개수 확인
first_url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_010101/1/1/"
response = requests.get(first_url).json()
total_count = response['LOCALDATA_010101']['list_total_count']
print(f"총 데이터 개수: {total_count}")

# 2. 500개씩 끊어서 반복문(for)을 돌립니다.
step = 500
for i in range(1, total_count + 1, step):
    start_index = i
    end_index = i + step - 1
    
    # 마지막 데이터 범위를 넘지 않게 조절
    if end_index > total_count:
        end_index = total_count
        
    url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_010101/{start_index}/{end_index}/"
    
    try:
        response = requests.get(url).json()
        # 데이터가 있는 경우 리스트에 추가
        if 'LOCALDATA_010101' in response and 'row' in response['LOCALDATA_010101']:
            all_data.extend(response['LOCALDATA_010101']['row'])
            print(f"성공: {start_index} ~ {end_index} 가져오기 완료!")
        
        # 서버에 무리가 가지 않게 아주 잠깐 멈춰주는 센스!
        time.sleep(0.1) 
        
    except Exception as e:
        print(f"에러 발생: {e}")

print(f"최종적으로 가져온 데이터 개수: {len(all_data)}")

총 데이터 개수: 905
성공: 1 ~ 500 가져오기 완료!
성공: 501 ~ 905 가져오기 완료!
최종적으로 가져온 데이터 개수: 905

In [4]:
# api key 가져오기

apikey  = os.getenv("HOSPITAL_API_KEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "1000"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_010101/{start_index}/{end_index}/"

response = requests.get(url).json()
print(response)

{'LOCALDATA_010101': {'list_total_count': 905, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}, 'row': [{'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220253220033021200001', 'APVPERMYMD': '2025-04-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6204-1004', 'SITEAREA': '378.02', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 논현동 5-4', 'RDNWHLADDR': '서울특별시 강남구 도산대로 138, 13층 (논현동)', 'RDNPOSTNO': '06039', 'BPLCNM': '리페이스치과병원', 'LASTMODTS': '2025-04-29 17:56:11', 'UPDATEGBN': 'I', 'UPDATEDT': '2024-12-05 00:01:00.0', 'UPTAENM': '치과병원', 'X': '202030.39113325', 'Y': '446137.667598512'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220153220033021200003', 'APVPERMYMD': '2015-07-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-539-2250', 'SITEAREA': '1392.61', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)', 'RDNPOSTNO': '06150', 'BPLCNM': '강남초이스병원', 'LASTMODTS': '2025-04-02 18:21:40', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-04 00:04:00.0', 'UPTAENM': '병원', 'X': '204215.162571746', 'Y': '444731.386522359'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220253220033021200002', 'APVPERMYMD': '2025-08-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-517-1110', 'SITEAREA': '1016.75', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 논현동 49-18 지하1~2층,2~5층', 'RDNWHLADDR': '서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)', 'RDNPOSTNO': '06044', 'BPLCNM': '하병원', 'LASTMODTS': '2025-10-31 16:12:49', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 00:02:00.0', 'UPTAENM': '병원', 'X': '201835.394674853', 'Y': '445560.702719066'}, {'OPNSFTEAMCODE': '3200000', 'MGTNO': 'PHMA219953200033021200001', 'APVPERMYMD': '1995-05-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '1661-8267', 'SITEAREA': '5712.14', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 관악구 관악로 242 (봉천동)', 'RDNPOSTNO': '08735', 'BPLCNM': '강남고려병원', 'LASTMODTS': '2025-04-25 08:58:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-03 22:07:00.0', 'UPTAENM': '병원', 'X': '196106.551569021', 'Y': '442595.671190452'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220163220033021200001', 'APVPERMYMD': '2016-04-21', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-547-4800', 'SITEAREA': '3717.97', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지상1~11층)', 'RDNPOSTNO': '06087', 'BPLCNM': '트리니티병원', 'LASTMODTS': '2025-05-15 09:39:57', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-04 23:07:00.0', 'UPTAENM': '병원', 'X': '205116.195218249', 'Y': '445783.267094395'}, {'OPNSFTEAMCODE': '3150000', 'MGTNO': 'PHMA220253150037021200001', 'APVPERMYMD': '2025-05-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-3665-0823', 'SITEAREA': '1308', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강서구 등촌동 700 플러스존', 'RDNWHLADDR': '서울특별시 강서구 공항대로41길 34, 플러스존 3,8,9층 (등촌동)', 'RDNPOSTNO': '07587', 'BPLCNM': '강서푸른꿈성모어린이병원', 'LASTMODTS': '2025-05-29 09:38:52', 'UPDATEGBN': 'I', 'UPDATEDT': '2024-12-04 21:01:00.0', 'UPTAENM': '병원', 'X': '186299.74267687', 'Y': '450792.016505679'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220053220033021200002', 'APVPERMYMD': '2005-03-03', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-513-8000', 'SITEAREA': '3191.43', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 청담동 47-4 우리들병원', 'RDNWHLADDR': '서울특별시 강남구 학동로 445, 우리들병원 (청담동)', 'RDNPOSTNO': '06068', 'BPLCNM': '우리들병원', 'LASTMODTS': '2025-03-04 17:34:41', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-03 00:06:00.0', 'UPTAENM': '병원', 'X': '204322.029055562', 'Y': '446314.495636826'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220223210034021200001', 'APVPERMYMD': '2022-06-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '0262075678', 'SITEAREA': '978.5', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 서초구 서초동 1302-2 대지스포츠프라자', 'RDNWHLADDR': '서울특별시 서초구 서운로 220, 대지스포츠프라자 4층 (서초동)', 'RDNPOSTNO': '06609', 'BPLCNM': '자이비뇨의학과병원', 'LASTMODTS': '2025-09-03 11:17:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-09 00:06:00.0', 'UPTAENM': '병원', 'X': '201856.625065785', 'Y': '444502.636699224'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220253240033021200002', 'APVPERMYMD': '2025-10-31', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6677-7533', 'SITEAREA': '4644.2', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 양재대로 1463, 5~15층 (길동)', 'RDNPOSTNO': '05353', 'BPLCNM': '강동아너스힐병원', 'LASTMODTS': '2026-01-28 14:57:03', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 21:00:00.0', 'UPTAENM': '병원', 'X': '', 'Y': ''}, {'OPNSFTEAMCODE': '3230000', 'MGTNO': 'PHMA220253230034021200001', 'APVPERMYMD': '2025-04-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2026-01-28', 'CLGSTDT': '2025-10-16', 'CLGENDDT': '2026-03-31', 'ROPNYMD': '', 'SITETEL': '02-6949-6670', 'SITEAREA': '1305.76', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 송파구 방이동 114-3', 'RDNWHLADDR': '서울특별시 송파구 오금로 173, 지하1층~지상6층 (방이동)', 'RDNPOSTNO': '05641', 'BPLCNM': '송파한성병원', 'LASTMODTS': '2026-01-29 14:18:22', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 21:01:00.0', 'UPTAENM': '병원', 'X': '209993.650236547', 'Y': '445282.210026105'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220233210034021200001', 'APVPERMYMD': '2023-06-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '16443878', 'SITEAREA': '2474.69', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 서초구 방배동 936-12 지하1층일부,2~5층', 'RDNWHLADDR': '서울특별시 서초구 방배로 151, 지하1층일부,2~5층 (방배동)', 'RDNPOSTNO': '06672', 'BPLCNM': '척바른병원', 'LASTMODTS': '2026-01-20 10:34:21', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 22:03:00.0', 'UPTAENM': '병원', 'X': '199360.582881543', 'Y': '442777.806241993'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA219833220033021200002', 'APVPERMYMD': '1983-04-04', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2019-3114', 'SITEAREA': '88093.68', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 도곡동 146-92 강남세브란스병원', 'RDNWHLADDR': '서울특별시 강남구 언주로 211, 강남세브란스병원 (도곡동)', 'RDNPOSTNO': '06273', 'BPLCNM': '연세대학교의과대학 강남세브란스병원', 'LASTMODTS': '2026-01-29 14:15:31', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 21:01:00.0', 'UPTAENM': '종합병원', 'X': '204044.915103209', 'Y': '443372.921666623'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA219943220033021200002', 'APVPERMYMD': '1994-04-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '-2222-4888', 'SITEAREA': '2300.89', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강남구 봉은사로 612 (삼성동)', 'RDNPOSTNO': '06170', 'BPLCNM': '(의)가산의료재단 광동병원', 'LASTMODTS': '2025-03-10 15:25:06', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-02 23:02:00.0', 'UPTAENM': '병원', 'X': '205423.286315029', 'Y': '445783.29482639'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220223220033021200002', 'APVPERMYMD': '2022-02-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '-1661-1177', 'SITEAREA': '3447.73', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 대치동 907-16 더드림병원', 'RDNWHLADDR': '서울특별시 강남구 선릉로 404, 더드림병원 (대치동)', 'RDNPOSTNO': '06198', 'BPLCNM': '더드림병원', 'LASTMODTS': '2025-03-14 15:53:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-02 23:06:00.0', 'UPTAENM': '병원', 'X': '204432.710770012', 'Y': '444309.006550907'}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'PHMA220083000034021200001', 'APVPERMYMD': '2008-06-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-10-01', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-766-2004', 'SITEAREA': '', 'SITEPOSTNO': '110-808', 'SITEWHLADDR': '서울특별시 종로구 돈의동 78번지', 'RDNWHLADDR': '서울특별시 종로구 돈화문로9길 26 (돈의동)', 'RDNPOSTNO': '03139', 'BPLCNM': '춘원당한방병원', 'LASTMODTS': '2018-10-01 13:40:47', 'UPDATEGBN': 'U', 'UPDATEDT': '2018-10-03 02:35:18.0', 'UPTAENM': '한방병원', 'X': '199079.009091626    ', 'Y': '452168.088676879    '}, {'OPNSFTEAMCODE': '3200000', 'MGTNO': 'PHMA220053200033021200001', 'APVPERMYMD': '2005-12-07', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-10-31', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '', 'SITEWHLADDR': '관악구 봉천8동 945-10', 'RDNWHLADDR': '서울특별시 관악구 남부순환로 1710 (봉천동)', 'RDNPOSTNO': '151-820', 'BPLCNM': '이너스치과병원', 'LASTMODTS': '2011-10-31 18:06:02', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '치과병원', 'X': '194613.552109266    ', 'Y': '442291.802164704    '}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA219993210034021200001', 'APVPERMYMD': '1999-07-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '6388-8114', 'SITEAREA': '6663.28', 'SITEPOSTNO': '137-820', 'SITEWHLADDR': '서울특별시 서초구 방배동 481번지 10호', 'RDNWHLADDR': '서울특별시 서초구 남부순환로 2151 (방배동)', 'RDNPOSTNO': '06699', 'BPLCNM': '대항병원', 'LASTMODTS': '2025-11-18 18:46:23', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-31 22:00:00.0', 'UPTAENM': '병원', 'X': '198865.609772728', 'Y': '441491.109507535'}, {'OPNSFTEAMCODE': '3030000', 'MGTNO': 'PHMA220253030033021200001', 'APVPERMYMD': '2025-06-23', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6941-1010', 'SITEAREA': '1864.88', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 성동구 용답동 99-2 남주빌딩', 'RDNWHLADDR': '서울특별시 성동구 천호대로 282, 남주빌딩 2~5층 (용답동)', 'RDNPOSTNO': '04804', 'BPLCNM': '성동필한방병원', 'LASTMODTS': '2025-07-07 09:09:48', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-07 00:09:00.0', 'UPTAENM': '한방병원', 'X': '204535.473963137', 'Y': '451612.328704931'}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'PHMA220103000034021200001', 'APVPERMYMD': '2008-09-12', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-10-07', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '3672-2233', 'SITEAREA': '', 'SITEPOSTNO': '110-841', 'SITEWHLADDR': '서울특별시 종로구 창신1동 327번지 2호 금호팰리스 4층', 'RDNWHLADDR': '서울특별시 종로구 지봉로 29 (창신동)', 'RDNPOSTNO': '110-841', 'BPLCNM': '동대문요양병원', 'LASTMODTS': '2011-10-30 14:41:52', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '201282.378349367    ', 'Y': '452249.643664396    '}, {'OPNSFTEAMCODE': '3080000', 'MGTNO': 'PHMA220103080033021200001', 'APVPERMYMD': '2010-03-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '15886853', 'SITEAREA': '7714.93', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강북구 번동 463번지 44호', 'RDNWHLADDR': '서울특별시 강북구 도봉로 374 (번동, 서울현대병원)', 'RDNPOSTNO': '01056', 'BPLCNM': '서울현대병원', 'LASTMODTS': '2026-02-25 11:05:40', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-01 22:07:00.0', 'UPTAENM': '종합병원', 'X': '202451.867599327', 'Y': '459765.521965024'}, {'OPNSFTEAMCODE': '3110000', 'MGTNO': 'PHMA220253110032021200001', 'APVPERMYMD': '2025-05-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6954-1149', 'SITEAREA': '1416.62', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 은평구 응암동 119-33 정원빌딩', 'RDNWHLADDR': '서울특별시 은평구 응암로 267, 정원빌딩 (응암동)', 'RDNPOSTNO': '03455', 'BPLCNM': '내일한방병원', 'LASTMODTS': '2025-12-08 17:28:21', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 23:00:00.0', 'UPTAENM': '한방병원', 'X': '192747.915890233', 'Y': '454846.243806105'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220243240033021200001', 'APVPERMYMD': '2024-01-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6416-1010', 'SITEAREA': '2663.12', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)', 'RDNPOSTNO': '05408', 'BPLCNM': '리움한방병원', 'LASTMODTS': '2025-12-22 10:26:41', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 22:04:00.0', 'UPTAENM': '한방병원', 'X': '211685.290218883', 'Y': '446692.439727784'}, {'OPNSFTEAMCODE': '3230000', 'MGTNO': 'PHMA220243230034021200002', 'APVPERMYMD': '2024-07-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-573-9573', 'SITEAREA': '2077.77', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 송파구 삼전동 180-8 태영빌딩', 'RDNWHLADDR': '서울특별시 송파구 삼학사로 53, 태영빌딩 1~7층 (삼전동)', 'RDNPOSTNO': '05585', 'BPLCNM': '엠에스병원', 'LASTMODTS': '2026-01-21 09:50:37', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 22:03:00.0', 'UPTAENM': '병원', 'X': '208477.775692904', 'Y': '444434.523206585'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220163210034021200001', 'APVPERMYMD': '2016-03-11', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6081-2114', 'SITEAREA': '7495.73', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 서초구 양재대로 54, 지1,2층, 2~9층 (우면동, 서초참병원)', 'RDNPOSTNO': '06768', 'BPLCNM': '의료법인 참예원의료재단 서초참요양병원', 'LASTMODTS': '2026-01-20 10:55:39', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 22:03:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '202173.072903522', 'Y': '439733.691014751'}, {'OPNSFTEAMCODE': '3230000', 'MGTNO': 'PHMA220193230034021200004', 'APVPERMYMD': '2019-05-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-406-0999', 'SITEAREA': '4471.31', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 송파구 마천동 32번지 윤진프라자타워', 'RDNWHLADDR': '서울특별시 송파구 마천로 238, 윤진프라자타워 (마천동)', 'RDNPOSTNO': '05737', 'BPLCNM': '송파그랜드요양병원', 'LASTMODTS': '2026-01-30 11:04:01', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-02 00:04:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '212643.860107402', 'Y': '444170.320122251'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220193240033021200001', 'APVPERMYMD': '2019-01-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-1899-5868', 'SITEAREA': '4025.06', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강동구 성내동 452 지하3, 지하1 일부, 1~5층', 'RDNWHLADDR': '서울특별시 강동구 강동대로 143-52, 지하3, 지하1 일부, 1~5층 (성내동)', 'RDNPOSTNO': '05398', 'BPLCNM': '포레스트한방병원', 'LASTMODTS': '2026-02-24 08:55:42', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-01 22:06:00.0', 'UPTAENM': '한방병원', 'X': '210587.488645319', 'Y': '447299.229870215'}, {'OPNSFTEAMCODE': '3200000', 'MGTNO': 'PHMA220253200033021200001', 'APVPERMYMD': '2025-09-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '1600-3565', 'SITEAREA': '3095.68', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 관악구 봉천동 869-12 대연빌딩', 'RDNWHLADDR': '서울특별시 관악구 남부순환로 1814, 대연빌딩 3,4,8,9층 (봉천동)', 'RDNPOSTNO': '08787', 'BPLCNM': '서울센트럴병원', 'LASTMODTS': '2025-10-21 11:49:46', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-30 22:03:00.0', 'UPTAENM': '병원', 'X': '195647.366393622', 'Y': '442105.342411703'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220073210034021200001', 'APVPERMYMD': '2007-12-31', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '-521-8275', 'SITEAREA': '1995.29', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 서초구 반포대로9길 42 (서초동)', 'RDNPOSTNO': '06709', 'BPLCNM': '의료법인 부원의료재단 서초요양병원', 'LASTMODTS': '2025-11-18 18:29:16', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-31 22:00:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '200757.424328934', 'Y': '442326.157537912'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220253240033021200001', 'APVPERMYMD': '2025-06-23', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6485-1234', 'SITEAREA': '1793.17', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강동구 성내동 77-27', 'RDNWHLADDR': '서울특별시 강동구 올림픽로 628-3, 지하1, 지상2~9층 (성내동)', 'RDNPOSTNO': '05378', 'BPLCNM': '123스텝업병원', 'LASTMODTS': '2025-12-17 14:35:14', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 23:09:00.0', 'UPTAENM': '병원', 'X': '210848.817337376', 'Y': '448349.321294041'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220143240033021200001', 'APVPERMYMD': '2014-02-04', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2225-1234', 'SITEAREA': '13068.4', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 진황도로61길 53, 서울요양병원 (둔촌동)', 'RDNPOSTNO': '05368', 'BPLCNM': '한국보훈복지의료공단 서울요양병원', 'LASTMODTS': '2025-12-29 11:34:11', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 21:01:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '212987.201084796', 'Y': '447504.948775288'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220183240033021200001', 'APVPERMYMD': '2018-02-22', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-1577-0082', 'SITEAREA': '4272.11', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 천호대로 1151 (길동)', 'RDNPOSTNO': '05356', 'BPLCNM': '고은빛여성병원', 'LASTMODTS': '2026-01-02 09:31:24', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-01 00:04:00.0', 'UPTAENM': '병원', 'X': '212244.532512145', 'Y': '447998.326845938'}, {'OPNSFTEAMCODE': '3070000', 'MGTNO': 'PHMA219883070034021200002', 'APVPERMYMD': '1988-03-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-926-7505', 'SITEAREA': '3846.37', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 성북구 안암로 99 (안암동5가)', 'RDNPOSTNO': '02856', 'BPLCNM': '의료법인 우신향병원', 'LASTMODTS': '2026-01-09 11:10:48', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 23:01:00.0', 'UPTAENM': '병원', 'X': '', 'Y': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220143240033021200005', 'APVPERMYMD': '2014-10-28', 'APV

In [5]:
response = requests.get(url)
data = response.json()

# 전체 데이터 개수 확인
total = data["LOCALDATA_010101"]["list_total_count"]
print(total)

905

In [6]:
# ① API 응답을 JSON으로 변환
data = response.json()

# ② 실제 데이터(row)만 추출
rows = data['LOCALDATA_010101']['row']

# ③ 확인용 출력
print(rows)

# ④ DataFrame으로 변환
hospital_df = pd.DataFrame(rows)

# ⑤ DataFrame 출력 
hospital_df

[{'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220253220033021200001', 'APVPERMYMD': '2025-04-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6204-1004', 'SITEAREA': '378.02', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 논현동 5-4', 'RDNWHLADDR': '서울특별시 강남구 도산대로 138, 13층 (논현동)', 'RDNPOSTNO': '06039', 'BPLCNM': '리페이스치과병원', 'LASTMODTS': '2025-04-29 17:56:11', 'UPDATEGBN': 'I', 'UPDATEDT': '2024-12-05 00:01:00.0', 'UPTAENM': '치과병원', 'X': '202030.39113325', 'Y': '446137.667598512'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220153220033021200003', 'APVPERMYMD': '2015-07-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-539-2250', 'SITEAREA': '1392.61', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)', 'RDNPOSTNO': '06150', 'BPLCNM': '강남초이스병원', 'LASTMODTS': '2025-04-02 18:21:40', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-04 00:04:00.0', 'UPTAENM': '병원', 'X': '204215.162571746', 'Y': '444731.386522359'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220253220033021200002', 'APVPERMYMD': '2025-08-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-517-1110', 'SITEAREA': '1016.75', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 논현동 49-18 지하1~2층,2~5층', 'RDNWHLADDR': '서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)', 'RDNPOSTNO': '06044', 'BPLCNM': '하병원', 'LASTMODTS': '2025-10-31 16:12:49', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 00:02:00.0', 'UPTAENM': '병원', 'X': '201835.394674853', 'Y': '445560.702719066'}, {'OPNSFTEAMCODE': '3200000', 'MGTNO': 'PHMA219953200033021200001', 'APVPERMYMD': '1995-05-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '1661-8267', 'SITEAREA': '5712.14', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 관악구 관악로 242 (봉천동)', 'RDNPOSTNO': '08735', 'BPLCNM': '강남고려병원', 'LASTMODTS': '2025-04-25 08:58:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-03 22:07:00.0', 'UPTAENM': '병원', 'X': '196106.551569021', 'Y': '442595.671190452'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220163220033021200001', 'APVPERMYMD': '2016-04-21', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-547-4800', 'SITEAREA': '3717.97', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지상1~11층)', 'RDNPOSTNO': '06087', 'BPLCNM': '트리니티병원', 'LASTMODTS': '2025-05-15 09:39:57', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-04 23:07:00.0', 'UPTAENM': '병원', 'X': '205116.195218249', 'Y': '445783.267094395'}, {'OPNSFTEAMCODE': '3150000', 'MGTNO': 'PHMA220253150037021200001', 'APVPERMYMD': '2025-05-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-3665-0823', 'SITEAREA': '1308', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강서구 등촌동 700 플러스존', 'RDNWHLADDR': '서울특별시 강서구 공항대로41길 34, 플러스존 3,8,9층 (등촌동)', 'RDNPOSTNO': '07587', 'BPLCNM': '강서푸른꿈성모어린이병원', 'LASTMODTS': '2025-05-29 09:38:52', 'UPDATEGBN': 'I', 'UPDATEDT': '2024-12-04 21:01:00.0', 'UPTAENM': '병원', 'X': '186299.74267687', 'Y': '450792.016505679'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220053220033021200002', 'APVPERMYMD': '2005-03-03', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-513-8000', 'SITEAREA': '3191.43', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 청담동 47-4 우리들병원', 'RDNWHLADDR': '서울특별시 강남구 학동로 445, 우리들병원 (청담동)', 'RDNPOSTNO': '06068', 'BPLCNM': '우리들병원', 'LASTMODTS': '2025-03-04 17:34:41', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-03 00:06:00.0', 'UPTAENM': '병원', 'X': '204322.029055562', 'Y': '446314.495636826'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220223210034021200001', 'APVPERMYMD': '2022-06-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '0262075678', 'SITEAREA': '978.5', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 서초구 서초동 1302-2 대지스포츠프라자', 'RDNWHLADDR': '서울특별시 서초구 서운로 220, 대지스포츠프라자 4층 (서초동)', 'RDNPOSTNO': '06609', 'BPLCNM': '자이비뇨의학과병원', 'LASTMODTS': '2025-09-03 11:17:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-09 00:06:00.0', 'UPTAENM': '병원', 'X': '201856.625065785', 'Y': '444502.636699224'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220253240033021200002', 'APVPERMYMD': '2025-10-31', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6677-7533', 'SITEAREA': '4644.2', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 양재대로 1463, 5~15층 (길동)', 'RDNPOSTNO': '05353', 'BPLCNM': '강동아너스힐병원', 'LASTMODTS': '2026-01-28 14:57:03', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 21:00:00.0', 'UPTAENM': '병원', 'X': '', 'Y': ''}, {'OPNSFTEAMCODE': '3230000', 'MGTNO': 'PHMA220253230034021200001', 'APVPERMYMD': '2025-04-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2026-01-28', 'CLGSTDT': '2025-10-16', 'CLGENDDT': '2026-03-31', 'ROPNYMD': '', 'SITETEL': '02-6949-6670', 'SITEAREA': '1305.76', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 송파구 방이동 114-3', 'RDNWHLADDR': '서울특별시 송파구 오금로 173, 지하1층~지상6층 (방이동)', 'RDNPOSTNO': '05641', 'BPLCNM': '송파한성병원', 'LASTMODTS': '2026-01-29 14:18:22', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 21:01:00.0', 'UPTAENM': '병원', 'X': '209993.650236547', 'Y': '445282.210026105'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220233210034021200001', 'APVPERMYMD': '2023-06-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '16443878', 'SITEAREA': '2474.69', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 서초구 방배동 936-12 지하1층일부,2~5층', 'RDNWHLADDR': '서울특별시 서초구 방배로 151, 지하1층일부,2~5층 (방배동)', 'RDNPOSTNO': '06672', 'BPLCNM': '척바른병원', 'LASTMODTS': '2026-01-20 10:34:21', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 22:03:00.0', 'UPTAENM': '병원', 'X': '199360.582881543', 'Y': '442777.806241993'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA219833220033021200002', 'APVPERMYMD': '1983-04-04', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2019-3114', 'SITEAREA': '88093.68', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 도곡동 146-92 강남세브란스병원', 'RDNWHLADDR': '서울특별시 강남구 언주로 211, 강남세브란스병원 (도곡동)', 'RDNPOSTNO': '06273', 'BPLCNM': '연세대학교의과대학 강남세브란스병원', 'LASTMODTS': '2026-01-29 14:15:31', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 21:01:00.0', 'UPTAENM': '종합병원', 'X': '204044.915103209', 'Y': '443372.921666623'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA219943220033021200002', 'APVPERMYMD': '1994-04-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '-2222-4888', 'SITEAREA': '2300.89', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강남구 봉은사로 612 (삼성동)', 'RDNPOSTNO': '06170', 'BPLCNM': '(의)가산의료재단 광동병원', 'LASTMODTS': '2025-03-10 15:25:06', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-02 23:02:00.0', 'UPTAENM': '병원', 'X': '205423.286315029', 'Y': '445783.29482639'}, {'OPNSFTEAMCODE': '3220000', 'MGTNO': 'PHMA220223220033021200002', 'APVPERMYMD': '2022-02-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '-1661-1177', 'SITEAREA': '3447.73', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강남구 대치동 907-16 더드림병원', 'RDNWHLADDR': '서울특별시 강남구 선릉로 404, 더드림병원 (대치동)', 'RDNPOSTNO': '06198', 'BPLCNM': '더드림병원', 'LASTMODTS': '2025-03-14 15:53:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-02 23:06:00.0', 'UPTAENM': '병원', 'X': '204432.710770012', 'Y': '444309.006550907'}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'PHMA220083000034021200001', 'APVPERMYMD': '2008-06-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-10-01', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-766-2004', 'SITEAREA': '', 'SITEPOSTNO': '110-808', 'SITEWHLADDR': '서울특별시 종로구 돈의동 78번지', 'RDNWHLADDR': '서울특별시 종로구 돈화문로9길 26 (돈의동)', 'RDNPOSTNO': '03139', 'BPLCNM': '춘원당한방병원', 'LASTMODTS': '2018-10-01 13:40:47', 'UPDATEGBN': 'U', 'UPDATEDT': '2018-10-03 02:35:18.0', 'UPTAENM': '한방병원', 'X': '199079.009091626    ', 'Y': '452168.088676879    '}, {'OPNSFTEAMCODE': '3200000', 'MGTNO': 'PHMA220053200033021200001', 'APVPERMYMD': '2005-12-07', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-10-31', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '', 'SITEWHLADDR': '관악구 봉천8동 945-10', 'RDNWHLADDR': '서울특별시 관악구 남부순환로 1710 (봉천동)', 'RDNPOSTNO': '151-820', 'BPLCNM': '이너스치과병원', 'LASTMODTS': '2011-10-31 18:06:02', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '치과병원', 'X': '194613.552109266    ', 'Y': '442291.802164704    '}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA219993210034021200001', 'APVPERMYMD': '1999-07-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '6388-8114', 'SITEAREA': '6663.28', 'SITEPOSTNO': '137-820', 'SITEWHLADDR': '서울특별시 서초구 방배동 481번지 10호', 'RDNWHLADDR': '서울특별시 서초구 남부순환로 2151 (방배동)', 'RDNPOSTNO': '06699', 'BPLCNM': '대항병원', 'LASTMODTS': '2025-11-18 18:46:23', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-31 22:00:00.0', 'UPTAENM': '병원', 'X': '198865.609772728', 'Y': '441491.109507535'}, {'OPNSFTEAMCODE': '3030000', 'MGTNO': 'PHMA220253030033021200001', 'APVPERMYMD': '2025-06-23', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6941-1010', 'SITEAREA': '1864.88', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 성동구 용답동 99-2 남주빌딩', 'RDNWHLADDR': '서울특별시 성동구 천호대로 282, 남주빌딩 2~5층 (용답동)', 'RDNPOSTNO': '04804', 'BPLCNM': '성동필한방병원', 'LASTMODTS': '2025-07-07 09:09:48', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-07 00:09:00.0', 'UPTAENM': '한방병원', 'X': '204535.473963137', 'Y': '451612.328704931'}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'PHMA220103000034021200001', 'APVPERMYMD': '2008-09-12', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-10-07', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '3672-2233', 'SITEAREA': '', 'SITEPOSTNO': '110-841', 'SITEWHLADDR': '서울특별시 종로구 창신1동 327번지 2호 금호팰리스 4층', 'RDNWHLADDR': '서울특별시 종로구 지봉로 29 (창신동)', 'RDNPOSTNO': '110-841', 'BPLCNM': '동대문요양병원', 'LASTMODTS': '2011-10-30 14:41:52', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '201282.378349367    ', 'Y': '452249.643664396    '}, {'OPNSFTEAMCODE': '3080000', 'MGTNO': 'PHMA220103080033021200001', 'APVPERMYMD': '2010-03-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '15886853', 'SITEAREA': '7714.93', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강북구 번동 463번지 44호', 'RDNWHLADDR': '서울특별시 강북구 도봉로 374 (번동, 서울현대병원)', 'RDNPOSTNO': '01056', 'BPLCNM': '서울현대병원', 'LASTMODTS': '2026-02-25 11:05:40', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-01 22:07:00.0', 'UPTAENM': '종합병원', 'X': '202451.867599327', 'Y': '459765.521965024'}, {'OPNSFTEAMCODE': '3110000', 'MGTNO': 'PHMA220253110032021200001', 'APVPERMYMD': '2025-05-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6954-1149', 'SITEAREA': '1416.62', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 은평구 응암동 119-33 정원빌딩', 'RDNWHLADDR': '서울특별시 은평구 응암로 267, 정원빌딩 (응암동)', 'RDNPOSTNO': '03455', 'BPLCNM': '내일한방병원', 'LASTMODTS': '2025-12-08 17:28:21', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 23:00:00.0', 'UPTAENM': '한방병원', 'X': '192747.915890233', 'Y': '454846.243806105'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220243240033021200001', 'APVPERMYMD': '2024-01-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6416-1010', 'SITEAREA': '2663.12', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)', 'RDNPOSTNO': '05408', 'BPLCNM': '리움한방병원', 'LASTMODTS': '2025-12-22 10:26:41', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 22:04:00.0', 'UPTAENM': '한방병원', 'X': '211685.290218883', 'Y': '446692.439727784'}, {'OPNSFTEAMCODE': '3230000', 'MGTNO': 'PHMA220243230034021200002', 'APVPERMYMD': '2024-07-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-573-9573', 'SITEAREA': '2077.77', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 송파구 삼전동 180-8 태영빌딩', 'RDNWHLADDR': '서울특별시 송파구 삼학사로 53, 태영빌딩 1~7층 (삼전동)', 'RDNPOSTNO': '05585', 'BPLCNM': '엠에스병원', 'LASTMODTS': '2026-01-21 09:50:37', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 22:03:00.0', 'UPTAENM': '병원', 'X': '208477.775692904', 'Y': '444434.523206585'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220163210034021200001', 'APVPERMYMD': '2016-03-11', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6081-2114', 'SITEAREA': '7495.73', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 서초구 양재대로 54, 지1,2층, 2~9층 (우면동, 서초참병원)', 'RDNPOSTNO': '06768', 'BPLCNM': '의료법인 참예원의료재단 서초참요양병원', 'LASTMODTS': '2026-01-20 10:55:39', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 22:03:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '202173.072903522', 'Y': '439733.691014751'}, {'OPNSFTEAMCODE': '3230000', 'MGTNO': 'PHMA220193230034021200004', 'APVPERMYMD': '2019-05-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-406-0999', 'SITEAREA': '4471.31', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 송파구 마천동 32번지 윤진프라자타워', 'RDNWHLADDR': '서울특별시 송파구 마천로 238, 윤진프라자타워 (마천동)', 'RDNPOSTNO': '05737', 'BPLCNM': '송파그랜드요양병원', 'LASTMODTS': '2026-01-30 11:04:01', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-02 00:04:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '212643.860107402', 'Y': '444170.320122251'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220193240033021200001', 'APVPERMYMD': '2019-01-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-1899-5868', 'SITEAREA': '4025.06', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강동구 성내동 452 지하3, 지하1 일부, 1~5층', 'RDNWHLADDR': '서울특별시 강동구 강동대로 143-52, 지하3, 지하1 일부, 1~5층 (성내동)', 'RDNPOSTNO': '05398', 'BPLCNM': '포레스트한방병원', 'LASTMODTS': '2026-02-24 08:55:42', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-01 22:06:00.0', 'UPTAENM': '한방병원', 'X': '210587.488645319', 'Y': '447299.229870215'}, {'OPNSFTEAMCODE': '3200000', 'MGTNO': 'PHMA220253200033021200001', 'APVPERMYMD': '2025-09-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '1600-3565', 'SITEAREA': '3095.68', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 관악구 봉천동 869-12 대연빌딩', 'RDNWHLADDR': '서울특별시 관악구 남부순환로 1814, 대연빌딩 3,4,8,9층 (봉천동)', 'RDNPOSTNO': '08787', 'BPLCNM': '서울센트럴병원', 'LASTMODTS': '2025-10-21 11:49:46', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-30 22:03:00.0', 'UPTAENM': '병원', 'X': '195647.366393622', 'Y': '442105.342411703'}, {'OPNSFTEAMCODE': '3210000', 'MGTNO': 'PHMA220073210034021200001', 'APVPERMYMD': '2007-12-31', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '-521-8275', 'SITEAREA': '1995.29', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 서초구 반포대로9길 42 (서초동)', 'RDNPOSTNO': '06709', 'BPLCNM': '의료법인 부원의료재단 서초요양병원', 'LASTMODTS': '2025-11-18 18:29:16', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-31 22:00:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '200757.424328934', 'Y': '442326.157537912'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220253240033021200001', 'APVPERMYMD': '2025-06-23', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-6485-1234', 'SITEAREA': '1793.17', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강동구 성내동 77-27', 'RDNWHLADDR': '서울특별시 강동구 올림픽로 628-3, 지하1, 지상2~9층 (성내동)', 'RDNPOSTNO': '05378', 'BPLCNM': '123스텝업병원', 'LASTMODTS': '2025-12-17 14:35:14', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 23:09:00.0', 'UPTAENM': '병원', 'X': '210848.817337376', 'Y': '448349.321294041'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220143240033021200001', 'APVPERMYMD': '2014-02-04', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2225-1234', 'SITEAREA': '13068.4', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 진황도로61길 53, 서울요양병원 (둔촌동)', 'RDNPOSTNO': '05368', 'BPLCNM': '한국보훈복지의료공단 서울요양병원', 'LASTMODTS': '2025-12-29 11:34:11', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-11-01 21:01:00.0', 'UPTAENM': '요양병원(일반요양병원)', 'X': '212987.201084796', 'Y': '447504.948775288'}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220183240033021200001', 'APVPERMYMD': '2018-02-22', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-1577-0082', 'SITEAREA': '4272.11', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 강동구 천호대로 1151 (길동)', 'RDNPOSTNO': '05356', 'BPLCNM': '고은빛여성병원', 'LASTMODTS': '2026-01-02 09:31:24', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-12-01 00:04:00.0', 'UPTAENM': '병원', 'X': '212244.532512145', 'Y': '447998.326845938'}, {'OPNSFTEAMCODE': '3070000', 'MGTNO': 'PHMA219883070034021200002', 'APVPERMYMD': '1988-03-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-926-7505', 'SITEAREA': '3846.37', 'SITEPOSTNO': '', 'SITEWHLADDR': '', 'RDNWHLADDR': '서울특별시 성북구 안암로 99 (안암동5가)', 'RDNPOSTNO': '02856', 'BPLCNM': '의료법인 우신향병원', 'LASTMODTS': '2026-01-09 11:10:48', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-11-30 23:01:00.0', 'UPTAENM': '병원', 'X': '', 'Y': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'PHMA220143240033021200005', 'APVPERMYMD': '2014-10-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD':

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,SITEWHLADDR,RDNWHLADDR,RDNPOSTNO,BPLCNM,LASTMODTS,UPDATEGBN,UPDATEDT,UPTAENM,X,Y
0,3220000,PHMA220253220033021200001,2025-04-29,,01,영업/정상,13,영업중,,,...,서울특별시 강남구 논현동 5-4,"서울특별시 강남구 도산대로 138, 13층 (논현동)",06039,리페이스치과병원,2025-04-29 17:56:11,I,2024-12-05 00:01:00.0,치과병원,202030.39113325,446137.667598512
1,3220000,PHMA220153220033021200003,2015-07-24,,01,영업/정상,13,영업중,,,...,,"서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)",06150,강남초이스병원,2025-04-02 18:21:40,U,2024-12-04 00:04:00.0,병원,204215.162571746,444731.386522359
2,3220000,PHMA220253220033021200002,2025-08-01,,01,영업/정상,13,영업중,,,...,"서울특별시 강남구 논현동 49-18 지하1~2층,2~5층","서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)",06044,하병원,2025-10-31 16:12:49,U,2024-11-01 00:02:00.0,병원,201835.394674853,445560.702719066
3,3200000,PHMA219953200033021200001,1995-05-20,,01,영업/정상,13,영업중,,,...,,서울특별시 관악구 관악로 242 (봉천동),08735,강남고려병원,2025-04-25 08:58:36,U,2024-12-03 22:07:00.0,병원,196106.551569021,442595.671190452
4,3220000,PHMA220163220033021200001,2016-04-21,,01,영업/정상,13,영업중,,,...,,"서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지...",06087,트리니티병원,2025-05-15 09:39:57,U,2024-12-04 23:07:00.0,병원,205116.195218249,445783.267094395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,3240000,PHMA219863240033021200001,1986-10-17,,01,영업/정상,13,영업중,,,...,,서울특별시 강동구 성안로 150 (길동),05355,성심의료재단강동성심병원,2026-02-24 08:55:50,U,2025-12-01 22:06:00.0,종합병원,211883.6883558,448216.574876094
901,3040000,PHMA220073040033021200002,2007-05-28,,01,영업/정상,13,영업중,,,...,서울특별시 광진구 구의2동 80번지 25호,서울특별시 광진구 자양로 215 (구의동),04993,제니스병원,2025-12-30 14:54:56,U,2025-12-01 00:01:00.0,병원,207569.609746903,449364.569115862
902,3010000,PHMA220163010033021200002,2016-09-13,,01,영업/정상,13,영업중,,,...,"서울특별시 중구 흥인동 86 리마크빌 동대문 2,3층","서울특별시 중구 다산로 258, 리마크빌 동대문 2,3층 (흥인동)",04570,참바로병원,2026-02-05 13:42:28,U,2025-12-02 00:07:00.0,병원,201400.824438273,451528.012185815
903,3090000,PHMA219743090033021200001,1974-03-28,,01,영업/정상,13,영업중,,,...,서울특별시 도봉구 쌍문동 388-1 한일병원,"서울특별시 도봉구 우이천로 308, 한일병원 (쌍문동)",01450,의료법인한전의료재단 한일병원,2026-02-10 09:55:42,U,2025-12-01 23:02:00.0,종합병원,202466.119176743,460394.329853007
904,3110000,PHMA219663110032021200001,1966-05-05,,01,영업/정상,13,영업중,,,...,,서울특별시 은평구 백련산로 90 (응암동),03476,서울특별시은평병원,2026-02-13 01:43:18,U,2025-12-01 23:05:00.0,정신병원,193192.019829273,454620.355721841

# 2. 데이터 전처리

In [7]:
### 데이터 전처리 전 확인 할 부분

df = pd.DataFrame(rows)
df.shape        # 행, 열 개수
df.info()       # 컬럼명, 데이터 타입, 결측값 확인
df.describe()   # 숫자 컬럼 통계 요약
df.head()       # 상위 5개 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 905 entries, 0 to 904
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OPNSFTEAMCODE  905 non-null    object
 1   MGTNO          905 non-null    object
 2   APVPERMYMD     905 non-null    object
 3   APVCANCELYMD   905 non-null    object
 4   TRDSTATEGBN    905 non-null    object
 5   TRDSTATENM     905 non-null    object
 6   DTLSTATEGBN    905 non-null    object
 7   DTLSTATENM     905 non-null    object
 8   DCBYMD         905 non-null    object
 9   CLGSTDT        905 non-null    object
 10  CLGENDDT       905 non-null    object
 11  ROPNYMD        905 non-null    object
 12  SITETEL        905 non-null    object
 13  SITEAREA       905 non-null    object
 14  SITEPOSTNO     905 non-null    object
 15  SITEWHLADDR    905 non-null    object
 16  RDNWHLADDR     905 non-null    object
 17  RDNPOSTNO      905 non-null    object
 18  BPLCNM         905 non-null    object
 19  LASTMODTS      905 non-null    object
 20  UPDATEGBN      905 non-null    object
 21  UPDATEDT       905 non-null    object
 22  UPTAENM        905 non-null    object
 23  X              905 non-null    object
 24  Y              905 non-null    object
dtypes: object(25)
memory usage: 176.9+ KB

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,SITEWHLADDR,RDNWHLADDR,RDNPOSTNO,BPLCNM,LASTMODTS,UPDATEGBN,UPDATEDT,UPTAENM,X,Y
0,3220000,PHMA220253220033021200001,2025-04-29,,01,영업/정상,13,영업중,,,...,서울특별시 강남구 논현동 5-4,"서울특별시 강남구 도산대로 138, 13층 (논현동)",06039,리페이스치과병원,2025-04-29 17:56:11,I,2024-12-05 00:01:00.0,치과병원,202030.39113325,446137.667598512
1,3220000,PHMA220153220033021200003,2015-07-24,,01,영업/정상,13,영업중,,,...,,"서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)",06150,강남초이스병원,2025-04-02 18:21:40,U,2024-12-04 00:04:00.0,병원,204215.162571746,444731.386522359
2,3220000,PHMA220253220033021200002,2025-08-01,,01,영업/정상,13,영업중,,,...,"서울특별시 강남구 논현동 49-18 지하1~2층,2~5층","서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)",06044,하병원,2025-10-31 16:12:49,U,2024-11-01 00:02:00.0,병원,201835.394674853,445560.702719066
3,3200000,PHMA219953200033021200001,1995-05-20,,01,영업/정상,13,영업중,,,...,,서울특별시 관악구 관악로 242 (봉천동),08735,강남고려병원,2025-04-25 08:58:36,U,2024-12-03 22:07:00.0,병원,196106.551569021,442595.671190452
4,3220000,PHMA220163220033021200001,2016-04-21,,01,영업/정상,13,영업중,,,...,,"서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지...",06087,트리니티병원,2025-05-15 09:39:57,U,2024-12-04 23:07:00.0,병원,205116.195218249,445783.267094395

In [8]:
# ① API 데이터 → DataFrame 변환
rows = data["LOCALDATA_010101"]["row"]
df = pd.DataFrame(rows)

# ② 바로 소문자 변환 (이 순서 중요!)
df.columns = df.columns.str.lower()

# ③ 확인
print(df.columns.tolist())

['opnsfteamcode', 'mgtno', 'apvpermymd', 'apvcancelymd', 'trdstategbn', 'trdstatenm', 'dtlstategbn', 'dtlstatenm', 'dcbymd', 'clgstdt', 'clgenddt', 'ropnymd', 'sitetel', 'sitearea', 'sitepostno', 'sitewhladdr', 'rdnwhladdr', 'rdnpostno', 'bplcnm', 'lastmodts', 'updategbn', 'updatedt', 'uptaenm', 'x', 'y']

In [9]:
# target_cols 필터링 하기 전에 확인
print("x" in df.columns)  # True인지 확인
print(df[['x','y']].head())  # x,y 둘 다 보이는지 확인

True
                  x                 y
0   202030.39113325  446137.667598512
1  204215.162571746  444731.386522359
2  201835.394674853  445560.702719066
3  196106.551569021  442595.671190452
4  205116.195218249  445783.267094395

In [10]:
import pandas as pd

# DF로 바꾸기
if isinstance(hospital_df, dict):
    hospital_df = pd.DataFrame(hospital_df["LOCALDATA_010101"]["row"])
    print("딕셔너리를 데이터프레임으로 변환했습니다!")

# 2. 이제 모든 컬럼명을 소문자로 바꿉니다
hospital_df.columns = hospital_df.columns.str.lower()

# 3. 원하는 컬럼만 선택
target_cols = [
    "dtlstatenm","bplcnm","uptaenm","rdnwhladdr",]


# 실제로 존재하는 컬럼만 안전하게 필터링해서 가져오기
available_cols = [c for c in target_cols if c in hospital_df.columns]
hospital_df = hospital_df[available_cols]

# 4. idx 추가 (전체 개수에 맞게)
hospital_df["idx"] = range(1, len(hospital_df) + 1)

# 5. idx를 맨 앞으로 보내기
cols = ["idx"] + [c for c in hospital_df.columns if c != "idx"]
hospital_df = hospital_df[cols]

hospital_df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_14188\3892174603.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hospital_df["idx"] = range(1, len(hospital_df) + 1)

,idx,dtlstatenm,bplcnm,uptaenm,rdnwhladdr
0,1,영업중,리페이스치과병원,치과병원,"서울특별시 강남구 도산대로 138, 13층 (논현동)"
1,2,영업중,강남초이스병원,병원,"서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)"
2,3,영업중,하병원,병원,"서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)"
3,4,영업중,강남고려병원,병원,서울특별시 관악구 관악로 242 (봉천동)
4,5,영업중,트리니티병원,병원,"서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지..."

In [11]:
# 컬럼명 nm,addr 변경
hospital_df.rename(columns={'bplcnm': 'nm', 'rdnwhladdr': 'addr', 'uptaenm':'type'}, inplace=True)

# 확인하기
print(hospital_df.columns)

Index(['idx', 'dtlstatenm', 'nm', 'type', 'addr'], dtype='object')

In [20]:
### 영업중 필터링
hospital_df = hospital_df[hospital_df["dtlstatenm"] == "영업중"]
print(len(hospital_df))

555

In [21]:
print(df['dtlstatenm'].unique())  # '영업중'만 남았는지 확인
print(len(df))  # 몇 개 남았는지 확인

['영업중']
555

In [22]:
# type 변수 추가
hospital_df['type'] = '병원'
hospital_df

C:\Users\user\AppData\Local\Temp\ipykernel_14188\921122442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hospital_df['type'] = '병원'

,idx,dtlstatenm,nm,type,addr,lat,lng
0,1,영업중,리페이스치과병원,병원,"서울특별시 강남구 도산대로 138, 13층 (논현동)",37.5174322865518,127.023786242369
1,2,영업중,강남초이스병원,병원,"서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)",37.5047949131565,127.048457476412
2,3,영업중,하병원,병원,"서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)",37.5122664382368,127.021613379337
3,4,영업중,강남고려병원,병원,서울특별시 관악구 관악로 242 (봉천동),37.4856188363947,126.956781703053
4,5,영업중,트리니티병원,병원,"서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지...",37.5142581260954,127.058674361192
...,...,...,...,...,...,...,...
900,901,영업중,성심의료재단강동성심병원,병원,서울특별시 강동구 성안로 150 (길동),37.5361555499193,127.135335702535
901,902,영업중,제니스병원,병원,서울특별시 광진구 자양로 215 (구의동),37.5465132167877,127.08644676217
902,903,영업중,참바로병원,병원,"서울특별시 중구 다산로 258, 리마크빌 동대문 2,3층 (흥인동)",37.5657948536437,127.016623843671
903,904,영업중,의료법인한전의료재단 한일병원,병원,"서울특별시 도봉구 우이천로 308, 한일병원 (쌍문동)",37.6466848477493,127.029058318974
904,905,영업중,서울특별시은평병원,병원,서울특별시 은평구 백련산로 90 (응암동),37.5939702620381,126.923210588363

# KAKAO API 가져오기

In [23]:
kakao_key  = os.getenv("KAKAO_API_KEY")

In [24]:
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)

for idx, add in hospital_df['addr'].items():
    params = {"query": add}
    resp = requests.get(url, headers=headers, params=params).json()

    docs = resp.get('documents', [])
    if not docs:
        continue

    road = docs[0].get('road_address')  # 없을 수도 있음

    if road:
        hospital_df.loc[idx, 'road_address'] = road.get('addr')
        hospital_df.loc[idx, 'lat'] = road.get('y') # Y 좌표값, 경위도인 경우 위도(latitude)
        hospital_df.loc[idx, 'lng'] = road.get('x') # X 좌표값, 경위도인 경우 경도(longitude)
    else:
        # road_address가 없으면 지번주소(address) 기준으로라도 좌표 저장
        addr = docs[0].get('addr')
        if addr:
            hospital_df.loc[idx, 'road_address'] = addr.get('addr')
            hospital_df.loc[idx, 'lat'] = addr.get('y')
            hospital_df.loc[idx, 'lng'] = addr.get('x')

hospital_df

C:\Users\user\AppData\Local\Temp\ipykernel_14188\779468087.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hospital_df.loc[idx, 'road_address'] = road.get('addr')

,idx,dtlstatenm,nm,type,addr,lat,lng,road_address
0,1,영업중,리페이스치과병원,병원,"서울특별시 강남구 도산대로 138, 13층 (논현동)",37.5174322865518,127.023786242369,None
1,2,영업중,강남초이스병원,병원,"서울특별시 강남구 테헤란로 337 (역삼동, 4~9층)",37.5047949131565,127.048457476412,None
2,3,영업중,하병원,병원,"서울특별시 강남구 강남대로132길 5, 지하1~2층,2~5층 (논현동)",37.5122664382368,127.021613379337,None
3,4,영업중,강남고려병원,병원,서울특별시 관악구 관악로 242 (봉천동),37.4856188363947,126.956781703053,None
4,5,영업중,트리니티병원,병원,"서울특별시 강남구 봉은사로 535 (삼성동, 트리니티재활병원빌딩, 지하1,2층, 지...",37.5142581260954,127.058674361192,None
...,...,...,...,...,...,...,...,...
900,901,영업중,성심의료재단강동성심병원,병원,서울특별시 강동구 성안로 150 (길동),37.5361555499193,127.135335702535,None
901,902,영업중,제니스병원,병원,서울특별시 광진구 자양로 215 (구의동),37.5465132167877,127.08644676217,None
902,903,영업중,참바로병원,병원,"서울특별시 중구 다산로 258, 리마크빌 동대문 2,3층 (흥인동)",37.5657948536437,127.016623843671,None
903,904,영업중,의료법인한전의료재단 한일병원,병원,"서울특별시 도봉구 우이천로 308, 한일병원 (쌍문동)",37.6466848477493,127.029058318974,None
904,905,영업중,서울특별시은평병원,병원,서울특별시 은평구 백련산로 90 (응암동),37.5939702620381,126.923210588363,None

### CSV 저장

In [25]:
# 저장 직전 최종 확인
print(f"저장할 데이터 개수: {len(hospital_df)}행")
print(f"최종 컬럼 목록: {list(hospital_df.columns)}")

저장할 데이터 개수: 555행
최종 컬럼 목록: ['idx', 'dtlstatenm', 'nm', 'type', 'addr', 'lat', 'lng', 'road_address']

In [26]:
# road_address 컬럼 삭제
hospital_df.drop(columns=["road_address"], inplace=True)

# CSV 저장
hospital_df.to_csv("hospital_df.csv", index=False, encoding="utf-8-sig")
print("저장 완료!")
print(hospital_df.columns)

저장 완료!
Index(['idx', 'dtlstatenm', 'nm', 'type', 'addr', 'lat', 'lng'], dtype='object')

C:\Users\user\AppData\Local\Temp\ipykernel_14188\3955508371.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hospital_df.drop(columns=["road_address"], inplace=True)

# 서울시 대형학원업 인허가 정보
데이터 가져오기

### 1. 데이터 불러오기

In [31]:
apikey  = os.getenv("ACADEMY_API_KEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "500"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/InstutBuildInfo/{start_index}/{end_index}/" #샘플 URL

response = requests.get(url)
print(response.content.decode('utf-8'))

{"InstutBuildInfo":{"list_total_count":37,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"ID":1.0,"NM":"클릭전원미술학원","ADDR_OLD":"서울특별시 마포구 창전동 6-4번지 ","ADDR":"서울특별시 마포구 와우산로 138 (창전동)","PERMISSION_DT":"20030701","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2180.99","POST":"121880","OWNER_TYPE":"자가","YEAR":"2003","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"3227911","XCODE":"193725.67173100000  ","YCODE":"450452.27169400000  ","PERMISSION_NO":"3130000-210-2003-00001","DETAIL_STAT_NM":"영업"},{"ID":2.0,"NM":"고려직업전문학교","ADDR_OLD":"서울특별시 동작구 노량진동 128-2번지 ","ADDR":"서울특별시 동작구 노량진로 186 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"4196.00","POST":"156801","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"195272.65374800000  ","YCODE":"445959.60330800000  ","PERMISSION_NO":"3190000-210-2011-00001","DETAIL_STAT_NM":"영업"},{"ID":3.0,"NM":"노량진행정고시학원","ADDR_OLD":"서울특별시 동작구 노량진동 151-10번지 ","ADDR":"서울특별시 동작구 노량진로 171 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"6554.42","POST":"156801","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  815 7819","XCODE":"195155.04031900000  ","YCODE":"446063.09385500000  ","PERMISSION_NO":"3190000-210-2011-00006","DETAIL_STAT_NM":"영업"},{"ID":4.0,"NM":"박문각임용고시학원","ADDR_OLD":"서울특별시 동작구 노량진동 151-10번지 ","ADDR":"서울특별시 동작구 노량진로 171 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156801","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"195155.04031900000  ","YCODE":"446063.09385500000  ","PERMISSION_NO":"3190000-210-2011-00018","DETAIL_STAT_NM":"영업"},{"ID":5.0,"NM":"노량진메가스터디입시어학원","ADDR_OLD":"서울특별시 동작구 노량진동 45-3번지 ","ADDR":"서울특별시 동작구 장승배기로 171 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"5400.58","POST":"156800","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"194690.54810500000  ","YCODE":"445950.55603400000  ","PERMISSION_NO":"3190000-210-2011-00019","DETAIL_STAT_NM":"영업"},{"ID":6.0,"NM":"케이지패스원한교고시학원","ADDR_OLD":"서울특별시 동작구 노량진동 45-3번지 ","ADDR":"서울특별시 동작구 장승배기로 171 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2942.13","POST":"156800","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"194690.54810500000  ","YCODE":"445950.55603400000  ","PERMISSION_NO":"3190000-210-2011-00020","DETAIL_STAT_NM":"영업"},{"ID":7.0,"NM":"대성학원","ADDR_OLD":"서울특별시 동작구 노량진동 46-6번지 ","ADDR":"서울특별시 동작구 노량진로 120 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"8426.33","POST":"156800","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  814 3114","XCODE":"194699.88871200000  ","YCODE":"445954.57955900000  ","PERMISSION_NO":"3190000-210-2011-00021","DETAIL_STAT_NM":"영업"},{"ID":8.0,"NM":"희소고시학원","ADDR_OLD":"서울특별시 동작구 노량진동 71-2번지 ","ADDR":"서울특별시 동작구 노량진로 146 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2410.18","POST":"156800","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"194887.03383100000  ","YCODE":"445977.38643200000  ","PERMISSION_NO":"3190000-210-2011-00022","DETAIL_STAT_NM":"영업"},{"ID":9.0,"NM":"이데아빌딩","ADDR_OLD":"서울특별시 동작구 노량진동 71-2번지 1,3,7,8층 ","ADDR":"서울특별시 동작구 노량진로 146 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2356.00","POST":"156800","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  817 2577","XCODE":"194887.03383100000  ","YCODE":"445977.38643200000  ","PERMISSION_NO":"3190000-210-2011-00023","DETAIL_STAT_NM":"영업"},{"ID":10.0,"NM":"노량진비타에듀3.0입시학원","ADDR_OLD":"서울특별시 동작구 노량진동 128-2번지 ","ADDR":"서울특별시 동작구 노량진로 186, 2,3층 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156801","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"195272.65374800000  ","YCODE":"445959.60330800000  ","PERMISSION_NO":"3190000-210-2011-00070","DETAIL_STAT_NM":"영업"},{"ID":11.0,"NM":"아모르이그잼학원","ADDR_OLD":"서울특별시 동작구 노량진동 41-9번지 ","ADDR":"서울특별시 동작구 노량진로 104 (노량진동)","PERMISSION_DT":"20110103","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156800","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  815 6400","XCODE":"194480.64410800000  ","YCODE":"445952.81459900000  ","PERMISSION_NO":"3190000-210-2011-00103","DETAIL_STAT_NM":"영업"},{"ID":12.0,"NM":"케이지패스원제이한교고시학원","ADDR_OLD":"서울특별시 동작구 노량진동 40-14번지 ","ADDR":"서울특별시 동작구 노량진로 114, 3~5층 (노량진동)","PERMISSION_DT":"20140101","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156800","OWNER_TYPE":"","YEAR":"2014","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  870 8500","XCODE":"194572.72707400000  ","YCODE":"445949.98079200000  ","PERMISSION_NO":"3190000-210-2014-00004","DETAIL_STAT_NM":"영업"},{"ID":13.0,"NM":"동우빌딩","ADDR_OLD":"서울특별시 동작구 노량진동 100-1번지 ","ADDR":"서울특별시 동작구 노량진로 158, 2~5층 (노량진동)","PERMISSION_DT":"20140101","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156800","OWNER_TYPE":"","YEAR":"2014","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  817 8264","XCODE":"195009.20559600000  ","YCODE":"445996.70518300000  ","PERMISSION_NO":"3190000-210-2014-00005","DETAIL_STAT_NM":"영업"},{"ID":14.0,"NM":"윈플스 공무원 학원","ADDR_OLD":"서울특별시 동작구 노량진동 147-12번지 ","ADDR":"서울특별시 동작구 노량진로 188, 2~9층 (노량진동)","PERMISSION_DT":"20140101","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156801","OWNER_TYPE":"","YEAR":"2014","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"195297.81276700000  ","YCODE":"445961.85109800000  ","PERMISSION_NO":"3190000-210-2014-00006","DETAIL_STAT_NM":"영업"},{"ID":15.0,"NM":"윌비스고시학원","ADDR_OLD":"서울특별시 동작구 노량진동 116-2번지 ","ADDR":"서울특별시 동작구 만양로 105, 2~5층 (노량진동)","PERMISSION_DT":"20140101","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"156801","OWNER_TYPE":"","YEAR":"2014","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"15440330","XCODE":"195049.67033000000  ","YCODE":"445932.32158800000  ","PERMISSION_NO":"3190000-210-2014-00007","DETAIL_STAT_NM":"영업"},{"ID":16.0,"NM":"중앙학원","ADDR_OLD":"서울특별시 성북구 안암동5가 15-27번지 ","ADDR":"서울특별시 성북구 개운사길 35 (안암동5가)","PERMISSION_DT":"20100401","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"136075","OWNER_TYPE":"","YEAR":"2010","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"202563.16568300000  ","YCODE":"454274.27225300000  ","PERMISSION_NO":"3070000-210-2010-00011","DETAIL_STAT_NM":"영업"},{"ID":17.0,"NM":"세일학원","ADDR_OLD":"서울특별시 성북구 돈암동 7-10번지 ","ADDR":"서울특별시 성북구 정릉로48길 13 (돈암동)","PERMISSION_DT":"20090423","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"136813","OWNER_TYPE":"","YEAR":"2009","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"202367.91674700000  ","YCODE":"455981.39147700000  ","PERMISSION_NO":"3070000-210-2009-00047","DETAIL_STAT_NM":"영업"},{"ID":18.0,"NM":"강남파고다외국어학원","ADDR_OLD":"서울특별시 서초구 서초동 1306-6번지 ,7호 ","ADDR":"서울특별시 서초구 강남대로 419 (서초동,,7호)","PERMISSION_DT":"20070101","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"3177.28","POST":"137070","OWNER_TYPE":"임대","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  20514000","XCODE":"202317.73564700000  ","YCODE":"444482.32732200000  ","PERMISSION_NO":"3210000-210-2007-00316","DETAIL_STAT_NM":"영업"},{"ID":19.0,"NM":"브리티쉬인터네셔널킨더가튼어학학원","ADDR_OLD":"서울특별시 서초구 서초동 1449-9번지 ","ADDR":"서울특별시 서초구 반포대로4길 58 (서초동)","PERMISSION_DT":"20080227","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2428.51","POST":"137867","OWNER_TYPE":"임대","YEAR":"2008","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  597 9025","XCODE":"201412.93386000000  ","YCODE":"442501.27420100000  ","PERMISSION_NO":"3210000-210-2008-00014","DETAIL_STAT_NM":"영업"},{"ID":20.0,"NM":"해커스어학원","ADDR_OLD":"서울특별시 서초구 서초동 1316-15번지 ","ADDR":"서울특별시 서초구 강남대로61길 23 (서초동)","PERMISSION_DT":"20080307","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2579.92","POST":"137856","OWNER_TYPE":"임대","YEAR":"2008","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  564 1737","XCODE":"202152.98830900000  ","YCODE":"444306.31851200000  ","PERMISSION_NO":"3210000-210-2008-00015","DETAIL_STAT_NM":"영업"},{"ID":21.0,"NM":"강남대성입시학원","ADDR_OLD":"서울특별시 서초구 서초동 1657-7번지 ","ADDR":"서울특별시 서초구 서초대로52길 28 (서초동)","PERMISSION_DT":"20080307","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"3536.91","POST":"137881","OWNER_TYPE":"임대","YEAR":"2008","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"5817215","XCODE":"201277.53491300000  ","YCODE":"443673.07342900000  ","PERMISSION_NO":"3210000-210-2008-00016","DETAIL_STAT_NM":"영업"},{"ID":22.0,"NM":"현재어학학원","ADDR_OLD":"서울특별시 서초구 반포동 53-5번지 아싸빌딩 1층일부,2층,3층,4층,5층일부 ","ADDR":"서울특별시 서초구 서초중앙로33길 14 (반포동,아싸빌딩 1층일부,2층,3층,4층,5층일부)","PERMISSION_DT":"20110405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2076.26","POST":"137803","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"200940.56824200000  ","YCODE":"444623.90083700000  ","PERMISSION_NO":"3210000-210-2011-00009","DETAIL_STAT_NM":"영업"},{"ID":23.0,"NM":"교대편입교대본원학원","ADDR_OLD":"서울특별시 서초구 서초동 1694-10번지 4,5,6,7,9층 ","ADDR":"서울특별시 서초구 서초중앙로 148 (서초동,4,5,6,7,9층)","PERMISSION_DT":"20110405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"3094.56","POST":"137883","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"201218.44543400000  ","YCODE":"443949.37052800000  ","PERMISSION_NO":"3210000-210-2011-00010","DETAIL_STAT_NM":"영업"},{"ID":24.0,"NM":"이익훈어학2관학원","ADDR_OLD":"서울특별시 서초구 서초동 1327-13번지 401호, 6~12층 ","ADDR":"서울특별시 서초구 서초대로78길 36 (서초동,401호, 6~12층)","PERMISSION_DT":"20110405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2030.69","POST":"137858","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"202489.82770300000  ","YCODE":"443917.58361100000  ","PERMISSION_NO":"3210000-210-2011-00011","DETAIL_STAT_NM":"영업"},{"ID":25.0,"NM":"피에스에이어학학원","ADDR_OLD":"서울특별시 서초구 서초동 1343-14번지 (1-5층) ","ADDR":"서울특별시 서초구 효령로 388 (서초동,(1-5층))","PERMISSION_DT":"20110405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2022.54","POST":"137861","OWNER_TYPE":"","YEAR":"2011","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"202333.11031200000  ","YCODE":"443127.43862000000  ","PERMISSION_NO":"3210000-210-2011-00012","DETAIL_STAT_NM":"영업"},{"ID":26.0,"NM":"고려학원빌딩","ADDR_OLD":"서울특별시 종로구 숭인동 1368번지 ","ADDR":"서울특별시 종로구 난계로 257 (숭인동)","PERMISSION_DT":"20080102","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"3742.00","POST":"110828","OWNER_TYPE":"","YEAR":"2008","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  22333311","XCODE":"202026.32073300000  ","YCODE":"452788.11275300000  ","PERMISSION_NO":"3000000-210-2008-00227","DETAIL_STAT_NM":"영업"},{"ID":27.0,"NM":"동국대학교 전자계산전공학원","ADDR_OLD":"서울특별시 중구 필동3가 26번지 혜화관 ","ADDR":"","PERMISSION_DT":"20070331","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2501.49","POST":"100273","OWNER_TYPE":"","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"0222603537","XCODE":"","YCODE":"","PERMISSION_NO":"3010000-210-2007-00405","DETAIL_STAT_NM":"영업"},{"ID":28.0,"NM":"종로학원","ADDR_OLD":"서울특별시 중구 중림동 363번지 종로학원 ","ADDR":"서울특별시 중구 청파로 456 (중림동,종로학원)","PERMISSION_DT":"20070331","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"3227.94","POST":"100859","OWNER_TYPE":"","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02  392 1881","XCODE":"197226.17362200000  ","YCODE":"451169.45884600000  ","PERMISSION_NO":"3010000-210-2007-00406","DETAIL_STAT_NM":"영업"},{"ID":29.0,"NM":"상계세일학원","ADDR_OLD":"서울특별시 노원구 상계동 591-7번지 ","ADDR":"서울특별시 노원구 상계로1길 34 (상계동)","PERMISSION_DT":"20150427","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2144.00","POST":"139821","OWNER_TYPE":"","YEAR":"2015","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"205454.32025600000  ","YCODE":"461991.36794100000  ","PERMISSION_NO":"3100000-210-2015-00107","DETAIL_STAT_NM":"영업"},{"ID":30.0,"NM":"강북메가스터디 입시학원","ADDR_OLD":"서울특별시 노원구 상계동 709-2번지 ","ADDR":"서울특별시 노원구 노해로 459 (상계동)","PERMISSION_DT":"20150427","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2712.00","POST":"139942","OWNER_TYPE":"","YEAR":"2015","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"205206.22826500000  ","YCODE":"461626.77351500000  ","PERMISSION_NO":"3100000-210-2015-00108","DETAIL_STAT_NM":"영업"},{"ID":31.0,"NM":"삼육외국어학원","ADDR_OLD":"서울특별시 동대문구 휘경동 287-1번지 ","ADDR":"서울특별시 동대문구 망우로18길 33 (휘경동)","PERMISSION_DT":"20070405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"5644.00","POST":"130878","OWNER_TYPE":"자가","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"205576.58200900000  ","YCODE":"454289.21023000000  ","PERMISSION_NO":"3050000-210-2007-00249","DETAIL_STAT_NM":"영업"},{"ID":32.0,"NM":"제일학원","ADDR_OLD":"서울특별시 동대문구 제기동 1015번지 경동빌딩2~6층 (왕산로 285) ","ADDR":"서울특별시 동대문구 왕산로 147 (제기동,경동빌딩2~6층 (왕산로 285))","PERMISSION_DT":"20070405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"3762.00","POST":"130865","OWNER_TYPE":"자가","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"203505.44798100000  ","YCODE":"453273.96070400000  ","PERMISSION_NO":"3050000-210-2007-00214","DETAIL_STAT_NM":"영업"},{"ID":33.0,"NM":"수도학원","ADDR_OLD":"서울특별시 동대문구 신설동 131-50번지 (왕산로 137) ","ADDR":"서울특별시 동대문구 보문로 6 (신설동,(왕산로 137))","PERMISSION_DT":"20070405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2862.00","POST":"130110","OWNER_TYPE":"자가","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02922 3335","XCODE":"202078.60775600000  ","YCODE":"452954.58756700000  ","PERMISSION_NO":"3050000-210-2007-00058","DETAIL_STAT_NM":"영업"},{"ID":34.0,"NM":"우성빌딩(비타에듀학원)","ADDR_OLD":"서울특별시 동대문구 신설동 76-34번지 (한빛길 16) ","ADDR":"서울특별시 동대문구 한빛로 12 (신설동,(한빛길 16))","PERMISSION_DT":"20070405","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"7368.00","POST":"130810","OWNER_TYPE":"자가","YEAR":"2007","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"02 9241468","XCODE":"202198.57584300000  ","YCODE":"453023.59914500000  ","PERMISSION_NO":"3050000-210-2007-00060","DETAIL_STAT_NM":"영업"},{"ID":35.0,"NM":"동양빌딩(주-IT뱅크멀티캠퍼스학원)","ADDR_OLD":"서울특별시 동대문구 신설동 98-27번지 ","ADDR":"","PERMISSION_DT":"20150421","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"","POST":"130811","OWNER_TYPE":"","YEAR":"2015","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"","XCODE":"202211.304378       ","YCODE":"452650.402462       ","PERMISSION_NO":"3050000-210-2015-00017","DETAIL_STAT_NM":"영업"},{"ID":36.0,"NM":"청담어학원","ADDR_OLD":"서울특별시 양천구 목동 408-121번지 서원빌딩 지상4,5층 ","ADDR":"서울특별시 양천구 오목로 282, 지상4,5층 (목동, 서원빌딩)","PERMISSION_DT":"20030929","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"4009.06","POST":"158806","OWNER_TYPE":"자가","YEAR":"2003","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"0226491881","XCODE":"188381.11391700000  ","YCODE":"447307.41684000000  ","PERMISSION_NO":"3140000-210-2003-00022","DETAIL_STAT_NM":"영업"},{"ID":37.0,"NM":"목동종로입시학원","ADDR_OLD":"서울특별시 양천구 목동 408-116번지 ","ADDR":"서울특별시 양천구 오목로 284 (목동)","PERMISSION_DT":"20011207","STATE":"운영중","STOP_DT":"","SUSPENSION_START_DT":"","SUSPENSION_END_DT":"","RE_OPEN_DT":"","AREA":"2257.76","POST":"158806","OWNER_TYPE":"임대","YEAR":"2001","USEDBYMANYPEOPLE":"N","HYGIENE_TYPE":"공중이용시설","HYGIENE_CONDITIONS":"학원","TEL":"0226492881","XCODE":"188415.65775700000  ","YCODE":"447304.13190600000  ","PERMISSION_NO":"3140000-210-2001-00012","DETAIL_STAT_NM":"영업"}]}}

In [32]:
response = requests.get(url)
academy_df = response.json()

# 전체 데이터 개수 확인
total = academy_df["InstutBuildInfo"]["list_total_count"]
print(total)

37

# 2. 전처리

In [33]:
academy_df = response.json()
total = academy_df["InstutBuildInfo"]["list_total_count"]

# rows 추출 추가!
rows = academy_df["InstutBuildInfo"]["row"]

# 전처리
df = pd.DataFrame(rows)
df.shape
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37 non-null     float64
 1   NM                   37 non-null     object
 2   ADDR_OLD             37 non-null     object
 3   ADDR                 37 non-null     object
 4   PERMISSION_DT        37 non-null     object
 5   STATE                37 non-null     object
 6   STOP_DT              37 non-null     object
 7   SUSPENSION_START_DT  37 non-null     object
 8   SUSPENSION_END_DT    37 non-null     object
 9   RE_OPEN_DT           37 non-null     object
 10  AREA                 37 non-null     object
 11  POST                 37 non-null     object
 12  OWNER_TYPE           37 non-null     object
 13  YEAR                 37 non-null     object
 14  USEDBYMANYPEOPLE     37 non-null     object
 15  HYGIENE_TYPE         37 non-null     object
 16  HYGIENE_CONDITIONS   37 non-null     object
 17  TEL                  37 non-null     object
 18  XCODE                37 non-null     object
 19  YCODE                37 non-null     object
 20  PERMISSION_NO        37 non-null     object
 21  DETAIL_STAT_NM       37 non-null     object
dtypes: float64(1), object(21)
memory usage: 6.5+ KB

,ID,NM,ADDR_OLD,ADDR,PERMISSION_DT,STATE,STOP_DT,SUSPENSION_START_DT,SUSPENSION_END_DT,RE_OPEN_DT,...,OWNER_TYPE,YEAR,USEDBYMANYPEOPLE,HYGIENE_TYPE,HYGIENE_CONDITIONS,TEL,XCODE,YCODE,PERMISSION_NO,DETAIL_STAT_NM
0,1.0,클릭전원미술학원,서울특별시 마포구 창전동 6-4번지,서울특별시 마포구 와우산로 138 (창전동),20030701,운영중,,,,,...,자가,2003,N,공중이용시설,학원,3227911,193725.67173100000,450452.27169400000,3130000-210-2003-00001,영업
1,2.0,고려직업전문학교,서울특별시 동작구 노량진동 128-2번지,서울특별시 동작구 노량진로 186 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,195272.65374800000,445959.60330800000,3190000-210-2011-00001,영업
2,3.0,노량진행정고시학원,서울특별시 동작구 노량진동 151-10번지,서울특별시 동작구 노량진로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,02 815 7819,195155.04031900000,446063.09385500000,3190000-210-2011-00006,영업
3,4.0,박문각임용고시학원,서울특별시 동작구 노량진동 151-10번지,서울특별시 동작구 노량진로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,195155.04031900000,446063.09385500000,3190000-210-2011-00018,영업
4,5.0,노량진메가스터디입시어학원,서울특별시 동작구 노량진동 45-3번지,서울특별시 동작구 장승배기로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,194690.54810500000,445950.55603400000,3190000-210-2011-00019,영업

In [34]:
rows = academy_df["InstutBuildInfo"]["row"]
df = pd.DataFrame(rows)

# 컬럼명 소문자로 변환
df.columns = df.columns.str.lower()
df.head()

,id,nm,addr_old,addr,permission_dt,state,stop_dt,suspension_start_dt,suspension_end_dt,re_open_dt,...,owner_type,year,usedbymanypeople,hygiene_type,hygiene_conditions,tel,xcode,ycode,permission_no,detail_stat_nm
0,1.0,클릭전원미술학원,서울특별시 마포구 창전동 6-4번지,서울특별시 마포구 와우산로 138 (창전동),20030701,운영중,,,,,...,자가,2003,N,공중이용시설,학원,3227911,193725.67173100000,450452.27169400000,3130000-210-2003-00001,영업
1,2.0,고려직업전문학교,서울특별시 동작구 노량진동 128-2번지,서울특별시 동작구 노량진로 186 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,195272.65374800000,445959.60330800000,3190000-210-2011-00001,영업
2,3.0,노량진행정고시학원,서울특별시 동작구 노량진동 151-10번지,서울특별시 동작구 노량진로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,02 815 7819,195155.04031900000,446063.09385500000,3190000-210-2011-00006,영업
3,4.0,박문각임용고시학원,서울특별시 동작구 노량진동 151-10번지,서울특별시 동작구 노량진로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,195155.04031900000,446063.09385500000,3190000-210-2011-00018,영업
4,5.0,노량진메가스터디입시어학원,서울특별시 동작구 노량진동 45-3번지,서울특별시 동작구 장승배기로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,194690.54810500000,445950.55603400000,3190000-210-2011-00019,영업

In [35]:
# 소수점 정수로 변환
df["id"] = df["id"].astype(int)
df.head()

,id,nm,addr_old,addr,permission_dt,state,stop_dt,suspension_start_dt,suspension_end_dt,re_open_dt,...,owner_type,year,usedbymanypeople,hygiene_type,hygiene_conditions,tel,xcode,ycode,permission_no,detail_stat_nm
0,1,클릭전원미술학원,서울특별시 마포구 창전동 6-4번지,서울특별시 마포구 와우산로 138 (창전동),20030701,운영중,,,,,...,자가,2003,N,공중이용시설,학원,3227911,193725.67173100000,450452.27169400000,3130000-210-2003-00001,영업
1,2,고려직업전문학교,서울특별시 동작구 노량진동 128-2번지,서울특별시 동작구 노량진로 186 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,195272.65374800000,445959.60330800000,3190000-210-2011-00001,영업
2,3,노량진행정고시학원,서울특별시 동작구 노량진동 151-10번지,서울특별시 동작구 노량진로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,02 815 7819,195155.04031900000,446063.09385500000,3190000-210-2011-00006,영업
3,4,박문각임용고시학원,서울특별시 동작구 노량진동 151-10번지,서울특별시 동작구 노량진로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,195155.04031900000,446063.09385500000,3190000-210-2011-00018,영업
4,5,노량진메가스터디입시어학원,서울특별시 동작구 노량진동 45-3번지,서울특별시 동작구 장승배기로 171 (노량진동),20110103,운영중,,,,,...,,2011,N,공중이용시설,학원,,194690.54810500000,445950.55603400000,3190000-210-2011-00019,영업

In [36]:
import pandas as pd

# 1. 딕셔너리에서 'row' 데이터만 추출해서 '진짜 표(DataFrame)'로 만듭니다.
# 이미지 6f5202.png의 구조에 맞춘 경로입니다.
if isinstance(academy_df, dict):
    academy_df = pd.DataFrame(academy_df["InstutBuildInfo"]["row"])
    print("딕셔너리를 데이터프레임으로 변환했습니다!")

# 2. 이제 모든 컬럼명을 소문자로 바꿉니다 (대소문자 에러 방지)
academy_df.columns = academy_df.columns.str.lower()

# 3. 원하는 컬럼만 선택 (이제 이 코드가 작동합니다!)
# 주의: API 응답에 실제로 있는 컬럼명인지 확인 후 넣어주세요.
target_cols = ["nm",  "addr"]

# 실제로 존재하는 컬럼만 안전하게 필터링해서 가져오기
available_cols = [c for c in target_cols if c in academy_df.columns]
academy_df = academy_df[available_cols]

# 4. idx 추가 (전체 개수에 맞게)
academy_df["idx"] = range(1, len(academy_df) + 1)

# 5. idx를 맨 앞으로 보내기
cols = ["idx"] + [c for c in academy_df.columns if c != "idx"]
academy_df = academy_df[cols]

academy_df.head()

딕셔너리를 데이터프레임으로 변환했습니다!

   idx             nm                        addr
0    1       클릭전원미술학원    서울특별시 마포구 와우산로 138 (창전동)
1    2       고려직업전문학교   서울특별시 동작구 노량진로 186 (노량진동)
2    3      노량진행정고시학원   서울특별시 동작구 노량진로 171 (노량진동)
3    4      박문각임용고시학원   서울특별시 동작구 노량진로 171 (노량진동)
4    5  노량진메가스터디입시어학원  서울특별시 동작구 장승배기로 171 (노량진동)

### KAKAO API 위도, 경도 가져오기

In [37]:
kakao_key  = os.getenv("KAKAO_API_KEY")

In [40]:
url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": f"KakaoAK {kakao_key}"}

for idx, add in academy_df['addr'].items():
    params = {"query": add}
    resp = requests.get(url, headers=headers, params=params).json()

    docs = resp.get('documents', [])
    if not docs:
        continue

    road = docs[0].get('road_address')

    if road:
        academy_df.loc[idx, 'lat'] = road.get('y')
        academy_df.loc[idx, 'lng'] = road.get('x')
    else:
        addr = docs[0].get('address')  # 'addr' → 'address' 로 수정!
        if addr:
            academy_df.loc[idx, 'lat'] = addr.get('y')
            academy_df.loc[idx, 'lng'] = addr.get('x')

# ① 주소 없는 행 2개 제거
academy_df.dropna(subset=["addr"], inplace=True)

# ② NaN 9개 상세주소 정제 후 재시도
academy_df["addr_clean"] = academy_df["addr"].str.split(",").str[0].str.strip()

for idx, add in academy_df[academy_df["lat"].isna()]["addr_clean"].items():
    params = {"query": add}
    resp = requests.get(url, headers=headers, params=params).json()
    docs = resp.get("documents", [])
    if not docs:
        continue
    road = docs[0].get("road_address")
    if road:
        academy_df.loc[idx, "lat"] = road.get("y")
        academy_df.loc[idx, "lng"] = road.get("x")
    else:
        addr = docs[0].get("address")
        if addr:
            academy_df.loc[idx, "lat"] = addr.get("y")
            academy_df.loc[idx, "lng"] = addr.get("x")

# ③ 그래도 NaN이면 제거
academy_df.dropna(subset=["lat", "lng"], inplace=True)

# ④ 임시 컬럼 제거
academy_df.drop(columns=["addr_clean"], inplace=True)

print(len(academy_df))
academy_df

33

,idx,nm,addr,road_address,lat,lng
0,1,클릭전원미술학원,서울특별시 마포구 와우산로 138 (창전동),None,37.5535716598276,126.928992857947
1,2,고려직업전문학교,서울특별시 동작구 노량진로 186 (노량진동),None,37.5125748616339,126.946031029177
2,3,노량진행정고시학원,서울특별시 동작구 노량진로 171 (노량진동),None,37.5140337441577,126.945198048883
3,4,박문각임용고시학원,서울특별시 동작구 노량진로 171 (노량진동),None,37.5140337441577,126.945198048883
4,5,노량진메가스터디입시어학원,서울특별시 동작구 장승배기로 171 (노량진동),None,37.5130172002473,126.939944867747
5,6,케이지패스원한교고시학원,서울특별시 동작구 장승배기로 171 (노량진동),None,37.5130172002473,126.939944867747
6,7,대성학원,서울특별시 동작구 노량진로 120 (노량진동),None,37.5127373356835,126.939919868723
7,8,희소고시학원,서울특별시 동작구 노량진로 146 (노량진동),None,37.5132655453299,126.942168403859
8,9,이데아빌딩,서울특별시 동작구 노량진로 146 (노량진동),None,37.5132655453299,126.942168403859
9,10,노량진비타에듀3.0입시학원,"서울특별시 동작구 노량진로 186, 2,3층 (노량진동)",NaN,37.5125748616339,126.946031029177
10,11,아모르이그잼학원,서울특별시 동작구 노량진로 104 (노량진동),None,37.5130363319711,126.937570688808
11,12,케이지패스원제이한교고시학원,"서울특별시 동작구 노량진로 114, 3~5층 (노량진동)",NaN,37.5130113794472,126.938612219414
12,13,동우빌딩,"서울특별시 동작구 노량진로 158, 2~5층 (노량진동)",NaN,37.5134328037672,126.943538374682
13,14,윈플스 공무원 학원,"서울특별시 동작구 노량진로 188, 2~9층 (노량진동)",NaN,37.5131653415138,126.946740931469
14,15,윌비스고시학원,"서울특별시 동작구 만양로 105, 2~5층 (노량진동)",NaN,37.5128549427149,126.944007081257
16,17,세일학원,서울특별시 성북구 정릉로48길 13 (돈암동),None,37.6033975514204,127.026809282107
17,18,강남파고다외국어학원,"서울특별시 서초구 강남대로 419 (서초동,,7호)",None,37.4998007315864,127.026210824749
18,19,브리티쉬인터네셔널킨더가튼어학학원,서울특별시 서초구 반포대로4길 58 (서초동),None,37.4819531499502,127.015974701815
19,20,해커스어학원,서울특별시 서초구 강남대로61길 23 (서초동),None,37.4982153593758,127.024347163495
20,21,강남대성입시학원,서울특별시 서초구 서초대로52길 28 (서초동),None,37.4925113593336,127.014445869639
21,22,현재어학학원,"서울특별시 서초구 서초중앙로33길 14 (반포동,아싸빌딩 1층일부,2층,3층,4층,...",None,37.5010788048655,127.010636684264
22,23,교대편입교대본원학원,"서울특별시 서초구 서초중앙로 148 (서초동,4,5,6,7,9층)",None,37.4950009216382,127.013778147123
23,24,이익훈어학2관학원,"서울특별시 서초구 서초대로78길 36 (서초동,401호, 6~12층)",None,37.4947119400032,127.028155068247
24,25,피에스에이어학학원,"서울특별시 서초구 효령로 388 (서초동,(1-5층))",None,37.4874264680583,127.026267219719
25,26,고려학원빌딩,서울특별시 종로구 난계로 257 (숭인동),None,37.5746367985617,127.02291940911
28,29,상계세일학원,서울특별시 노원구 상계로1길 34 (상계동),None,37.6575429499887,127.061812569334
29,30,강북메가스터디 입시학원,서울특별시 노원구 노해로 459 (상계동),None,37.6542594101858,127.058998300206
30,31,삼육외국어학원,서울특별시 동대문구 망우로18길 33 (휘경동),None,37.5881468965245,127.062906725648
31,32,제일학원,"서울특별시 동대문구 왕산로 147 (제기동,경동빌딩2~6층 (왕산로 285))",None,37.5787842338973,127.03965869498
32,33,수도학원,"서울특별시 동대문구 보문로 6 (신설동,(왕산로 137))",None,37.5761433223238,127.02352619506
33,34,우성빌딩(비타에듀학원),"서울특별시 동대문구 한빛로 12 (신설동,(한빛길 16))",None,37.5767579715876,127.024888817848
35,36,청담어학원,"서울특별시 양천구 오목로 282, 지상4,5층 (목동, 서원빌딩)",None,37.5251846768452,126.868558058163
36,37,목동종로입시학원,서울특별시 양천구 오목로 284 (목동),None,37.5251555582672,126.868948851656

### CSV 파일 저장

In [44]:
# CSV 저장
academy_df.to_csv("academy_df.csv", index=False, encoding="utf-8-sig")
print("저장 완료!")
print(academy_df.columns)

저장 완료!
Index(['idx', 'nm', 'addr', 'lat', 'lng'], dtype='object')

# 서울시 무도학원업 인허가 정보
데이터 가져오기

### 1. 데이터 가져오기

In [72]:
apikey  = os.getenv("PHYSICAL_ACADEMY_API_KEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "500"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_103302/{start_index}/{end_index}/" #샘플 URL

response = requests.get(url)
print(response.content.decode('utf-8'))

{"LOCALDATA_103302":{"list_total_count":397,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"OPNSFTEAMCODE":"3040000","MGTNO":"CDFH3301112025000001","APVPERMYMD":"2025-03-18","APVCANCELYMD":"","TRDSTATEGBN":"01","TRDSTATENM":"영업/정상","DTLSTATEGBN":"13","DTLSTATENM":"영업중","DCBYMD":"","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"","SITEWHLADDR":"서울특별시 광진구 중곡동 157-11","RDNWHLADDR":"서울특별시 광진구 능동로38길 10-1, 지층 (중곡동)","RDNPOSTNO":"04929","BPLCNM":"참진댄스스포츠","LASTMODTS":"2025-03-18 18:03:51","UPDATEGBN":"I","UPDATEDT":"2024-12-02 22:00:00.0","UPTAENM":"","X":"207042.230083785","Y":"450582.857383855","CULPHYEDCOBNM":"","PUPRSENM":"","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3090000","MGTNO":"CDFH3301112015000002","APVPERMYMD":"2015-04-15","APVCANCELYMD":"","TRDSTATEGBN":"01","TRDSTATENM":"영업/정상","DTLSTATEGBN":"13","DTLSTATENM":"영업중","DCBYMD":"","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-900-8877","SITEAREA":"","SITEPOSTNO":"","SITEWHLADDR":"서울특별시 도봉구 창동 3-3 콤마프라자 지층","RDNWHLADDR":"서울특별시 도봉구 마들로11길 73, 지층 7,8,9,14,15호 (창동)","RDNPOSTNO":"01414","BPLCNM":"탑댄스 아카데미","LASTMODTS":"2025-10-23 10:11:05","UPDATEGBN":"U","UPDATEDT":"2024-10-30 22:05:00.0","UPTAENM":"","X":"204263.706546457","Y":"461207.244729609","CULPHYEDCOBNM":"","PUPRSENM":"","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112007000001","APVPERMYMD":"2007-10-22","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2013-04-19","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-2273-1911","SITEAREA":"","SITEPOSTNO":"110-290","SITEWHLADDR":"서울특별시 종로구 인사동 75-4번지 ","RDNWHLADDR":"서울특별시 종로구 삼일대로 403-1 (인사동)","RDNPOSTNO":"110-290","BPLCNM":"현대스포츠댄스","LASTMODTS":"2014-08-28 13:46:31","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"198811.965898086    ","Y":"452040.822179636    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112010000002","APVPERMYMD":"2010-04-27","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2017-10-23","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-973-9739","SITEAREA":"","SITEPOSTNO":"110-826","SITEWHLADDR":"서울특별시 종로구 숭인동 304번지 ","RDNWHLADDR":"서울특별시 종로구 종로 346 (숭인동)","RDNPOSTNO":"03114","BPLCNM":"현대스포츠댄스","LASTMODTS":"2017-10-23 15:12:10","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201364.016891795    ","Y":"452297.758597168    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112001000001","APVPERMYMD":"2001-01-11","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-07-28","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-840","SITEWHLADDR":"서울특별시 종로구 창신동 292-0번지 ","RDNWHLADDR":"서울특별시 종로구 종로 335  (창신동)","RDNPOSTNO":"","BPLCNM":"동대문무도학원","LASTMODTS":"2006-03-10 15:45:15","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201238.696068454    ","Y":"452317.86559669     ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"0","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112001000002","APVPERMYMD":"2001-04-11","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2006-03-03","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-290","SITEWHLADDR":"서울특별시 종로구 인사동 75-4번지 ","RDNWHLADDR":"","RDNPOSTNO":"","BPLCNM":"현대댄스","LASTMODTS":"2014-08-28 12:58:54","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"198811.965898086    ","Y":"452040.822179636    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112001000004","APVPERMYMD":"2001-06-01","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-02-24","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 503-24번지 ","RDNWHLADDR":"서울특별시 종로구 청계천로 245-1  (종로5가)","RDNPOSTNO":"","BPLCNM":"C.F","LASTMODTS":"2005-02-24 17:26:01","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200367.526283209    ","Y":"451960.981814808    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"0","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111999000003","APVPERMYMD":"1999-10-02","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2018-12-18","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-2274-4555","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 182-4번지 5통1반 ","RDNWHLADDR":"서울특별시 종로구 동호로 408 (종로5가)","RDNPOSTNO":"03196","BPLCNM":"은이 무도학원","LASTMODTS":"2018-12-18 14:37:36","UPDATEGBN":"U","UPDATEDT":"2018-12-20 02:40:00.0","UPTAENM":"","X":"200127.51876762     ","Y":"452047.758449913    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111999000004","APVPERMYMD":"1999-12-16","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2014-09-25","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 444-5번지 ","RDNWHLADDR":"서울특별시 종로구 종로46길 20  (창신동)","RDNPOSTNO":"","BPLCNM":"콤 비","LASTMODTS":"2014-09-25 17:51:06","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200841.176868527    ","Y":"452049.502624754    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"0","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112000000001","APVPERMYMD":"2000-02-09","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2001-06-27","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 237-1번지 ","RDNWHLADDR":"","RDNPOSTNO":"","BPLCNM":"서울무도학원","LASTMODTS":"2014-08-28 13:14:36","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"","Y":"","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112000000003","APVPERMYMD":"2000-03-17","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-02-04","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 433-1번지 ","RDNWHLADDR":"서울특별시 종로구 종로50길 20 (창신동)","RDNPOSTNO":"110-842","BPLCNM":"DSK댄스스포츠","LASTMODTS":"2014-08-28 13:19:47","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201028.021886289    ","Y":"452082.474392538    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112001000006","APVPERMYMD":"2001-10-29","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2014-04-28","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-853","SITEWHLADDR":"서울특별시 종로구 종로4가 8-0번지 광림빌딩4층 ","RDNWHLADDR":"서울특별시 종로구 종로 195, 4층 (종로4가, 광림빌딩)","RDNPOSTNO":"110-853","BPLCNM":"황실스포츠댄스","LASTMODTS":"2014-09-12 17:15:03","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"199870.080275739    ","Y":"452092.183279631    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112001000007","APVPERMYMD":"2001-11-15","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-02-04","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 433-1번지 ","RDNWHLADDR":"서울특별시 종로구 종로50길 20 (창신동)","RDNPOSTNO":"","BPLCNM":"D.S.K","LASTMODTS":"2015-01-09 16:15:35","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201028.021886289    ","Y":"452082.474392538    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112002000001","APVPERMYMD":"2002-03-25","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-02-04","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 460-1번지 ","RDNWHLADDR":"서울특별시 종로구 종로48길 12 (창신동)","RDNPOSTNO":"","BPLCNM":"LOD댄스스포츠","LASTMODTS":"2014-08-28 13:32:10","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200964.684774217    ","Y":"452138.719846742    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112002000004","APVPERMYMD":"2002-10-28","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-02-07","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 182-5번지 ","RDNWHLADDR":"서울특별시 종로구 동호로 406-1  (종로5가)","RDNPOSTNO":"","BPLCNM":"국 제","LASTMODTS":"2005-02-11 09:06:42","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200129.775227347    ","Y":"452034.69521884     ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"0","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112002000005","APVPERMYMD":"2002-11-11","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2011-07-11","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 231-23번지 ","RDNWHLADDR":"서울특별시 종로구 종로36가길 14  (종로5가)","RDNPOSTNO":"","BPLCNM":"대한무도학원","LASTMODTS":"2011-07-11 17:03:52","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200342.281179853    ","Y":"452034.168308564    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"0","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112003000001","APVPERMYMD":"2003-01-06","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2005-01-03","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-470","SITEWHLADDR":"서울특별시 종로구 연지동 254-1번지 ","RDNWHLADDR":"서울특별시 종로구 종로31길 22  (연지동)","RDNPOSTNO":"","BPLCNM":"스포츠댄스","LASTMODTS":"2005-01-03 11:01:49","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"199913.736412998    ","Y":"452181.573855188    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"0","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112003000002","APVPERMYMD":"2003-10-20","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2006-04-19","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"763-5005","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 420-2번지 ","RDNWHLADDR":"서울특별시 종로구 종로44길 56  (창신동)","RDNPOSTNO":"","BPLCNM":"중앙무도학원","LASTMODTS":"2006-04-20 11:17:49","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201101.50866306     ","Y":"452033.842824901    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"0","LDERCNT":"1","BDNGDNGNUM":"","BDNGYAREA":"926.71","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112005000002","APVPERMYMD":"2005-03-22","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2010-12-30","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"2277-4004","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 257-1번지 ","RDNWHLADDR":"서울특별시 종로구 종로 248-1 (종로5가)","RDNPOSTNO":"","BPLCNM":"정 무도학원","LASTMODTS":"2014-08-28 13:39:47","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200401.722939568    ","Y":"452062.956830205    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"521.04","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112005000003","APVPERMYMD":"2005-03-24","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2015-08-05","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-2268-0119","SITEAREA":"","SITEPOSTNO":"110-836","SITEWHLADDR":"서울특별시 종로구 종로5가 182-14번지 ","RDNWHLADDR":"서울특별시 종로구 종로 224 (종로5가)","RDNPOSTNO":"03196","BPLCNM":"방울스포츠댄스학원","LASTMODTS":"2015-08-06 09:14:47","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200148.604026448    ","Y":"452051.486946608    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111996000005","APVPERMYMD":"1996-09-11","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2016-12-20","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-742-6400","SITEAREA":"","SITEPOSTNO":"110-123","SITEWHLADDR":"서울특별시 종로구 종로3가 26-2번지 ","RDNWHLADDR":"서울특별시 종로구 종로 133 (종로3가)","RDNPOSTNO":"","BPLCNM":"선진 무도학원","LASTMODTS":"2016-12-21 14:18:28","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"199260.723514456    ","Y":"452050.064241471    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301112011000001","APVPERMYMD":"2011-03-31","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2025-06-18","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-764-9788","SITEAREA":"","SITEPOSTNO":"110-825","SITEWHLADDR":"서울특별시 종로구 숭인동 200-8","RDNWHLADDR":"서울특별시 종로구 종로66길 10 (숭인동)","RDNPOSTNO":"03115","BPLCNM":"김동완 댄스학원","LASTMODTS":"2025-06-18 15:55:19","UPDATEGBN":"U","UPDATEDT":"2024-12-05 22:00:00.0","UPTAENM":"","X":"201834.95408039","Y":"452450.347246254","CULPHYEDCOBNM":"","PUPRSENM":"","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111999000001","APVPERMYMD":"1999-01-20","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"1999-11-09","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-840","SITEWHLADDR":"서울특별시 종로구 창신동 292-0번지 ","RDNWHLADDR":"서울특별시 종로구 종로 335  (창신동)","RDNPOSTNO":"","BPLCNM":"동대문","LASTMODTS":"2003-02-07 09:11:15","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201238.696068454    ","Y":"452317.86559669     ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"0","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111999000002","APVPERMYMD":"1999-05-20","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2000-09-08","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 436-64번지 ","RDNWHLADDR":"서울특별시 종로구 청계천로 331  (창신동)","RDNPOSTNO":"","BPLCNM":"유천무도학원","LASTMODTS":"2003-02-07 09:11:15","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"201236.543011311    ","Y":"451980.76162207     ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"0","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111993000001","APVPERMYMD":"1993-01-20","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2008-07-31","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-842","SITEWHLADDR":"서울특별시 종로구 창신동 438-14번지 ","RDNWHLADDR":"서울특별시 종로구 종로46길 33  (창신동)","RDNPOSTNO":"","BPLCNM":"창 신","LASTMODTS":"2008-07-31 17:57:08","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"200831.786288808    ","Y":"451988.829440497    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"0","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111993000002","APVPERMYMD":"1993-08-18","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2006-05-29","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-071","SITEWHLADDR":"서울특별시 종로구 당주동 41번지 ","RDNWHLADDR":"서울특별시 종로구 새문안로5길 11-1 (당주동)","RDNPOSTNO":"","BPLCNM":"한국표준 무도학원","LASTMODTS":"2014-08-28 12:59:48","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"197695.669525769    ","Y":"452110.487747195    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111993000003","APVPERMYMD":"1993-09-09","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2004-02-11","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"02-732-1300","SITEAREA":"","SITEPOSTNO":"110-123","SITEWHLADDR":"서울특별시 종로구 종로3가 28번지 ","RDNWHLADDR":"서울특별시 종로구 종로 137-1 (종로3가)","RDNPOSTNO":"110-123","BPLCNM":"한국볼륨 무도학원","LASTMODTS":"2014-08-28 12:42:58","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"199303.652669443    ","Y":"452050.449446176    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"","BDNGYAREA":"","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111996000001","APVPERMYMD":"1996-02-02","APVCANCELYMD":"","TRDSTATEGBN":"03","TRDSTATENM":"폐업","DTLSTATEGBN":"03","DTLSTATENM":"폐업","DCBYMD":"2012-02-15","CLGSTDT":"","CLGENDDT":"","ROPNYMD":"","SITETEL":"","SITEAREA":"","SITEPOSTNO":"110-290","SITEWHLADDR":"서울특별시 종로구 인사동 170번지 ","RDNWHLADDR":"서울특별시 종로구 인사동길 23 (인사동)","RDNPOSTNO":"","BPLCNM":"장영화땐스 스튜디오","LASTMODTS":"2014-08-28 12:57:23","UPDATEGBN":"I","UPDATEDT":"2018-08-31 23:59:59.0","UPTAENM":"","X":"198713.721333434    ","Y":"452278.103938912    ","CULPHYEDCOBNM":"무도학원업","PUPRSENM":"사립","INSURJNYNCODE":"","LDERCNT":"","BDNGDNGNUM":"0","BDNGYAREA":"0","MEMCOLLTOTSTFNUM":"","DRMKCOBNM":"","BUPNM":""},{"OPNSFTEAMCODE":"3000000","MGTNO":"CDFH3301111996000002","APVPERMYMD":

In [73]:
response = requests.get(url)
data = response.json()

# 전체 데이터 개수 확인
total = data["LOCALDATA_103302"]["list_total_count"]
print(total)

397

In [74]:
# ① API 응답을 JSON으로 변환
data = response.json()

# ② 실제 데이터(row)만 추출
rows = data['LOCALDATA_103302']['row']

# ③ 확인용 출력
print(rows)

# ④ DataFrame으로 변환
physical_df = pd.DataFrame(rows)

# ⑤ DataFrame 출력 
physical_df

[{'OPNSFTEAMCODE': '3040000', 'MGTNO': 'CDFH3301112025000001', 'APVPERMYMD': '2025-03-18', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 광진구 중곡동 157-11', 'RDNWHLADDR': '서울특별시 광진구 능동로38길 10-1, 지층 (중곡동)', 'RDNPOSTNO': '04929', 'BPLCNM': '참진댄스스포츠', 'LASTMODTS': '2025-03-18 18:03:51', 'UPDATEGBN': 'I', 'UPDATEDT': '2024-12-02 22:00:00.0', 'UPTAENM': '', 'X': '207042.230083785', 'Y': '450582.857383855', 'CULPHYEDCOBNM': '', 'PUPRSENM': '', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3090000', 'MGTNO': 'CDFH3301112015000002', 'APVPERMYMD': '2015-04-15', 'APVCANCELYMD': '', 'TRDSTATEGBN': '01', 'TRDSTATENM': '영업/정상', 'DTLSTATEGBN': '13', 'DTLSTATENM': '영업중', 'DCBYMD': '', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-900-8877', 'SITEAREA': '', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 도봉구 창동 3-3 콤마프라자 지층', 'RDNWHLADDR': '서울특별시 도봉구 마들로11길 73, 지층 7,8,9,14,15호 (창동)', 'RDNPOSTNO': '01414', 'BPLCNM': '탑댄스 아카데미', 'LASTMODTS': '2025-10-23 10:11:05', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-10-30 22:05:00.0', 'UPTAENM': '', 'X': '204263.706546457', 'Y': '461207.244729609', 'CULPHYEDCOBNM': '', 'PUPRSENM': '', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112007000001', 'APVPERMYMD': '2007-10-22', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2013-04-19', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2273-1911', 'SITEAREA': '', 'SITEPOSTNO': '110-290', 'SITEWHLADDR': '서울특별시 종로구 인사동 75-4번지 ', 'RDNWHLADDR': '서울특별시 종로구 삼일대로 403-1 (인사동)', 'RDNPOSTNO': '110-290', 'BPLCNM': '현대스포츠댄스', 'LASTMODTS': '2014-08-28 13:46:31', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '198811.965898086    ', 'Y': '452040.822179636    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112010000002', 'APVPERMYMD': '2010-04-27', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2017-10-23', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-973-9739', 'SITEAREA': '', 'SITEPOSTNO': '110-826', 'SITEWHLADDR': '서울특별시 종로구 숭인동 304번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로 346 (숭인동)', 'RDNPOSTNO': '03114', 'BPLCNM': '현대스포츠댄스', 'LASTMODTS': '2017-10-23 15:12:10', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201364.016891795    ', 'Y': '452297.758597168    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112001000001', 'APVPERMYMD': '2001-01-11', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-07-28', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-840', 'SITEWHLADDR': '서울특별시 종로구 창신동 292-0번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로 335  (창신동)', 'RDNPOSTNO': '', 'BPLCNM': '동대문무도학원', 'LASTMODTS': '2006-03-10 15:45:15', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201238.696068454    ', 'Y': '452317.86559669     ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112001000002', 'APVPERMYMD': '2001-04-11', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2006-03-03', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-290', 'SITEWHLADDR': '서울특별시 종로구 인사동 75-4번지 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '현대댄스', 'LASTMODTS': '2014-08-28 12:58:54', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '198811.965898086    ', 'Y': '452040.822179636    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112001000004', 'APVPERMYMD': '2001-06-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-02-24', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 503-24번지 ', 'RDNWHLADDR': '서울특별시 종로구 청계천로 245-1  (종로5가)', 'RDNPOSTNO': '', 'BPLCNM': 'C.F', 'LASTMODTS': '2005-02-24 17:26:01', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200367.526283209    ', 'Y': '451960.981814808    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111999000003', 'APVPERMYMD': '1999-10-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-12-18', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2274-4555', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 182-4번지 5통1반 ', 'RDNWHLADDR': '서울특별시 종로구 동호로 408 (종로5가)', 'RDNPOSTNO': '03196', 'BPLCNM': '은이 무도학원', 'LASTMODTS': '2018-12-18 14:37:36', 'UPDATEGBN': 'U', 'UPDATEDT': '2018-12-20 02:40:00.0', 'UPTAENM': '', 'X': '200127.51876762     ', 'Y': '452047.758449913    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111999000004', 'APVPERMYMD': '1999-12-16', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2014-09-25', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 444-5번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로46길 20  (창신동)', 'RDNPOSTNO': '', 'BPLCNM': '콤 비', 'LASTMODTS': '2014-09-25 17:51:06', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200841.176868527    ', 'Y': '452049.502624754    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112000000001', 'APVPERMYMD': '2000-02-09', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2001-06-27', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 237-1번지 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '서울무도학원', 'LASTMODTS': '2014-08-28 13:14:36', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '', 'Y': '', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112000000003', 'APVPERMYMD': '2000-03-17', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-02-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 433-1번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로50길 20 (창신동)', 'RDNPOSTNO': '110-842', 'BPLCNM': 'DSK댄스스포츠', 'LASTMODTS': '2014-08-28 13:19:47', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201028.021886289    ', 'Y': '452082.474392538    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112001000006', 'APVPERMYMD': '2001-10-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2014-04-28', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-853', 'SITEWHLADDR': '서울특별시 종로구 종로4가 8-0번지 광림빌딩4층 ', 'RDNWHLADDR': '서울특별시 종로구 종로 195, 4층 (종로4가, 광림빌딩)', 'RDNPOSTNO': '110-853', 'BPLCNM': '황실스포츠댄스', 'LASTMODTS': '2014-09-12 17:15:03', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '199870.080275739    ', 'Y': '452092.183279631    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112001000007', 'APVPERMYMD': '2001-11-15', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-02-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 433-1번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로50길 20 (창신동)', 'RDNPOSTNO': '', 'BPLCNM': 'D.S.K', 'LASTMODTS': '2015-01-09 16:15:35', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201028.021886289    ', 'Y': '452082.474392538    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112002000001', 'APVPERMYMD': '2002-03-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-02-04', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 460-1번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로48길 12 (창신동)', 'RDNPOSTNO': '', 'BPLCNM': 'LOD댄스스포츠', 'LASTMODTS': '2014-08-28 13:32:10', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200964.684774217    ', 'Y': '452138.719846742    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112002000004', 'APVPERMYMD': '2002-10-28', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-02-07', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 182-5번지 ', 'RDNWHLADDR': '서울특별시 종로구 동호로 406-1  (종로5가)', 'RDNPOSTNO': '', 'BPLCNM': '국 제', 'LASTMODTS': '2005-02-11 09:06:42', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200129.775227347    ', 'Y': '452034.69521884     ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112002000005', 'APVPERMYMD': '2002-11-11', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-07-11', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 231-23번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로36가길 14  (종로5가)', 'RDNPOSTNO': '', 'BPLCNM': '대한무도학원', 'LASTMODTS': '2011-07-11 17:03:52', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200342.281179853    ', 'Y': '452034.168308564    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112003000001', 'APVPERMYMD': '2003-01-06', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-01-03', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-470', 'SITEWHLADDR': '서울특별시 종로구 연지동 254-1번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로31길 22  (연지동)', 'RDNPOSTNO': '', 'BPLCNM': '스포츠댄스', 'LASTMODTS': '2005-01-03 11:01:49', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '199913.736412998    ', 'Y': '452181.573855188    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112003000002', 'APVPERMYMD': '2003-10-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2006-04-19', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '763-5005', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 420-2번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로44길 56  (창신동)', 'RDNPOSTNO': '', 'BPLCNM': '중앙무도학원', 'LASTMODTS': '2006-04-20 11:17:49', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201101.50866306     ', 'Y': '452033.842824901    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '1', 'BDNGDNGNUM': '', 'BDNGYAREA': '926.71', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112005000002', 'APVPERMYMD': '2005-03-22', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2010-12-30', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '2277-4004', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 257-1번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로 248-1 (종로5가)', 'RDNPOSTNO': '', 'BPLCNM': '정 무도학원', 'LASTMODTS': '2014-08-28 13:39:47', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200401.722939568    ', 'Y': '452062.956830205    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '521.04', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112005000003', 'APVPERMYMD': '2005-03-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2015-08-05', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-2268-0119', 'SITEAREA': '', 'SITEPOSTNO': '110-836', 'SITEWHLADDR': '서울특별시 종로구 종로5가 182-14번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로 224 (종로5가)', 'RDNPOSTNO': '03196', 'BPLCNM': '방울스포츠댄스학원', 'LASTMODTS': '2015-08-06 09:14:47', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200148.604026448    ', 'Y': '452051.486946608    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111996000005', 'APVPERMYMD': '1996-09-11', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2016-12-20', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-742-6400', 'SITEAREA': '', 'SITEPOSTNO': '110-123', 'SITEWHLADDR': '서울특별시 종로구 종로3가 26-2번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로 133 (종로3가)', 'RDNPOSTNO': '', 'BPLCNM': '선진 무도학원', 'LASTMODTS': '2016-12-21 14:18:28', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '199260.723514456    ', 'Y': '452050.064241471    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301112011000001', 'APVPERMYMD': '2011-03-31', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2025-06-18', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-764-9788', 'SITEAREA': '', 'SITEPOSTNO': '110-825', 'SITEWHLADDR': '서울특별시 종로구 숭인동 200-8', 'RDNWHLADDR': '서울특별시 종로구 종로66길 10 (숭인동)', 'RDNPOSTNO': '03115', 'BPLCNM': '김동완 댄스학원', 'LASTMODTS': '2025-06-18 15:55:19', 'UPDATEGBN': 'U', 'UPDATEDT': '2024-12-05 22:00:00.0', 'UPTAENM': '', 'X': '201834.95408039', 'Y': '452450.347246254', 'CULPHYEDCOBNM': '', 'PUPRSENM': '', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111999000001', 'APVPERMYMD': '1999-01-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '1999-11-09', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-840', 'SITEWHLADDR': '서울특별시 종로구 창신동 292-0번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로 335  (창신동)', 'RDNPOSTNO': '', 'BPLCNM': '동대문', 'LASTMODTS': '2003-02-07 09:11:15', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201238.696068454    ', 'Y': '452317.86559669     ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111999000002', 'APVPERMYMD': '1999-05-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2000-09-08', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 436-64번지 ', 'RDNWHLADDR': '서울특별시 종로구 청계천로 331  (창신동)', 'RDNPOSTNO': '', 'BPLCNM': '유천무도학원', 'LASTMODTS': '2003-02-07 09:11:15', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '201236.543011311    ', 'Y': '451980.76162207     ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111993000001', 'APVPERMYMD': '1993-01-20', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2008-07-31', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-842', 'SITEWHLADDR': '서울특별시 종로구 창신동 438-14번지 ', 'RDNWHLADDR': '서울특별시 종로구 종로46길 33  (창신동)', 'RDNPOSTNO': '', 'BPLCNM': '창 신', 'LASTMODTS': '2008-07-31 17:57:08', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '200831.786288808    ', 'Y': '451988.829440497    ', 'CULPHYEDCOBNM': '무도학원업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3000000', 'MGTNO': 'CDFH3301111993000002', 'APVPERMYMD': '1993-08-18', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2006-05-29', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '110-071', 'SITEWHLADDR': '서울특별시 종로구 당주동 41번지 ', 'RDNWHLADDR': '서울특별시 종로구 새문안로5길 11-1 (당주동)', 'RDNPOSTNO': '', 'BPLCNM': '한국표준 무도학원', 'LASTMODTS': '2014-08-28 12:59:48', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '197695.669525769    ', 'Y': '452110.487747195    ', 'CULPH

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,Y,CULPHYEDCOBNM,PUPRSENM,INSURJNYNCODE,LDERCNT,BDNGDNGNUM,BDNGYAREA,MEMCOLLTOTSTFNUM,DRMKCOBNM,BUPNM
0,3040000,CDFH3301112025000001,2025-03-18,,01,영업/정상,13,영업중,,,...,450582.857383855,,,,,,,,,
1,3090000,CDFH3301112015000002,2015-04-15,,01,영업/정상,13,영업중,,,...,461207.244729609,,,,,,,,,
2,3000000,CDFH3301112007000001,2007-10-22,,03,폐업,03,폐업,2013-04-19,,...,452040.822179636,무도학원업,사립,,,,,,,
3,3000000,CDFH3301112010000002,2010-04-27,,03,폐업,03,폐업,2017-10-23,,...,452297.758597168,무도학원업,사립,,,,,,,
4,3000000,CDFH3301112001000001,2001-01-11,,03,폐업,03,폐업,2005-07-28,,...,452317.86559669,무도학원업,사립,0,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,3240000,CDFH3301112005000004,2005-07-25,,04,취소/말소/만료/정지/중지,35,직권말소,2021-12-15,,...,448108.629965194,무도학원업,사립,Y,0,1,196.43,0,,
393,3240000,CDFH3301112007000001,2007-12-04,,04,취소/말소/만료/정지/중지,35,직권말소,2018-02-23,,...,448257.541433568,무도학원업,사립,,,1,3298,,,
394,3240000,CDFH3301112002000004,2002-12-16,,03,폐업,03,폐업,2025-04-07,,...,448345.727351302,,,,,,,,,
395,3240000,CDFH3301112013000001,2013-05-20,,01,영업/정상,13,영업중,,,...,448450.575807613,,,,,,,,,
396,3180000,CDFH3301112018000002,2018-09-19,,01,영업/정상,13,영업중,,,...,446265.282454703,,,,,,,,,

### 2. 데이터 전처리

In [75]:
### 데이터 전처리 전 확인 할 부분

df = pd.DataFrame(rows)
df.shape        # 행, 열 개수
df.info()       # 컬럼명, 데이터 타입, 결측값 확인
df.describe()   # 숫자 컬럼 통계 요약
df.head()       # 상위 5개 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OPNSFTEAMCODE     397 non-null    object
 1   MGTNO             397 non-null    object
 2   APVPERMYMD        397 non-null    object
 3   APVCANCELYMD      397 non-null    object
 4   TRDSTATEGBN       397 non-null    object
 5   TRDSTATENM        397 non-null    object
 6   DTLSTATEGBN       397 non-null    object
 7   DTLSTATENM        397 non-null    object
 8   DCBYMD            397 non-null    object
 9   CLGSTDT           397 non-null    object
 10  CLGENDDT          397 non-null    object
 11  ROPNYMD           397 non-null    object
 12  SITETEL           397 non-null    object
 13  SITEAREA          397 non-null    object
 14  SITEPOSTNO        397 non-null    object
 15  SITEWHLADDR       397 non-null    object
 16  RDNWHLADDR        397 non-null    object
 17  RDNPOSTNO         397 non-null    object
 18  BPLCNM            397 non-null    object
 19  LASTMODTS         397 non-null    object
 20  UPDATEGBN         397 non-null    object
 21  UPDATEDT          397 non-null    object
 22  UPTAENM           397 non-null    object
 23  X                 397 non-null    object
 24  Y                 397 non-null    object
 25  CULPHYEDCOBNM     397 non-null    object
 26  PUPRSENM          397 non-null    object
 27  INSURJNYNCODE     397 non-null    object
 28  LDERCNT           397 non-null    object
 29  BDNGDNGNUM        397 non-null    object
 30  BDNGYAREA         397 non-null    object
 31  MEMCOLLTOTSTFNUM  397 non-null    object
 32  DRMKCOBNM         397 non-null    object
 33  BUPNM             397 non-null    object
dtypes: object(34)
memory usage: 105.6+ KB

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,Y,CULPHYEDCOBNM,PUPRSENM,INSURJNYNCODE,LDERCNT,BDNGDNGNUM,BDNGYAREA,MEMCOLLTOTSTFNUM,DRMKCOBNM,BUPNM
0,3040000,CDFH3301112025000001,2025-03-18,,01,영업/정상,13,영업중,,,...,450582.857383855,,,,,,,,,
1,3090000,CDFH3301112015000002,2015-04-15,,01,영업/정상,13,영업중,,,...,461207.244729609,,,,,,,,,
2,3000000,CDFH3301112007000001,2007-10-22,,03,폐업,03,폐업,2013-04-19,,...,452040.822179636,무도학원업,사립,,,,,,,
3,3000000,CDFH3301112010000002,2010-04-27,,03,폐업,03,폐업,2017-10-23,,...,452297.758597168,무도학원업,사립,,,,,,,
4,3000000,CDFH3301112001000001,2001-01-11,,03,폐업,03,폐업,2005-07-28,,...,452317.86559669,무도학원업,사립,0,,,,,,

In [76]:
# ① API 데이터 → DataFrame 변환
rows = data["LOCALDATA_103302"]["row"]
df = pd.DataFrame(rows)

# ② 바로 소문자 변환 (이 순서 중요!)
df.columns = df.columns.str.lower()

# ③ 확인
print(df.columns.tolist())

['opnsfteamcode', 'mgtno', 'apvpermymd', 'apvcancelymd', 'trdstategbn', 'trdstatenm', 'dtlstategbn', 'dtlstatenm', 'dcbymd', 'clgstdt', 'clgenddt', 'ropnymd', 'sitetel', 'sitearea', 'sitepostno', 'sitewhladdr', 'rdnwhladdr', 'rdnpostno', 'bplcnm', 'lastmodts', 'updategbn', 'updatedt', 'uptaenm', 'x', 'y', 'culphyedcobnm', 'puprsenm', 'insurjnyncode', 'ldercnt', 'bdngdngnum', 'bdngyarea', 'memcolltotstfnum', 'drmkcobnm', 'bupnm']

In [77]:
import pandas as pd

# 1. 딕셔너리에서 'row' 데이터만 추출해서 '진짜 표(DataFrame)'로 만듭니다.
# 이미지 6f5202.png의 구조에 맞춘 경로입니다.
if isinstance(physical_df, dict):
    physical_df = pd.DataFrame(physical_df["LOCALDATA_103302"]["row"])
    print("딕셔너리를 데이터프레임으로 변환했습니다!")

# 2. 이제 모든 컬럼명을 소문자로 바꿉니다 (대소문자 에러 방지)
physical_df.columns = physical_df.columns.str.lower()

# 3. 원하는 컬럼만 선택 (이제 이 코드가 작동합니다!)
# 주의: API 응답에 실제로 있는 컬럼명인지 확인 후 넣어주세요.
target_cols = ['dtlstatenm', 'rdnwhladdr','uptaenm', 'bplcnm']

# 실제로 존재하는 컬럼만 안전하게 필터링해서 가져오기
available_cols = [c for c in target_cols if c in physical_df.columns]
physical_df = physical_df[available_cols]

# 4. idx 추가 (전체 개수에 맞게)
physical_df["idx"] = range(1, len(physical_df) + 1)

# 5. idx를 맨 앞으로 보내기
cols = ["idx"] + [c for c in physical_df.columns if c != "idx"]
physical_df = physical_df[cols]

physical_df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_14188\1370405179.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  physical_df["idx"] = range(1, len(physical_df) + 1)

   idx dtlstatenm                                 rdnwhladdr uptaenm    bplcnm
0    1        영업중            서울특별시 광진구 능동로38길 10-1, 지층 (중곡동)           참진댄스스포츠
1    2        영업중  서울특별시 도봉구 마들로11길 73, 지층 7,8,9,14,15호 (창동)          탑댄스 아카데미
2    3         폐업                 서울특별시 종로구 삼일대로 403-1 (인사동)           현대스포츠댄스
3    4         폐업                     서울특별시 종로구 종로 346 (숭인동)           현대스포츠댄스
4    5         폐업                    서울특별시 종로구 종로 335  (창신동)           동대문무도학원

In [78]:
# 컬럼명 nm,addr 변경
physical_df.rename(columns={'bplcnm': 'nm', 'rdnwhladdr': 'addr', 'uptaenm':'type'}, inplace=True)

# 확인하기
print(physical_df.columns)

Index(['idx', 'dtlstatenm', 'addr', 'type', 'nm'], dtype='object')

In [79]:
### 영업중 필터링
physical_df = physical_df[physical_df["dtlstatenm"] == "영업중"]
print(len(physical_df))

60

In [80]:
physical_df['type'] = '학원'
physical_df

,idx,dtlstatenm,addr,type,nm
0,1,영업중,"서울특별시 광진구 능동로38길 10-1, 지층 (중곡동)",학원,참진댄스스포츠
1,2,영업중,"서울특별시 도봉구 마들로11길 73, 지층 7,8,9,14,15호 (창동)",학원,탑댄스 아카데미
30,31,영업중,서울특별시 종로구 동호로 406-1 (종로5가),학원,국제무도학원
31,32,영업중,서울특별시 종로구 종로 62 (종로2가),학원,탑댄스 스포츠
32,33,영업중,서울특별시 종로구 종로31길 22 (연지동),학원,스포츠댄스
61,62,영업중,,학원,한국무도학원
62,63,영업중,,학원,백조무도학원
63,64,영업중,,학원,한일
64,65,영업중,,학원,정통댄스스포츠학원
65,66,영업중,,학원,상록무도학원
66,67,영업중,"서울특별시 중구 세종대로 28, 5층 (남대문로5가)",학원,썬 무도학원
67,68,영업중,,학원,흥인무도학원
68,69,영업중,,학원,성림무도학원
69,70,영업중,,학원,영무도학원
70,71,영업중,,학원,대한무도학원
71,72,영업중,,학원,한일무도학원
72,73,영업중,,학원,중부무도학원
89,90,영업중,서울특별시 성동구 무학로2길 48 (도선동),학원,천사스포츠댄스
90,91,영업중,"서울특별시 성동구 천호대로 296, 영보빌딩 3층 (용답동)",학원,위너스 댄스스포츠
91,92,영업중,"서울특별시 성동구 천호대로 282, 남주빌딩 지하1층 (용답동)",학원,최동일&홍미경 댄스스포츠 아카데미
92,93,영업중,"서울특별시 성동구 자동차시장1길 85, JS 빌딩 지하2층 (용답동)",학원,블랙플 댄스스포츠
127,128,영업중,서울특별시 동대문구 천호대로 263 (답십리동),학원,해바라기 댄스
128,129,영업중,"서울특별시 동대문구 장한로2길 36, 2,3층 (장안동)",학원,더오페라
135,136,영업중,"서울특별시 중랑구 면목로 318, 611동 3호 (면목동,3층)",학원,나너 댄스스포츠
136,137,영업중,"서울특별시 동대문구 천호대로 305, 지하1층 (답십리동)",학원,굿댄스라이프
137,138,영업중,서울특별시 중랑구 망우로 384 (망우동),학원,조이 스포츠댄스
138,139,영업중,서울특별시 중랑구 상봉로 108 (망우동),학원,김정민 댄스스포츠 학원
170,171,영업중,"서울특별시 도봉구 마들로11가길 15, 4층 402호 (창동)",학원,김정남 댄스
171,172,영업중,서울특별시 도봉구 마들로11가길 12 (창동),학원,하바나댄스스포츠학원
172,173,영업중,"서울특별시 도봉구 마들로11가길 13, 505호 (창동, 월드프라자)",학원,국제학원
173,174,영업중,"서울특별시 도봉구 마들로11가길 16, KING 프라자 8층 803호 (창동)",학원,백장미댄스
174,175,영업중,"서울특별시 도봉구 노해로69길 15-15, 지하1층 1-6,13-22호 (창동)",학원,안혜상 댄스 아카데미
181,182,영업중,"서울특별시 은평구 통일로 724, 4층 (불광동)",학원,불광무도학원
198,199,영업중,"서울특별시 은평구 통일로 855-16, 4층 (갈현동)",학원,서울무도학원
199,200,영업중,"서울특별시 은평구 통일로 728, 4층 (불광동)",학원,아사모생활댄스연수학원
225,226,영업중,"서울특별시 강서구 방화동로 1, 3층 (방화동)",학원,송정 댄스스포츠
226,227,영업중,서울특별시 강서구 강서로5나길 134 (화곡동),학원,한국스포츠무도학원
227,228,영업중,"서울특별시 강서구 강서로12길 5-15, 2층 (화곡동)",학원,현대무도학원
228,229,영업중,"서울특별시 강서구 개화동로29길 60, 3층 (방화동)",학원,관문스포츠댄스학원
271,272,영업중,"서울특별시 영등포구 여의대방로 383, 501,502호 (여의도동,경도빌딩)",학원,써니박 라틴댄스 아카데미
272,273,영업중,"서울특별시 영등포구 영중로 95-1 (영등포동7가,지하1층)",학원,와 스포츠댄스학원
273,274,영업중,,학원,영신
274,275,영업중,"서울특별시 영등포구 영등포로 251 (영등포동2가,3층층)",학원,동작무도학원
275,276,영업중,"서울특별시 영등포구 영중로 52-1, 지하1층 (영등포동5가)",학원,세븐댄스스포츠
276,277,영업중,"서울특별시 영등포구 영등포로 231-1, 3층 (영등포동5가)",학원,이동석댄스스포츠스쿨
317,318,영업중,"서울특별시 관악구 조원로2길 42, 지하1층 (신림동)",학원,디앤스토리 댄스 스튜디오
318,319,영업중,"서울특별시 관악구 신림로70길 20, 지하1층 (신림동)",학원,클래스댄스스쿨
328,329,영업중,"서울특별시 관악구 시흥대로 578 (신림동,광안빌딩 지2층)",학원,공단무도학원
334,335,영업중,서울특별시 서초구 사임당로 14 (서초동),학원,한국볼륨댄스학원
335,336,영업중,서울특별시 서초구 강남대로53길 7 (서초동),학원,강남무도학원
340,341,영업중,"서울특별시 강남구 학동로 342, 에스케이 허브블루 B2층 201호 (논현동)",학원,샤리권 댄스스쿨
341,342,영업중,"서울특별시 강남구 논현로 604 (논현동,5층)",학원,월드댄스아카데미(12)
342,343,영업중,서울특별시 강남구 강남대로 620 (신사동),학원,신사(6)
343,344,영업중,서울특별시 강남구 봉은사로 327 (논현동),학원,K.P 댄스스쿨(3)
344,345,영업중,"서울특별시 강남구 테헤란로10길 11 (역삼동,4층)",학원,듀오댄스스포츠(3)
345,346,영업중,"서울특별시 강남구 선릉로 507 (역삼동,403호)",학원,선릉댄스스쿨(4)
346,347,영업중,"서울특별시 강남구 학동로 337 (논현동,4층)",학원,조앤리 댄스스쿨(1)
363,364,영업중,"서울특별시 송파구 올림픽로 80 (잠실동, 영원빌딩)",학원,강남 댄스스포츠
395,396,영업중,서울특별시 강동구 천호대로 1027 (천호동),학원,하바나 댄스 스튜디오
396,397,영업중,서울특별시 영등포구 영등포로 262 (영등포동3가),학원,베스트리듬댄스 무도학원

### KAKAO API 위도 경도 가져오기

In [81]:
kakao_key  = os.getenv("KAKAO_API_KEY")

In [85]:
url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": f"KakaoAK {kakao_key}"}

# ① 주소 없는 행 먼저 삭제
physical_df.dropna(subset=["addr"], inplace=True)

for idx, add in physical_df['addr'].items():
    # ② 복잡한 주소 정제 (쉼표 뒤 제거)
    clean_addr = add.split(",")[0].strip()
    
    params = {"query": clean_addr}
    resp = requests.get(url, headers=headers, params=params).json()

    docs = resp.get('documents', [])
    if not docs:
        continue

    road = docs[0].get('road_address')

    if road:
        physical_df.loc[idx, 'lat'] = road.get('y')
        physical_df.loc[idx, 'lng'] = road.get('x')
    else:
        addr = docs[0].get('address')  # 'addr' → 'address' 수정!
        if addr:
            physical_df.loc[idx, 'lat'] = addr.get('y')
            physical_df.loc[idx, 'lng'] = addr.get('x')
    
    time.sleep(0.3)

# ③ 그래도 NaN이면 제거
physical_df.dropna(subset=["lat", "lng"], inplace=True)

# ④ idx 재정렬
physical_df["idx"] = range(1, len(physical_df) + 1)

physical_df

,idx,dtlstatenm,addr,type,nm,lat,lng
0,1,영업중,"서울특별시 광진구 능동로38길 10-1, 지층 (중곡동)",학원,참진댄스스포츠,37.5575156292653,127.08050423912
1,2,영업중,"서울특별시 도봉구 마들로11길 73, 지층 7,8,9,14,15호 (창동)",학원,탑댄스 아카데미,37.6532567533904,127.049060560533
30,3,영업중,서울특별시 종로구 동호로 406-1 (종로5가),학원,국제무도학원,37.5706007422209,127.002255096369
31,4,영업중,서울특별시 종로구 종로 62 (종로2가),학원,탑댄스 스포츠,37.5699336122191,126.984287137633
32,5,영업중,서울특별시 종로구 종로31길 22 (연지동),학원,스포츠댄스,37.5719315335697,126.999820127904
66,6,영업중,"서울특별시 중구 세종대로 28, 5층 (남대문로5가)",학원,썬 무도학원,37.5588849988761,126.974638383017
89,7,영업중,서울특별시 성동구 무학로2길 48 (도선동),학원,천사스포츠댄스,37.5623887641634,127.034694813429
90,8,영업중,"서울특별시 성동구 천호대로 296, 영보빌딩 3층 (용답동)",학원,위너스 댄스스포츠,37.5660126480034,127.053138658366
91,9,영업중,"서울특별시 성동구 천호대로 282, 남주빌딩 지하1층 (용답동)",학원,최동일&홍미경 댄스스포츠 아카데미,37.5667983056365,127.052152534724
92,10,영업중,"서울특별시 성동구 자동차시장1길 85, JS 빌딩 지하2층 (용답동)",학원,블랙플 댄스스포츠,37.5605377248611,127.067148620046
127,11,영업중,서울특별시 동대문구 천호대로 263 (답십리동),학원,해바라기 댄스,37.5685046121538,127.051120497766
128,12,영업중,"서울특별시 동대문구 장한로2길 36, 2,3층 (장안동)",학원,더오페라,37.5617499581591,127.067091532
135,13,영업중,"서울특별시 중랑구 면목로 318, 611동 3호 (면목동,3층)",학원,나너 댄스스포츠,37.5802323207696,127.088455941098
136,14,영업중,"서울특별시 동대문구 천호대로 305, 지하1층 (답십리동)",학원,굿댄스라이프,37.5659324524229,127.054536940859
137,15,영업중,서울특별시 중랑구 망우로 384 (망우동),학원,조이 스포츠댄스,37.598456280684,127.094898130177
138,16,영업중,서울특별시 중랑구 상봉로 108 (망우동),학원,김정민 댄스스포츠 학원,37.5954420338517,127.093292722403
170,17,영업중,"서울특별시 도봉구 마들로11가길 15, 4층 402호 (창동)",학원,김정남 댄스,37.6526568870103,127.049257910527
171,18,영업중,서울특별시 도봉구 마들로11가길 12 (창동),학원,하바나댄스스포츠학원,37.6528132165075,127.048802690211
172,19,영업중,"서울특별시 도봉구 마들로11가길 13, 505호 (창동, 월드프라자)",학원,국제학원,37.652904680016,127.049203340119
173,20,영업중,"서울특별시 도봉구 마들로11가길 16, KING 프라자 8층 803호 (창동)",학원,백장미댄스,37.6525659173791,127.048970356141
174,21,영업중,"서울특별시 도봉구 노해로69길 15-15, 지하1층 1-6,13-22호 (창동)",학원,안혜상 댄스 아카데미,37.6528238071177,127.049976589031
181,22,영업중,"서울특별시 은평구 통일로 724, 4층 (불광동)",학원,불광무도학원,37.6103214562903,126.930363138778
198,23,영업중,"서울특별시 은평구 통일로 855-16, 4층 (갈현동)",학원,서울무도학원,37.6195270333319,126.920254459044
199,24,영업중,"서울특별시 은평구 통일로 728, 4층 (불광동)",학원,아사모생활댄스연수학원,37.6105757824283,126.930171610875
225,25,영업중,"서울특별시 강서구 방화동로 1, 3층 (방화동)",학원,송정 댄스스포츠,37.5621635742806,126.808044242886
226,26,영업중,서울특별시 강서구 강서로5나길 134 (화곡동),학원,한국스포츠무도학원,37.5284038783305,126.840748879491
227,27,영업중,"서울특별시 강서구 강서로12길 5-15, 2층 (화곡동)",학원,현대무도학원,37.5321240068703,126.846940027199
228,28,영업중,"서울특별시 강서구 개화동로29길 60, 3층 (방화동)",학원,관문스포츠댄스학원,37.5634654168104,126.809710612576
271,29,영업중,"서울특별시 영등포구 여의대방로 383, 501,502호 (여의도동,경도빌딩)",학원,써니박 라틴댄스 아카데미,37.5193436883433,126.931504190261
272,30,영업중,"서울특별시 영등포구 영중로 95-1 (영등포동7가,지하1층)",학원,와 스포츠댄스학원,37.5248769411722,126.905087792624
274,31,영업중,"서울특별시 영등포구 영등포로 251 (영등포동2가,3층층)",학원,동작무도학원,37.5192505630959,126.909359491863
275,32,영업중,"서울특별시 영등포구 영중로 52-1, 지하1층 (영등포동5가)",학원,세븐댄스스포츠,37.5208706088216,126.905168093153
276,33,영업중,"서울특별시 영등포구 영등포로 231-1, 3층 (영등포동5가)",학원,이동석댄스스포츠스쿨,37.5196557463138,126.907273082927
317,34,영업중,"서울특별시 관악구 조원로2길 42, 지하1층 (신림동)",학원,디앤스토리 댄스 스튜디오,37.481886077083,126.901530876573
318,35,영업중,"서울특별시 관악구 신림로70길 20, 지하1층 (신림동)",학원,클래스댄스스쿨,37.4876733452452,126.929963012921
328,36,영업중,"서울특별시 관악구 시흥대로 578 (신림동,광안빌딩 지2층)",학원,공단무도학원,37.4843090452129,126.903247316338
335,37,영업중,서울특별시 서초구 강남대로53길 7 (서초동),학원,강남무도학원,37.4942643848404,127.028259839376
340,38,영업중,"서울특별시 강남구 학동로 342, 에스케이 허브블루 B2층 201호 (논현동)",학원,샤리권 댄스스쿨,37.5167560126387,127.040841265738
341,39,영업중,"서울특별시 강남구 논현로 604 (논현동,5층)",학원,월드댄스아카데미(12),37.5076483851132,127.034040281333
342,40,영업중,서울특별시 강남구 강남대로 620 (신사동),학원,신사(6),37.5171459798091,127.01969555607
343,41,영업중,서울특별시 강남구 봉은사로 327 (논현동),학원,K.P 댄스스쿨(3),37.5101865123901,127.042653360305
344,42,영업중,"서울특별시 강남구 테헤란로10길 11 (역삼동,4층)",학원,듀오댄스스포츠(3),37.4983798565841,127.032670998374
345,43,영업중,"서울특별시 강남구 선릉로 507 (역삼동,403호)",학원,선릉댄스스쿨(4),37.5049906216119,127.048432834632
346,44,영업중,"서울특별시 강남구 학동로 337 (논현동,4층)",학원,조앤리 댄스스쿨(1),37.5170718563031,127.039928031242
363,45,영업중,"서울특별시 송파구 올림픽로 80 (잠실동, 영원빌딩)",학원,강남 댄스스포츠,37.5115454105966,127.07956762791
395,46,영업중,서울특별시 강동구 천호대로 1027 (천호동),학원,하바나 댄스 스튜디오,37.5381084632581,127.126395521678
396,47,영업중,서울특별시 영등포구 영등포로 262 (영등포동3가),학원,베스트리듬댄스 무도학원,37.5185874621212,126.910471448427

### 3. 데이터 csv 파일 저장

In [86]:
physical_df.to_csv("physical_df.csv", index=False, encoding="utf-8-sig")
print("physical_df.csv")

physical_df.csv

# 서울시 체육도장업 인허가 정보

### 1. 데이터 가져오기

In [108]:
import pandas as pd
import requests
import os
from tqdm import tqdm  # 진행 상태를 보기 위해 필요해요
import time

apikey = os.getenv("GYM_TRAINING_BS_API_KEY")
total_count = 5351  # 승둥이님이 확인하신 전체 행 개수
page_size = 500     # 한 번에 가져올 양
all_rows = []       # 각 페이지 데이터를 모아둘 리스트

# 1. 반복문 시작: 1부터 total_count까지 page_size(500) 간격으로 루프
for start in tqdm(range(1, total_count + 1, page_size)):
    end = start + page_size - 1
    if end > total_count:
        end = total_count
    
    # 2. URL 생성 (start_index와 end_index가 매번 바뀝니다)
    url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/LOCALDATA_104101/{start}/{end}/"
    
    # 3. API 요청 및 응답 받기
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        
        # 4. 데이터 알맹이(row)만 추출해서 리스트에 추가
        # 'LOCALDATA_104101' 키 이름이 정확한지 확인해 주세요!
        if "LOCALDATA_104101" in data and "row" in data["LOCALDATA_104101"]:
            all_rows.extend(data["LOCALDATA_104101"]["row"])
    

# 5. 수집된 모든 리스트를 데이터프레임으로 변환
gym_df = pd.DataFrame(all_rows)

print(f"\n총 {len(gym_df)}개의 행을 가져왔습니다.")
gym_df.head()

100%|██████████| 11/11 [00:01<00:00,  5.89it/s]

총 5351개의 행을 가져왔습니다.

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,Y,CULPHYEDCOBNM,PUPRSENM,INSURJNYNCODE,LDERCNT,BDNGDNGNUM,BDNGYAREA,MEMCOLLTOTSTFNUM,DRMKCOBNM,BUPNM
0,3140000,CDFH3301022025000002,2025-02-03,,01,영업/정상,13,영업중,,,...,448633.408280957,,,,,,,,,
1,3220000,CDFH3301022017000010,2017-08-07,,01,영업/정상,13,영업중,,,...,445875.091007593,,,,,,,,,
2,3220000,CDFH3301022011000004,2011-08-31,,01,영업/정상,13,영업중,,,...,445583.333370025,,,,,,,,,
3,3060000,CDFH3301022019000001,2019-07-01,,01,영업/정상,13,영업중,,,...,456996.056603203,,,,,,,,,
4,3120000,CDFH3301022025000001,2025-03-10,,01,영업/정상,13,영업중,,,...,454111.274791974,,,,,,,,,

In [109]:
# ① API 응답을 JSON으로 변환
data = response.json()

# ② 실제 데이터(row)만 추출
rows = data['LOCALDATA_104101']['row']

# ③ 확인용 출력
print(rows)

# ④ DataFrame으로 변환
gym_df = pd.DataFrame(rows)

# ⑤ DataFrame 출력 
gym_df

[{'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021998000001', 'APVPERMYMD': '1998-03-12', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2007-04-06', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '472-3714', 'SITEAREA': '', 'SITEPOSTNO': '134-868', 'SITEWHLADDR': '서울특별시 강동구 천호동 337-19번지 1층 ', 'RDNWHLADDR': '서울특별시 강동구 올림픽로77길 46-9  (천호동,1층)', 'RDNPOSTNO': '', 'BPLCNM': '금강태권도장', 'LASTMODTS': '2007-04-06 12:57:45', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '210768.152134068    ', 'Y': '449091.867374585    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022012000003', 'APVPERMYMD': '2012-09-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2016-09-06', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '02-429-1282', 'SITEAREA': '', 'SITEPOSTNO': '134-100', 'SITEWHLADDR': '서울특별시 강동구 강일동 679-2번지 MIDC빌딩 501호', 'RDNWHLADDR': '서울특별시 강동구 아리수로 421, 501호 (강일동)', 'RDNPOSTNO': '05211', 'BPLCNM': '강일 복싱', 'LASTMODTS': '2016-09-06 10:56:50', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '215311.087618287    ', 'Y': '451385.841389885    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021992000003', 'APVPERMYMD': '1992-07-06', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-03-14', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '134-828', 'SITEWHLADDR': '서울특별시 강동구 명일동 268-2번지 3층 ', 'RDNWHLADDR': '서울특별시 강동구 양재대로130길 47  (명일동,3층)', 'RDNPOSTNO': '', 'BPLCNM': '경원대대명태권도장', 'LASTMODTS': '2011-03-14 14:18:02', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '212824.552741963    ', 'Y': '449319.609109957    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '663.55', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022009000002', 'APVPERMYMD': '2009-06-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2011-07-22', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '429-6589', 'SITEAREA': '', 'SITEPOSTNO': '134-100', 'SITEWHLADDR': '서울특별시 강동구 강일동 695번지 리버파크10단지상가 204~206호 ', 'RDNWHLADDR': '서울특별시 강동구 고덕로97길 20  (강일동,리버파크10단지상가 204~206호)', 'RDNPOSTNO': '', 'BPLCNM': '경희대박사태권도', 'LASTMODTS': '2011-07-22 13:25:23', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '215901.594590118    ', 'Y': '450869.91564519     ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '1', 'BDNGYAREA': '677', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021995000006', 'APVPERMYMD': '1995-03-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2017-01-17', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '478-1112', 'SITEAREA': '', 'SITEPOSTNO': '134-817', 'SITEWHLADDR': '서울특별시 강동구 둔촌동 68-12번지 3층 ', 'RDNWHLADDR': '서울특별시 강동구 풍성로65길 55  (둔촌동,3층)', 'RDNPOSTNO': '', 'BPLCNM': '태성태권도', 'LASTMODTS': '2017-01-17 14:13:35', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '212361.672027533    ', 'Y': '447572.597657265    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '1', 'BDNGDNGNUM': '1', 'BDNGYAREA': '489', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021995000004', 'APVPERMYMD': '1995-03-15', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2006-05-23', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '429-3706', 'SITEAREA': '', 'SITEPOSTNO': '134-100', 'SITEWHLADDR': '서울특별시 강동구 강일동 351-3번지 2층 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '서울체육관', 'LASTMODTS': '2006-05-23 17:55:20', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '', 'Y': '', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021995000005', 'APVPERMYMD': '1995-03-17', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2008-01-10', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '429-1909', 'SITEAREA': '', 'SITEPOSTNO': '134-801', 'SITEWHLADDR': '서울특별시 강동구 고덕동 191-5번지 ', 'RDNWHLADDR': '서울특별시 강동구 고덕로83길 28  (고덕동)', 'RDNPOSTNO': '', 'BPLCNM': '고일태권도', 'LASTMODTS': '2008-01-11 12:55:34', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '214864.638202048    ', 'Y': '450684.210584771    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021996000003', 'APVPERMYMD': '1996-05-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '1998-04-29', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '134-836', 'SITEWHLADDR': '서울특별시 강동구 상일동 126-0번지 3층 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '한국시각장애인복지회', 'LASTMODTS': '2003-04-11 10:24:39', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '214866.322882804    ', 'Y': '449869.026666       ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022009000001', 'APVPERMYMD': '2009-05-08', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2012-06-29', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '427-6589', 'SITEAREA': '', 'SITEPOSTNO': '134-100', 'SITEWHLADDR': '서울특별시 강동구 강일동 674번지 강일리버파크 상가동 204~206호 ', 'RDNWHLADDR': '서울특별시 강동구 아리수로93길 40  (강일동,강일리버파크 상가동 204~206호)', 'RDNPOSTNO': '', 'BPLCNM': '경희박사스포츠', 'LASTMODTS': '2012-06-29 12:34:06', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '215366.063352066    ', 'Y': '451618.231227225    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '1', 'BDNGDNGNUM': '1', 'BDNGYAREA': '589', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022006000005', 'APVPERMYMD': '2006-11-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2013-04-15', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '134-810', 'SITEWHLADDR': '서울특별시 강동구 길동 333-2번지 지하1층 ', 'RDNWHLADDR': '서울특별시 강동구 양재대로124길 25, 지하1층 (길동)', 'RDNPOSTNO': '134-810', 'BPLCNM': '왕호태권도', 'LASTMODTS': '2013-04-15 16:49:52', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '212618.645848182    ', 'Y': '448983.948439782    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '1', 'BDNGYAREA': '1675', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021989000009', 'APVPERMYMD': '1989-12-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '1998-04-23', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '', 'SITEAREA': '', 'SITEPOSTNO': '134-837', 'SITEWHLADDR': '서울특별시 강동구 상일동 283-0번지 2층 ', 'RDNWHLADDR': '서울특별시 강동구 천호대로219길 68  (상일동,2층)', 'RDNPOSTNO': '', 'BPLCNM': '신화랑태권도체육도장', 'LASTMODTS': '2003-04-11 10:24:39', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '215053.049029786    ', 'Y': '449623.176713625    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021989000010', 'APVPERMYMD': '1989-12-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2004-10-22', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '485-5276', 'SITEAREA': '', 'SITEPOSTNO': '134-883', 'SITEWHLADDR': '서울특별시 강동구 성내동 120-84번지 2층 ', 'RDNWHLADDR': '서울특별시 강동구 풍성로 104  (성내동,2층)', 'RDNPOSTNO': '', 'BPLCNM': '대한태권도', 'LASTMODTS': '2004-10-22 11:33:31', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '210863.964122971    ', 'Y': '447784.798733406    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022013000005', 'APVPERMYMD': '2013-04-08', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2014-03-19', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '426-4409', 'SITEAREA': '', 'SITEPOSTNO': '134-742', 'SITEWHLADDR': '서울특별시 강동구 강일동 717번지 고덕리엔파크 2단지아파트 상가동 202호', 'RDNWHLADDR': '서울특별시 강동구 고덕로 427 (강일동, 고덕리엔파크 아파트 2단지 상가 202호)', 'RDNPOSTNO': '134-742', 'BPLCNM': '강명 경희대 태권스쿨', 'LASTMODTS': '2014-03-20 10:40:38', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '215223.604630417    ', 'Y': '450827.270292439    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '1', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022006000004', 'APVPERMYMD': '2006-09-01', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2007-04-02', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '470-6661', 'SITEAREA': '', 'SITEPOSTNO': '134-822', 'SITEWHLADDR': '서울특별시 강동구 둔촌동 380-3번지 2층 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '용인대석사태권도', 'LASTMODTS': '2007-04-02 11:53:53', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '', 'Y': '', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '1', 'BDNGDNGNUM': '1', 'BDNGYAREA': '440', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021989000012', 'APVPERMYMD': '1989-12-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-07-17', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '473-9101', 'SITEAREA': '', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강동구 둔촌동 172-1번지 ', 'RDNWHLADDR': '서울특별시 강동구 명일로 74 (둔촌동, 주공아파트)', 'RDNPOSTNO': '05412', 'BPLCNM': '제일태권도', 'LASTMODTS': '2018-07-17 10:16:10', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '211979.520569314    ', 'Y': '446932.653730601    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022002000012', 'APVPERMYMD': '2002-05-22', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2003-03-13', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '442-6907', 'SITEAREA': '', 'SITEPOSTNO': '134-080', 'SITEWHLADDR': '서울특별시 강동구 고덕동 0-0번지 531-6  2층 ', 'RDNWHLADDR': '', 'RDNPOSTNO': '', 'BPLCNM': '태극호키체육관', 'LASTMODTS': '2003-07-23 13:58:46', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '', 'Y': '', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022002000013', 'APVPERMYMD': '2002-05-24', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2012-05-14', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '426-5153', 'SITEAREA': '', 'SITEPOSTNO': '134-825', 'SITEWHLADDR': '서울특별시 강동구 명일동 48-6번지 ', 'RDNWHLADDR': '서울특별시 강동구 동남로 885  (명일동)', 'RDNPOSTNO': '', 'BPLCNM': '에디슨체육관', 'LASTMODTS': '2012-05-14 09:07:47', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '213706.765762204    ', 'Y': '450054.26590882     ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021989000008', 'APVPERMYMD': '1989-12-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2019-06-28', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '426-5383', 'SITEAREA': '', 'SITEPOSTNO': '', 'SITEWHLADDR': '서울특별시 강동구 명일동 246-5번지 3층 ', 'RDNWHLADDR': '서울특별시 강동구 상암로61길 28 (명일동)', 'RDNPOSTNO': '05271', 'BPLCNM': '석사체육관', 'LASTMODTS': '2019-06-28 14:20:32', 'UPDATEGBN': 'U', 'UPDATEDT': '2019-06-30 02:40:00.0', 'UPTAENM': '', 'X': '213428.462513901    ', 'Y': '449528.765017832    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022002000010', 'APVPERMYMD': '2002-04-25', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2003-01-13', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '487-8996', 'SITEAREA': '', 'SITEPOSTNO': '134-840', 'SITEWHLADDR': '서울특별시 강동구 성내동 26-2번지 2층 ', 'RDNWHLADDR': '서울특별시 강동구 천호대로162길 42  (성내동,2층)', 'RDNPOSTNO': '', 'BPLCNM': '성내중앙체육관', 'LASTMODTS': '2003-04-11 10:24:39', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '211240.048085658    ', 'Y': '448094.629233685    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '0', 'BDNGDNGNUM': '0', 'BDNGYAREA': '0', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022013000009', 'APVPERMYMD': '2013-11-13', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2025-01-07', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '426-0026', 'SITEAREA': '', 'SITEPOSTNO': '134-100', 'SITEWHLADDR': '서울특별시 강동구 강일동 679 ', 'RDNWHLADDR': '서울특별시 강동구 아리수로 427 (강일동)', 'RDNPOSTNO': '05211', 'BPLCNM': '골든킥 태권도 유아체육', 'LASTMODTS': '2025-01-07 09:39:42', 'UPDATEGBN': 'U', 'UPDATEDT': '2025-01-09 02:40:00.0', 'UPTAENM': '태권도', 'X': '215356.343212895    ', 'Y': '451422.369618004    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '1', 'BDNGDNGNUM': '0', 'BDNGYAREA': '9427.36', 'MEMCOLLTOTSTFNUM': '0', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022002000005', 'APVPERMYMD': '2002-02-19', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2004-10-12', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '485-7022', 'SITEAREA': '', 'SITEPOSTNO': '134-817', 'SITEWHLADDR': '서울특별시 강동구 둔촌동 54번지 삼익파크상가 2층 ', 'RDNWHLADDR': '서울특별시 강동구 명일로13길 12  (둔촌동,삼익파크상가 2층)', 'RDNPOSTNO': '', 'BPLCNM': '경희화랑체육관', 'LASTMODTS': '2005-04-14 09:26:34', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '212655.192238201    ', 'Y': '447986.259837685    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021989000014', 'APVPERMYMD': '1989-12-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2003-04-15', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '442-3679', 'SITEAREA': '', 'SITEPOSTNO': '134-856', 'SITEWHLADDR': '서울특별시 강동구 암사동 487-37번지 2층 ', 'RDNWHLADDR': '서울특별시 강동구 구천면로 335  (암사동,2층)', 'RDNPOSTNO': '', 'BPLCNM': '천호태권도', 'LASTMODTS': '2003-07-23 13:34:18', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '211980.722391849    ', 'Y': '449676.184304154    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301021989000015', 'APVPERMYMD': '1989-12-02', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2005-10-17', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '477-8586', 'SITEAREA': '', 'SITEPOSTNO': '134-871', 'SITEWHLADDR': '서울특별시 강동구 천호동 397-99번지 2층 ', 'RDNWHLADDR': '서울특별시 강동구 구천면로34길 10  (천호동,2층)', 'RDNPOSTNO': '', 'BPLCNM': '한국체대태권도체육관', 'LASTMODTS': '2005-10-18 20:12:39', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '211579.754436948    ', 'Y': '448900.097319406    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '', 'BDNGDNGNUM': '', 'BDNGYAREA': '', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022013000011', 'APVPERMYMD': '2013-12-23', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2018-07-27', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '473-7989', 'SITEAREA': '', 'SITEPOSTNO': '134-811', 'SITEWHLADDR': '서울특별시 강동구 길동 348-1번지 3층 ', 'RDNWHLADDR': '서울특별시 강동구 양재대로 1514 (길동)', 'RDNPOSTNO': '05343', 'BPLCNM': '천지체육관', 'LASTMODTS': '2018-07-27 17:21:48', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '212432.347754443    ', 'Y': '448732.683813851    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '', 'LDERCNT': '1', 'BDNGDNGNUM': '', 'BDNGYAREA': '668.44', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022006000006', 'APVPERMYMD': '2006-11-23', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2008-03-28', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '486-3877', 'SITEAREA': '', 'SITEPOSTNO': '134-896', 'SITEWHLADDR': '서울특별시 강동구 천호동 393-7번지 2층 ', 'RDNWHLADDR': '서울특별시 강동구 구천면로 251  (천호동,2층)', 'RDNPOSTNO': '', 'BPLCNM': '태권도코리아아카데미', 'LASTMODTS': '2008-03-28 14:08:43', 'UPDATEGBN': 'I', 'UPDATEDT': '2018-08-31 23:59:59.0', 'UPTAENM': '', 'X': '211534.308192035    ', 'Y': '448962.671553258    ', 'CULPHYEDCOBNM': '체육도장업', 'PUPRSENM': '사립', 'INSURJNYNCODE': '0', 'LDERCNT': '1', 'BDNGDNGNUM': '1', 'BDNGYAREA': '424', 'MEMCOLLTOTSTFNUM': '', 'DRMKCOBNM': '', 'BUPNM': ''}, {'OPNSFTEAMCODE': '3240000', 'MGTNO': 'CDFH3301022006000007', 'APVPERMYMD': '2006-11-29', 'APVCANCELYMD': '', 'TRDSTATEGBN': '03', 'TRDSTATENM': '폐업', 'DTLSTATEGBN': '03', 'DTLSTATENM': '폐업', 'DCBYMD': '2015-05-22', 'CLGSTDT': '', 'CLGENDDT': '', 'ROPNYMD': '', 'SITETEL': '442-8827', 'SITEAREA': '', 'SITEPOSTNO': '134-781', 'SITEWHLAD

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,Y,CULPHYEDCOBNM,PUPRSENM,INSURJNYNCODE,LDERCNT,BDNGDNGNUM,BDNGYAREA,MEMCOLLTOTSTFNUM,DRMKCOBNM,BUPNM
0,3240000,CDFH3301021998000001,1998-03-12,,03,폐업,03,폐업,2007-04-06,,...,449091.867374585,체육도장업,사립,0,,,,,,
1,3240000,CDFH3301022012000003,2012-09-25,,03,폐업,03,폐업,2016-09-06,,...,451385.841389885,체육도장업,사립,,,,,,,
2,3240000,CDFH3301021992000003,1992-07-06,,03,폐업,03,폐업,2011-03-14,,...,449319.609109957,체육도장업,사립,,,,663.55,,,
3,3240000,CDFH3301022009000002,2009-06-25,,03,폐업,03,폐업,2011-07-22,,...,450869.91564519,체육도장업,사립,,,1,677,,,
4,3240000,CDFH3301021995000006,1995-03-24,,03,폐업,03,폐업,2017-01-17,,...,447572.597657265,체육도장업,사립,,1,1,489,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,3090000,CDFH3301022026000001,2026-02-23,,01,영업/정상,13,영업중,,,...,463585.041752236,,,,,,,,,
347,3070000,CDFH3301022024000007,2024-12-19,,01,영업/정상,13,영업중,,,...,454568.492198262,,,,,,,,,
348,3060000,CDFH3301022022000002,2022-02-10,,01,영업/정상,13,영업중,,,...,454464.431663999,,,,,,,,,
349,3240000,CDFH3301022005000008,2005-11-14,,03,폐업,03,폐업,2026-02-24,,...,449169.817272414,,,,,,,,,
350,3060000,CDFH3301021994000003,1994-10-10,,01,영업/정상,13,영업중,,,...,456039.62716713,,,,,,,,,

### 2. 데이터 전처리

In [110]:
### 데이터 전처리 전 확인 할 부분

df = pd.DataFrame(rows)
df.shape        # 행, 열 개수
df.info()       # 컬럼명, 데이터 타입, 결측값 확인
df.describe()   # 숫자 컬럼 통계 요약
df.head()       # 상위 5개 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OPNSFTEAMCODE     351 non-null    object
 1   MGTNO             351 non-null    object
 2   APVPERMYMD        351 non-null    object
 3   APVCANCELYMD      351 non-null    object
 4   TRDSTATEGBN       351 non-null    object
 5   TRDSTATENM        351 non-null    object
 6   DTLSTATEGBN       351 non-null    object
 7   DTLSTATENM        351 non-null    object
 8   DCBYMD            351 non-null    object
 9   CLGSTDT           351 non-null    object
 10  CLGENDDT          351 non-null    object
 11  ROPNYMD           351 non-null    object
 12  SITETEL           351 non-null    object
 13  SITEAREA          351 non-null    object
 14  SITEPOSTNO        351 non-null    object
 15  SITEWHLADDR       351 non-null    object
 16  RDNWHLADDR        351 non-null    object
 17  RDNPOSTNO         351 non-null    object
 18  BPLCNM            351 non-null    object
 19  LASTMODTS         351 non-null    object
 20  UPDATEGBN         351 non-null    object
 21  UPDATEDT          351 non-null    object
 22  UPTAENM           351 non-null    object
 23  X                 351 non-null    object
 24  Y                 351 non-null    object
 25  CULPHYEDCOBNM     351 non-null    object
 26  PUPRSENM          351 non-null    object
 27  INSURJNYNCODE     351 non-null    object
 28  LDERCNT           351 non-null    object
 29  BDNGDNGNUM        351 non-null    object
 30  BDNGYAREA         351 non-null    object
 31  MEMCOLLTOTSTFNUM  351 non-null    object
 32  DRMKCOBNM         351 non-null    object
 33  BUPNM             351 non-null    object
dtypes: object(34)
memory usage: 93.4+ KB

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,Y,CULPHYEDCOBNM,PUPRSENM,INSURJNYNCODE,LDERCNT,BDNGDNGNUM,BDNGYAREA,MEMCOLLTOTSTFNUM,DRMKCOBNM,BUPNM
0,3240000,CDFH3301021998000001,1998-03-12,,03,폐업,03,폐업,2007-04-06,,...,449091.867374585,체육도장업,사립,0,,,,,,
1,3240000,CDFH3301022012000003,2012-09-25,,03,폐업,03,폐업,2016-09-06,,...,451385.841389885,체육도장업,사립,,,,,,,
2,3240000,CDFH3301021992000003,1992-07-06,,03,폐업,03,폐업,2011-03-14,,...,449319.609109957,체육도장업,사립,,,,663.55,,,
3,3240000,CDFH3301022009000002,2009-06-25,,03,폐업,03,폐업,2011-07-22,,...,450869.91564519,체육도장업,사립,,,1,677,,,
4,3240000,CDFH3301021995000006,1995-03-24,,03,폐업,03,폐업,2017-01-17,,...,447572.597657265,체육도장업,사립,,1,1,489,,,

In [111]:
# 처음부터 다시
rows = data["LOCALDATA_104101"]["row"]
df = pd.DataFrame(rows)
df.columns = df.columns.str.lower()
print(df.columns.tolist())  # 전체 컬럼 확인

['opnsfteamcode', 'mgtno', 'apvpermymd', 'apvcancelymd', 'trdstategbn', 'trdstatenm', 'dtlstategbn', 'dtlstatenm', 'dcbymd', 'clgstdt', 'clgenddt', 'ropnymd', 'sitetel', 'sitearea', 'sitepostno', 'sitewhladdr', 'rdnwhladdr', 'rdnpostno', 'bplcnm', 'lastmodts', 'updategbn', 'updatedt', 'uptaenm', 'x', 'y', 'culphyedcobnm', 'puprsenm', 'insurjnyncode', 'ldercnt', 'bdngdngnum', 'bdngyarea', 'memcolltotstfnum', 'drmkcobnm', 'bupnm']

In [112]:
import pandas as pd

# 'row' 데이터만 추출
if isinstance(gym_df, dict):
    gym_df = pd.DataFrame(gym_df["LOCALDATA_104101"]["row"])
    print("딕셔너리를 데이터프레임으로 변환")

# 모든 컬럼명을 소문자
gym_df.columns = gym_df.columns.str.lower()

# 3. 원하는 컬럼만 선택
target_cols = ['dtlstatenm','rdnwhladdr', 'bplcnm', 'uptaenm']

# 실제로 존재하는 컬럼만 안전하게 필터링해서 가져오기
available_cols = [c for c in target_cols if c in gym_df.columns]
gym_df = gym_df[available_cols]

# 4. idx 추가 (전체 개수에 맞게)
gym_df["idx"] = range(1, len(gym_df) + 1)

# 5. idx를 맨 앞으로 보내기
cols = ["idx"] + [c for c in gym_df.columns if c != "idx"]
gym_df = gym_df[cols]

gym_df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_14188\2490370541.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gym_df["idx"] = range(1, len(gym_df) + 1)

,idx,dtlstatenm,rdnwhladdr,bplcnm,uptaenm
0,1,폐업,"서울특별시 강동구 올림픽로77길 46-9 (천호동,1층)",금강태권도장,
1,2,폐업,"서울특별시 강동구 아리수로 421, 501호 (강일동)",강일 복싱,
2,3,폐업,"서울특별시 강동구 양재대로130길 47 (명일동,3층)",경원대대명태권도장,
3,4,폐업,"서울특별시 강동구 고덕로97길 20 (강일동,리버파크10단지상가 204~206호)",경희대박사태권도,
4,5,폐업,"서울특별시 강동구 풍성로65길 55 (둔촌동,3층)",태성태권도,

In [113]:
gym_df.rename(columns={'bplcnm':'nm','rdnwhladdr':'addr','uptaenm':'type'},inplace=True)
print(gym_df.columns)

Index(['idx', 'dtlstatenm', 'addr', 'nm', 'type'], dtype='object')

In [114]:
gym_df = gym_df[gym_df["dtlstatenm"] == "영업중"]
print(len(gym_df))

266

In [115]:
gym_df['type'] = '학원'
gym_df

,idx,dtlstatenm,addr,nm,type
37,38,영업중,"서울특별시 강동구 양재대로 1393, 지층 (성내동)",미르메,학원
38,39,영업중,"서울특별시 강동구 진황도로 190, 6층 (둔촌동)",한국체대우리태권도,학원
39,40,영업중,"서울특별시 강동구 상암로 425, 2층 (상일동)",상일유도스쿨,학원
40,41,영업중,"서울특별시 강동구 구천면로 250, 신성빌딩 5층 (천호동)",캡틴복싱클럽,학원
41,42,영업중,"서울특별시 강동구 상일로 31-1, 2층 (상일동)",한국위너복싱 상일동점,학원
...,...,...,...,...,...
345,346,영업중,"서울특별시 강남구 개포로109길 5, 301호 (개포동, 대치2단지 종합상가)",태권메이트,학원
346,347,영업중,"서울특별시 도봉구 마들로 721, 2층 (도봉동)",MMA STORY (엠엠에이 스토리),학원
347,348,영업중,"서울특별시 성북구 동소문로20가길 46, 4층 (동선동1가)",성신여대주짓수 킥복싱 레슬링,학원
348,349,영업중,"서울특별시 중랑구 봉우재로 120, 재동의원 지하1층 (면목동)",탑클래스 레슬링 체육관,학원
350,351,영업중,"서울특별시 중랑구 중랑역로 147, 3층 (묵동)",고려대 새서울 태권도장,학원

### KAKAO API 변환

In [116]:
kakao_key  = os.getenv("KAKAO_API_KEY")

In [118]:
url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": f"KakaoAK {kakao_key}"}

# ① 주소 없는 행 먼저 삭제
gym_df.dropna(subset=["addr"], inplace=True)

for idx, add in gym_df['addr'].items():
    # ② 복잡한 주소 정제 (쉼표 뒤 제거)
    clean_addr = add.split(",")[0].strip()
    
    params = {"query": clean_addr}
    resp = requests.get(url, headers=headers, params=params).json()

    docs = resp.get('documents', [])
    if not docs:
        continue

    road = docs[0].get('road_address')

    if road:
        gym_df.loc[idx, 'lat'] = road.get('y')
        gym_df.loc[idx, 'lng'] = road.get('x')
    else:
        addr = docs[0].get('address')  # 'addr' → 'address' 수정!
        if addr:
            gym_df.loc[idx, 'lat'] = addr.get('y')
            gym_df.loc[idx, 'lng'] = addr.get('x')
    
    time.sleep(0.3)

# # ③ 그래도 NaN이면 제거
# gym_df.dropna(subset=["lat", "lng"], inplace=True)

# ④ idx 재정렬
gym_df["idx"] = range(1, len(gym_df) + 1)

gym_df

,idx,dtlstatenm,addr,nm,type,lat,lng
37,1,영업중,"서울특별시 강동구 양재대로 1393, 지층 (성내동)",미르메,학원,37.5304836404047,127.136840451912
38,2,영업중,"서울특별시 강동구 진황도로 190, 6층 (둔촌동)",한국체대우리태권도,학원,37.5292613524201,127.142992352633
39,3,영업중,"서울특별시 강동구 상암로 425, 2층 (상일동)",상일유도스쿨,학원,37.5458283723052,127.169810241076
40,4,영업중,"서울특별시 강동구 구천면로 250, 신성빌딩 5층 (천호동)",캡틴복싱클럽,학원,37.542515581948,127.131456746578
41,5,영업중,"서울특별시 강동구 상일로 31-1, 2층 (상일동)",한국위너복싱 상일동점,학원,37.5499378035071,127.172743178673
...,...,...,...,...,...,...,...
345,262,영업중,"서울특별시 강남구 개포로109길 5, 301호 (개포동, 대치2단지 종합상가)",태권메이트,학원,37.4923220024104,127.074601198665
346,263,영업중,"서울특별시 도봉구 마들로 721, 2층 (도봉동)",MMA STORY (엠엠에이 스토리),학원,37.6747612200713,127.046759567317
347,264,영업중,"서울특별시 성북구 동소문로20가길 46, 4층 (동선동1가)",성신여대주짓수 킥복싱 레슬링,학원,37.5934071051068,127.018819188551
348,265,영업중,"서울특별시 중랑구 봉우재로 120, 재동의원 지하1층 (면목동)",탑클래스 레슬링 체육관,학원,37.5924741699797,127.086302878565
350,266,영업중,"서울특별시 중랑구 중랑역로 147, 3층 (묵동)",고려대 새서울 태권도장,학원,37.6066585931769,127.076587163625

### 3. CSV 파일 저장

In [119]:
gym_df.to_csv("gym_df.csv", index=False, encoding="utf-8-sig")
print("gym_df.csv")

gym_df.csv